### ISSUE TITLE
CIS Benchmark bad links

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-documentation#1005]
Hello team,

I've noticed CIS Benchmark links in the following documentation page https://documentation.wazuh.com/current/user-manual/capabilities/policy-monitoring/rootcheck/how-it-works.html aren't correct.

Regards.

**Comment by JaoChaos** [comment]
Hi team,
I'm working on this issue.

The links are not broken, CIS Benchmark page has received an update and now users need to be registered to download the files.

But when a user registers, the download links are generated with a private personal TOKEN, so there are no public download links.

I am studying how to solve this situation, but the most probable option is to change the section eliminating the table with the links and writing how to register and download the files.

Regards.

**Comment by jesusgn90** [comment]
Removed broken links from current documentation @havidarou

**Comment by jesusgn90** [comment]
3.9.0

![image](https://user-images.githubusercontent.com/8860227/54426451-2f4eee80-4718-11e9-80fa-d617e3f44c9b.png)
