### ISSUE TITLE
Missing detail regarding Agent Registration with Password Authorization.

### ISSUE THREAD

**Issue by jmmallorq** [wazuh/wazuh-documentation#1006]
The current page _[Using the registration service](https://documentation.wazuh.com/current/user-manual/registering/use-registration-service.html?highlight=authd%20password#password-authorization)_ of the Documentation doesn't mention the required change to be made in:
`/var/ossec/etc/ossec.conf`

to allow that feature. It is, to replace the default value `no` by `yes` in the line:
`<use_password>no</use_password>`

in the section `<auth> </auth>`

**Comment by JaoChaos** [comment]
Hi team, this issue closes with PR #1007.

Regards.
