### ISSUE TITLE
Wrong version of our current puppet module

### ISSUE THREAD

**Issue by LuisGi93** [wazuh/wazuh-documentation#1015]
Hi team,
right now the correct version of our puppet module is "3.8.2" instead of the version "3.8.2-1" that is specified at [our documentation](https://documentation.wazuh.com/current/deploying-with-puppet/wazuh-puppet-module/index.html#install-wazuh-module). Using the current command will cause an error:
![image](https://user-images.githubusercontent.com/17405573/54214867-46f36080-44e7-11e9-8d54-74086e62c412.png)

**Comment by JaoChaos** [comment]
This issue has been fixed in PR #995 

Regards.
