### ISSUE TITLE
Wazuh aws integration

### ISSUE THREAD

**Issue by nikhilsingh42** [wazuh/wazuh-documentation#1033]
for aws integration while running 
./getawslog.py -b s3bucketname -d -j -D -l /path-with-write-permission/amazon.log
getting the error 
./getawslog.py: No such file or directory

**Comment by JaoChaos** [comment]
Hi @nikhilsingh42 

First, make sure you are on the same path where the file is located.

Second, execute the script using the python command:
`python getawslog.py -b s3bucketname -d -j -D -l /path-with-write-permission/amazon.log`
or
`python3 getawslog.py -b s3bucketname -d -j -D -l /path-with-write-permission/amazon.log`
depending on the python version you have installed.

Remember that you can ask us any questions you need in our #community slack channel or in Wazuh's google group:
https://wazuh.com/community/join-us-on-slack/
https://groups.google.com/forum/#!forum/wazuh

Best regards,
Juan Anaya Ortiz.

**Comment by nikhilsingh42** [comment]
Hi ,

I am following this link for integration 
https://documentation.wazuh.com/3.0/amazon/index.html

On the step 
Run the python script to download the JSON data 
./getawslog.py -b s3bucketname -d -j -l /path-with-write-permission/amazon.log -s /path-with-write-permission/awslogstat.db
 
What is the correct patch for the running this script?

**Comment by JaoChaos** [comment]
Hi @nikhilsingh42,

What I mean, is to move to the path where the `getawslog.py` file is located.
For example, if the file is in `/home/user/desktop/aws`
Try to move to that pat using `cd /home/user/desktop/aws`
And then executing the script as I told you, using Python.

Hope this helps to solve your problem.
Regards.

**Comment by nikhilsingh42** [comment]
Hi,
I have located the file in /etc .
Now after running the 
./getawslog.py -b s3bucketname -d -j -l /path-with-write-permission/amazon.log -s /path-with-write-permission/awslogstat.db

getting this error
![image](https://user-images.githubusercontent.com/47519186/54424765-a779dc00-4739-11e9-846c-e0117945fccb.png)

**Comment by JaoChaos** [comment]
Hi @nikhilsingh42,
First of all, make sure you are following the documentation relative to your version of Wazuh.
For example, if you have installed the 3.8.2 Wazuh version, using the 3.0 version of the documentation will only guide you to errors.
After that, if you are using the Wazuh version 3.0, I really recommend you to upgrade to a newer version.
I highly recommend 3.8.2, it's a very stable version.

I will wait for your answer.
Best regards.

**Comment by nikhilsingh42** [comment]
Hi ,
I am using at 3.8.2 version.

Thanks & Regards
Nikhil

**Comment by mgmacias95** [comment]
Hello @nikhilsingh42,

The documentation you were using is deprecated. I recommend you using our [current documentation](https://documentation.wazuh.com/current/amazon/index.html). A summary of the steps you have to follow:
1. Configure AWS to send logs to a bucket. You can configure the following services:
    * VPC Flow
    * CloudTrail
    * Config
    * GuardDuty
    * Macie
    * KMS
    * Trusted Advisor
    * Inspector
2. Add the following configuration to the `/var/ossec/etc/ossec.conf` file (check our [docs](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-s3.html) to get more information about the available settings):
    ```xml
    <wodle name="aws-s3">
      <disabled>no</disabled>
      <interval>10m</interval>
      <run_on_start>yes</run_on_start>
      <skip_on_error>yes</skip_on_error>
      <bucket type="cloudtrail">
         <name>wazuh-cloudtrail</name>
         <access_key>*****</access_key>
         <secret_key>*****</secret_key>
      </bucket>
    </wodle>
    ```
3. Install python module `boto3`
    ```shellsession
    # pip install boto3
    ```
4. Restart Wazuh:
    ```shellsession
    # systemctl restart wazuh-manager
    ```

I hope this brief summary helps.

Best regards,
Marta

**Comment by nikhilsingh42** [comment]
Hi,

Thanks for the mail.
Integrated  AWS successfully.

Thanks & Regards
Nikhil

**Comment by jesusgn90** [comment]
Closing this ticket @nikhilsingh42, don't hesitate to open a new ticket if you need it.

Also, we have a [Slack channel](https://wazuh.com/community/join-us-on-slack/) for our community users, feel free to join it.

Regards,
Jesús
