### ISSUE TITLE
Discrepancies in active-response documentations?

### ISSUE THREAD

**Issue by falkowich** [wazuh/wazuh-documentation#1062]
Hi, 

If I don't misunderstand things there seems to bee a discrepancy on:  

Add an IP to the iptables deny list: and 
https://documentation.wazuh.com/current/user-manual/capabilities/active-response/remediation-configuration.html#add-an-ip-to-the-iptables-deny-list  
and  
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/active-response.html#rules-group  

In the example on "Add an IP to the iptables deny list" is says.
```
<active-response>
  <command>firewall-drop</command>
  <location>all</location>
  <rules_group>authentication_failed,authentication_failures</rules_group>
  <timeout>700</timeout>
  <repeated_offenders>30,60,120</repeated_offenders>
</active-response>
```
But in "rules_group" is says:
```
Allowed values | Any rule group is allowed. Multiple groups should be separated with a pipe character (|).
```
And the first example didn't work for me, but when I changed to | (pipes) between the groups things started working.

If this is a thing, the diff is here. Otherwise, well ignore my rambling :)
```
diff remediation-configuration.rst_old remediation-configuration.rst                                                                                                                2 changed files  master 
82c82
<     <rules_group>authentication_failed,authentication_failures</rules_group>
---
>     <rules_group>authentication_failed|authentication_failures</rules_group>
```

--
Regards Falk

**Comment by jesusgn90** [comment]
Hi @falkowich thanks for your feedback, you are right, we've just merged a fix for it.

Don't hesitate to open a new ticket if needed. We'll update our live docs on next Monday, it will include some other tiny fixes.

Kind regards,
Jesús
