### ISSUE TITLE
Hide Ip address from email alerts

### ISSUE THREAD

**Issue by nikhilsingh42** [wazuh/wazuh-documentation#1065]
Hi Team,

I have configured the mail alert for the events.
Is it possible to to hide ip address from the email alerts?

Thanks & Regards
Nikhil Singh

**Comment by JaoChaos** [comment]
Hello @nikhilsingh42:

No, at the moment it is not possible to modify the template of the emails.
But it is an option that our team has pending and that very possibly will be included in an upcoming version of Wazuh.

I also remind you that you can join our #community Slack channel for more personalized attention:
https://wazuh.com/community/join-us-on-slack/

Don't hesitate to write in there whenever you may need it.

I hope this helps you.

Best regards,
Juan Anaya Ortiz.

**Comment by nikhilsingh42** [comment]
Hi,

Thanks For the updtae.

**Comment by jesusgn90** [comment]
Related https://github.com/wazuh/wazuh/issues/923

**Comment by jesusgn90** [comment]
Closing this ticket. This issue is included in https://github.com/wazuh/wazuh/issues/3568 and https://github.com/wazuh/wazuh/issues/923 and will be solved in further releases.

Stay updated tracking those tickets instead.

Regards,
Jesús
