### ISSUE TITLE
No reporting tab in Wazuh

### ISSUE THREAD

**Issue by nikhilsingh42** [wazuh/wazuh-documentation#1094]
Hi ,

While clicking the reporting tab in management it is showing go on  overview and agent create the report:
![image](https://user-images.githubusercontent.com/47519186/55156584-5b3e8b00-5180-11e9-9a92-dd8c2815660d.png)

But not the able to find any reporting icon on overview and management page.

Thanks & Regards
Nikhil Singh

**Comment by JaoChaos** [comment]
Hi @nikhilsingh42:

Sorry for the late response.

I'll give you an example of where to find that option:

![imagen](https://user-images.githubusercontent.com/16852482/55412204-4c345000-5567-11e9-8855-f4f8008631b4.png)

In the "Overview" section, select one of the options inside as "Security Events" or "Policy Monitoring" and you will find the icon to generate the reports in there.

Hope this helps to solve your problem.

Best regards.

**Comment by nikhilsingh42** [comment]
Hi ,

Thanks for the update.

Thanks & Regards
Nikhil Singh

**Comment by jesusgn90** [comment]
Hi @nikhilsingh42, 

It seems like you've got the answer you were looking for, I'm going to close this ticket. If not the case, reopen the thread or create a new one, thanks.

Kind regards,
Jesús
