### ISSUE TITLE
ossec_amazon

### ISSUE THREAD

**Issue by netflash** [wazuh/wazuh-documentation#11]
Hey guys, 
I've found bunch of things with http://documentation.wazuh.com/en/latest/ossec_amazon.html

1. After installing awscli, boto, getawslog.py still doesn't work - error is related to AWS credentials. I was able to fix it only by creating `.boto` file http://boto.cloudhackers.com/en/latest/getting_started.html - Configuring Boto Credentials section. After that I did `pip uninstall awscli` and everything still works fine. Looks like one doesn't even have to install it.

2. Security IAM rules `Give the user(s) permission to manage security policies, press Attach Policy and select AmazonS3FullAccess policy.` defo not the best way to do things. If you don't mind I can create a pull-request with more tighten IAM policy example, which will allow only `read` and `delete` access to specific bucket and only `list` this particular bucket. Also in this case `getawslog.py` should be a bit adjusted as it would no be able list all buckets in account. I could do a pull-request for this too.

3. CloudTrail `Enable log file validation` parameter has to be configured as NO. If YES - then `getawslog.py` fails with error provided below: (line numbers are different as I modified the script a bit)
```
 error Traceback (most recent call last):
  File "./getawslog.py", line 100, in <module>
    main(sys.argv[1:])
  File "./getawslog.py", line 77, in main
    records = j["Records"]
KeyError: 'Records'
```

4. Let's assume everything with this `getawslog.py`works fine and we have `amazon.log` filled with data. What should happen next ? Which part of software have to read data in this file ? I suppose ossec-agent has to be configured somehow, but not yet sure about this. Could you please shed some light here ?

Thanks for your work, guys.

**Comment by jlruizmlg** [comment]
Hi @netflash, this document still under review, for this reason it's not included in any Doctree, anyway where do you try the installation? which system? our test are under CenOS 7 and Ubuntu 14.04 and work fine.
Your system is in AmazonAWS?

[root@collector2 ~]# ./getawslog.py -b test-logs -d -j -D -l /var/log/amazon.log
Traceback (most recent call last):
  File "./getawslog.py", line 16, in <module>
    import boto
ImportError: No module named boto
[root@collector2 ~]# pip install boto
Collecting boto
  Downloading boto-2.39.0-py2.py3-none-any.whl (1.3MB)
    100% |████████████████████████████████| 1.4MB 231kB/s
Installing collected packages: boto
Successfully installed boto-2.39.0
[root@collector2 ~]# ./getawslog.py -b test-logs -d -j -D -l /var/log/amazon.log
+++ Debug mode on
+++ Connecting to Amazon S3
+++ Found new log:  809629481101_CloudTrail_us-east-1_20160209T1435Z_9sM6k05xLvm4SQC9.json.gz
+++ Found new log:  809629481101_CloudTrail_us-east-1_20160209T1435Z_xVD5TIYdotRAGl8H.json.gz

2 - Yes you are right, it is no the best way and of course we will appreciate your pull request.

3.- By default, this option is not activated when you add a new trail but we will specify this in the documentation.  Thanks for the feedback! We will to add this like a note in the documentation.

The result file amazon.log is a flat file, so this needs to be checked for ossec-agent as a normal log, adding the path file to your ossec.conf or using[ centralized agent configuration ](http://ossec-docs.readthedocs.org/en/latest/manual/agent/agent-configuration.html#create-agent-configuration)

**Comment by netflash** [comment]
1. Ubuntu 14.04, all the configuration was done under `ossec` user. Had to `sudo chown ossec /var/ossec && sudo chmod 0750 /var/ossec` before.

2. Deal.

3. I figured this out by playing with options. So yeah, I think it worth to be mentioned.

4. amazon.log file - I've used syslog log_format (see below) and probably I'm wrong b/c I started to get this in alerts.json (for specific messages)
```
"description": "Non standard syslog message (size too large)."
```
ossec.conf
```
 <localfile>
    <log_format>syslog</log_format>
    <location>/var/amazon/amazon.log</location>
  </localfile>
```

**Comment by netflash** [comment]
BTW this http://documentation.wazuh.com/en/latest/ossec_ruleset.html doc exist in a doc-tree and probably has the same content as the one I mentioned in the beginning (Amazon part, of course)

**Comment by jlruizmlg** [comment]
@netflash yes we know that, we are looking which is the more "logical" structure. The amazon guide is no the final version :).

1.- In the python script as you told, you modified the script a bit, you still having the line 25 `os.environ["HOME"] = "/root"` ?

**Comment by netflash** [comment]
1 Yep, right. My bad. I think this line is not necessary so I removed it at my pull-request https://github.com/wazuh/ossec-rules/pull/13
2 #12 
4 How do you configure this `localfile` directive ?

**Comment by jlruizmlg** [comment]
@netflash can you push the getawslog.py pull request to the development branch? for now the master is only for releases, sorry for the inconvenience.

In the manual the command `sudo aws configure` is wrong, the correct is without sudo, i will fix that.
With sudo `aws configure` creates the aws credential file under root folder because uses $HOME environment variable.

We need this credentials file under the $HOME environment path, in your case under $HOME ossec user if you did with sudo the `aws configure` here is your error, my fault for don`t think about that.

I will fix a couple commands and push again with your comment as well.

**Comment by netflash** [comment]
1 Sure, my bad. https://github.com/wazuh/ossec-rules/pull/14
I did that without sudo, and as you mentioned before all this issue is about `os.environ["HOME"] = "/root"` line in the script. I did the test: removed this line, removed .boto file and it works.

**Comment by jlruizmlg** [comment]
cool perfect, let me review the documentation, and i will upload again for the review

**Comment by netflash** [comment]
Cool, thanks.
Could you please help me with the `localfile` directive in ossec.conf, to be precise - how should I set up agent config so `amazon.log` file would be processed correctly ?

**Comment by jlruizmlg** [comment]
so your are taking many alerts with 

`"description": "Non standard syslog message (size too large)."`

Thats normal because amazon.log is not a standard syslog log, and Cloudtrail log many not useful logs.

It can parse the log without problems. This message is generated by this rule: 

 <rule id="1003" level="13" maxsize="1025"> 
     <description>Non standard syslog message (size too large).</description> 
 </rule> 


So, you can ignore that rule for this specific log you are parsing or 
just increase 
the size for everyone... Example: 

 <rule id="100103" level="0"> 
     <description>Ignoring size to large alerts for myapp.</description> 
   <match>myapp log</match> OR you can use <program_name>myapp</program_name> 
 </rule> 

You can read about this here: https://groups.google.com/forum/#!topic/ossec-list/SpHFukigGlg

We are working in improvement in our rules and decoder to be more efficient. Let me now if this option can fix your problem.

**Comment by netflash** [comment]
@jlruizmlg Thanks, I gonna play with it a bit later.
ATM I'm trying to check that OSSEC correctly reacts to logs. And getting another issue.
Here's what I have in amazon.log
```
"AmazonAWS":"eventVersion":"1.02","eventID":"$ID","eventTime":"2016-03-15T18:43:46Z","additionalEventData":"{u'MFAUsed': u'Yes', u'LoginTo': u'https://console.aws.amazon.com/console/home?state=hashArgs%23&isauthcode=true', u'MobileVersion': u'No'}","requestParameters":"None","eventType":"AwsConsoleSignIn","errorMessage":"Failed authentication","responseElements":"{u'ConsoleLogin': u'Failure'}","awsRegion":"us-east-1","eventName":"ConsoleLogin","userIdentity":"{u'userName': u'$USER', u'accessKeyId': u'', u'type': u'IAMUser', u'principalId': u'$UID', u'accountId': u'$ID'}","eventSource":"signin.amazonaws.com","userAgent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10.11; rv:45.0) Gecko/20100101 Firefox/45.0","sourceIPAddress":"$IP","recipientAccountId":"$Acc"
```

But the alert for this log is 
```
** Alert 1458068001.308786: mail  - syslog,errors,
2016 Mar 15 18:53:21 (ip-10-15-8-45) any->/var/ossec/amazon.log
Rule: 1002 (level 2) -> 'Unknown problem somewhere in the system.'
```

At ossec-wazuh/etc/rules/syslog_rules.xml 
`<var name="BAD_WORDS">core_dumped|failure|error|attack|bad |illegal |denied|refused|unauthorized|fatal|failed|Segmentation Fault|Corrupted</var>` and 
```
<rule id="1002" level="2">
    <match>$BAD_WORDS</match>
    <options>alert_by_email</options>
    <description>Unknown problem somewhere in the system.</description>
  </rule>
```

Looks like this rule has been triggered before 
```
<rule id="80802" level="5">
        <if_sid>80801</if_sid>
        <match>'ConsoleLogin': u'Failure'</match>
        <description>Amazon-signin: User Login failed</description>
        <group>amazon,authentication_failed,pci_dss_10.2.4,pci_dss_10.2.5,</group>
    </rule>
```

If I get it right - the only way to make AWS rules work in this circumstances - is to change $BAD_WORDS or remove rule 1002 completely. Could you gimme some advice please ?

**Comment by jlruizmlg** [comment]
Hi @netflash i'm out for a couple days, let me review and will give you some information as soon as possible.

sorry for the inconveniences.

**Comment by jlruizmlg** [comment]
Hi @netflash after the last update in the amazon rules and decoders this issue should be solved.

**Comment by netflash** [comment]
Cool, thanks!
I'm not able to check it right now. Closing the issue.

**Comment by paulyehorov** [comment]
Hello, guys. I've got same problem as @netflash when BAD_WORDS rule rise before AmazonAWS rules. I've used updated rules and decoders, but still get it. Maybe there is some special `log_format` for amazon.log or we still need to use `syslog`

**Comment by mohakkataria** [comment]
Hey Guys,

I too have got the same problem as @netflash  and @paulyehorov. Even after using the new rules/decoders I am still stuck with "Unknown problem somewhere in the system". The amazon decoder is working but rule is being satisfied. For e.g. my logs had events of creating users and although the rule "80861" should have been triggered, it only fires rule "1002". 
Can you help here please, @jlruizmlg .

**Comment by paulyehorov** [comment]
@mohakkataria Try to check `ossec.conf`. It doesn't include `amazon_rules.xml`,`amazon-ec2_rules.xml` and `amazon-iam_rules.xml` by default. Also some `BAD WORDS` from `syslog_rules.xml` should be deleted.

**Comment by jesuslinares** [comment]
@mohakkataria try the suggestion of @paulyehorov.

The next release of Wazuh will be include all the new rules by default. Also, the rule _1002_ and the variable _BAD WORDS_ are necessary to detect if you need other rule. In other words, if you see the rule 1002, probably you need to create a rule to capture that event.

Regards.
