### ISSUE TITLE
ossec-authd use is not correct when using certificates

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#1100]
Hello team

  Regarding the documentation at this point: https://documentation.wazuh.com/current/user-manual/registering/use-registration-service.html#manager-verification-using-ssl the step `Copy the newly created certificate (and its key) to the /var/ossec/etc folder on the manager, and start the registration service:` contains the instruction: `# /var/ossec/bin/ossec-authd`. If the daemon _ossec-authd_ is running, the new configuration will not be taken and the error:
`ERROR: (1206): Unable to Bind port '1515' due to [(98)-(Address already in use)]`
is showed in ossec.log. 

A new instruction referring to the wazuh-manager restarting could be more appropriate. 
Best regards, 

Alberto R.

**Comment by JaoChaos** [comment]
Hi @alberpilot,

I've been working to solve this issue and others in the PR (1050)[https://github.com/wazuh/wazuh-documentation/pull/1050]

That PR changes the use-registration-service section to adapt it to the new authd behavior.

Best regards.
