### ISSUE TITLE
ossec-control enable auth is deprecated

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#1107]
Hello team

  Regarding the section: https://documentation.wazuh.com/3.x/user-manual/reference/tools/ossec-control.html#ossec-control we noticed that the option `enable auth` is deprecated. Please remove this option from text: `The ossec-control script is used to start, stop, configure, or check on the status of Wazuh processes. This script can enable or disable client-syslog, the authentication daemon`

Best regards, 
Alberto R.

**Comment by jesusgn90** [comment]
Thanks @alberpilot, merged into 3.9
