### ISSUE TITLE
 Getting email alerts of logs but not able to see logs in kibana discover.

### ISSUE THREAD

**Issue by nikhilsingh42** [wazuh/wazuh-documentation#1110]
Hi team,

I am getting the email alerts of logs but not able to see logs in kibana discover.
i have also received the alert that disk of my Wazuh server is reached 90%.

Thanks & Regards
Nikhil Singh

**Comment by jesusgn90** [comment]
Hi @nikhilsingh42,

There is more than one component involved in the data flow. Let's dig into your environment with some commands that may give us some light about your issue.

Check if Logstash/Filebeat is reading your `alerts.json` (Wazuh manager side):

```
lsof /var/ossec/logs/alerts/alerts.json
```

We can look for errors in the Logstash log file:

```
cat /var/log/logstash/logstash-plain.log | grep -i -E "warn|error|critic"
```

Please paste the output from the above commands.

Regards,
Jesús

**Comment by jesusgn90** [comment]
Closing this ticket due to inactivity. Please re-open it or create a new one if needed.

Regards,
Jesús
