### ISSUE TITLE
Update Docker versions

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-documentation#1114]
Hi,

It seems that our Docker guide is not updated and there are no references to the latest `3.8.2_6.7.0` images. You can check it [here](https://documentation.wazuh.com/3.x/docker/wazuh-container.html), they're all referencing the `3.8.2_6.5.4`.

- [x] Update to the latest `3.8.2_6.7.0`.

Cheers

**Comment by jesusgn90** [comment]
Fixed https://github.com/wazuh/wazuh-documentation/commit/90666dca6f67792d4bc7d89f535f852af963886f, thanks @manuasir
