### ISSUE TITLE
Docker compose can't be executed

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#1115]
Hello team

  I followed the step described here: https://documentation.wazuh.com/current/docker/docker-installation.html#docker-compose in Centos 7 and Amazon Linux 2. There is an error as you can see in the information below: 

```
[root@ ec2-user]# curl -L "https://github.com/docker/compose/releases/download/1.23.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   617    0   617    0     0   2557      0 --:--:-- --:--:-- --:--:--  2560
100 11.1M  100 11.1M    0     0  29.8M      0 --:--:-- --:--:-- --:--:-- 29.8M
[root@ ec2-user]# chmod +x /usr/local/bin/docker-compose
[root@ ec2-user]# docker-compose --version
bash: docker-compose: command not found
[root@ ec2-user]# ls -l /usr/local/bin/docker-compose
-rwxr-xr-x 1 root root 11737584 Apr  4 16:20 /usr/local/bin/docker-compose
[root@ ec2-user]# echo $PATH
/sbin:/bin:/usr/sbin:/usr/bin:/opt/aws/bin
```
As you can see, the folder `/usr/local/bin/` is not included in PATH. So, we have two options: 

1. Add `/usr/local/bin/` to PATH
2. Locate the docker-compose file to other folder included in PATH.

Best regards,

**Comment by jesusgn90** [comment]
Fixed https://github.com/wazuh/wazuh-documentation/commit/efe6d0d03a4e1b9190cb0361c85da902d9af1ecd, thanks @alberpilot !
