### ISSUE TITLE
Setting up SSL for Filebeat and Logstash - cert error

### ISSUE THREAD

**Issue by shmurf** [wazuh/wazuh-documentation#1116]
When setting up SSL for Filebeat and Logstash as per [the docs](https://documentation.wazuh.com/current/installation-guide/optional-configurations/elastic_ssl.html#elastic-ssl) instructions should be included after step 3 noting that permissions for the key file should be updated to allow the logstash user access. Or ownership of the file should be changed to the logstash user.

Otherwise you will get an error stating 
`Looks like you either have a bad certificate, an invalid key or your private key was not in PKCS8 format.`
Which can lead to erroneous troubleshooting , as the format is correct, rather logstash simply can't read it as seen earlier in the log file
`java.security.KeyException: could not find key file: /etc/logstash/logstash.key`

**Comment by jesusgn90** [comment]
Hi @shmurf, you are right, we must review it. We'll fix it for the current version and the next version as soon as we can.

Thanks for the feedback, I'll update you on this ticket.

Regards

**Comment by jesusgn90** [comment]
Hi @shmurf I've just added a note about the permissions and how to set them properly both for Logstash and Filebeat as well. 

Thanks
