### ISSUE TITLE
Improve cluster documentation

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh-documentation#1118]
Hello team,

Our current guide to install, configure and explain how it works isn't easy to follow for a user. I think the following points must be improved:

* **Location**: The cluster guide is under `Docs >> User Manual >> Wazuh server administration >> Configuring a cluster`. It isn't easy to find without using the search bar.
* **Structure**: The document structure isn't clear:
    * The introduction gives too much detail about the cluster. Lots of scrolls are necessary to reach the install steps.
    * The Getting started guide should be a section with commands to copy and paste. In our case it's a section explaining how to install a single node, explaining how to register agents, how to install in CentOS 6, how to setup Kibana/Splunk.... All this information should be moved to another section appart from the Getting started. The getting started must be a guide with commands to copy and paste and which last step is a _hello world command_ that helps the user check if all the installation was correct (for example,  `cluster_control -l`?).
   * All the information is placed in a single document, it must be splitted in multiple sections.

Best regards,
Marta

**Comment by jctello** [comment]
Additionally the cluster documentation only specifies configuring agents to communicate with a Load Balancer and fails to mention the possibility of adding more than one manager.
In this case the agent will not perform load balancing but will switch to the additional managers if the first one fails.

**Comment by AdriiiPRodri** [comment]
Thanks @jctello  for the addition, I'm currently working on this issue, I'll add what you say, I'm also changing the getting started section and the location of the cluster documentation to make it more accessible.
