### ISSUE TITLE
Table in vulnerability detector reference for feed too wide

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-documentation#1125]
The table in the vulnerability detection reference page for the feed ([link](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-vuln-detector.html#feed)) options is too wide, which will hide options and make it difficult to navigate and find what is necessary.
![vulnerability-detector-scroll](https://user-images.githubusercontent.com/36071202/55939359-d3f01d80-5c3d-11e9-8d31-a2d9d3641b9e.gif)
This may lead to omission of the notes depending on the user's browser width.

 Line breaks and line wrapping for these cells would make it more user friendly.

**Comment by jesusgn90** [comment]
We've changed the way tables are shown, it will be public soon, sorry about the inconveniences.

**Comment by jesusgn90** [comment]
Split into two new tables, reduced their width as much as possible. Further improvements will be done regarding tables but we'll open a new ticket for detailed information about this task.
