### ISSUE TITLE
Documentation still assumes authd is manually executed

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-documentation#1126]
As mentioned in https://github.com/wazuh/wazuh-documentation/issues/787 with version 3.8 the authd daemon runs by default, so it should not be executed service manually as specified here:
https://documentation.wazuh.com/current/user-manual/registering/use-registration-service.html#simple-method

Additionally if password authentication is to be used it must be specified in the `ossec.conf` file's `auth` section with `<use_password>yes</use_password>`

**Comment by jesusgn90** [comment]
Changes were not uploaded yet, but they already exist. They will be live soon.
