### ISSUE TITLE
Java download command in docs doesn't work

### ISSUE THREAD

**Issue by loosus456** [wazuh/wazuh-documentation#1130]
On this page: source/installation-guide/installing-elastic-stack/elastic_server_rpm.rst

This command doesn't work:
curl -Lo jre-8-linux-x64.rpm --header "Cookie: oraclelicense=accept-securebackup-cookie" "https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-linux-x64.rpm"

Even after logging into Oracle's website, I get a 404.  I am guessing this happened because of Oracle's licensing changes with Java 8?

It might be better to either point to a more stable repository or simply give more vague directions on getting the RPM.

**Comment by jesusgn90** [comment]
Hi @loosus456 ,

We've decided to replace Oracle Java with OpenJDK, the new command for CentOS / Red Hat is:

```
yum install java-1.8.0-openjdk
```

Also, we are currently adapting all our Elastic integration for Elastic 7.0.0, and it's no longer needed to install Java, from 7.0, it comes within the Elasticsearch package.

Regards,
Jesús

**Comment by jesusgn90** [comment]
**Update**

Java is still needed for Logstash 7.0.0
