### ISSUE TITLE
SELinux command doesn't work during Docker install

### ISSUE THREAD

**Issue by loosus456** [wazuh/wazuh-documentation#1131]
On this page: source/docker/wazuh-container.rst

It says to issue this command on CentOS installs:
chcon -R system_u:object_r:admin_home_t:s0 docker-elk/

On my CentOS install, the following error is displayed:
chcon: cannot access ‘docker-elk/’: No such file or directory

I did a search on the entire filesystem for docker-elk and found nothing.

**Comment by LuisGi93** [comment]
Hi @loosus456,
Thanks for letting us know about this error. The command is intended to be used after cloning the [wazuh-docker repository](https://github.com/wazuh/wazuh-docker/tree/3.8.2_6.7.0), so the correct command is:
```
chcon -R system_u:object_r:admin_home_t:s0 wazuh-docker/
```
![image](https://user-images.githubusercontent.com/17405573/56493670-20661380-64f0-11e9-9182-9d8c3a735b73.png)
Regards,
Luis.

**Comment by jesusgn90** [comment]
Closing this ticket due to inactivity. Please re-open it or create a new one if needed.

Best regards,
Jesús
