### ISSUE TITLE
Docker docs don't indicate default username and password

### ISSUE THREAD

**Issue by loosus456** [wazuh/wazuh-documentation#1132]
On this page: source/docker/container-usage.rst

The following sentence exists:
_Then access the Kibana UI trough Nginx by hitting https://localhost with a web browser if you are in the Docker host._

A page attempts to appear, but a username and password is required.
![signin](https://user-images.githubusercontent.com/25268183/56393902-b144a280-6203-11e9-9b44-1a5bee2630be.png)

Leaving the username and password blank doesn't work, and clicking "Cancel" makes a "401 Authorization Required" error appear.

This documentation page, nor the page before it, indicated anything about a username and password.

In addition, there is a typo in the sentence: "trough"

**Comment by LuisGi93** [comment]
Hi @loosus456,
you are right. I have opened a PR https://github.com/wazuh/wazuh-documentation/pull/1134 to fix this issue. By default the username "foo" and the password "bar" are used.

Regards.
Luis.

**Comment by jesusgn90** [comment]
Hi @LuisGi93, @loosus456 ,

https://github.com/wazuh/wazuh-documentation/pull/1134 has been merged, changes will be live soon.

Regards
