### ISSUE TITLE
Improve cluster load balancing documentation

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh-documentation#1135]
Hello team,

Reading our cluster documentation in 3.9 I found out some improvements for the [load balancing section](https://github.com/wazuh/wazuh-documentation/blob/3.9/source/user-manual/manager/wazuh-cluster.rst#pointing-agents-to-the-cluster-with-a-load-balancer):
1. Use [IPVS](https://man.cx/?page=ipvsadm(8)) instead of NGINX. This would add support for UDP agents (NGINX only supports TCP).
2. The balanced load should be done in port 1514 instead of 1516.

Best regards,
Marta

**Comment by mgmacias95** [comment]
Hello team,

I have been trying to do a configuration with IPVS but I didn't get it working. The response packages aren't being correctly routed from the LB to the agent. As you can see, `OutBytes` is 0:
```shellsession
root@lb:/home/vagrant# ipvsadm -L --stats
IP Virtual Server version 1.2.1 (size=4096)
Prot LocalAddress:Port               Conns   InPkts  OutPkts  InBytes OutBytes
  -> RemoteAddress:Port
UDP  lb:1514                             1        1        0      113        0
  -> 172.17.0.100:1514                   0        0        0        0        0
  -> 172.17.0.101:1514                   1        1        0      113        0
```
These are the logs generated in the agent:
```
2019/04/23 15:01:01 ossec-agentd: WARNING: (4101): Waiting for server reply (not started). Tried: '172.17.0.50'.
2019/04/23 15:01:12 ossec-agentd: INFO: Trying to connect to server (172.17.0.50:1514/udp).
```

However, using NGINX it's been much easier to make it work using the following configuration:
```
# cat /etc/nginx/nginx.conf

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

stream {
  upstream cluster {
    hash $remote_addr consistent;
    server 172.17.0.100:1514;
    server 172.17.0.101:1514;
  }

  server {
    listen 1514;
    proxy_pass cluster;
  }
}
```
There is a guide in the NGINX documentation to support both [UDP and TCP](https://docs.nginx.com/nginx/admin-guide/load-balancer/tcp-udp-load-balancer/) which should be linked in our own documentation.

With this research I'm ready to summit a PR to the documentation fixing the actual LB cluster section.

Best regards,
Marta

**Comment by davidjiglesias** [comment]
Hello team, 

I have added support to agents registration through the load balancer in a wazuh cluster. 

```
# cat /etc/nginx/nginx.conf

user  nginx;
worker_processes  1;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;


events {
    worker_connections  1024;
}

stream {
    upstream cluster {
        server {wazuh-master-IP}:1514;
        server {wazuh-worker1-IP}:1514;
        server {wazuh-worker2-IP}:1514;
    }
    upstream master {
        server{wazuh-master-IP}:1515;
    }
    server {
        listen 1514;
        proxy_pass cluster;
    }
    server {
        listen 1515;
        proxy_pass master;
    }
}
