### ISSUE TITLE
'no_full_log' option documentation incomplete

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh-documentation#1142]
Hi team,

We need to indicate that the `no_full_log` option only works for JSON alerts (https://documentation.wazuh.com/3.x/user-manual/ruleset/ruleset-xml-syntax/rules.html#options).

As it is now, it may be confusing; someone could expect no full log in an alert mail (when the alert source is `alert.log` and not `alert.json`). Related PR: https://github.com/wazuh/wazuh/pull/3174

Regards.

**Comment by davidfmiranda** [comment]
Hello @DaveVG1 , we are closing this issue because the problem was solved in this [PR](https://github.com/wazuh/wazuh/pull/3174). If you consider that this issue shouldn't have been closed, do not hesitate to open it again.

Regards,

David
