### ISSUE TITLE
Uninstalling MACOS agent instructions

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh-documentation#1151]
the current doc ( https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_macos.html)  has no steps regarding how to uninstall the agent.

I have followed those steps to remove all related Wazuh directories/files  : 

```
pkgutil --pkgs | grep wazuh
com.wazuh.pkg.wazuh-agent-etc
com.wazuh.pkg.wazuh-agent 
rm -rf /Library/Ossec
rm -rf /Library/StartupItems/WAZUH
rm -f /Library/LaunchDaemons/com.wazuh.agent.plist
rm -f /private/etc/ossec-init.conf
pkgutil --forget com.wazuh.pkg.wazuh-agent-etc
pkgutil --forget com.wazuh.pkg.wazuh-agent
```

**Comment by alberpilot** [comment]
Done: https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_macos.html#uninstall
