### ISSUE TITLE
Old version as current version

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh-documentation#1154]
Hi team,

I've found that in the [Compatibility matrix](https://documentation.wazuh.com/current/installation-guide/compatibility_matrix/index.html#wazuh-agent) section of our documentation we say that the current version of Wazuh is 3.3.1. We must update this information.

![image](https://user-images.githubusercontent.com/11405177/57077962-9dae3700-6ced-11e9-9d32-06456aab44d5.png)

Best regards,
Cerv1.

**Comment by jesusgn90** [comment]
It says "From X to Y", but it's not so clear so we've decided to explicitly say that:

![image](https://user-images.githubusercontent.com/8860227/57623519-323b5380-7590-11e9-81f9-9390e372f1e3.png)

Regards
