### ISSUE TITLE
Fix wrong flow in securing API documentation

### ISSUE THREAD

**Issue by hemedga** [wazuh/wazuh-documentation#1172]
Hi,
In _**source/installation-guide/installing-wazuh-server/securing_api.rst**_, we guide people to change the default credentials and then run a script to enable HTTPS which also changes the password.

I propose to guide the users to first change the run the script. If they decide not to run it we offer an optional change of credentials.

**Comment by DanielMorLoz** [comment]
Hello hemedga,

We really appreciate your contribution to the documentation.
We have reviewed the documentation and we have made this [PR](https://github.com/wazuh/wazuh-documentation/pull/1211) in order to apply it.
It will be merged as soon as possible.

Regards.
