### ISSUE TITLE
zypper should be mentioned in upgrade pages

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-documentation#1175]
Although zypper (the package manager utility for OpenSUSE) is mentioned in the [agent installation page](https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_rpm.html) it is not mentioned in the upgrade pages: 

- [same minor version](https://documentation.wazuh.com/current/installation-guide/upgrading/same_minor.html)
- [same major version](https://documentation.wazuh.com/current/installation-guide/upgrading/same_major.html)
- [different major version](https://documentation.wazuh.com/current/installation-guide/upgrading/different_major.htm)
 - [same major version](https://documentation.wazuh.com/current/installation-guide/upgrading/latest_wazuh3_minor.html)

This may lead to confusion as users may then use yum instead of zypper causing unexpected behaviour.

**Comment by paroma96** [comment]
Good evening, 
all requests proposed on this issue have been considered with the changes taken at the following pull request:

https://github.com/wazuh/wazuh-documentation/pull/1389

**Comment by snaow** [comment]
Merged, thanks.
