### ISSUE TITLE
Java installation guide for CIS-CAT

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-documentation#1177]
Hello team,
there are no instructions/recommendations to install Java in Windows systems for CIS-CAT integration.

Link: https://documentation.wazuh.com/3.x/user-manual/capabilities/policy-monitoring/ciscat/ciscat.html

Regards.

**Comment by javierescobarcerezo** [comment]
PR created for the issue: https://github.com/wazuh/wazuh-documentation/pull/1388

**Comment by MiguelCasaresRobles** [comment]
Merged: https://github.com/wazuh/wazuh-documentation/pull/1388
