### ISSUE TITLE
Add upgrade of Wazuh Manager and API at same time

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-documentation#1179]
Hi team,

We have detected that upgrade of Wazuh Manager with an API installed produce some errors on `apt` package manager when only the Wazuh manager is specified on the command like 
`apt-get upgrade wazuh-manager`
On this situation we have to upgrade both packages at same time with 
`apt-get upgrade wazuh-manager wazuh-api`
So, we have to upgrade the following documentation link adding this case https://documentation.wazuh.com/current/installation-guide/upgrading/latest_wazuh3_minor.html#upgrading-latest-minor

Another way to approach this is to use `apt-mark unhold wazuh-api` to upgrade it separately maybe we could add this option to our documentation, thanks to @shmurf to this use case.

Regards!.

**Comment by shmurf** [comment]
Hi,
Regarding using `apt-mark unhold wazuh api` It would simply cause the API to be auto upgraded when running apt-get upgrade wazuh-manager. It wouldn't require it to be run separately, so technically it is the same as  `apt-get upgrade wazuh-manager wazuh-api`
