### ISSUE TITLE
Extension 'sphinx pretty search results' not found on building

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-documentation#1180]
Hi team,

We have detected that the following extension `sphinxprettysearchresults` isn't referenced on README an it's needed to build the documentation with `make html`, we attach the following log:
```
# make html
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.6.5
making output directory...
/usr/lib/python2.7/site-packages/sphinx/util/compat.py:40: RemovedInSphinx17Warning: sphinx.util.compat.Directive is deprecated and will be removed in Sphinx 1.7, please use docutils' instead.
  RemovedInSphinx17Warning)

Extension error:
Could not import extension sphinxprettysearchresults (exception: No module named sphinxprettysearchresults)
make: *** [html] Error 1
```

The solution to this error is to install such extension so, it would be good to be added to the README.

Regards!.

**Comment by okynos** [comment]
It seems that with `pip3 install -r requirements.txt` works well but it would be great to be added to the README and add a bit of explanation of such task.

Regards!.

**Comment by jesusgn90** [comment]
Hi @okynos,

It's explained in https://github.com/wazuh/wazuh-documentation/blob/master/CONTRIBUTING.md, also I've added https://github.com/wazuh/wazuh-documentation/blob/master/Dockerfile so you don't need to install any dependency.

Best regards,
Jesús
