### ISSUE TITLE
New extension to add examples on less space

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-documentation#1181]
Hi team,

While we were coding to the `rst` format we have view this extension https://github.com/svx/sphinxcontrib-osexample that can simplify our operative system command examples in a few lines, maybe it's a good way to do a better reading documentation.
One example:
![Peek 2019-05-06 14-25](https://user-images.githubusercontent.com/10661307/57256265-086fb300-700b-11e9-99bb-ffaa7f0b9ea8.gif)

Regards.

**Comment by alberpilot** [comment]
Finally, this extension doesn't match with our needs. 
Best regards, 
Alberto R
