### ISSUE TITLE
Oracle Linux and OpenSUSE OS are missing in the compatibility matrix

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-documentation#1184]
Hi team,

in this PR https://github.com/wazuh/wazuh-documentation/pull/1042/ we added Oracle Linux and OpenSUSE hosts to the compatibility matrix, but in the current branch 3.9, both entries have been removed. 

Regards.

**Comment by alberpilot** [comment]
Done: https://github.com/wazuh/wazuh-documentation/pull/1185
