### ISSUE TITLE
Wazuh download module internal option missing

### ISSUE THREAD

**Issue by TJOSERAFAEL** [wazuh/wazuh-documentation#1186]
### Download module

The wazuh download module is missing in the internal options documentation.

```
# Enable download module
# 0. Disabled
# 1. Enabled (default)
wazuh_download.enabled=1
```

Need to add it to the documentation

**Comment by TJOSERAFAEL** [comment]
This PR https://github.com/wazuh/wazuh-documentation/pull/1187 solves the issue

**Comment by alberpilot** [comment]
Done
