### ISSUE TITLE
Improve syslog output documentation

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-documentation#1188]
Hello team,

I've noticed that here: https://documentation.wazuh.com/3.x/user-manual/manager/manual-syslog-output.html

there are no instructions about enabling syslog output with ossec-control:

`/var/ossec/bin/ossec-control enable client-syslog`

Regards.

**Comment by DanielMorLoz** [comment]
This PR should solve it https://github.com/wazuh/wazuh-documentation/pull/1220

**Comment by alberpilot** [comment]
Hello @havidarou 

 This issue looks solved. Please re-open if necessary. 

Regards, 
Alberto R
