### ISSUE TITLE
Add an example of the use of decoded fields on rule description (logcollector)

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh-documentation#1189]
Hi team!

I have noticed that on the [Rules Syntax](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#description) page of the documentation it is specified that "Since Wazuh v3.3.0 it is possible to include any decoded field (static or dynamic) to the description message.", but it doesn't explain how to add these fields to the description nor is there any example for this.

I have been investigating and found an issue where reference is made to this functionality and it seems that the syntax is `$(field_name)`.

Cheers
Francisco Navarro

**Comment by MiguelCasaresRobles** [comment]
This PR closes this: https://github.com/wazuh/wazuh-documentation/pull/1203
