### ISSUE TITLE
Searchguard guide improvement by remove 1 step

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#1194]
Hello team

  I think that the section: `Setting up Search Guard for Logstash` of https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/searchguard.html#searchguard can be simplified, with only 2 steps: 

1.- Modify the file
2.- Restart logstash

It's not necessary to have logstash stopped for config file editing. 

Best regards, 
Alberto R.

**Comment by jesusgn90** [comment]
Update https://github.com/wazuh/wazuh-kibana-app/issues/1433#issuecomment-491891800

**Comment by alberpilot** [comment]
Removed logstash, change not necessary.
