### ISSUE TITLE
Wrong regex expression in the ruleset example.

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-documentation#1212]
Hi team!

I've noticed that the example of usage of the <regex> field in:  https://documentation.wazuh.com/3.x/user-manual/ruleset/ruleset-xml-syntax/rules.html#regex

![image](https://user-images.githubusercontent.com/46649922/57769496-5886fd80-770e-11e9-93ce-8ec938fff6a7.png)

The example doesn't specify the rule `id` and `level`. And the regex specified is not valid and generates the following error when executing `/var/ossec/bin/ossec-logtest`

![image](https://user-images.githubusercontent.com/46649922/57769606-a1d74d00-770e-11e9-8fa0-921a39e6f954.png)

Regards!

Jose

**Comment by DanielMorLoz** [comment]
This PR should fix it https://github.com/wazuh/wazuh-documentation/pull/1219

**Comment by MiguelCasaresRobles** [comment]
Fixed and merged
