### ISSUE TITLE
Wrong nginx configuration for load balancer in cluster configuration

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-documentation#1221]
The suggested NGINX configuration to set up a load balancer in a Wazuh [configuration cluster](https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html?highlight=configuring%20cluster) is wrong.

Actual documentation states to add the following code to nginx.conf:
```
cluster-stream {
  upstream mycluster {
    server <INSTANCE_IP>:1516;
    server <INSTANCE_IP>:1516;
    server <INSTANCE_IP>:1516;
    ...
  }

  server {
    listen 1516;

    location / {
      proxy_pass mycluster;
    }
  }
}
```

**Comment by jesusgn90** [comment]
Related https://github.com/wazuh/wazuh-documentation/issues/1135, closing this ticket
