### ISSUE TITLE
Fix 3.9.0 on 3.9.1 documentation

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-documentation#1231]
Hi team,

We have detected that some documentation resources like OSX installation guide need to be updated in order to reflect 3.9.1 release, we have to improve the way of upgrade such strings.
Seems that Windows have the same defect -> https://documentation.wazuh.com/current/installation-guide/installing-wazuh-agent/wazuh_agent_windows.html

Regards!.

**Comment by jesusgn90** [comment]
Hi @okynos ,

Thanks for reporting that, it seems to be fixed right now, closing this ticket. Re-open it or open a new one if needed.

![image](https://user-images.githubusercontent.com/8860227/58338249-b1aa0c00-7e47-11e9-97b5-bc13386ae198.png)

![image](https://user-images.githubusercontent.com/8860227/58338272-c090be80-7e47-11e9-99e0-a66697b9ab51.png)
