### ISSUE TITLE
Single-Host Upgrading ELK from 6.7 to 7.x

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh-documentation#1242]
This issue is related to [this page](https://documentation.wazuh.com/current/installation-guide/upgrading-elastic-stack/elastic_server_rolling_upgrade.html#upgrading-elastic-stack-from-6-7-to-7-x).

The 3.8 documentation explained you could avoid using Filebeat when you're deploying a single host environment and to use only Logstash.

People with this kind of environment can't follow this guide. It should be explained we're no longer using Logstash and they should start using Filebeat.

**Comment by jesusgn90** [comment]
In the top of the guide we say that:

![image](https://user-images.githubusercontent.com/8860227/58786250-67632080-85e7-11e9-8f6a-74e269e7d882.png)

And for those users that still want to use Logstash: 

- https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/transform_logstash.html

From my view, the docs are just fine and clearly explained.

Regards
