### ISSUE TITLE
Upgrading to ELK 6.8

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh-documentation#1250]
Hello team

We should indicate that our [ELK upgrading guide from 6.x to 6.7](https://documentation.wazuh.com/3.9/installation-guide/upgrading-elastic-stack/elastic_server_hard_upgrade.html) works to upgrade ELK to 6.8 too.

There is no mention to ELK 6.8 in our docu so it would be nice to indicate it.

**Comment by jesusgn90** [comment]
Done here https://github.com/wazuh/wazuh-documentation/commit/29c305ee701d124a403222ddf6c8b66ae135b0e1, and already live.
