### ISSUE TITLE
The <same_field> and <not_same_field> options with static fields only

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh-documentation#1252]
Hello team,

In our [Rules Syntax](https://documentation.wazuh.com/3.x/user-manual/ruleset/ruleset-xml-syntax/rules.html#same-field) documentation about the `<same_field>` and `<not_same_field>` options we don't indicate they can only be used with dynamic fields. 

It would be nice to clarify it in order to help the users to use these options.

**Comment by davidfmiranda** [comment]
Hello @DanielMorLoz thanks for your issue. We are going to close this issue since the problem was already solved in this #2252. This PR specifies that the field has to be dynamic in both cases. 

Regards,

David
