### ISSUE TITLE
Logstash and Filebeat configuration is not available in the upgrading Elastic Stack page

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#1253]
Hi Team,

I have realized the following links from this [documentation page](https://documentation.wazuh.com/current/installation-guide/upgrading-elastic-stack/elastic_server_hard_upgrade.html?highlight=upgrading) are not available:

https://raw.githubusercontent.com/wazuh/wazuh/v3.9.0/extensions/filebeat/6.x/filebeat.yml
https://raw.githubusercontent.com/wazuh/wazuh/v3.9.0/extensions/filebeat/6.x/filebeat.yml

Instead, it should be:
https://raw.githubusercontent.com/wazuh/wazuh/v3.9.1/extensions/logstash/6.x/01-wazuh-remote.conf
https://raw.githubusercontent.com/wazuh/wazuh/v3.9.1/extensions/filebeat/6.x/filebeat.yml

Regards,

Miguel Casares

**Comment by jesusgn90** [comment]
Hi @MiguelCasaresRobles, you are right, fixed in https://github.com/wazuh/wazuh-documentation/commit/3f57d3e7b58861ef82858fce700758bf68264e74
