### ISSUE TITLE
It is not necessary to restart WazuhAPI after deleting an agent

### ISSUE THREAD

**Issue by sergiospa** [wazuh/wazuh-documentation#1256]
Hi team,

In the following documentation page → https://documentation.wazuh.com/current/user-manual/api/reference.html, we can find this text in the `Delete agents` section:

```
Delete agents
Removes agents, using a list of them or a criterion based on the status or time of the last connection. The Wazuh API must be restarted after removing an agent.
```

It says that it's necessary to restart the Wazuh API after deleting an agent, but it's not.

I'll open a PR to change that if you guys agree.

Regards,
Sergio

**Comment by crd1985** [comment]
Done in https://github.com/wazuh/wazuh-documentation/pull/1272
