### ISSUE TITLE
Detect filesystem changes section needs to be updated

### ISSUE THREAD

**Issue by DaveVG1** [wazuh/wazuh-documentation#1277]
Hi team,

The `Detect filesystem changes` section in `Learning Wazuh` (https://documentation.wazuh.com/current/learning-wazuh/detect-fs-changes.html) needs to be updated as it contains wrong information (the last section and a reference to the use of the option `syscheck.debug` in Windows, for example).

Although this section is not present in the doctree anymore it can be accessed both directly and through the searching tool (if a word that is contained in this doc is searched this section will be shown).

**Comment by javierescobarcerezo** [comment]
Hi team,

I have created a PR regarding the issue https://github.com/wazuh/wazuh-documentation/pull/1399

**Comment by snaow** [comment]
PR closed and merged.
Thanks.
