### ISSUE TITLE
type is no longer an attribute of decoder tag but a full-fledged tag

### ISSUE THREAD

**Issue by Enaxadrel** [wazuh/wazuh-documentation#1286]
Hello, 

The attribute "type" for decoder tag doesn't work now and create a syntax error :
![image](https://user-images.githubusercontent.com/34360061/59355776-ef53d380-8d27-11e9-9308-c38a4c47bd4a.png)

The correct syntax is the "type" tag : 
![image](https://user-images.githubusercontent.com/34360061/59356046-66896780-8d28-11e9-8ba9-677729817e7a.png)

But the documentation for the 3.9 presents only the attribute : 
![image](https://user-images.githubusercontent.com/34360061/59356178-a3555e80-8d28-11e9-9bbd-ea6bfef93029.png)

I hope this help you to improve your documentation ^^

**Comment by DaveVG1** [comment]
Hi @Enaxadrel ,

You're absolutely right, this is an error in the documentation. I've fixed this in the following PR: https://github.com/wazuh/wazuh-documentation/pull/1290

Thank you so much for reporting this. 

Best regards,
David
