### ISSUE TITLE
Incorrect compatibility matrix for Agent on Windows OS

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#1294]
Hello Team,

I have realized that on the following page:https://documentation.wazuh.com/current/installation-guide/compatibility_matrix/index.html#wazuh-agent

The table shows that we support `Windows XP 2003` and `Windows server 2008`. Should it be Windows server 2003 instead of Windows server 2008? Shouldn't it be Windows XP instead of Windows XP 2003?

Regards,

Miguel Casares

**Comment by javierescobarcerezo** [comment]
Hi team, 
I made a PR to fix the issue: https://github.com/wazuh/wazuh-documentation/pull/1386

**Comment by snaow** [comment]
Merged, thanks @javierescobarcerezo GJ.
