### ISSUE TITLE
The WPK package has a size of 200 MB if documentation is followed

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#1304]
Hello team,

We have noticed if we follow the documentation to create a custom WPK package its size is 200 MB.

https://documentation.wazuh.com/current/user-manual/agents/remote-upgrading/create-custom-wpk.html?highlight=wpk

**Comment by DFolchA** [comment]
Hello team,

The size of the WPK can be reduced by deleting the files that are no longer useful after compiling the sources, as it is done in wazuh-packages:
```shellsession
clean() {
    rm -rf doc wodles/oscap/content/* gen_ossec.sh add_localfiles.sh Jenkinsfile*
    rm -rf src/{addagent,analysisd,client-agent,config,error_messages,external/*,headers,logcollector,monitord,os_auth,os_crypto,os_csyslogd,os_dbdos_execd}
    rm -rf src/{os_integrator,os_maild,os_netos_regex,os_xml,os_zlib,remoted,reportd,shared,syscheckd,tests,update,wazuh_db,wazuh_modules}
  
    if [[ "${BUILD_TARGET}" != "winagent" ]]; then
        rm -rf src/win32
    fi

    rm -rf src/*.a
    rm -rf etc/{decoders,lists,rules}

    find etc/templates/* -maxdepth 0 -not -name "en" | xargs rm -rf
}
```
I have updated the documentation to include this step.

Regards, 
Daniel Folch

**Comment by alberpilot** [comment]
Done
