### ISSUE TITLE
Update documentation for new Puppet Release

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-documentation#1310]
Hi team,

The Puppet release has been recently published: [Wazuh-Puppet](https://www.github.com/wazuh/wazuh-puppet)

In order to adapt the documentation, the following task must be done:

- [ ] Fix puppet version on the installation guide.

- [ ] Update module versions in installation examples

- [ ] Update manifest example to add Kibana, Elastic & Filebeat

- [ ] Add examples of new `ossec.conf` parameters. 

- [ ] Add examples of new features like install agent without registering it.

- [ ] Review Puppet parameters.

Best Regards,

Jose

**Comment by alberpilot** [comment]
Done
