### ISSUE TITLE
Kibana shows "Error: No Matching indices found:" after configuring search-guard.

### ISSUE THREAD

**Issue by decoyspikeyhair** [wazuh/wazuh-documentation#1318]
Following the Wazuh Documentation (https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/protect-installation/searchguard.html) for installing and configuring Search-Guard resulted in Kibana breaking and unable to see or use "wazuh-alerts-3.x-*

The filebeat.yml file was the default file that came with Filebeat 7.1.1. 
Versions for the other components involved were Elasticsearch 7.1.1 Wazuh 3.9 and Search Guard 35.0.0.  This was a fresh install on a test server, all in one setup. 

((Side Note: Also, I noted during the install if /usr/shared/elasticsearch/plugins  was not granted greater permissions (not sure what specifically it needed but i set 775) the search-guard plugin would fail to install. ))

After posting this to the Wazuh Slack Community we investigated the issue and found the filebeat.yml file was not referencing the wazuh-alerts-3.x-* index, was not passing data to elasticsearch, and could not authenticate  with elasticsearch.

To resolve this we replaced the existing filebeat.yml file with wazuh-filebeat .yml file found here (https://raw.githubusercontent.com/wazuh/wazuh/v3.9.2/extensions/filebeat/7.x/filebeat.yml)

We updated the file to ensure the index was created, add username and password for Search-Guard, and reference the host and ssl certs and keys used by elasticsearch and searchguard for authentication between the two. 
Once all of this was in place we were able to restore functionality of Kibana and use Search-Guard. 

Ultimately I think documentation should be updated to  include the correct filebeat.yml file for use with current Wazuh and Elastic along or a special note at least mention the need for this. 

Thanks to Javier Castro, Juan Carlos Tello and especially to Wali for all the help and support with this issue!

**Comment by elwali10** [comment]
Hello @decoyspikeyhair 

I have created this PR https://github.com/wazuh/wazuh-documentation/pull/1324 to enhance our SearchGuard documentation.

Thanks for reporting this.

I'm going to close this issue, feel free to re-open it.

Regards,
Wali.
