### ISSUE TITLE
Adapt SCA documentation to the refactor of the module

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh-documentation#1333]
The SCA module is having a refactor: https://github.com/wazuh/wazuh/issues/3249

Due to these changes the documentation needs an update.
- Change the rule syntax
- Remove the old policies and add new policies
- Review the examples
- Add the documentation of `compare`

**Comment by JuantAldea** [comment]
Updating documentation in branch https://github.com/wazuh/wazuh-documentation/tree/1333-adapt-sca-docu

Several tables added, style changes, syntax updates.
