### ISSUE TITLE
How to build up an Inventory data dasbhoard?

### ISSUE THREAD

**Issue by langyajiekou** [wazuh/wazuh-documentation#1355]
How to build up an Inventory data dashboard? so that can easy search and filter the packages that which hosts have been installed.

**Comment by juankaromo** [comment]
Hi @langyajiekou 

I don't know if this is exactly what you mean, but in the Wazuh app you can find the Inventory data section that does what you're asking for.

All you need to do is enter the Wazuh plugin from Kibana, go to the Agents section and select the agent that belongs to the host you are interested in.

![image](https://user-images.githubusercontent.com/21195730/61434802-40627300-a937-11e9-91c7-475bd322c9a4.png)

Then once inside the agent, you must enter the inventory data section, which collects applications, network configuration, open ports and processes running on your host.

![image](https://user-images.githubusercontent.com/21195730/61434904-83bce180-a937-11e9-8dd7-c4a786cba2d9.png)

Inside that section, you will find the table you are looking for, from which you can search or filter the packages that the host has installed.

![image](https://user-images.githubusercontent.com/21195730/61435122-165d8080-a938-11e9-9bdb-68fff7172fcc.png)

Tell me if this was what you needed, or if on the contrary, you need for example that these data are shown in a graphical visualization.

On the other hand, we have an open ticket to include in future versions the possibility of using external visualizations or your own. Here you can find it https://github.com/wazuh/wazuh-kibana-app/issues/1609

Hope this helps.

Regards,

**Comment by langyajiekou** [comment]
> 
> 
> Hi @langyajiekou
> 
> I don't know if this is exactly what you mean, but in the Wazuh app you can find the Inventory data section that does what you're asking for.
> 
> All you need to do is enter the Wazuh plugin from Kibana, go to the Agents section and select the agent that belongs to the host you are interested in.
> 
> ![image](https://user-images.githubusercontent.com/21195730/61434802-40627300-a937-11e9-91c7-475bd322c9a4.png)
> 
> Then once inside the agent, you must enter the inventory data section, which collects applications, network configuration, open ports and processes running on your host.
> 
> ![image](https://user-images.githubusercontent.com/21195730/61434904-83bce180-a937-11e9-8dd7-c4a786cba2d9.png)
> 
> Inside that section, you will find the table you are looking for, from which you can search or filter the packages that the host has installed.
> 
> ![image](https://user-images.githubusercontent.com/21195730/61435122-165d8080-a938-11e9-9bdb-68fff7172fcc.png)
> 
> Tell me if this was what you needed, or if on the contrary, you need for example that these data are shown in a graphical visualization.
> 
> On the other hand, we have an open ticket to include in future versions the possibility of using external visualizations or your own. Here you can find it [wazuh/wazuh-kibana-app#1609](https://github.com/wazuh/wazuh-kibana-app/issues/1609)
> 
> Hope this helps.
> 
> Regards,

thank your quick response, however, this inventory data section is just for single host, but I would like to know which host has a special package installed, and what version it is. say tomcat. however, I couldn't find it from Wazuh, but when I use experimental search all agents, it always has timeout executing API request returned.

**Comment by juankaromo** [comment]
Hi @langyajiekou 

Unfortunately the experimental API calls are still under development: they're slower than a normal API call and they can be changed in future releases if we find a better way to implement them. That's why they're experimental. 

You can use them but knowing that they are susceptible to failure.

This functionality you are asking for is not included in the list of 'official' requests, so feel free to open a feature-request issue, or to improve the one that already exists in an experimental way.

Regards.
