### ISSUE TITLE
Ansible Debian/Ubuntu installation steps missing 

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-documentation#1367]
Hell team,

this link: https://documentation.wazuh.com/current/deploying-with-ansible/guide/install-ansible.html#installation-on-debian-ubuntu 

is missing `#` in the `Setup ansible repository` step for Debian:

```
# echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/ansible-debian.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
apt-get update
```

Regards.

**Comment by paroma96** [comment]
Hi Team,
Solved at PR https://github.com/wazuh/wazuh-documentation/pull/1393
Greetings.

**Comment by snaow** [comment]
Thanks, merged.
