### ISSUE TITLE
Wrong code at Wazuh server Installation Guide with OpenSUSE

### ISSUE THREAD

**Issue by paroma96** [wazuh/wazuh-documentation#1390]
Hi, team.
 I've recently seen a mistake with the code in the following link:

https://documentation.wazuh.com/current/installation-guide/installing-wazuh-server/wazuh_server_rpm_suse_opensuse.html

To disable the Wazuh repository, 
it cannot be: sed -i "s/^enabled=1/enabled=0/" /etc/yum.repos.d/wazuh.repo

**Comment by paroma96** [comment]
Corrected with PR #1394

**Comment by MiguelCasaresRobles** [comment]
This was solved in this PR: #1397
