### ISSUE TITLE
ADD NEW API error

### ISSUE THREAD

**Issue by wooyunvip** [wazuh/wazuh-documentation#140]
when i add new api and click save ，i have a error message "Invalid user field" ,how can i do ?thank you ！

**Comment by JuanjiJG** [comment]
Hi @wooyunvip,

Make sure you insert the correct API credentials. Use the following command to test your connection:
`curl -u <api_username>:<api_password> -XGET -k "http://<api_ip_address>:55000?pretty"`

You should get an output similar to **this**:
```JSON
{
   "error": 0,
   "data": {
      "msg": "Welcome to Wazuh HIDS API",
      "api_version": "v3.1.0",
      "hostname": "node01",
      "timestamp": "Tue Jan 09 2018 16:26:44 GMT+0100 (CET)"
   }
}
```

After checking your credentials, try again to insert them into the app.

Best regards,
Juanjo

**Comment by wooyunvip** [comment]
@JuanjiJG  thank you !!!
