### ISSUE TITLE
Update Remote syslog documentation

### ISSUE THREAD

**Issue by javierescobarcerezo** [wazuh/wazuh-documentation#1401]
Hi team,

In this [page](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-it-works.html), in the `Remote syslog` section. The first option to have Wazuh listening to a port to get syslog logs is incomplete: there are no `<port>` nor `<protocol>` options where it should be: 

```
<remote>
    <connection>syslog</connection>
    <port>513</port>
    <protocol>udp</protocol>
    <allowed-ips>172.16.1.0/24</allowed-ips>
</remote>
```

Also, the examples could be better explained, specially the relationship between syslog and Wazuh.

Regards.

**Comment by javierescobarcerezo** [comment]
Hi team, 
I have created a PR to resolve the issue: https://github.com/wazuh/wazuh-documentation/pull/1402

**Comment by snaow** [comment]
Merged. Thanks.
