### ISSUE TITLE
Add a guide about creating custom kibana dashboards

### ISSUE THREAD

**Issue by jojelupipa** [wazuh/wazuh-documentation#1405]
We have created a guide to help the users out to create their custom dashboards.

This guide includes how to:

- [x] Create Visualization
- [x] Save a Visualization
- [x] Create a Custom Dashboard
- [x] Save a Custom Dashboard

**Comment by MiguelCasaresRobles** [comment]
Solved here: https://github.com/wazuh/wazuh-documentation/pull/1407
