### ISSUE TITLE
Highliting not working

### ISSUE THREAD

**Issue by jojelupipa** [wazuh/wazuh-documentation#1430]
Tested on Firefox, Chromium, and Chrome.

![imagen](https://user-images.githubusercontent.com/14235896/63035491-84578200-bebb-11e9-9fb3-cf2968dad9da.png)

As can be seen in the URL, the word "active" should be highlighted. But, as shown in the image, it is not.

**Comment by vamera** [comment]
Hi,
Thanks for letting us know about this problem.

This has been fixed for every branch:
 - PR for 3.9: https://github.com/wazuh/wazuh-documentation/pull/1453
 - PR for 3.8: https://github.com/wazuh/wazuh-documentation/pull/1464
 - PR for 3.7: https://github.com/wazuh/wazuh-documentation/pull/1465
 - PR for 3.6: https://github.com/wazuh/wazuh-documentation/pull/1466
 - PR for 3.5: https://github.com/wazuh/wazuh-documentation/pull/1467
 - PR for 3.4: https://github.com/wazuh/wazuh-documentation/pull/1468
 - PR for 3.3: https://github.com/wazuh/wazuh-documentation/pull/1469
 - PR for 3.2: https://github.com/wazuh/wazuh-documentation/pull/1470
 - PR for 3.1: https://github.com/wazuh/wazuh-documentation/pull/1471
 - PR for 3.0: https://github.com/wazuh/wazuh-documentation/pull/1472
 - PR for 2.1: https://github.com/wazuh/wazuh-documentation/pull/1473
