### ISSUE TITLE
Elastic Stack installation guide does not have single/distributed host environment specification

### ISSUE THREAD

**Issue by jojelupipa** [wazuh/wazuh-documentation#1447]
Following the [instructions to install elastic stack](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_rpm.html) will lead you to an unfinished configuration setting up a distributed environment.

We should improve this section of the documentation. 

On [the index of this section](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/index.html) we should clearly split the sections into *Single Host Installation* and *Distributed Environment Installation*. Pay special attention to *Distributed Environment Installation* as you can use a cluster of Elasticsearch or just a single instance.

E.g. elastic search configuration should have its fields *"network.host"* and *"discovery.seed_hosts"* properly set.

Things we should improve:

- [x] Re-structure the [index](https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/index.html)

- [ ] Adding a section for the *Distributed Environment Installation* having a single Elasticsearch instance: https://github.com/wazuh/wazuh-documentation/issues/1448

- [ ] Adding a section for the *Distributed Environment Installation* having an Elasticsearch cluster: https://github.com/wazuh/wazuh-documentation/issues/1449

**Comment by MiguelCasaresRobles** [comment]
`Adding a section for the Distributed Environment Installation having a single Elasticsearch instance: #1448` Added here: https://github.com/wazuh/wazuh-documentation/pull/1446/files

**Comment by alberpilot** [comment]
Done in branch `new-documentation-structure`. It will be merged soon. 

Regards, 
Alberto R
