### ISSUE TITLE
Documentation for Wazuh Puppet module installation has mistakes

### ISSUE THREAD

**Issue by alguacilaguamara** [wazuh/wazuh-documentation#1575]
Hello team,

Command to install the Wazuh module from Puppet Forge in the documentation https://documentation.wazuh.com/current/deploying-with-puppet/wazuh-puppet-module/index.html#install-wazuh-module, there is a mistake in this line

```# puppet module install wazuh-wazuh --version 3.9.5```

The error code is:

```
Notice: Preparing to install into /etc/puppetlabs/code/environments/production/modules ...

Notice: Downloading from https://forgeapi.puppet.com ...
Error: Could not install 'wazuh-wazuh' (v3.9.5)
  No releases matching '3.9.5' are available from https://forgeapi.puppet.com
```

The command should be.

```# puppet module install wazuh-wazuh --version 3.9.5-1```

Regards.

**Comment by manuasir** [comment]
Hello @alguacilaguamara ,

Thanks for reporting this. Currently preparing a new PR to solve it.

Regards

**Comment by manuasir** [comment]
Hello @alguacilaguamara,


Fixed here: https://github.com/wazuh/wazuh-documentation/pull/1591
Thanks for your collaboration.

Regards
