### ISSUE TITLE
Wazuh 3.x Documentation Regarding Capabilities and VULS

### ISSUE THREAD

**Issue by GJSmith3rd** [wazuh/wazuh-documentation#166]
I have Wazuh 3.x installed on a PC with Ubuntu 16.04 LTS Desktop, with several other Windows 10 PCs running agents, in a SOHO environment. Everything is working fine and I have just completed VirusTotal integration successfully.

I started the VULS integration installation script and immediately ran into a problem:

`# /var/ossec/wodles/vuls/deploy_vuls.sh ubuntu 16`

> ...This script will install dependencies, download VULS, download CVE and OVAL databases, and configure VULS. This deployment supports the following operating systems:...

> https://documentation.wazuh.com/3.x/user-manual/capabilities/vuls.html#how-it-works

The referenced documentation above fails to mention that if you run the installation script, on a Ubuntu 16 Desktop PC, it will uninstall the Ubuntu Desktop among other things like (pardon paraphrases) ttf-mscorefonts-installer, ubuntu-desktop, update-manager, ubuntu-release-updater-gtk, update-notification-common.

I'm sure not many are running this type of software on desktop PCs but it would have been helpful to get a warning.

Just thought someone should know.

**Comment by GJSmith3rd** [comment]
Ok, after a reboot I still have a desktop GUI which is what I was concerned about - feel a bit lucky on that on. Everything seems to be working fine even after the uninstalls.  VULS is reporting alerts for the Linux manager - 




`

**Comment by sarankals** [comment]
unable to find deploy.sh script /var/ossec/wodles/vuls/deploy_vuls.sh
-su: /var/ossec/wodles/vuls/deploy_vuls.sh: No such file or directory

when i ran unable to find deploy_vuls.sh in ubuntu 18.04

**Comment by sarankals** [comment]
Hi
let me know path to find 
/var/ossec/wodles/vuls/deploy_vuls.sh in ubuntu 16 & ubuntu 18

**Comment by JuanjiJG** [comment]
Hello @sarankals

The VULS integration was deprecated since the release of Wazuh v3.5.0. You can still find the VULS deployment script on [this link](https://github.com/wazuh/wazuh/tree/v3.4.0/wodles/vuls).

If you can't find the script on your installation directory, that means you're using a more recent version of Wazuh, and we strongly recommend you using our native [vulnerability detection tool](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection.html).

Let us know if you have more questions.

Regards,
Juanjo

**Comment by sarankals** [comment]
i checked the script which is shared in git hub no windows vulerabilities found
    echo "          - redhat 7, redhat 6, readhat 5"
    echo "          - centos 7, centos 6, centos 5"
    echo "          - ubuntu 16, ubuntu 14, ubuntu 12"
    echo "          - debian 10, debian 9, debian 8, debian 7"
    echo "          - oracle 7, oracle 6, oracle 5"
    exit 1

**Comment by JuanjiJG** [comment]
Hi again @sarankals,

Our VULS script is not compatible with Windows vulnerabilities. As you can see, the allowed values to deploy VULS on your Wazuh manager are primarily Linux Operating Systems.

Let us know if you have more questions.

Regards,
Juanjo

**Comment by sarankals** [comment]
Hi juanjo,

kindly let me know policy can be created for windows vuls.

regards,
Saravana.

**Comment by JuanjiJG** [comment]
Hi @sarankals,

Unfortunately, according to the [VULS documentation](https://vuls.io/docs/en/supported-os.html), Windows systems are not supported at this moment.

Regards,
Juanjo
