### ISSUE TITLE
Update ossec.conf documentation

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-documentation#1735]
Hello team,

The documentation for the `ossec.conf` does not indicate that it is possible to have multiple `<ossec_config>`  blocks, this is a useful feature and should be shown in our documentation.

Also, we should include a section explaining how creating a new block may affect the configuration set by the blocks that already exist in the ossec.conf file.

Regards, 
Daniel Folch

**Comment by jaymecd** [comment]
It's very important to note, `ossec.conf` with multiple root elements, no longer considered a valid XML document, so `xmllint` would fail.

As a workaround wrap content with a single root tag:

```
$ sed -e '1s,^,<x>,;$s,$,</x>,' /var/ossec/etc/ossec.conf | xmllint - >/dev/null
```

**Comment by DFolchA** [comment]
Hello team,

Thanks to @jaymecd for reporting this issue in our Slack channel, if there is any other problem you need help do not hesitate to contact us and we will do our best to help you.

And thank you for your contribution to solve the problem.

Regards
Daniel Folch
