### ISSUE TITLE
Update the Getting started section

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-documentation#1736]
The content of the `Getting started` section is very outdated.

https://documentation.wazuh.com/3.9/getting-started/index.html#getting-started

It talks about how the Wazuh solution is composed. Including at the same level the OSSEC product, OpenSCAP and ElasticStack. Now, the Wazuh core is composed of much more modules, differentiating from OSSEC and including other important components and features.

**Comment by alberpilot** [comment]
Done and updated. 
Regards, 
Alberto R
