### ISSUE TITLE
Wazuh Alert Level Description

### ISSUE THREAD

**Issue by nizarakbarm** [wazuh/wazuh-documentation#177]
Hello, i am trying to learn about wazuh ruleset and create my own ruleset but i need to know the description of every level which is written in core ruleset of wazuh.

**Comment by PSanchezR** [comment]
Hello nizarakbarm,

I'm Pablo and I'm gonna try to help you as much as I can.
First of all, thank you for contributing to this repository. Alert levels are related to the alert's severity, so you can configure your set of rules accordingly. You can configure from which level the alerts will be displayed in the manager as follow:

```xml
<alerts>
  <log_alert_level>3</log_alert_level>.
  <email_alert_level>12</email_alert_alert>
</alerts>
```
In the previous code you can see the alert level configuration fields in the ossec.conf file of the manager (those are the default values), you can configure when the alert must be reported to the manager, with "log_alert_level", and when the alert must be sended to the sysadmin, with "email_alert_level". You can find this information in https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/alerts.html?highlight=alert#log-alert-level

If you have any other question don't hesitate to contact us.

Best regards,

Pablo.
