### ISSUE TITLE
Building documentation with Docker results in an endless loop

### ISSUE THREAD

**Issue by jm404** [wazuh/wazuh-documentation#1802]
Hi team,

When building the Wazuh Documentation using the Dockerfile by running:

```
docker build -t sphinx-autobuild .
docker run -it -p 8000:8000 --rm -v "$(pwd)/source":/home/python/docs sphinx-autobuild
```

The build process detects changes on some `.css` files, rebuilding continously and resulting in an infinite loop.

As @vamera stated, error could be associated with some dynamic files getting modified during the build process which triggers the rebuild as sphinx detects a file changed.

Best regards,

Jose

**Comment by vamera** [comment]
If changed the code in charge of the minification to;
1. Check if the minified file exists before the compilation process. If the minified file does not exist, it will be created as usual.
2. If the minified file exists, its content is compared to the content of the original non-minified file once processed for the minification but before it is written to a file.
  - If the content is exactly the same, the minified file will remain unchanged.
  - If the content is different, the minified file will be overwritten.

This solves the compilation loop as the minified files will we created and rewritten only when required.

Note: to test this solution without Docker, go to the root directory containing the documentation and use this command:

`sphinx-autobuild -b html -d build/doctrees source build/html`
