### ISSUE TITLE
Sregex format not specified

### ISSUE THREAD

**Issue by rafamunoz98** [wazuh/wazuh-documentation#1819]
Hello team.
The `location` parameter of the reports section accepts Sregex format but it is not specified in the documentation. It is important information which users should know.
Example of configuration:
```
<reports>
  <title>Example_Report</title>
  <location>10.0.0.|10.0.5.|10.0.3.3|10.0.6.4</location>
  <email_to>recipient@example.wazuh.com</email_to>
</reports>
```
This also affects `group, rule, level, user, srcip, filename`
https://documentation.wazuh.com/3.10/user-manual/reference/ossec-conf/reports.html#location
Regards,
Rafa.

**Comment by MiguelCasaresRobles** [comment]
Merged: https://github.com/wazuh/wazuh-documentation/pull/1871
