### ISSUE TITLE
Incorrect command on macos deployment variables examples.

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh-documentation#1846]
Hello team! We've detected a failure in the [documentation about deployment variables for OSX](https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-agent/deployment_variables/deployment_variables_macos.html#deployment-variables-macos).

There are some snippets such as:

```java
# launchctl setenv WAZUH_MANAGER="10.0.0.2" WAZUH_REGISTRATION_PASSWORD="TopSecret" \
     WAZUH_AGENT_NAME="aix-agent" && installer -pkg wazuh-agent-3.10.1-1.pkg -target
```

That doesn't work. After the `-target` flag, a path must be given (for example `/`).

We might solve that.

Best regards,

**Comment by alberpilot** [comment]
Done
