### ISSUE TITLE
CIS-CAT Integration XML Typos

### ISSUE THREAD

**Issue by sgreatorex** [wazuh/wazuh-documentation#1874]
Hi,

There's a couple of typos in an XML tag for the CIS-CAT Integration where `<wday>monday</monday>`  should be `<wday>monday</wday>`.

https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/capabilities/policy-monitoring/ciscat/ciscat.rst#scheduling-executions-by-day-of-the-week.

**Comment by javierescobarcerezo** [comment]
Hi, 
We have updated this PR(https://github.com/wazuh/wazuh-documentation/pull/1388) to resolve this issue.

**Comment by alberpilot** [comment]
Done. I proceed to close this issue. Don't hesitate to open it again if needed.
