### ISSUE TITLE
Directives - Menu. Error. Could not locate that index-pattern

### ISSUE THREAD

**Issue by begize** [wazuh/wazuh-documentation#191]
hi:
in the Wazuh page top show "Directives - Menu. Error. Could not locate that index-pattern (id: f1175040-d5c5-11e7-8ef5-a5944cf52264), click here to re-create it"
but i click to recreate, it's don't work  ,in the same time , in the Discover page  filter "wazuh-alert-3.x-*" show "No results found"

please tell me how to fix it ,thanks~~

**Comment by JuanjiJG** [comment]
Hello @begize,

I'll try to help you with this.

I need to get some information about your current Wazuh installation. Could you please send me the content of your `package.json` file? You can get it with this command:
`cat /usr/share/kibana/plugins/wazuh/package.json`

Also, I need information about your current indices and templates. Please, execute the following commands:
```
curl -XGET localhost:9200/_cat/indices?v
curl -XGET localhost:9200/_cat/templates?v
```

Paste here all the results. Thanks for your patience.

Regards,
Juanjo

**Comment by begize** [comment]
**cat /usr/share/kibana/plugins/wazuh/package.json**

{
  "name": "wazuh",
  "version": "3.2.1",
  "revision": "0386",
  "kibana": {
    "version": "6.2.2"
  },
  "description": "Wazuh App",
  "main": "index.js",
  "keywords": [
    "kibana",
    "wazuh",
    "ossec"
  ],
  "author": "Wazuh, Inc",
  "license": "GPL-2.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/wazuh/wazuh-kibana-app.git"
  },
  "bugs": {
    "url": "https://github.com/wazuh/wazuh-kibana-app/issues"
  },
  "homepage": "https://www.wazuh.com/",
  "dependencies": {
    "angular-animate": "1.6.5",
    "angular-aria": "1.6.5",
    "angular-cookies": "1.6.5",
    "angular-material": "1.1.1",
    "angular-md5": "^0.1.10",
    "ansicolors": "^0.3.2",
    "install": "^0.10.1",
    "js-yaml": "3.10.0",
    "lodash": "3.10.1",
    "needle": "^2.0.1",
    "node-cron": "^1.1.2"
  }
}

**curl -XGET localhost:9200/_cat/indices?v**
health status index                           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
yellow open   wazuh-monitoring-3.x-2018.03.22 W9HtE2m_RiOPfe5p3TtZ0Q   5   1         83            0    375.6kb        375.6kb
yellow open   wazuh-alerts-3.x-2018.03.22     tzPdUC27Q06YFpmM9BB40g   5   1        139            0    372.6kb        372.6kb
yellow open   wazuh-alerts-3.x-2018.03.23     SIGcYu0lTqCzp77w80Vf7w   5   1          2            0     25.3kb         25.3kb
yellow open   .wazuh                          DgoFRM0IQmK-rzbhjvqhOw   1   1          1            0       10kb           10kb
yellow open   .kibana                         DT3kPAvQTzSDn8XRmFk_0A   5   1        266            1    228.9kb        228.9kb
yellow open   wazuh-monitoring-3.x-2018.03.23 VuO5GhoFRxG_NCYyOjf2pQ   5   1         55            0      470kb          470kb
yellow open   .wazuh-version                  ozqGFDblTda-OgIFCiEf3Q   1   1          1            0      4.9kb          4.9kb

 **curl -XGET localhost:9200/_cat/templates?v**
name                          index_patterns       order version
kibana_index_template:.kibana [.kibana]            0
wazuh                         [wazuh-alerts-3.x-*] 0
wazuh-agent                   [wazuh-monitoring*]  0
wazuh-kibana                  [.kibana*]           0
logstash                      [logstash-*]         0     60001

**Comment by JuanjiJG** [comment]
Hello again @begize,

Your templates are not correctly inserted. Let's try a few steps to clear your Wazuh app installation. Execute the following commands as superuser:

1. Stop the Kibana and Logstash services:
```bash
systemctl stop logstash
systemctl stop kibana
```

2. Delete the Wazuh app indices and the `.kibana` index. *Warning:* Deleting the `.kibana` index will remove your custom Kibana visualizations and saved searches. 
```bash
curl -XDELETE localhost:9200/.kibana
curl -XDELETE localhost:9200/.wazuh
curl -XDELETE localhost:9200/.wazuh-version
```

3. Delete the Kibana optimization bundles. Don't worry about this, they're just cached files for faster loading times when using Kibana.
```bash
rm -rf /usr/share/kibana/optimize/bundles
```

4. Insert the Wazuh Elasticsearch templates and the sample alert:
```bash
curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/wazuh-elastic6-template-alerts.json | curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-
curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/wazuh-elastic6-template-monitoring.json | curl -XPUT 'http://localhost:9200/_template/wazuh-agent' -H 'Content-Type: application/json' -d @-
curl https://raw.githubusercontent.com/wazuh/wazuh/3.2/extensions/elasticsearch/alert_sample.json | curl -XPUT "http://localhost:9200/wazuh-alerts-3.x-"`date +%Y.%m.%d`"/wazuh/sample" -H 'Content-Type: application/json' -d @-
```

5. Restart the Kibana and Logstash services:
```bash
systemctl restart logstash
systemctl restart kibana
```

Now try to open the app again, and see if everything is working now properly. Please, let me know about the results. Thanks for your patience.

Regards,
Juanjo

**Comment by begize** [comment]
hi juanjo:
thanks for help , but after this steps , same error show again, new information for you  

` cat /usr/share/kibana/plugins/wazuh/package.json`
{
  "name": "wazuh",
  "version": "3.2.1",
  "revision": "0386",
  "kibana": {
    "version": "6.2.2"
  },
  "description": "Wazuh App",
  "main": "index.js",
  "keywords": [
    "kibana",
    "wazuh",
    "ossec"
  ],
  "author": "Wazuh, Inc",
  "license": "GPL-2.0",
  "repository": {
    "type": "git",
    "url": "https://github.com/wazuh/wazuh-kibana-app.git"
  },
  "bugs": {
    "url": "https://github.com/wazuh/wazuh-kibana-app/issues"
  },
  "homepage": "https://www.wazuh.com/",
  "dependencies": {
    "angular-animate": "1.6.5",
    "angular-aria": "1.6.5",
    "angular-cookies": "1.6.5",
    "angular-material": "1.1.1",
    "angular-md5": "^0.1.10",
    "ansicolors": "^0.3.2",
    "install": "^0.10.1",
    "js-yaml": "3.10.0",
    "lodash": "3.10.1",
    "needle": "^2.0.1",
    "node-cron": "^1.1.2"
  }
}

`curl -XGET localhost:9200/_cat/indices?v`

health status index                           uuid                   pri rep docs.count docs.deleted store.size pri.store.size
green  open   .kibana                         QRqKMTcpQJyKEWydtsH6rQ   1   0        266            2      181kb          181kb
yellow open   .wazuh-version                  9PuhsY7oSQapTM4Oz9X6ww   1   1          1            0      4.9kb          4.9kb
yellow open   .wazuh                          Z82FnHcATZOdwN_hOryXYw   1   1          1            0       10kb           10kb
yellow open   wazuh-monitoring-3.x-2018.03.22 W9HtE2m_RiOPfe5p3TtZ0Q   5   1         83            0    375.6kb        375.6kb
yellow open   wazuh-alerts-3.x-2018.03.22     tzPdUC27Q06YFpmM9BB40g   5   1        139            0    372.6kb        372.6kb
yellow open   wazuh-alerts-3.x-2018.03.23     SIGcYu0lTqCzp77w80Vf7w   5   1         30            0    230.6kb        230.6kb
yellow open   wazuh-monitoring-3.x-2018.03.23 VuO5GhoFRxG_NCYyOjf2pQ   5   1         57            0    382.5kb        382.5kb

`curl -XGET localhost:9200/_cat/templates?v`
name                          index_patterns       order version
logstash                      [logstash-*]         0     60001
wazuh                         [wazuh-alerts-3.x-*] 0
wazuh-kibana                  [.kibana*]           0
wazuh-agent                   [wazuh-monitoring*]  0
kibana_index_template:.kibana [.kibana]            0

**Comment by begize** [comment]
hi juanjo:
I try reinstall in centos 7 few time. I find a illogical question, 
If the hostname use "wazuh.suntech.com.tw" that will show this error, use other world don't.
so i reinstall  and  use other hostname , this question is done
thanks for you help

Regards,

**Comment by JuanjiJG** [comment]
Hello again @begize,

I'm glad you finally solved your problem.

That's a very weird situation. The team will take a look into that, so we can see if there are some possible bugs with that.

Thanks for your feedback and patience.

Regards,
Juanjo
