### ISSUE TITLE
Fix Elasticsearch upgrade breaking changes

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-documentation#1910]
Hi team,

There is an issue with the Elastic 6.8 to 7.x guide. It has a step that includes the `cluster.initial_master_nodes: ` option, but it is missing `discovery.seed_hosts:` which is the actual configuration that will allow cluster nodes to discover the masters.

The option we are currently considering is a bootstrapping tool, not the actual discovery config.

Here you can find more information: https://www.elastic.co/guide/en/elasticsearch/reference/current/discovery-settings.html#initial_master_nodes

Best regards,
Miguel

**Comment by MiguelCasaresRobles** [comment]
Merged
