### ISSUE TITLE
The documentation does not show the versions to install the Wazuh manager and API in later versions. 

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-documentation#1921]
Hello team,

The documentation does not show the versions to install the Wazuh manager and API in versions prior to the last one, therefore we will always install the last version regardless of the version selector. 

![image](https://user-images.githubusercontent.com/8913336/66664322-99972580-ec4c-11e9-90c4-f6d9ec7ca78f.png)

Best reagards,

Alfonso Ruiz-Bravo

**Comment by alberpilot** [comment]
Duplicated: https://github.com/wazuh/wazuh-documentation/issues/2301
