### ISSUE TITLE
Improve AWS documentation

### ISSUE THREAD

**Issue by crd1985** [wazuh/wazuh-documentation#1948]
## Introduction

AWS wodle documentation should be updated and improved. Some points give users a wrong idea of how to use and configure the wodle.

## Points to be fixed:
- [x] Section `Monitoring AWS services` relies on the user having read the prerequisites section first. This could be fixed by reordering the sections a giving more visibility to the prerequisites section. This must be the first thing a user should be when reading the doc.
- [x] Section `AWS S3 bucket` should be better placed inside the prerequisites section to avoid confusions with other services.
- [x] `aws_profile` could be misunderstood as mandatory, although is the recommended approach. Maybe this could be fixed thanks to point 1.
- [x] The bucket type `custom` requires a more detailed explanation. Many users gets confused and deduce that `custom` may be used for any service. It must be clearly detailed which services can be monitored with it.
- [x] Error codes explanation is very poor. A simple explanation about the cause of the error and how to proceed should be added.

**Comment by druizz90** [comment]
# Issue update

I am working in branch `dev-improve-aws-docs-1948` for solving this issue.

Sections about monitoring `AWS` services are the next after the rework:

![aws_1](https://user-images.githubusercontent.com/32929872/67362767-0f17c580-f56c-11e9-988a-780914dd2eae.png)

The `AWS` services and the wodle configurations are in the first position now (`prerequisites`). Section about configuring an `S3` bucket is placed in the `prerequisites` section too.

About `custom` buckets, I put clearly the services which are available for our integration. Services which are configured as `custom` type in the wodle only mentions this type in their configuration section.

In `troubleshooting` section, a new column for giving a possible remediation to an error code was added.
