### ISSUE TITLE
Fix error in agent status

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-documentation#198]
https://documentation.wazuh.com/3.x/user-manual/agents/agent-life-cycle.html#agent-status

An agent is considered disconnected when no keep-alive was received from it within the last 30 minutes, no matter the protocol –so far–.

Related issue: https://github.com/wazuh/wazuh/issues/507

**Comment by JuanjiJG** [comment]
Hello @vikman90.

I've added your suggestion to the documentation in #199. If the fix is good for you, we can merge it right now into the branch.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
I'll close this issue since it's now fixed in #199.

Regards,
Juanjo
