### ISSUE TITLE
wazuh-agent MSI variables

### ISSUE THREAD

**Issue by rossengeorgiev** [wazuh/wazuh-documentation#1985]
There used to be list of all variables supported by the `wazuh-agent.msi`. Is that still available? I cannot seem to find it.

**Comment by alberpilot** [comment]
Hello @rossengeorgiev 

  Here you will find the list: https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-agent/deployment_variables/deployment_variables_windows.html

Please let me know if you have any questions. 
Best regards, 
Alberto R

**Comment by rossengeorgiev** [comment]
Thanks
