### ISSUE TITLE
Lack of information regarding rules syntax

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh-documentation#1998]
Hello team,

By looking at our documentation about [Rules Syntax](https://documentation.wazuh.com/3.10/user-manual/ruleset/ruleset-xml-syntax/rules.html) It is easy to see there is almost no information about some of the options.

For example, the field `<same_id>` shows the following information:

```
Specifies that the decoded id must be the same. This option is used in conjunction with frequency and timeframe.
```

I've seen this is the same documentation that is shown in the Ossec project:

![image](https://user-images.githubusercontent.com/47329460/67953572-ac6b9d00-fbef-11e9-9081-95bfb5b24079.png)

The problem here is that it is not possible to know if that option is related to the `alert id`, the `rule.id` or the `agent.id`.

**Comment by davidfmiranda** [comment]
Hello @DanielMorLoz, we have included more information related to this issue since it was created. For example in PR #1297 and #2252 the rules section has been improved.

Nevertheless, do not hesitate to open this issue again if you consider it necessary.

Best regards,

David
