### ISSUE TITLE
wazuh AWS Config documentation and wazuh code not in sync

### ISSUE THREAD

**Issue by gopivalleru** [wazuh/wazuh-documentation#2001]
Documentation says to use Cloudwatch to send Config events to firehose. firehose sends logs to S3. In this flow AWS is creating this directory structure under prefix: YYYY/MM/DD/HH

S3 bucket that we use for config to store configuration history and configuration snapshot files has this directory structure under prefix: /AWSLogs/<ACCOUNT_NUMBER>/Config/<REGION>/YYYY/MM/DD/ConfigHistory.

AWS services integration code (aws-s3.py) looks to get logs from the later path. Please make changes to the documentation which confusing so that it would eliminate confusion. 

Also please refer to https://groups.google.com/forum/#!topic/wazuh/3aq47N1rwvY

**Comment by druizz90** [comment]
Hi @gopivalleru,

I responded to you in https://groups.google.com/forum/#!topic/wazuh/3aq47N1rwvY.

I made the PR (https://github.com/wazuh/wazuh-documentation/pull/2002) for including this screenshot, where you can see the path of your `AWS Config` logs:

![aws-create-config-1](https://user-images.githubusercontent.com/32929872/68112057-cc9da380-fef0-11e9-846e-fd36c2d1386c.png)

Best regards,

Demetrio.

**Comment by alberpilot** [comment]
I proceed to close this issue. Thanks, @druizz90 and @gopivalleru.
