### ISSUE TITLE
please add "uninstall" section to "install from sources"

### ISSUE THREAD

**Issue by supersexy** [wazuh/wazuh-documentation#2068]
The docs about installing [from sources](https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-agent/linux/debian7-or-greater/wazuh_agent_sources_debian7_or_greater.html#wazuh-agent-sources-debian7-or-greater) are missing an uninstall section. It s not clear how to remove the software. Also there no information about how to do updates.

**Comment by Zenidd** [comment]
Hello @supersexy,

Thank you for pointing this out. We should quickly add this section. As soon as our workflow allows it we will extend the documentation with detailed steps for uninstallation.

On the other hand, you can find the [Wazuh and Elastic Stack Upgrade guide](https://documentation.wazuh.com/3.10/upgrade-guide/index.html) in our documentation. It is located in a separate section from the installation guide.

Greetings, JP Sáez
