### ISSUE TITLE
Review regex and order decoder settings descriptions

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-documentation#2091]
Hello,
I noticed that the regex and order settings need certain others to properly work, but the documentation doesn't mention it.

### regex

The regex setting needs, as far as my testing goes:
- A `prematch` tag in the same decoder or
- A `program_name`  tag in the same decoder or
- A `parent` tag that will, in turn, have a `prematch` or `program_name` tag in it.

### order

This setting needs the `regex` one in the very same decoder where it is defined.

Regards, 
Javier.

**Comment by davidfmiranda** [comment]
Hello Javier,
I do not really understand why those labels should be mandatory. Here is an example of a decoder and a rule without using them and how it successfully worked: 

Here is the decoder:
```
<decoder name="evil">
  <program_name>^evil</program_name>
</decoder>

<decoder name="evil">
  <parent>evil</parent>
  <regex>User '(\w+)' from '(\d+.\d+.\d+.\d+)'</regex>
  <order>dstuser, srcip</order>
</decoder>
```
Here is the rule:
```
  <rule id="100010" level="0">
    <program_name>evil</program_name>
    <description>Evil alert!</description>
  </rule>
```
And this is the output: 

![output](https://user-images.githubusercontent.com/60152567/76071892-4e810480-5f97-11ea-997e-e1ffcb05f965.png)

Regards,

David
