### ISSUE TITLE
Incorrect deployment variable for Windows installer

### ISSUE THREAD

**Issue by torataks** [wazuh/wazuh-documentation#2099]
https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-agent/deployment_variables/deployment_variables_windows.html states the variable to set the registration password is "WAZUH_REGISTRATION_PASSWORD".

wazuh-agent-3.10.2-1.msi appears to silently ignore that variable, so ossec-authd reports an invalid password was provided.

Previous posts to the Wazuh mailing list refer to the variable "PASSWORD".  wazuh-agent-3.10.2-1.msi does recognize that variable, and sends the correct password to ossec-authd.

So the documentation for 3.10 should probably refer to "PASSWORD" instead of "WAZUH_REGISTRATION_PASSWORD".

**Comment by Zenidd** [comment]
Hello @torataks,

I've been recreating the environment. When I use the newer deployment variables(v3.10.2+) the behavior is alternating:

- Sometimes the registration process leads to one of the two errors below:
```
# Error 1 
2019/12/26 16:38:40 ossec-authd: INFO: New connection from 192.168.75.141
2019/12/26 16:38:40 ossec-authd: ERROR: Invalid password provided by 192.168.75.141. Closing connection.


# Error 2
2019/12/26 16:38:40 ossec-authd: INFO: New connection from 192.168.75.141
2019/12/26 16:38:40 ossec-authd: ERROR: Invalid password provided by 192.168.75.141. Closing connection.
```

- Sometimes the registration process is successful:
```
2019/12/26 17:00:28 ossec-authd: INFO: New connection from 192.168.75.141
2019/12/26 17:00:28 ossec-authd: INFO: Received request for a new agent (DESKTOP-D33AN6I) from: 192.168.75.141
2019/12/26 17:00:28 ossec-authd: INFO: Agent key generated for 'DESKTOP-D33AN6I' (requested by 192.168.75.141)
2019/12/26 17:00:28 ossec-remoted: WARNING: (1213): Message from '192.168.75.141' not allowed. Cannot find the ID of the agent. Source agent ID is unknown.
2019/12/26 17:00:32 ossec-remoted: INFO: (1409): Authentication file changed. Updating.
2019/12/26 17:00:32 ossec-remoted: INFO: (1410): Reading authentication keys file.
```
I need some more information to figure out what is happening:

- Could you paste here the `<auth>` section from the `ossec.conf` manager file?
- Are you using the `/var/ossec/bin/ossec-authd -P` command before the deployment?

Please, let me know more details about your use case to fully recreate it. Greetings, 
JP Sáez

**Comment by torataks** [comment]
Hi @Zenidd ,
Thanks for your response!  Here's the requested <auth> section:

```
  <auth>
    <disabled>no</disabled>
    <port>1515</port>
    <use_source_ip>no</use_source_ip>
    <force_insert>yes</force_insert>
    <force_time>0</force_time>
    <purge>yes</purge>
    <use_password>yes</use_password>
    <limit_maxagents>yes</limit_maxagents>
    <ciphers>HIGH:!ADH:!EXP:!MD5:!RC4:!3DES:!CAMELLIA:@STRENGTH</ciphers>
    <!-- <ssl_agent_ca></ssl_agent_ca> -->
    <ssl_verify_host>no</ssl_verify_host>
    <ssl_manager_cert>/var/ossec/etc/sslmanager.cert</ssl_manager_cert>
    <ssl_manager_key>/var/ossec/etc/sslmanager.key</ssl_manager_key>
    <ssl_auto_negotiate>no</ssl_auto_negotiate>
  </auth>
```

I am not manually running the ossec-authd command.  Since <auth><disabled> is set to "no" (the default value), that daemon starts along with the rest of Wazuh Manager.

Also FYI I have set a registration password in /var/ossec/etc/authd.pass on the Wazuh Manager.  The file is owned by root/ossec with permissions of 640.

Thanks!

**Comment by Zenidd** [comment]
Hello again @torataks,

The settings seem fine. 

Please, Could you please paste in the line that didn't work and the line that did? It is weird but maybe the line you used isn't handled in our [wazuh-installer.wxs](https://github.com/wazuh/wazuh/blob/v3.11.0/src/win32/wazuh-installer.wxs) file.



Greetings, JP Sáez

**Comment by torataks** [comment]
Hi @Zenidd,

Here is the command that did not work:

- wazuh-agent-3.10.2.1.msi /q ADDRESS="_wazuh_server_" AUTHD_SERVER="_wazuh_server_" WAZUH_PROTOCOL="TCP" WAZUH_REGISTRATION_PASSWORD="_agent_registration_password_"

And this command worked for me:

- wazuh-agent-3.10.2.1.msi /q ADDRESS="_wazuh_server_" AUTHD_SERVER="_wazuh_server_" WAZUH_PROTOCOL="TCP" PASSWORD="_agent_registration_password_"

I issued the commands from cmd.exe, not PowerShell.

Thanks!

**Comment by Zenidd** [comment]
Hello @torataks,

Thanks for your detailed descriptions, appreciated.

**I think the problem here is that your original command mixes v3.9 and v3.10.2 deployment variables:**

```
.\wazuh-agent-3.10.2-1.msi /q ADDRESS="192.168.75.1" AUTHD_SERVER="192.168.75.1" WAZUH_PROTOCOL="TCP" WAZUH_REGISTRATION_PASSWORD="TopSecret"

v3.9 -> ADDRESS, AUTHD_SERVER
v3.10.2 -> WAZUH_PROTOCOL, WAZUH_REGISTRATION_PASSWORD
```
So it leads to error in agent registering.
```
2019/12/30 12:41:13 ossec-authd: INFO: New connection from 192.168.75.141
2019/12/30 12:41:13 ossec-authd: ERROR: Invalid password provided by 192.168.75.141. Closing connection.
```

**In case we use your command again but replacing the v3.9 vars with the v3.10.2 ones:**
```
 .\wazuh-agent-3.10.2-1.msi /q WAZUH_MANAGER="192.168.75.1" WAZUH_REGISTRATION_SERVER="192.168.75.1" WAZUH_PROTOCOL="TCP" WAZUH_REGISTRATION_PASSWORD="TopSecret"

v3.9 -> NONE
v3.10.2 -> WAZUH_MANAGER, WAZUH_REGISTRATION_SERVER, WAZUH_PROTOCOL, WAZUH_REGISTRATION_PASSWORD
```
The registering is successful now.
```
2019/12/30 12:41:46 ossec-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2019/12/30 12:45:42 rootcheck: INFO: Ending rootcheck scan.
2019/12/30 12:46:15 ossec-authd: INFO: New connection from 192.168.75.141
2019/12/30 12:46:15 ossec-authd: INFO: Received request for a new agent (DESKTOP-D33AN6I) from: 192.168.75.141
2019/12/30 12:46:15 ossec-authd: INFO: Agent key generated for 'DESKTOP-D33AN6I' (requested by 192.168.75.141)
2019/12/30 12:46:20 ossec-remoted: INFO: (1409): Authentication file changed. Updating.
```

While some of the mixed cases are covered we recommend using only variables from the same version. I hope it helps. Let me know if I can close the issue.



Greetings, JP Sáez

**Comment by torataks** [comment]
Happy New Year @Zenidd !

Thank you very much!  Exclusively using the WAZUH_* variables fixed my issue.

https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-agent/windows/wazuh_agent_package_windows.html refers to the old v3.9 variable names.  Then I followed the link on that page to see all the Windows deployment variables, which lists the v3.10 names.  Hence the mixed usage of 3.9 and 3.10 variable names.

So maybe the actual issue is that https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-agent/windows/wazuh_agent_package_windows.html uses the old v3.9 variable names?  The same page for v3.11 also refers to the v3.9 names.

Thanks!

**Comment by Zenidd** [comment]
Hello again @torataks and Happy New Year your you too !


> Thank you very much! Exclusively using the WAZUH_* variables fixed my issue.

Really glad that this is working now.

> So maybe the actual issue is that https://documentation.wazuh.com/3.10/installation-guide/installing-wazuh-agent/windows/wazuh_agent_package_windows.html uses the old v3.9 variable names? The same page for v3.11 also refers to the v3.9 names.

That's right. I asked the CICD team and they confirmed the documentation is wrong. Let me create a PR changing this detail so the correct variables are shown.

Thanks for your contribution @torataks. I'm moving this issue to the documentation repo and creating the related PR.

Greetings, JP Sáez

**Comment by torataks** [comment]
Thanks @Zenidd!

**Comment by alberpilot** [comment]
Hello @torataks 

 Thanks for your awesome contribution! I proceed to close this issue. 

Best regards, 
Alberto R
