### ISSUE TITLE
Improve documentation for database output

### ISSUE THREAD

**Issue by crolopez** [wazuh/wazuh-documentation#210]
The [documentation](https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/database-output.html) to configure the alert output to the database is not sufficient. The explanation given in https://github.com/wazuh/wazuh/issues/569 may be helpful.

### Pending tasks

- Elaborate a list of steps for both MySQL and PostgreSQL. The list must be minimal but sufficient to properly configure database output:
  - MySQL:
    - [x] Required configuration
    - [x] Wazuh configuration block
  - PostgreSQL:
    - [x] Required configuration
    - [x] Wazuh configuration block

**Comment by JuanjiJG** [comment]
Updating the first comment to add an initial list of pending tasks in order to accomplish this task.

**Comment by JuanjiJG** [comment]
Working on branch [`dev-database-output`](https://github.com/wazuh/wazuh-documentation/tree/dev-database-output).
