### ISSUE TITLE
Update documentation about changes to Elasticsearch replica counts 

### ISSUE THREAD

**Issue by branchnetconsulting** [wazuh/wazuh-documentation#2113]
Starting with Wazuh 3.8 the default replica counts were all changed from 1 to 0.  There were also changes to shard counts.

It still says [here](https://documentation.wazuh.com/3.10/user-manual/kibana-app/reference/config-file.html#advanced-index-options) that the Wazuh app defaults to 

- .wazuh and .wazuh-version - 1 shard and 1 replica
- wazuh-monitoring-3.x-* - 5 shards and 1 replica

and [here](https://documentation.wazuh.com/3.10/installation-guide/installing-elastic-stack/elastic_tuning.html#setting-the-number-of-shards-and-replicas) it says that alerts/archives indices default to 5 shards and 1 replica.

It also says [here](https://documentation.wazuh.com/3.10/user-manual/kibana-app/reference/config-file.html#advanced-index-options) that the ***.replicas** settings "are only valid if they’re modified before starting the Kibana service for the very first time" which is not accurate.  Actually those settings are applied every time the Wazuh web app is opened, even if just previously you had manually set all Elasticsearch indices to have a specific number of replicas.

In conflict with the documentation, everything unexpectedly defaults to zero replicas now.  Please align the documentation with the actual defaults.  

When making end-user impacting changes like this, please clearly represent them in the release notes and changelog.  Our user community is counting on us to clearly account for all changes to default behavior, both in our general documentation and in our release notes / changelogs.

This situation gives users the impression that they have replicas when they don't.  For me that assumption resulted in my biggest production cluster going red today.  Ouch.

Kevin

**Comment by alberpilot** [comment]
Hello @branchnetconsulting 

  Please don't hesitate to open this issue again if you consider it. Thanks a lot!
