### ISSUE TITLE
Registering agents page rework 

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#2114]
Hello Team,

Currently, the registering agents' page does not contain enough information and it is not as useful as it should be.

Consequently, I propose to rework the page by doing the following:

- [ ] Structure:

The less the better. We are going to simplify the following table: https://documentation.wazuh.com/3.11/user-manual/registering/index.html#available-registration-methods

I proposed the following structure:

| Registration method  | Description|
|---|---|
|Using command line (CLI)| Description|
|Using Wazuh API| Description|
|Using registration service| Description|

In each of the above mentioned, a link to the method with all the possibilities of each option on the same page. 

This structure should match on the left bar of the menu.

- [ ] Content:

We should remove the Prerequisites section, it is not useful right now. 

Regarding the content, the process should be pretty straightforward. The user should choose the method that best suits him and register the agent and see the agent connected.
To accomplish this, the process should be: copy and paste and it should work.

I would add also a troubleshooting section to help them out.

- [ ] Writing:

Technical writing.

- [ ] Technical features:

We are working on the following branch: https://github.com/wazuh/wazuh-documentation/tree/3.11-registering-agents-rework

Regards,

Miguel Casares

**Comment by chemamartinez** [comment]
Hi team,

I think the _Prerequisites_ section should specify in a clearer way that these steps are always automatic since the `openssl` package is embedded into the Wazuh package.
https://documentation.wazuh.com/current/user-manual/registering/index.html#prerequisites

Regards.

**Comment by alberpilot** [comment]
This issue is related to https://github.com/wazuh/wazuh-documentation/issues/2320. Closing this and moving to the mentioned issue.
