### ISSUE TITLE
Missed section page "Vulnerability-detection" in 3.11 version

### ISSUE THREAD

**Issue by esfateev** [wazuh/wazuh-documentation#2116]
Please, check page - https://documentation.wazuh.com/3.11/user-manual/capabilities/vulnerability-detection/index.html
Error page - 404

**Comment by Zenidd** [comment]
Hello @esfateev,

Currently, I can access that documentation section with no error. I think your issue could be related to a known issue for some documentation sections. Let me explain the steps to reproduce the error:

- Opening an old vulnerability documentation section, i.e the one related to Wazuh v3.2 https://documentation.wazuh.com/3.2/user-manual/capabilities/vulnerability-detection.html
![image](https://user-images.githubusercontent.com/14923294/72169832-21b5d400-33d0-11ea-83d0-42bd3b6059bc.png)

- The old version should load with no issues but switching to a newer version, using the version selector, as in the example above, could lead, for some sections as the vulnerability detector one to 404 error page:
![image](https://user-images.githubusercontent.com/14923294/72170508-4a8a9900-33d1-11ea-8a05-8552efaf7019.png)

- Anyway, searching in the documentation sections directly in the desired version leads to no error.
i.e:the vulnerability-detector section for v3.11:
![image](https://user-images.githubusercontent.com/14923294/72170703-9f2e1400-33d1-11ea-8323-1280c6dae999.png)

Let me know if it is your use case or you find a different bug. I hope it helps.

Greetings, JP Sáez

**Comment by alberpilot** [comment]
Hello 

  I proceed to close this issue, please don't hesitate to open it again if you have any doubt. 

Best regards, 
Alberto R
