### ISSUE TITLE
Update vulnerability detector example

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-documentation#2122]
Hello team,
We have noticed that the vulnerability detector configuration example from this page:

https://documentation.wazuh.com/3.11/user-manual/reference/ossec-conf/vuln-detector.html?highlight=vulnerability%20detector

Contains some options that are not valid for Wazuh 3.11, for example:
```
<provider name="debian">
        <enabled>yes</enabled>
        <os interval="1d">9</os>
 </provider>
```
Should be:

```
<provider name="debian">
        <enabled>yes</enabled>
        <os update_interval="1d">9</os>
 </provider>
```
We have to update it with a correct and more updated configuration example.

Also,  in the same page we should add Debian buster/10, that was included in version 3.11.0, has one of the accepted parameters for the update provider. 

Regards, 
Daniel Folch

**Comment by davidfmiranda** [comment]
Hello @DFolchA, I have just check the documentation and right now appears as: `<update_interval>1h</update_interval>`

Which would be the correct syntax?

Regards,

David
