### ISSUE TITLE
Hardware Requirements 

### ISSUE THREAD

**Issue by apalooza1** [wazuh/wazuh-documentation#2125]
Can someone point me to the documentation regarding hardware requirements for the wazuh server?

**Comment by Zenidd** [comment]
Hi @chaputj ,

We are still working on hardware requirements guidelines for our documentation. Sorry for the inconvenience. Anyway, I'll let here some tips:

- First of all, the recommended hardware will depend on the requisites you need to be compliant with: how many agents you will have monitoring, the number of EPS (events per second generated), if you will monitor other types of devices (network devices), how long you will need the data to be online, etc..

i.e: _Usually, Windows agents generate more event than Linux, but if you are using Audit in Linux, it may be very noisy._

- We highly recommend having Elastic Stack and the Wazuh Manager in different nodes, so they will not going to interfere with each other's performance.

- For Wazuh managers, we recommend scaling horizontally:
    - https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html.
    - Resources for the Wazuh manager: 4 cores, 16 GB of RAM and 1TB disk space. (Per node).

I hope it helps. We are keeping this issue as a reminder for this important section to be included in our documentation soon.

Do not hesitate to ask or propose anything you think is useful. Greetings, 
JP Sáez

**Comment by apalooza1** [comment]
https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html  - this does not work (404).

Resources for the Wazuh manager: 4 cores, 16 GB of RAM and 1TB disk space.
--What kind of deployment (number of agents, EPS, etc) are you basing this Manager for?

**Comment by Zenidd** [comment]
Hello again @apalooza1,


> https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html - this does not work (404).

Sorry for the wrong link, the further one is working:
https://documentation.wazuh.com/3.11/user-manual/configuring-cluster/index.html

> --What kind of deployment (number of agents, EPS, etc) are you basing this Manager for?

- With the resources above, the Wazuh manager should be able to handle 8K EPS as an upper limit. 
- Around 1K agents can be monitored.
- The 1TB disk space is intended for environments that should retain logs for a long time to be compliant with the logs retention policy. It can be dimensioned for your custom use case. The RAM could be also reduced after monitoring the consumption.

I hope it helps. Greetings, 
JP Sáez

**Comment by xxmoC** [comment]
And what about the OVA? What storage, CPU and memory should I assign?

**Comment by Zenidd** [comment]
Hello @xxmoC,

> And what about the OVA? What storage, CPU and memory should I assign?

Below the minimum requirements to run the OVA environment:
```
4 cores
~ 4GB RAM
~ 7GB HDD/SSD storage
```
These requirements are enough to run the OVA environment, nevertheless, it is desirable to increase the RAM and storage space. Also the hardware required will be really determined by the number of agents and its average EPS.

You should also take into account that the storage unit on the Wazuh OVA is resized on-demand as more space is needed. For other specifications than those configured in the OVA, all can be easily modified via VMWare, VirtualBox or another virtualization service.

Greetings, JP Sáez

**Comment by alberpilot** [comment]
Hello

    I proceed to close this issue, please don't hesitate to open it again if you have any doubt. 

Best regards, 
Alberto R
