### ISSUE TITLE
Update new cluster documentation

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh-documentation#213]
Hello team,

The new cluster has changed for the next version of Wazuh, so now we need to update the documentation to reflect the new configuration options and the `How it works` section.

This issue will track the progress on the new documentation for this.

Currently defined tasks:
- [x] Remove "all cluster nodes must have the same date" note - fcbf5b3de7d8e745bdedb582d78862ce7c20e767
- [x] Update "How it works" section - d20d42959a3c3637a7198134ee60fc4eb215b69c
- [x] Update "Master" subsection from "How it works" section - 8645f31ee74d01a6cf71ec25eb6657e0b862893e
- [x] Make a flow diagram of how the cluster works - d20d42959a3c3637a7198134ee60fc4eb215b69c
- [x] Update "Client" subsection from "How it works" section - 4e860046d85a09fae5f6af21efa674617910409b
- [x] Remove `wazuh-clusterd-internal` daemon and update `wazuh-clusted` daemon from daemons section - 8eb64bb64cab0f0c17b10507b4ba42d19b2047e4 2a30d325ed9cf8825546fe684fea58901e4903c8
- [x] Update `cluster_control` section - bf7c345d1201f9d1d8501f0414239a18da6ed156
- [x] Remove cluster database section - d074398e65e9f07b7a61f1029d6db19f5d6a4c5a
- [x] Update "use case & how to install" section - 043bd5add1be29be4d0dcda995581e4f4ac435a9
- [x] Update "how to install on centos6" section - 08a380e74b109afa8adcab0ebcc5146a0f61d10c
- [x] Add "how to update cluster" section - db95f2528afab19cf300277e38aa28f3e7f63e41
- [x] Update cluster configuration section - 45b7d9e2543028d5dfdfa5ca47b6c4670f8df75d
- [x] Update cluster API calls - 3c246e84059e14304bd5aca3f916b42d04ff4d55

Best regards,
Marta

**Comment by JuanjiJG** [comment]
This documentation task is finished, so I proceed to close it.

Regards,
Juanjo
