### ISSUE TITLE
What's the difference between Single Host and DIstributed Architecture ?

### ISSUE THREAD

**Issue by gagantous** [wazuh/wazuh-documentation#215]
Hi Wazuh Team!

I have some question regarding the `Architecture` section of Wazuh Documentation. It's been bugging me for a days, because it stated on Wazuh Documentation said, that Single Host architecture is recommended for a Small Wazuh deployments (<50 agents), quoted from the wazuh documentation said:

>  In smaller Wazuh deployments, Wazuh and Elastic Stack with a single-node Elasticsearch instance can all be deployed on a single server. In this scenario, Logstash can read the Wazuh alerts and/or archived events directly from the local file system and feed them into the local Elasticsearch instance.

Compare it with the Distributed ones quoted from wazuh doc :

> An Elasticsearch cluster is a collection of one or more nodes (servers) that communicate with each other to perform read and write operations on indexes. Small Wazuh deployments (<50 agents), can easily be handled by a single-node cluster. Multi-node clusters are recommended when there is a large number of monitored systems, when a large volume of data is anticipated and/or when high availability is required.
> 
> When the Wazuh server and the Elasticsearch cluster are on different hosts, Filebeat is used to securely forward Wazuh alerts and/or archived events to the Elasticsearch server(s) using TLS encryption.

i am not fully understand with the different between these two Architecture, especially with the advantages and disadvantages on both Architecture. My summary on both Architecture:

- Single-Host

1. More recommended in small architecture.
2. Elastic and Wazuh manager are on the same machine

- Distrbuted

1. Strongly recommended on bigger architecture
2. Have file beat to encrypt the forwarded log 
3. More capable to handle many many agents and log
4. Elastic and Wazuh are on seperated machine.

I mean, `what if i used the distributed architecture on small deployment such as i only have 5 agents that wanted to be monitored, and i only have one ossec server, is it prohibited?` I questioned this because i always seen some people that used Distributed architecture even in smaller deployment. I just want to make sure that what i conclude was correct, or am i missed something ?

What's the matter with Wazuh and ELK on different machine ? i know that the answer would be " because in some condition you just want to do it that way," i mean, is there any condition that didnt stated on the wazuh documentation like you want to do it because that or because this or because "when the `machine A` which has ELK got infected by virus, fortunately, it was separate with `machine B` which has ossec on it, so my log data and configuration are untouched/safe from virus, thank god".

Regards
fathin

**Comment by JuanjiJG** [comment]
Hello @gagantous,

There's no prohibited architecture when deciding how to deploy Wazuh on your infrastructure. It depends on your current needs, such as the amount of data that you think you'll generate with your amount of monitored servers.

If you're planning to increase the number of monitored agents in the future, then I recommend you a distributed architecture, because it will be easier to add more nodes to your clusters whenever you need more processing power on your Wazuh manager or your Elastic server. But if you're planning to stick with 5 agents, then I recommend you a single host architecture, since it requires fewer resources.

I hope that all your doubts and questions are now solved, but if you still have more, don't hesitate to post a new comment, we'll be happy to help you.

Regards,
Juanjo

**Comment by gagantous** [comment]
Thanka @JuanjiJG for the replies!

Is there another reason for making the ELK and wazuh ossec on separate machine ? I mean like security purposes or anything like that

**Comment by JuanjiJG** [comment]
Hello again @gagantous,

In addition to security, one of the main reasons to separate your Elastic installation from your Wazuh manager is to deploy an Elasticsearch cluster, which can provide you periodical snapshots of your indices to have backups of your indexed data.

I think that separating the different servers according to its main role helps for a better architecture distribution, and as I said in my previous message, allows to implement HA (High Availability).

In the beginning, it's hard to determine what your actual needs are, so practice and time will help you to see if you'll need a separated architecture or just a single-host one.

Again, I hope that my answers are useful to you and all your doubts are now solved. In any case, don't hesitate to post a new comment if you still have questions about this, we'll be glad to help you.

Regards,
Juanjo

**Comment by gagantous** [comment]
@JuanjiJG

Thank you very much for made such a nice and well explanation. 

It's really helpful !
Again, thanks !

Best Regards
Fathin

**Comment by JuanjiJG** [comment]
You're welcome, @gagantous 😄

I'll proceed to close the issue then. Don't hesitate to open a new one if you have more questions or problems.

Regards,
Juanjo
