### ISSUE TITLE
Wrong eventchannel query syntax

### ISSUE THREAD

**Issue by Zenidd** [wazuh/wazuh-documentation#2156]
Hello team, 

The [Filtering events from Windows Event Channel with queries](https://documentation.wazuh.com/3.11/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html#filtering-events-from-windows-event-channel-with-queries) documentation section shows an incorrect example configuration for the advance XML filtering:

![image](https://user-images.githubusercontent.com/14923294/73435823-a9489000-4349-11ea-9288-8e1a19dda45e.png)

The following version is correct: All XML labels inside the `<query>` need to be escaped as it should be interpreted as text and not as another configuration XML labels.
```XML
<localfile>
    <location>System</location>
    <log_format>eventchannel</log_format>
    <query>
        \<QueryList\>
            \<Query Id="0" Path="System"\>
                \<Select Path="System"\>*[System[(Level&lt;=3)]]\</Select\>
            \</Query\>
        \</QueryList\>
    </query>
</localfile>
```

Greetings, JP Sáez

**Comment by chemamartinez** [comment]
Merged #2157. 

Thanks, @Zenidd!!
