### ISSUE TITLE
Can't installing wazuh 

### ISSUE THREAD

**Issue by lasithaccna** [wazuh/wazuh-documentation#2160]
Could you please give me the correct steps for installing wazuh. i reffer official site guidelines
but not work

**Comment by Zenidd** [comment]
Hello @lasithaccna,

In order to help you, we will need some extra information:

- Which Wazuh version are you trying to install?
- What is your target OS?
- Did you try the packages or sources install?
- If you had errors during installation, could you paste it here?

Let me know so we can provide guidance.

Greetings, JP Sáez

**Comment by lasithaccna** [comment]
Hi Juan Pablo Sáez Gutiérrez,

Thank you for respond me.


   - Which Wazuh version are you trying to install?

*I try with 3.11 version.*


   - What is your target OS?

*With Cent OS also try with Virtual machine which given from official site*


   - Did you try the packages or sources install?

*packages*


   - If you had errors during installation, could you paste it here?

*when i try to login wazuh dashboard with browser there is no any website.
and also when i check agents in wazuh server, it shows my agent " never
connected"*


could you please help me to install this. i need your help. because i
haven't clear idea of installation steps in order. if you can givbe me the
correct order it's really helpful. thank you .

**Comment by Zenidd** [comment]
Hello @lasithaccna and sorry for the late reply.

I think it is a good idea trying a single-host architecture. Our virtual appliance, available [here](https://packages.wazuh.com/vm/wazuh3.11.3_7.5.2.ova), contains all the needed components.

> *when i try to login wazuh dashboard with browser there is no any website.
> and also when i check agents in wazuh server, it shows my agent " never
> connected"*

Just importing the OVA on VirtualBox or other OVA compatible virtualization systems should be enough. Make sure that the machine has at least 4GB RAM.

On the other hand, you could also install the Wazuh manager standalone in an environment lab. Read more about the Wazuh-server installation steps [here](https://documentation.wazuh.com/3.11/installation-guide/installing-wazuh-manager/).

For further questions please we would like you to use our [#community Slack channel](https://wazuh.com/community/join-us-on-slack/) or the [Wazuh mail list](https://groups.google.com/forum/?hl=es#!forum/wazuh).

Greetings, JP Sáez

**Comment by lasithaccna** [comment]
Thank you for your response my dear.

**Comment by alberpilot** [comment]
Hello 

  I proceed to close this issue, please don't hesitate to open it again if you have any doubt. 

Best regards, 
Alberto R

**Comment by lasithaccna** [comment]
Dear supporter. I finished the installation part.now my problem is my
router syslogs are not showing here. And how can i set router as a agent.
Please help me. I refer the official guide. But it not working
