### ISSUE TITLE
Problems in `Running API as service`

### ISSUE THREAD

**Issue by GeiliCode** [wazuh/wazuh-documentation#22]
There are two problems I encountered when I followed the section `running-api-as-service` in [ossec_api_installation](https://github.com/wazuh/wazuh-documentation/blob/master/source/ossec_api_installation.rst#running-api-as-service).

* `sudo /var/ossec/api/scripts/install_daemon.sh` will not work.

The error message is: `sed: can't read wazuh-api: No such file or directory`
The below is work.
```
cd /var/ossec/api/scripts
./install_daemon.sh
```
* The function `status` in `wazuh-api` is empty...

**Comment by GeiliCode** [comment]
I just remembered another little problem, it's in section [Running API on the backgroun](https://github.com/wazuh/wazuh-documentation/blob/master/source/ossec_api_installation.rst#running-api-on-the-background).

The location of `node` is different on my OS (Debian 6), it is `/usr/local/bin/node`.

**Comment by jlruizmlg** [comment]
Hi @GeiliCode both problems are fixed in the next release, you can try the scripts from the development branch, should be work fine.

https://github.com/wazuh/wazuh-API/tree/development/scripts

**Comment by GeiliCode** [comment]
Thank you very much.
