### ISSUE TITLE
Kibana plugin config backup in upgrade guide for 3.12

### ISSUE THREAD

**Issue by juankaromo** [wazuh/wazuh-documentation#2256]
Hi team,

In 3.11 the Kibana plugin update guide was modified to make a backup of the configuration file because it was lost when updating.

For 3.12 the location of this file has been changed so that it is kept after the upgrade. 

Because of this, if a user upgrades from 3.11 to 3.12, they must make a copy of the file located in `/kibana/plugins/wazuh/wazuh.yml`, but now they must restore it to `/usr/share/kibana/optimize/wazuh/config/wazuh.yml`.

This has been done here https://github.com/wazuh/wazuh-kibana-app/issues/2087

Regards,

**Comment by alberpilot** [comment]
Done
