### ISSUE TITLE
Update decoders documentation

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-documentation#227]
Two variables are missing in the decoder documentation: https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html

In particular, one is called `plugin_decoder` and the other one is `use_own_name`.

It has been also added a new one in https://github.com/wazuh/wazuh/pull/677 that needs to be included when it is available in new versions of Wazuh.

**Comment by bah07** [comment]
Done in [#251](https://github.com/wazuh/wazuh-documentation/pull/251)

**Comment by chemamartinez** [comment]
We have to include the new option when https://github.com/wazuh/wazuh/pull/677 is added to a release.

**Comment by MiguelCasaresRobles** [comment]
Done in [#275](https://github.com/wazuh/wazuh-documentation/pull/275)
