### ISSUE TITLE
FIM rework options

### ISSUE THREAD

**Issue by Lopuiz** [wazuh/wazuh-documentation#2296]
Hello team,

From 3.12 version FIM doesn't use the following options, we should tag them as deprecated.

- `syscheck.sleep_after`
-  `syscheck.sleep`

Greetings,
Eva

**Comment by FernandoCP** [comment]
Hi! 

The description of `syscheck.sleep` has to be changed because it says "Number of seconds to sleep after reading `syscheck.sleep_after` number of files." but `syscheck.sleep_after` doesn't work yet. 

Best regards, Fernando.

**Comment by bah07** [comment]
Done! #2367
