### ISSUE TITLE
Specify versions in older documentation

### ISSUE THREAD

**Issue by mikykeane** [wazuh/wazuh-documentation#2301]
If a client is looking at an older version of our documentation on purpose. Wanting to install an older version. Our documentation will give them commands like this: 

```yum install wazuh-manager```

Which will install the latest version. 

So for example, in the documentation for 3.10, the command should be: 

```yum install wazuh-manager-3.10.2-1```

This will point to the latest release of the 3.10 version. But this is fine because seeing this, if the client wanted the 3.10.0 release, they can easily change it knowing the command. It is intuitive. 

It can also have indirect advantages, like clients that have not seen the top banner advising that they are on an outdated section of the documentation, they could see that the version on the command is not the one they are looking for. 

This affects many places in the documentation. It is not an urgent matter, but it could be interesting to have it implemented in the future.

**Comment by davidfmiranda** [comment]
This issue is related with issue #1317.

**Comment by jchermoso** [comment]
- [ ] 3.12: https://github.com/wazuh/wazuh-documentation/pull/2832

- [ ] 3.11: https://github.com/wazuh/wazuh-documentation/pull/2835

- [ ] 3.10: https://github.com/wazuh/wazuh-documentation/pull/2738

- [ ] 3.9: https://github.com/wazuh/wazuh-documentation/pull/2837

- [ ] 3.8: https://github.com/wazuh/wazuh-documentation/pull/2843

- [ ] 3.7: https://github.com/wazuh/wazuh-documentation/pull/2853

- [ ] 3.6: https://github.com/wazuh/wazuh-documentation/pull/2855

- [ ] 3.5: https://github.com/wazuh/wazuh-documentation/pull/2875

- [ ] 3.4: https://github.com/wazuh/wazuh-documentation/pull/2888

- [ ] 3.3: https://github.com/wazuh/wazuh-documentation/pull/2892

- [ ] 3.2: https://github.com/wazuh/wazuh-documentation/pull/2893

- [ ] 3.1: https://github.com/wazuh/wazuh-documentation/pull/2896

- [ ] 3.0:

- [ ] 2.1:
