### ISSUE TITLE
Step 4 of Upgrade Elastic from 2 to 4 is pointing to a wrong document

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#233]
If we follow the upgrade steps from ELK 2 to ELK 5, there is an error with the step 4 link. 
We start at:
https://documentation.wazuh.com/current/installation-guide/upgrading/index.html
then we chose "Upgrade from a legacy version":
https://documentation.wazuh.com/current/installation-guide/upgrading/legacy/index.html#upgrading-wazuh-legacy
then we click on "Upgrade from Elastic Stack 2.x to 5.x"
https://documentation.wazuh.com/current/installation-guide/upgrading/legacy/upgrading-elastic-stack.html#upgrade-from-elastic-stack-2-x-to-5-x
and the step 4 is:

> At this point, you are ready to install the new version of Elastic Stack. Follow the appropriate link below for installation instructions for your specific operating system:
> 
> Install Elastic Stack with RPM packages
> Install Elastic Stack with DEB packages

Both links point to a Elastic Stack version 6 installation. These links must to point to 5 version (Wazuh 2.1 documentation). 

Best regards, 
Alberto R.

**Comment by JuanjiJG** [comment]
Hello @alberpilot,

This has been fixed here: https://github.com/wazuh/wazuh-documentation/commit/0c080e62f05566d105f196c9f319dc53be06d410

Thanks for your report! It's really appreciated!

Regards,
Juanjo
