### ISSUE TITLE
Incorrect sha512 checksums for el5 wazuh-agent packages

### ISSUE THREAD

**Issue by jjrbg** [wazuh/wazuh-documentation#2357]
Hi,
Very minor point, but the sha512 checksums published for...

wazuh-agent-3.12.0-1.el5.i386.rpm
wazuh-agent-3.12.0-1.el5.x86_64.rpm

...don't appear to be correct.

All others are fine though. Repeated the download a number of times, so I don't believe it's a corruption issue.

`
$ sha512sum wazuh-agent-3.12.0-1.el5.i386.rpm 
49bb37053ba115653f8f82d2c71e8048913a407dfd44eb8d8d4defd991d6595cb3a4d8a215446aab20e6d5563249a1f9821c1f7ecea7341942a8457f62ac95dd  wazuh-agent-3.12.0-1.el5.i386.rpm
`
`
$ cat wazuh-agent-3.12.0-1.el5.i386.rpm.sha512 
39d84ba6be811e1dc060357381e9e85b4f6e68c7eda075c41fb086743f89151b7638ed32b29c4864a0e03b8b25939443dba1e3bdedacf74f1d7c8ec3876cb1f6  wazuh-agent-3.12.0-1.el5.i386.rpm
`

`
$ sha512sum wazuh-agent-3.12.0-1.el5.x86_64.rpm 
7f1333e01cecdf87e43da78697d47966a160cadb62eefa50f1c823f4e8e926bf4bca06d0ded43e6b6f57982b649d1e3ab77e4774e9351914926786970ddb12ac  wazuh-agent-3.12.0-1.el5.x86_64.rpm
`
`
$ cat wazuh-agent-3.12.0-1.el5.x86_64.rpm.sha512 
45c9e47f904126f7ab15151a20246faa76d1fbec14a2b802ff16b6ba16d2ffc0b30cc97cb1f40c50a3ba6e2e40ed63b99c4a1536f60586ef639577ed0665352c  wazuh-agent-3.12.0-1.el5.x86_64.rpm
`

**Comment by alberpilot** [comment]
Hello @jjrbg 

 Thanks for reporting this issue. You are right, the checksums files were wrong and now it's fixed. Sorry for the inconveniences. 

Best regards, 
Alberto R
