### ISSUE TITLE
Change Solaris Intel nomenclature

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#2373]
Hello team!

The aim of this issue is to change the nomenclature used in Solaris to refer to Intel's architecture. We ought to use `i386` rather than `Intel architecture`.

![image](https://user-images.githubusercontent.com/60152567/78677019-81e0e700-78e7-11ea-9676-44f8ffca1815.png)

Regards,

David

**Comment by alberpilot** [comment]
Thanks @BraulioV for reporting
