### ISSUE TITLE
Kibana App user manual rework

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#2384]
Hello team! 

The aim of this issue is to improve the actual Kibana App section in User manual. 

The idea is to update and reorganize the information letting the user find the information in the less clicks as possible.

Regards,

David

**Comment by s-ocando** [comment]
A rework of the Kibana App - Wazuh dashboard documentation was introduced in https://github.com/wazuh/wazuh-documentation/pull/5011.
