### ISSUE TITLE
@avinash-gudagi: Please put a note about the CloudTrails digit

### ISSUE THREAD

**Issue by snaow** [wazuh/wazuh-documentation#24]
Referring to [#PR 23](https://github.com/wazuh/wazuh-documentation/pull/23)

Quoting @avinash-gudagi

> I was using your script to get aws logs of cloudtrails from a bucket and then use OSSEC to monitor these trails. I noticed that the s3 bucket also contained logs about cloudtail-digest. The getawslog.py script throws a exception. Just sending a pull request to mention this in a note.
> 
> ./getawslog.py -b cloudtrails-ossec -d -j -D -l /home/ubuntu/cloudtrail-logs/amazon.log
> +++ Debug mode on
> +++ Connecting to Amazon S3
> +++ Found new log: 072477793200_CloudTrail-Digest_ap-northeast-1_Test-trail_us-west-2_20160802T142331Z.json.gz
> Traceback (most recent call last):
> File "./getawslog.py", line 101, in 
> main(sys.argv[1:])
> File "./getawslog.py", line 80, in main
> records = j["Records"]
> KeyError: 'Records'

Let me take a look on it and I will update you in few minutes.

**Comment by avinash-gudagi** [comment]
Thanks a lot Pedro.

Avinash

**Comment by snaow** [comment]
Hi @avinash-gudagi,

It seems like digest-file logs [Amazon docs](http://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-log-file-validation-digest-file-structure.html) do not have the same log format than Cloud Trail logs we are processing [Amazon docs](http://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-log-file-examples.html).

I fixed the script so it will check for the existence of "Records" key preventing it from throwing an exception, I think that should be enough to make it works in your environment.

Commit: https://github.com/wazuh/ossec-rules/commit/be283fa0a0caa7d942fcd81fcfe994e360d42401

Download the new version by running:

> $ wget  https://raw.githubusercontent.com/wazuh/ossec-rules/master/tools/amazon/getawslog.py

We are currently working on the Amazon AWS integration so you won't need to use an external script, Wazuh will do the job automatically for you (fetch, process, analyse, alert).

Please don't hesitate to ask if you need anything, thanks so much for your feedback,

**Comment by avinash-gudagi** [comment]
Thanks Pedro. Yes, the digest logs are different. I did fix the script on
my machine. I wanted to let you know about this issue so that future clones
will not have a problem.

Thanks a lot for your quick response. Appreciate it.

Avinash

**Comment by snaow** [comment]
We will add digest logs processing on our roadmap, thanks for let us know about this issue.

Best regards,

Pedro S.
