### ISSUE TITLE
Add "how to create rules" section to FIM FAQ

### ISSUE THREAD

**Issue by jesusjimsa** [wazuh/wazuh-documentation#2407]
We need to add a new section in the [FIM FAQ page](https://documentation.wazuh.com/3.12/user-manual/capabilities/file-integrity/fim-faq.html) in the documentation explaining how to create rules for FIM.

**Comment by bah07** [comment]
Done! [#2414](https://github.com/wazuh/wazuh-documentation/pull/2414)
