### ISSUE TITLE
Order alphabetically syscheck options

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#2418]
Hello team! 

The aim of this issue is to order alphabetically the different options in [syscheck](https://documentation.wazuh.com/3.12/user-manual/reference/ossec-conf/syscheck.html).

Regards,

David

**Comment by alberpilot** [comment]
See similar sections in order to make the same work.

**Comment by dkempny** [comment]
**Syscheck** options ordered alphabetically in PR: #2367
