### ISSUE TITLE
Add missing options for generate_rpm_package

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#2420]
Hello team!

The aim of this issue is to add the missing options available for `generate_rpm_package.sh`.

As @elwali10 noticed, some options have been added and the documentation was not updated.

Besides, it would be worthy to add a reference to the Docker installation section in the [requirement section](https://documentation.wazuh.com/3.12/development/packaging/generate-rpm-package.html#requirements)

Regards,

David

**Comment by alberpilot** [comment]
Duplicated: https://github.com/wazuh/wazuh-documentation/issues/2783
