### ISSUE TITLE
Fix the schema shown in the architecture of Elastick stack section

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#2434]
Hello team! 

This PR aims to fix the image shown in [getting started](https://documentation.wazuh.com/3.12/getting-started/architecture.html#elastic-stack) section to illustrate the Elastic stack architecture. 

As @vikman90 reports, it is shown that a Wazuh `worker node`, connects with another `worker node` and this never happens. All `worker nodes` connect to a `master node`, never between them. This image should be changed: 

![image](https://user-images.githubusercontent.com/60152567/81390102-322a5100-911b-11ea-945e-33720a916893.png)

Regards,

David

**Comment by alberpilot** [comment]
Rework done.
