### ISSUE TITLE
Review and update API securitization

### ISSUE THREAD

**Issue by davidjiglesias** [wazuh/wazuh-documentation#2479]
Hello team,

With the new API in 4.0, we need to review and update the API securitization guide in our documentation. The actual guide is very obsolete and we shall include actual API changes as well as some other recommendations to increase API security.

https://github.com/wazuh/wazuh-documentation/blob/4.0/source/installation-guide/securing_api.rst

Regards,

David I.

**Comment by vicferpoy** [comment]
| Working branch |
| --- |
|[2479-api-securitization](https://github.com/wazuh/wazuh-documentation/tree/2479-api-securitization)|
