### ISSUE TITLE
Documentation for socket output in Logcollector

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-documentation#248]
Related PR: https://github.com/wazuh/wazuh/pull/395

**Comment by vikman90** [comment]
Duplicated: https://github.com/wazuh/wazuh-documentation/pull/179

**Comment by JuanjiJG** [comment]
Hello @vikman90,

As you can see, this PR is duplicated. The related changes to the documentation are already merged on the `master` branch. And here's the commit: https://github.com/wazuh/wazuh-documentation/commit/2aa1c756d8edf8b9734688518b27e1ec1e75f633

Regards,
Juanjo
