### ISSUE TITLE
ossec-awscloudtrail issue

### ISSUE THREAD

**Issue by mohakkataria** [wazuh/wazuh-documentation#25]
This is in continuation with the #11 . As mentioned already,

I too have got the same problem as others on #11. Even after using the new rules/decoders I am still stuck with "Unknown problem somewhere in the system". The amazon decoder is working but rule is being satisfied. For e.g. my logs had events of creating users and although the rule "80861" should have been triggered, it only fires rule "1002". 
Can you help here please, @jlruizmlg .

**Comment by jesuslinares** [comment]
Check out the last comments in https://github.com/wazuh/wazuh-documentation/issues/11

Amazon decoders:

> https://github.com/wazuh/ossec-rules/blob/development/decoders/amazon_decoders.xml

Amazon rules: 
```
https://github.com/wazuh/ossec-rules/blob/development/rules/amazon_rules.xml
https://github.com/wazuh/ossec-rules/blob/development/rules/amazon-iam_rules.xml
https://github.com/wazuh/ossec-rules/blob/development/rules/amazon-ec2_rules.xml
```

ossec.conf:

> <include>amazon_rules.xml</include>
> <include>amazon-ec2_rules.xml</include>
> <include>amazon-iam_rules.xml</include>

In case you continue seeing the alert _1002_, can you share here a log of that event?.

Thanks.

**Comment by mohakkataria** [comment]
Hey @jesuslinares ,

Thanks for the quick reply. Sorry for that, i forgot to add rules to ossec.conf. But after including them, i am unable to start the ossec daemon. Following is the error : 

Starting OSSEC HIDS v2.9.0 (by Trend Micro Inc.)...
OSSEC analysisd: Testing rules failed. Configuration error. Exiting.

Following is output of ossec.log : 
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/active-response_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/aix-ipsec_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/apache_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/arpwatch_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/asterisk_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/auditd_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/checkpoint_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/cimserver_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/cisco-ios_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/cisco-vpn_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/clamav_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/courier_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/dovecot_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/dragon-nids_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/dropbear_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/ftpd_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/grandstream_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/horde_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/imapd_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/kernel-iptables_apparmor_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/mailscanner_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/mysql_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/named_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/netscreen_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/nginx_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/ntpd_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/openbsd_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/openldap_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/ossec_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/pam_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/pix_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/portsentry_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/postfix_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/postgresql_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/proftpd_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/pure-ftpd_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/racoon_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/roundcube_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/rshd_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/samba_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/sendmail_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/snort_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/solares-bsm-audit_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/solaris-ipfilter_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/sonicwall_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/squid_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/ssh_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/su_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/sudo_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/suhosin_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/symantec_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/telnet_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/trend-osce_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/unbound_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/unix_chkpwd_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/vm-pop3_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/vmware_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/vpopmail_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/vsftpd_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/web-accesslog_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/windows_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/wordpress_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/ossec_decoders/zeus_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/wazuh_decoders/amazon_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/wazuh_decoders/netscaler_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/wazuh_decoders/ossec_ruleset_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/wazuh_decoders/puppet_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/wazuh_decoders/redis_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/wazuh_decoders/serv-u_decoders.xml.
2016/09/13 08:37:02 ossec-testrule: INFO: Reading decoder file etc/local_decoder.xml.
2016/09/13 08:37:02 rules_list: Signature ID '80201' not found. Invalid 'if_sid'.

**Comment by jesuslinares** [comment]
Hi,

did you add the 3 files? are they at _/var/ossec/rules_?.

_ossec.conf_ should look like:
```
 <rules>
     ...
    <include>amazon_rules.xml</include>
    <include>amazon-ec2_rules.xml</include>
    <include>amazon-iam_rules.xml</include>
    ...
    <include>local_rules.xml</include>
  </rules>
```

Regards.

**Comment by mohakkataria** [comment]
Yup, added the same 3 lines as suggested and also the files are at the location mentioned. But the observation which I have made is that the I had added them in wrong order. I had to include amazon_rules.xml first. Hence it was throwing an error on Invalid SID. 

Thanks so much for the swift help @jesuslinares.  👍

**Comment by jesuslinares** [comment]
The order is very important.
Enjoy the rules!

Regards.
