### ISSUE TITLE
Active-response script syntax

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-documentation#252]
To make easier to create new custom scripts for active-response, it would be useful to explain the arguments sent by Wazuh to the scripts when an active-response is triggered.

These arguments are the following order:

```
<script> <action: add/delete> <user> <IP> <alert-id> <rule-id> <trigger> ...
```

Related to this issue: [#679](https://github.com/wazuh/wazuh/issues/679)

**Comment by JuanjiJG** [comment]
Done here: #661 

Regards,
Juanjo
