### ISSUE TITLE
Clarifying the information about the Wazuh Kibana plugin configuration file backup when upgrading from versions older than 3.11 and for documentation for 3.11 

### ISSUE THREAD

**Issue by dkempny** [wazuh/wazuh-documentation#2570]
Hello team! 

The aim of this issue is to clarify the information about the Wazuh Kibana plugin configuration file backup when upgrading from versions older than 3.11 and in the documentation for version 3.11.

https://documentation.wazuh.com/3.11/upgrade-guide/upgrading-elastic-stack/elastic_server_minor_upgrade.html

Regards,

Daria

**Comment by alberpilot** [comment]
Done.
