### ISSUE TITLE
Adding the information about the Wazuh Kibana plugin configuration file backup when upgrading to version 3.10.

### ISSUE THREAD

**Issue by dkempny** [wazuh/wazuh-documentation#2571]
Hello team! 

The aim of this issue is to add the information about the Wazuh Kibana plugin configuration file backup when upgrading to version 3.10.

https://documentation.wazuh.com/3.10/upgrade-guide/upgrading-elastic-stack/elastic_server_minor_upgrade.html#upgrade-kibana

Regards,

Daria

**Comment by alberpilot** [comment]
Done.
