### ISSUE TITLE
New Upgrade guide - Wazuh, Elastic Stack using Elasticsearch and Elastic Stack using Open Distro.

### ISSUE THREAD

**Issue by dkempny** [wazuh/wazuh-documentation#2575]
Hello team! 

The aim of this issue is to create the new **Upgrade guide** explaining the upgrade process of Wazuh, Elastic Stack using Elasticsearch and Elastic Stack using Open Distro.

All the best,
Daria

**Comment by alberpilot** [comment]
Done.
