### ISSUE TITLE
Vulnerability Detection for macOS

### ISSUE THREAD

**Issue by hazcod** [wazuh/wazuh-documentation#2585]
Hi, macOS doesn't seem to be mentioned in https://documentation.wazuh.com/3.12/user-manual/capabilities/vulnerability-detection/compatibility_matrix.html

**Comment by DFolchA** [comment]
Hello @hazcod,

For the moment Wazuh does not support vulnerability detection on macOS systems.

However, this capability is in our roadmap and will be available in the future.

Regards,
Daniel Folch

**Comment by alberpilot** [comment]
I proceed to close this issue. Please don't hesitate to open it if you have any doubt. 

Regards, 
Alberto R
