### ISSUE TITLE
'select' parameter isn't documented in some API reference endpoints

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-documentation#262]
Hi team,

There are many API endpoints where the 'select' argument is missing and not referenced in the documentation. It only appears in **/cluster/node** and **/agents/no_group** endpoints.

Regards,
Manu

**Comment by JuanjiJG** [comment]
Hello @manuasir,

We'll continue this task on [this issue](https://github.com/wazuh/wazuh-api/issues/199), where it has more sense.

Thanks and regards,
Juanjo
