### ISSUE TITLE
Unused asterisk character in API reference

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-documentation#264]
Hi team,

I saw that there are some asterisk (*) written in the description field of some endpoints, but it's not referenced anywhere in the documentation so I think it's useless.

![captura](https://user-images.githubusercontent.com/10210567/41547538-bff192a2-7320-11e8-9717-fe026ec61a7a.PNG)
![captura2](https://user-images.githubusercontent.com/10210567/41547540-c00f9202-7320-11e8-954e-1a031ef8bfcf.PNG)

Regards,
Manu

**Comment by JuanjiJG** [comment]
Fixed here: #532

Regards,
Juanjo
