### ISSUE TITLE
Upgrading guide from the same major version fix

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-documentation#266]
Currently the app's link references the old wazuhapp.zip name.

https://documentation.wazuh.com/current/installation-guide/upgrading/same_major.html#upgrading-same-major

We should update it with the current version of it.

Regards.

**Comment by JuanjiJG** [comment]
Hello @havidarou,

This has been fixed in https://github.com/wazuh/wazuh-documentation/commit/2c943acf3a2e151b02f3932d8e3763dcbf6d0c93.

Thanks for your report!

Regards,
Juanjo
