### ISSUE TITLE
Indicate that the OVA uses the OSS version of Elasticsearch

### ISSUE THREAD

**Issue by DFolchA** [wazuh/wazuh-documentation#2662]
Hello team,

We need to clearly specify in our documentation that the VM appliance uses the OSS versions of  Elasticsearch, Kibana, and Filebeat.

These will be handy for those who want to upgrade the Elastic Stack because they must use this version of the packages to correctly do it.

Regards,
Daniel Folch

**Comment by b4b857f6ee** [comment]
Hello,

If i may, don't write "yum upgrade" for the appliance because this confusing me enough to use it and install kibana 7.8 ahah.

**Comment by alberpilot** [comment]
This section must be reviewed. The next OVA will have Open Distro for elasticsearch by default so we need to adapt the section consequently.
