### ISSUE TITLE
Add list of expected fields in output for each API request in API reference

### ISSUE THREAD

**Issue by Lifka** [wazuh/wazuh-documentation#268]
Hi team,

it's necessary to add the list of expected fields in output for each API request. Each field should be able to be used like parameter in `select` and `sort`.

Regards,
Javi.

**Comment by JuanjiJG** [comment]
This issue will be closed and discussed on this Wazuh API issue, where it has more sense: https://github.com/wazuh/wazuh-api/issues/199

Regards,
Juanjo
