### ISSUE TITLE
SMTP Authentication example through relay does not work by default

### ISSUE THREAD

**Issue by vicosurge** [wazuh/wazuh-documentation#2785]
I was just looking at this item and I was bashing my head to figure out why I kept getting different errors when trying to make it work, below are some observations:

OS: Debian Sid (Experimental) (Not sure if anything else is relevant at this point)

Initially, I was getting an error that I should start the command with STARTTLS, turns out that the certificate mentioned in the documentation was not available in my current distro (had to pull it from elsewhere)

Once that bit is fixed postfix will throw out a message stating the Username and Password are bad and to check them, giving a link to a site from Google to check on this.

The issue here is that Gmail will not allow a connection unless the option for "Allow less secure apps" to connect is enabled.

Once the above is completed it all works fine.

While I understand this has nothing to do with the project itself, and that other e-mails should work fine, it is a bit frustrating and at the same time confusing to see that even though the instructions are relatively simple they do not work unless fidgeting is done for an hour or two.

**Comment by davidfmiranda** [comment]
Hello @vicosurge, thanks for reporting this issue!

I've been reviewing the SMTP Authentication section and, as you reported, Gmail won't allow connection unless the option Allow less secure apps is enabled. I've opened the [following issue](https://github.com/wazuh/wazuh-documentation/issues/2908) to do a rework of the whole section and include this information.

I'll proceed to close this issue. If you consider that it shouldn't have been closed, please do not hesitate to reopen it again.

Regards,

David

**Comment by vicosurge** [comment]
¡Gracias @davidfmiranda!
