### ISSUE TITLE
Update Wazuh Ansible documentation

### ISSUE THREAD

**Issue by rtnoyld** [wazuh/wazuh-documentation#282]
It's necessary to update the Wazuh Ansible roles documentation accordingly to the latest release.

https://github.com/wazuh/wazuh-ansible/issues/32

**Comment by JuanjiJG** [comment]
Hello all,

I just realized that this task was already done here: https://github.com/wazuh/wazuh-documentation/pull/400

I forgot to link this issue to that pull request. We can proceed to close this.

Regards,
Juanjo
