### ISSUE TITLE
Lock Wazuh repositories 

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#284]
Hello team

  We could consider locking the Wazuh repositories in installations in order to avoid a mismatch between Wazuh API and WazuhApp version. Actually, we indicate in our documentation to lock the Elasticsearch repositories, so WazuhApp it remains in the same version. On the other hand, the Wazuh repository is not locked, so if somebody performs a system upgrade (a long time ago from the first installation) Wazuh Manager and Wazuh API will be upgraded to the latest version and could produce incompatibility with the Wazuh App which remains in the same version as the moment of the first installation. 

Best regards, 
Alberto R.

**Comment by JuanjiJG** [comment]
Done here: #493

Thanks a lot for your contribution @alberpilot!

Regards,
Juanjo
