### ISSUE TITLE
Fix the order of the steps in the Kibana installation

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-documentation#2842]
### Description
Hello team, I found a small mistake in the documentation of the steps to install Kibana, both RPM and DEB. The first step asks to change the owner of a Kibana directory, before installing it.

It is necessary to reverse the order of these two steps in both installation guides:
https://documentation.wazuh.com/3.13/installation-guide/installing-elastic-stack/elastic_server_rpm.html#kibana
https://documentation.wazuh.com/3.13/installation-guide/installing-elastic-stack/elastic_server_deb.html#kibana

**Comment by alberpilot** [comment]
@wazuh/technical-writing please review if it's done in the new documentation installation guide.

**Comment by s-ocando** [comment]
Verified that the steps are in the correct order in the new installation guide.

**Comment by jchermoso** [comment]
I agree.
