### ISSUE TITLE
Adapt DevOps deployments to the next major release

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-documentation#2844]
Hello team,

As the upcoming `v4.0` is about to be released soon, we must update the required instructions and variables that changed recently. 

To do:

- [ ] Review the current documentation.
- [ ] Update Ansible documents.
- [ ] Update Puppet documents. https://github.com/wazuh/wazuh-documentation/pull/2847
- [ ] Update Chef documents.
- [ ] Ensure the documentation compiles properly.

Regards

**Comment by Zenidd** [comment]
## Status Update | September 2, 2020
### Puppet

- The development branch has created: [feature-2844-puppet-docu-update](https://github.com/wazuh/wazuh-documentation/tree/feature-2844-puppet-docu-update)
- The related PR has been created https://github.com/wazuh/wazuh-documentation/pull/2847
- I am in the process of creating detailed sections for groups of variables (Rootcheck, Syscheck, SCA, Syscollector). 
- I found and removed several duplicated variables.

Greetings,

JP

**Comment by Zenidd** [comment]
## Status Update | September 3, 2020
### Puppet

- The development branch has been updated: [feature-2844-puppet-docu-update](https://github.com/wazuh/wazuh-documentation/tree/feature-2844-puppet-docu-update)
- The related PR has been created https://github.com/wazuh/wazuh-documentation/pull/2847
- The agent and manager reference guides have been updated including all the available variables divided by sections:

*Old reference index*
![reference_old](https://user-images.githubusercontent.com/14923294/92136595-7cdb8180-ee0c-11ea-8d4e-f5e416c4297e.png)

*New reference index*
![reference_updated](https://user-images.githubusercontent.com/14923294/92136612-806f0880-ee0c-11ea-86ae-45fefd7e0ff8.png)


Greetings,

JP
