### ISSUE TITLE
Oracle JRE really required via 3rdparty ppa?

### ISSUE THREAD

**Issue by iasdeoupxe** [wazuh/wazuh-documentation#285]
Hi,

https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_deb.html#elastic-server-deb currently is telling us that Oracle Java JRE 8 is required and that a 3rdparty ppa needs to be included on a Debian installation.

However if we're checking:

https://www.elastic.co/guide/en/elasticsearch/reference/current/setup.html

it is currently stating:

> Only Oracle’s Java and the OpenJDK are supported.

As openjdk-8-jre is available in Debian Stretch (and on jessie-backports as well):

https://packages.debian.org/search?keywords=openjdk-8-jre

the documentation could be updated to only suggest the 3rdparty ppa on Debian < stretch or am i wrong?

*Edit*

A more comprehensive compatibility matrix seems to be available here:

https://www.elastic.co/support/matrix#matrix_jvm

**Comment by jesusgn90** [comment]
Hello @iasdeoupxe , thanks for your feedback. What you said makes sense and the team will review it. I'll copy you our decission here.

Regards,
Jesús

**Comment by JuanjiJG** [comment]
Hello @iasdeoupxe,

The main problem here is that Elastic requires Java 8, and in some older distributions, the `openjdk-8` package is not available. Using the 3rd-party PPA allows us to download the compatible version for Java in a wider range of Linux distributions.

In any case, we're still studying this proposal, so nothing is still written in stone.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
As @JuanjiJG said, for now we need to maintain both Java alternatives. We may remove the Oracle alternative in future versions, but not now.

Regards

**Comment by iasdeoupxe** [comment]
@jesusgn90 I had posted this issue not to remove the Oracle alternative completely but add a note to e.g. mention that the Oracle repository is not absolutely required and should be used only if the used linux distro isn't providing Java 8 on its own.

With the current state of the documentation most people on a recent Linux Distro (like e.g. Debian Strech) are adding a completely unnecessary 3rd party repository to their system. Generally this should be done only if it is really required and if there are no other alternatives.

Just to note that i'm running the OpenJDK-8 directly from the Debian repository with the ELK stack since my initial post 2 months ago without any issues.

I strongly suggest to re-think the closing of the issue here and to update the documentation accordingly so that the 3rdparty-PPA is only mentioned as an alternative and not a requirement.

**Comment by JuanjiJG** [comment]
Hi @iasdeoupxe,

We'll discuss your suggestion and make a decision. We'll let you know as soon as possible. Some compatibility concerns are needed to keep in mind.

Regards,
Juanjo

**Comment by iasdeoupxe** [comment]
Suggestion on how to handle this in #436
