### ISSUE TITLE
Review curl commands

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-documentation#289]
Hello team, we have some inconsistences in our curl commands.

- Using `-k` flag with http requests
- We must add double quotes to al URLs cause some linux shells are having troubles parsing `?` out of double quotes
- We have references to localhost and 127.0.0.1, we must use only one
- We have a mix between http and https calls to our API but its default value is http so we must use http in all requests except ssl related docs or lab docs

Regards,
Jesús

**Comment by jesusgn90** [comment]
Done https://github.com/wazuh/wazuh-documentation/pull/290

**Comment by JuanjiJG** [comment]
Reopening this issue. We must review the documentation again and unify the usage of `HTTP` and `HTTPS`.

**Comment by JuanjiJG** [comment]
Done here: #619 

Regards,
Juanjo
