### ISSUE TITLE
Required changes to split rpm and rpm5 repositories

### ISSUE THREAD

**Issue by grg121** [wazuh/wazuh-documentation#2898]
Hello team,

We've experimented some issues with the creation of repositories for rpm/rpm5 explained in this issue: https://github.com/wazuh/wazuh-jenkins/issues/1687 

We've decided to split the rpm repository into two different repositories, rpm, and rpm5. This would require to adapt the installation guides for rpm5 agents.

- https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-agent/linux/centos5/wazuh_agent_package_centos5.html#wazuh-agent-package-centos5

**Comment by alberpilot** [comment]
Repository to be used:
```
rpm --import https://packages.wazuh.com/key/GPG-KEY-WAZUH-5
cat > /etc/yum.repos.d/wazuh.repo <<\EOF
[wazuh_repo]
gpgcheck=1
gpgkey=https://packages.wazuh.com/key/GPG-KEY-WAZUH-5
enabled=1
name=Wazuh repository
baseurl=https://packages.wazuh.com/4.x/yum5/$basearch/
protect=1
EOF
```
