### ISSUE TITLE
agent status is in "never-connected" state

### ISSUE THREAD

**Issue by YashMangla** [wazuh/wazuh-documentation#291]
Hi Guyz,

I installed wazuh in two different vms. one has wazuh agent and other vm has wazuh-manager, wazuh-api and elk stack, wazuh app.

components running on following IP
wazuh-manager: 192.168.115.157
wazuh-agent: 192.168.115.151

I did all configuration properly as mentioned in document. but wazuh-agent is not moving to active state. I didn't have any clue what issue is going on. where i can troubleshoot.

please see below screenshot.
![image](https://user-images.githubusercontent.com/8745715/42691593-48b1739c-86c6-11e8-8096-d31111c2e69e.png)

Please help me to resolve this problem.

**Comment by jesusgn90** [comment]
Hi @YashMangla ,

Your agent is not fully conected to the Wazuh manager regardless its registration. Maybe you forgot to restart the agent? If not the case, follow next steps to verify if there is something wrong.

Login into the Wazuh manager machine and verify the agent status using the next command.

```
# /var/ossec/bin/agent_control -l
```

Check for errors in the manager machine:

```
# cat /var/ossec/logs/ossec.log | grep -i -E '(error|warn)'
```

Also take a look into the ossec.log file from the agent in the same way.

Regards,
Jesús

**Comment by matt-lucero** [comment]
Any updates on this issue? I seem to be encountering the same problem on Wazuh app version 3.3.1, Kibana 6.2.4. ``` /var/ossec/bin/agent_control -l outputs ``` Reports the same thing as Kibana, lists agents with status of ", Never connected". There are no errors or warnings in the ossec.log. Please advise.

**Comment by matt-lucero** [comment]
My issue turned out to be on the agent, I did a TCP dump and found out the agent was trying to listen on the UDP port, which led me to believe Wazuh wasn't picking up the config properly. Sure enough upon restart, the agent reported:
```2018/07/18 21:09:35 ossec-agentd: WARNING: The <server-hostname> tag is deprecated, please use <server><address> instead.
2018/07/18 21:09:35 ossec-agentd: WARNING: The <protocol> tag is deprecated, please use <server><protocol> instead.
2018/07/18 21:09:35 ossec-agentd: INFO: Using notify time: 10 and max time to reconnect: 60```
I was using some deprecated options in the configuration file. Once I changed the agent values per: https://documentation.wazuh.com/3.x/user-manual/reference/ossec-conf/client.html?highlight=server#server-ip it looks like the agents are connecting properly.

**Comment by YashMangla** [comment]
I was struggling to firewall issue it was resolved as of now.

**Comment by YashMangla** [comment]
Hi Team,

Earlier did dry run at test machine. Earlier we didn't able to figure it out the root cause for it. why agent is showing in never disconnected state even we registered agents with manager.

We tried to troubleshoot but still kibana app is still showing in never-connected state.

![image](https://user-images.githubusercontent.com/8745715/49206912-9222b100-f3d9-11e8-8c83-f6d32e1eb458.png)

Kibana Screen:
![image](https://user-images.githubusercontent.com/8745715/49207337-a1562e80-f3da-11e8-829d-a03ad84b542d.png)


Could you guys help me to resolve this issue ASAP.

**Comment by JuanjiJG** [comment]
Hello @YashMangla,

I'll proceed to close this issue. We can continue it on the [Wazuh mailing list](https://groups.google.com/d/msg/wazuh/xL9qWRItmpA/xO16wBVYCAAJ).

Regards,
Juanjo

**Comment by armynavy** [comment]
Hi! im facing the same issue "Never Connected" status of agent. Im new with this but I did follow the documentation on adding agent.

agent's log file wazuh-manager
![image](https://user-images.githubusercontent.com/27793496/50731533-5fbb5f00-11a2-11e9-916d-962f501b9359.png)

agent's log file wazuh-agent
![image](https://user-images.githubusercontent.com/27793496/50731749-69939100-11a7-11e9-9679-0feeaa6a6fd3.png)

/var/ossec/bin/agent_control -l
![image](https://user-images.githubusercontent.com/27793496/50731539-7f528780-11a2-11e9-938f-493fa044ca20.png)

hope someone can help me.

**Comment by abhishekunotech** [comment]
@JuanjiJG . Could you also specify the manager and agent versions? A higher version of manager when compared to agent, could cause this issue..

**Comment by jesusgn90** [comment]
Hi @armynavy and @abhishekunotech ,

> Incorrectly formatted message from agent 'XYZ'

The Wazuh manager version must be greater or equal than the Wazuh agent version. For instance, the Wazuh agent 3.6.1 uses a different cipher for communicating that is not accepted by Wazuh manager 3.4.0. 

My suggestion is to upgrade your Wazuh manager.

- Upgrading same major: 
  - https://documentation.wazuh.com/current/installation-guide/upgrading/latest_wazuh3_minor.html#upgrading-latest-minor
- Product compatibility: 
  - https://documentation.wazuh.com/current/installation-guide/compatibility_matrix/index.html#product-compatibility

I hope it helps.

**Comment by AdjiDarmawan** [comment]
Hi YashMangla, 

I have same problem with you, The agent "Never Connected" status. For fixing this problem, I Just opened port 1514/udp on my agent server.

**Comment by singh0777** [comment]
> Hi YashMangla,
> 
> I have same problem with you, The agent "Never Connected" status. For fixing this problem, I Just opened port 1514/udp on my agent server and wazuh server.
> 
> I think my advice can help your problem. tks

@AdjiDarmawan Could you plz elaborate what exactly did you do to resolve the issue?

**Comment by dkrasmusjohnsen** [comment]
Hi the solution we found was to remove the old client:
Centos: 

# yum remove wazuh-agent

OPS: you need to be ROOT users in roder to give the agent enough rights to run the "shit", normal user will not be enough.
Re-install the agent again but using the managers quick install code:
# sudo WAZUH_MANAGER_IP='YOUR-MANAGER-IP-HERE' yum install https://packages.wazuh.com/3.x/yum/wazuh-agent-3.10.2-1.x86_64.rpm

check the conf file for right manager info:
# nano -w /var/ossec/etc/ossec.conf
output:
<ossec_config>
  <client>
    <server>
      <address>YOUR-MANAGER-IP-HERE</address>
      <port>1514</port>
      <protocol>udp</protocol>
    </server>

That is it.
There could also be your local centos firewall issues, remeber to open up ports on your manager: 
# sudo firewall-cmd --zone=public --add-port=514/udp --permanent
# sudo firewall-cmd --zone=public --add-port=1514/tcp --permanent
# sudo firewall-cmd --zone=public --add-port=1515/tcp --permanent

Or turn the firewall off..

A good thing is always a reboot of the centos pc before reinstall, and restart the agnet after reinstall.

**Comment by abdoni** [comment]
Resolve for me:
chown ossec:ossec /var/ossec/queue/agents-info

https://github.com/wazuh/wazuh/issues/2388

**Comment by biancaasan** [comment]
Hello
I have a problem with agent status, it is never connected.
When I verify /var/ossec/logs/ossec.log  I have some errors
 ossec-analysisd: ERROR: Invalid option 'same_srcip' for rule '100002'.3 ossec-analysisd: CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'.
 ossec-analysisd: ERROR: Invalid option 'same_srcip' for rule '100002'.
 ossec-analysisd: CRITICAL: (1220): Error loading the rules: 'etc/rules/local_rules.xml'.
 

Can you help me, please?

**Comment by abhishekunotech** [comment]
@biancaasan 

I know this is trivial, but could you check that the file local_rules.xml exists in /var/ossec/etc/rules/local_rules.xml, since it checks for these files while loading the agent. I am OoO, but once I am back can check on it.

**Comment by biancaasan** [comment]
@abhishekunotech no, I don't have the file. Can you, please, tell me how can I add it?

**Comment by abhishekunotech** [comment]
@biancaasan 

Could be an issue with the installation, but you could place this file in all your agents at the location - 

https://github.com/wazuh/wazuh/blob/master/etc/local_rules.xml

**Comment by dashashutosh24** [comment]
Restarting wazuh manager with /var/ossec/bin/wazuh-control restart seems to have done the job for me. The agents are showing as connected now.

**Comment by mehmetaskn45** [comment]
The agent I installed on windows says never connected, I wanted to install wazuhu from ubuntu and install an agent on windows, I am waiting for your help on how to solve it.
