### ISSUE TITLE
Check installation guide from sources for CentOS 8

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#2971]
Hello team!

This issue aims to check and fix the steps given for the [installation guide from sources](https://documentation.wazuh.com/3.13/installation-guide/installing-wazuh-manager/linux/centos/wazuh_server_sources_centos.html#wazuh-server-sources-centos) for CentOS.

As @snaow reports, the installation of the Wazuh manager fails in CentOS 8.

Regards,

David

**Comment by tinachoB** [comment]
Hi @davidfmiranda - I've been working on splitting the information from the _Installation guide from sources_ section regarding centOS 6/7 and centOS 8. Maybe you'd like to take a look at the following PR: https://github.com/wazuh/wazuh-documentation/pull/3206 to see if it could be useful to tackle this issue down.
Thanks!

**Comment by davidfmiranda** [comment]
Thank you @tinachoB. I'll review it and merge it as soon as possible. Thanks! 

Regards,

David
