### ISSUE TITLE
"new_template" branch on readthedocs

### ISSUE THREAD

**Issue by hex2a** [wazuh/wazuh-documentation#30]
please consider also building the "new_template" branch on readthedocs.
even if it is still WIP, it reflects the current state of wazuh/master + ELK Stack 5.x

perhaps also using webhooks?
https://docs.readthedocs.io/en/latest/webhooks.html

**Comment by snaow** [comment]
Hi @hex2a,

That's a great idea, we would love to publish the new documentation as soon as posible.
We are not longer using RTD for documentation, we are hosting our own HTML docs at Amazon S3, which would be faster, reliable and powerful.
Let us a few days and we will publish the new documentation, also we are thinking about having two different LIVE documentation sites, one for the latest stable version, the other one for current development version.

Thanks again for the feedback.

**Comment by hex2a** [comment]
Closing this, as the documentation is available at https://documentation-dev.wazuh.com/
