### ISSUE TITLE
Update the description of the delete_old_agents setting

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-documentation#3116]
### Description

As part of the [Epic 5887](https://github.com/wazuh/wazuh/issues/5887) a new setting was added to configure the time after which an agent should be set as disconnected. This suggests that we must be clear in the description of the `delete_old_agents` and specify that is a time after the agent is set as disconnected. So, this may variate depending on the time configured for the new `agents_disconnection_time` included as part of the [Issue 6310](https://github.com/wazuh/wazuh/issues/6310).

### Definition of done

- [x] Setting `delete_old_agents` with the description updated.

**Comment by pereyra-m** [comment]
Closing issue with PR [3124](https://github.com/wazuh/wazuh-documentation/pull/3124)
