### ISSUE TITLE
How to change the admin password?

### ISSUE THREAD

**Issue by vncloudsco** [wazuh/wazuh-documentation#3143]
I want to change this password. How can I do it?

https://github.com/wazuh/wazuh-documentation/blob/cd6b58537abf39ca3f4d7cc4d8e86dc8c5ba4624/resources/open-distro/elasticsearch/roles/internal_users.yml#L14

**Comment by vncloudsco** [comment]
I have fixed this. is crazy. My password contains special characters (@ in password) I changed it to normal and everything is back to normal. Thank you very much, if possible please leave a notice to the user about this filebeat error

**Comment by davidfmiranda** [comment]
Hello @vncloudsco I've been trying to replicate this behavior and you can definitely use special characters in your passwords. I'll close this issue now. If you consider that it should be re-opened, please do not hesitate to do it.

Regards,

David
