### ISSUE TITLE
Review the certificate generation command

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#329]
Hello team

  I see in this section: 
https://documentation.wazuh.com/current/installation-guide/optional-configurations/kibana_ssl.html
  
![image](https://user-images.githubusercontent.com/3830293/43570852-b25a9b1e-963b-11e8-950c-8e14062a1411.png)

a flag which indicates the validity of 365 days. On the other hand: 
https://documentation.wazuh.com/current/installation-guide/optional-configurations/elastic_ssl.html

![image](https://user-images.githubusercontent.com/3830293/43570938-ee1fbd5a-963b-11e8-90e4-0d3aaae4c91e.png)

the same flag has 3650 days. It make sense?
Best regards, 

Alberto R.

**Comment by JuanjiJG** [comment]
Done here: #494

Thanks a lot for your contribution @alberpilot!

Regards,
Juanjo
