### ISSUE TITLE
Missing information in audit configuration section 3.11 - 3.12 - 3.13 - 4.0

### ISSUE THREAD

**Issue by tinachoB** [wazuh/wazuh-documentation#3311]
# Missing configuration in audit configuration section

## Description
In section [User manual - Capabilities - Monitoring system calls - Configuration](https://documentation.wazuh.com/4.0/user-manual/capabilities/system-calls-monitoring/audit-configuration.html#editing-ossec-conf) it seems like for some reason an ossec configuration section is missed since version 3.11 and above. The text says: "_Wazuh must be aware of the events detected by Audit. So, it is needs to be configured to read the audit log file:"_ ending with a ":" which tends the user to expect an example which is not there.

Version 3.10 is correct and it has the complete information.
- **Documentation for 3.11, 3.12, 3.13 and 4.0:**
![image](https://user-images.githubusercontent.com/22640902/105648552-d7907b00-5e8a-11eb-9e05-b7f38e68ea65.png)

- **Documentation for 3.10:**
![image](https://user-images.githubusercontent.com/22640902/105648489-8b453b00-5e8a-11eb-9e93-6c39cb8fbb1d.png)

This was reported by an user over the Slack Community channel: https://wazuh.slack.com/archives/C0A933R8E/p1611517111185200

**Comment by s-ocando** [comment]
This issue has been solved by fixing a broken code block. All branches have been updated.
