### ISSUE TITLE
When to use which? (and some other questions and comments)

### ISSUE THREAD

**Issue by barahon** [wazuh/wazuh-documentation#34]
(sorry for over-loading the Issue)

When does one choose the "OSSEC HIDS" container versus the "OSSEC-ELK" container?

I'm guessing that since the WUI is abandoned and I don't have an ELK of my own, I want OSSEC-ELK, but even if I'm correct, shouldn't that be in the doc somewhere?

Where's the dashboard? I see 5 ports being mapped to the container, but which one is the dashboard? I'll try my browser against them all, but shouldn't that go in the doc, too?

In my opinion, the section that gives credit to xetus-oss should not be in the middle of the Docker installation section. It could be first, or before the container sections, or in the head of each container section, instead.

Last, I wish there was a "bunny slope", a guide for impatient geeks. There are lots of setup choices, and I'm hoping the container is the simplest and fastest.

Thank you for making it easy to offer feedback!

**Comment by snaow** [comment]
Hi @barahon,

Thanks for your feedback, we really appreciate it.
We are working on a new documentation where we'll try to improve and made simpler the process of installing Wazuh, including Docker containers.
We are in process of prepare a new docker containers for Wazuh and Elastic Stack, using last Docker technology (docker compose) for modular building.

Regarding to the ports:
55000: Wazuh RESTful API
1514: OSSEC UDP Communication port
1515: OSSEC Authd registration service
514: Standard syslog port
5601: Kibana (Dashboards) web port

BTW, I like your idea of a guide for "impatient geeks" or "quick guide", we will think about it.

Best regards,
Pedro Sanchez.

**Comment by jlruizmlg** [comment]
Hi @barahon you can also take a look from our last [wazuh-docker](https://github.com/wazuh/wazuh-docker) container, which has the last Wazuh 2.0 (here the [Changelog](https://github.com/wazuh/wazuh/blob/master/CHANGELOG.md)) and ELK 5.3 which include the last version from our plugin for kibana [WazuhAPP](https://github.com/wazuh/wazuh-kibana-app).

**Comment by jesuslinares** [comment]
Here the current documentation for wazuh-docker container: https://documentation.wazuh.com/current/docker/index.html.

Let us know if you have any questions.
Thanks for your feedback.
