### ISSUE TITLE
Review Learning Wazuh documentation

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-documentation#341]
### Pending tasks

- [x] The learning Wazuh documentation received some grammar typos on the `3.7` branch. We need to merge this into the `dev-learning-wazuh` branch.
- [x] After merging all the content, review each document. For each document we need the following:
  - [x] Review grammar.
  - [x] Update with latest Wazuh features, keeping in mind possible breaking changes or new ways to configure certain features.
  - [x] Review document structure.
- [x] Review images.
- [ ] Final revision to ensure everything is properly organized.
- [ ] After merging and make the documentation available for everyone, we need to remove the documentation from previous branches in order to avoid them to appear on the search results.
- [x] Fix note message on `audit-commands -> make-a-smarter-list` about "not needed to restart Wazuh manager after recompiling CDB lists".

**Comment by JuanjiJG** [comment]
**September 14th update**

We've merged the last PR from @branchnetconsulting (https://github.com/wazuh/wazuh-documentation/pull/188), and now we are going to work on updating the contents to make it compatible with the latest versions of Wazuh.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Updating the first comment to add an initial list of pending tasks in order to accomplish this task.

**Comment by jctello** [comment]
New push checklist:
 - [ ] Add more options to set up the lab environment other than Amazon S3
   - [ ] OVA
   - [ ] vagrant
   - [ ] Multi computer
 - [ ] Review current Labs:
    - [ ] Detect an ssh brute-force
    - [ ] Detect an RDP brute force attack
    - [ ] Expose hiding processes
    - [ ] Detect filesystem changes
    - [ ] Change the rules
        - [ ] Contributing to the ruleset
    - [ ] Survive a log flood
    - [ ] Detect and react to a Shellshock attack
    - [ ] Keep watch for malicious command execution
    - [ ] Catch suspicious network traffic
    - [ ] Track down vulnerable applications
 - [ ] Add new Labs
    - [ ] Creating a custom integration
    - [ ] Agent deployment methods
    - [ ] Harden a system's security (SCA, OpenSCAP labs)
    - [ ] Owlh enhancement

 - [ ] Consider adding more in-depth labs
    - [ ] Creating custom dashboards (not really Wazuh)
    - [ ] Balancing agents (Load Balancers and fail backs)
    - [ ] Troubleshooting errors
    - [ ] Agentless monitoring
        - [ ] Network devices 
            - [ ] Syslog
            - [ ] agentless
        - [ ] AWS
        - [ ] Mobile devices

**Comment by jctello** [comment]
## New Structure

 - Introduction page (This could also include a set of clear objectives).
    - Building your environment
          - Virtual Machine Appliance + Additional Virtual Machines for the Agents.
          - Fully automated vagrant scripts
          - Docker containers?
          - Amazon EC2 VPC
     - Configure the Wazuh Components
          - Wazuh Manager
          - Elastic Stack Software
          - Wazuh Linux Agent
          - Wazuh Windows Agent
     - Wazuh Lab Tutorials
          - Detect an ssh brute-force
          - Detect an RDP brute force attack
          - Expose hidden processes
          - Detect filesystem changes
          - Change the rules
              - Contributing to the ruleset
          - Survive a log flood
          - Detect and react to a Shellshock attack
          - Keep watch for malicious command execution
          - Catch suspicious network traffic
          - Track down vulnerable applications
