### ISSUE TITLE
Links return 404 in Securing Wazuh API Documentation

### ISSUE THREAD

**Issue by isaaclepes** [wazuh/wazuh-documentation#3427]
https://documentation.wazuh.com/current/user-manual/api/securing_api.html

The links for these items return 404 errors, which is a problem because I could really use the topic on changing wazuh and wazuh-wui passwords.

"The default password can be changed using the following Wazuh API request: PUT /security/users/{user_id}"
LINK: https://documentation.wazuh.com/current/user-manual/api/4.1user-manual/api/reference.html#operation/api.controllers.security_controller.update_user

"After changing the password, there is no need to restart the Wazuh API but a new authentication will be required for the affected users."
LINK: https://documentation.wazuh.com/current/user-manual/api/4.1user-manual/api/reference.html#operation/api.controllers.security_controller.login_user

**Comment by isaaclepes** [comment]
Also, if someone could please provide an example of curl command to change the Wazuh API user passwords, I would really appreciate it. I really would like to secure that hole.

**Comment by isaaclepes** [comment]
(I didn't mean to reply and close)

**Comment by isaaclepes** [comment]
I finally found the API documentation by comparing the invalid URLs to working URLs.  If anyone else comes looking, here is how to change the API passwords with curl

Store token

TOKEN=$(curl -u wazuh:wazuh -k -X GET "https://localhost:55000/security/user/authenticate?raw=true")

Find the numeric ID of user with

curl -k -X GET "https://localhost:55000/security/users" -H "Authorization: Bearer $TOKEN"

change password for user ID 1
curl -k -X PUT -d '{ "password": "My!NewP4ssword", "allow_run_as": false }' "https://localhost:55000/security/users/1" -H "Authorization: Bearer $TOKEN" -H "Content-Type: application/json"

**Comment by davidfmiranda** [comment]
Hello @isaaclepes, we have fixed this issue in the following PRs
- [4.0](https://github.com/wazuh/wazuh-documentation/pull/3451)
- [4.1](https://github.com/wazuh/wazuh-documentation/pull/3452)

Thanks for reporting this issue. I'll close this issue now. If you consider that it should be re-opened, please do not hesitate to open it again.

Regards,

David
