### ISSUE TITLE
Rename users and group according to the Wazuh standard

### ISSUE THREAD

**Issue by danimegar** [wazuh/wazuh-documentation#3522]
### Description

According to the described in https://github.com/wazuh/wazuh/issues/7646, `ossec`, `ossecr` and `ossecm` users will be replaced by the user wazuh. Also, the `ossec` group will be replaced by the `wazuh` group.

I found some references related to these users and group:
- source/deploying-with-ansible/reference.rst
- source/development/makefile.rst
- source/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-agent/index.rst
- source/installation-guide/more-installation-alternatives/wazuh-from-sources/wazuh-server/index.rst
- source/installation-guide/wazuh-agent/wazuh_agent_package_hpux.rst
- source/user-manual/reference/daemons/wazuh-agentd.rst
- source/user-manual/reference/daemons/wazuh-csyslogd.rst
- source/user-manual/reference/daemons/wazuh-dbd.rst
- source/user-manual/reference/daemons/wazuh-maild.rst
- source/user-manual/reference/daemons/wazuh-agentd.rst
- source/user-manual/reference/daemons/wazuh-monitord.rst
- source/user-manual/reference/daemons/wazuh-remoted.rst
- source/user-manual/reference/ossec-conf/global.rst
- Check for more references.

Regards,
Daniel

**Comment by alromeros** [comment]
Devel branch: https://github.com/wazuh/wazuh-documentation/tree/3522-rename-users-group
