### ISSUE TITLE
4.1 Documentation - 2 bugs - Change User Password Incorrect Command + Spelling

### ISSUE THREAD

**Issue by squirrelboot** [wazuh/wazuh-documentation#3525]
[https://i.imgur.com/EHYpi0N.png](https://i.imgur.com/EHYpi0N.png)

As shown, there is a duplicate curl call, and then a subsequent incorrect continuation of the tutorial:
`bash wazuh-passwords-tool.sh -u admin -p mypassword` should be passwords.sh in the example. 

Additionally, in the password changing script, at the end, where it reminds you to update filebeat.yml and kinbana.yml, it has a spelling error:
`Passwords changed. **Renember** to update the password in /etc/filebeat/filebeat.yml and /etc/kibana/kibana.yml if necessary and restart the services.`

**Comment by davidfmiranda** [comment]
Hello @squirrelboot, thanks for reporting. I've already fixed the double call to `curl` and the typo.

I'll close this issue now. If you consider that it shouldn't be closed, please do not hesitate to reopen it again.

Regards,

David
