### ISSUE TITLE
Error in active-response command example

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-documentation#3537]
The  `<command>` block in _**Add an IP to the iptables deny list**_ section of [`active-response`](https://documentation.wazuh.com/current/user-manual/capabilities/active-response/remediation-configuration.html#add-an-ip-to-the-iptables-deny-list) documentation is not correct:

```
<command>
  <name>firewall-drop</command>
  <executable>firewall-drop.sh</executable>
  <expect>srcip</expect>
</command>
```

The correct `command` block should be:

```
<command>
  <name>firewall-drop</name>
  <executable>firewall-drop.sh</executable>
  <expect>srcip</expect>
</command>
```

**Comment by s-ocando** [comment]
Issue is fixed https://github.com/wazuh/wazuh-documentation/commit/9f9178b3ca1590cf3198637a811206b33abd7cf7. Thanks @Rebits for reporting!
