### ISSUE TITLE
Missing Elasticsearch restart in user manual for X-Pack

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-documentation#355]
Hello team, if you follow next steps:

2. Enable the Security plugin on Elasticsearch. On the same machine where Elasticsearch is installed, open the /etc/elasticsearch/elasticsearch.yml file and set this option to true:

```
# Set this option in /etc/elasticsearch/elasticsearch.yml
xpack.security.enabled: true
```

3. Create the passwords for the built-in users. The interactive mode prompts the user to enter new passwords for the elastic, kibana, logstash_system, and beats_system users:

```
# /usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive
```

Elasticsearch will throw this error:

```
[root@localhost ~]# /usr/share/elasticsearch/bin/elasticsearch-setup-passwords interactive

Unexpected response code [500] from calling GET http://127.0.0.1:9200/_xpack/security/_authenticate?pretty
It doesn't look like the X-Pack security feature is enabled on this Elasticsearch node.
Please check if you have enabled X-Pack security in your elasticsearch.yml configuration file.

ERROR: X-Pack Security is disabled by configuration.
```

You must restart Elasticsearch after modify its configuration file.

**Comment by JuanjiJG** [comment]
Thanks for the report @jesusgn90, I'll fix it immediately.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Done here: https://github.com/wazuh/wazuh-documentation/pull/356

Regards,
Juanjo
