### ISSUE TITLE
Document the addition of Arch Linux as supported OS for Vulnerability Detector

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-documentation#3577]
### Description

Issue https://github.com/wazuh/wazuh/issues/7075 adds Arch Linux as a supported OS for Vulnerability Detector including a vendor feed as well.

These changes should be reflected in the documentation as follows:

- The inventory section should include the improvements to the Linux package inventory, which collects the pacman packages
- The Vulnerability Detector section must include the new feed and the Arch Linux OS as supported platform
- The Vulnerability Detector reference has to include the new provider as well

**Comment by alromeros** [comment]
**Devel branch:** https://github.com/wazuh/wazuh-documentation/tree/3577-arch-linux-support-docu
