### ISSUE TITLE
Create Wazuh 4.2.0 release notes

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3587]
Hello team!

This issue aims to create the release notes for 4.2.0.

Regards,

David

**Comment by MarVergara** [comment]
First review done. 
Pending changes from other teams.

**Comment by MarVergara** [comment]
Hi team, 
Release Notes 4.2.0 has been created so I'm closing this issue. 
I'm opening issue #3902 as a second iteration to update the RNs based on current Changelog changes. 
Regards,
Mariel
