### ISSUE TITLE
Create Central components index page

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3593]
Hello team!

The aim of this issue is to create the content of the new page in the installation guide "Central components" where all the server-side components of Wazuh will be briefly explained.

Regards,

David

**Comment by s-ocando** [comment]
First iteration of the "Central components" section is finished here https://github.com/wazuh/wazuh-documentation/commit/13d1defde616c6771e8d64854c087f51e9858958.
