### ISSUE TITLE
Review installation guide index

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3625]
Hello team,

The aim of this issue is to improve the installation guide index.

Regards,

David

**Comment by MarVergara** [comment]
IG Review_ V1

- [ ] Installation guide
  - [ ] Requirements
  - [ ] Wazuh server
    - [ ] All-in-one deployment
      - [ ] Unattended installation
      - [ ] Step-by-step installation
    - [ ] Distributed deployment 
      - [ ] Unattended installation
        - [ ] Elasticsearch & Kibana unattended installation 
        - [ ] Wazuh server unattended installation
      - [ ] Step-by-step installation
        - [ ] Elasticsearch cluster
          - [ ] Elasticsearch single-node cluster 
          - [ ] Elasticsearch multi-node cluster
        - [ ] Wazuh cluster 
          - [ ] Wazuh single-node cluster
          - [ ] Wazuh multi-node cluster
          - [ ] Kibana
  - [ ] Wazuh agent 
    - [ ] AIX 
    - [ ] HP-UX
    - [ ] Linux
    - [ ] macOS
    - [ ] Solaris
    - [ ] Windows
    - [ ] Deployment variables
      - [ ] Deployment variables for AIX
      - [ ] Deployment variables for Linux
        - [ ] Deployment variables for Linux using apt repository
        - [ ] Deployment variables for Linux using dnf repository
        - [ ] Deployment variables for Linux using yum repository
        - [ ] Deployment variables for Linux using zypper repository
      - [ ] Deployment variables for macOS
      - [ ] Deployment variables for Windows
  - [ ] Packages list 
  - [ ] More installation alternatives
    - [ ] Wazuh with Elastic Stack basic license
      - [ ] All-in-one deployment
        - [ ] Unattended installation
        - [ ] Step-by-step installation
      - [ ] Distributed deployment 
        - [ ] Unattended installation
          - [ ] Elasticsearch & Kibana unattended installation 
          - [ ] Wazuh server unattended installation
        - [ ] Step-by-step installation
          - [ ] Elasticsearch cluster
            - [ ] Elasticsearch single-node cluster 
            - [ ] Elasticsearch multi-node cluster
          - [ ] Wazuh cluster 
            - [ ] Wazuh single-node cluster
            - [ ] Wazuh multi-node cluster
          - [ ] Kibana
    - [ ] Wazuh with Splunk
      - [ ] Install Splunk in single-instance mode
      - [ ] Installing & Configuring Splunk Cluster
      - [ ] Install the Wazuh app for Splunk
      - [ ] Install and configure Splunk Forwarder
      - [ ] Setting up reverse proxy configuration for Splunk
      - [ ] Customize agents status indexation
    - [ ] Wazuh installation from sources 
      - [ ] Installing Wazuh server from sources 
      - [ ] Installing Wazuh agent from sources

**Comment by MarVergara** [comment]
V2 done based on Sandra's feedback.
