### ISSUE TITLE
CVEs alerts inventory for Vulnerability Detector - Documentation analysis

### ISSUE THREAD

**Issue by DProvinciani** [wazuh/wazuh-documentation#3627]
### Description

As part of the epic https://github.com/wazuh/wazuh/issues/7749, we are implementing a mechanism to have an inventory of vulnerabilities that affect the endpoint in which the Wazuh agent is installed. For doing this, many things change in Vulnerability Detector, from the setting to the scanning mechanisms. Having said that, all the documentation should be reviewed in order to determine the list of changes that should be implemented.

**Comment by MiguelazoDS** [comment]
### Introduction

Some needed chages were already included in the documentation ([#3600](https://github.com/wazuh/wazuh-documentation/pull/3600)) as consequence of the modifications introduced by [#7892](https://github.com/wazuh/wazuh/pull/7892) that involves the renaming of `ignore_time` property as `min_full_scan_interval`. In addition other required changes are detailed below.

### Documentation revision

Sequence diagram image with `ignore_time` -> `./source/images/manual/vuln-detector/vuln-detector-workflow.png` needs to be changed.

Revise the columns names [syscollector-operating_system](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#operating-system). New columns `reference` `triaged` were added. 
**Description**: Hash reference, row identifier, **Available**: All.
**Description**: Scan indicator **Available**: All.

New `item_id` column added [syscollector-packages](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#packages)
**Description**: package identified, **Available**: All

New `checksum` column added [sycollector-hotfixes](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#windows-updates)
**Description**: Hash reference, **Available**: Windows

Add new searchable fields [Kibana fields](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#new-searchable-fields-for-kibana)

New output for `sqlite> select * from sys_programs where name="wazuh-agent";`

Revise [API doc](https://documentation.wazuh.com/current/user-manual/api/reference.html)

[status & type Issue](https://github.com/wazuh/wazuh/issues/7972)
[status & type PR](https://github.com/wazuh/wazuh/pull/8100)

-------------------------------------------

Redo [How does vulnerability detection work](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how_it_works.html#how-it-works)

New sequence diagram.

**Scan types:**

*BASELINE*: This scan type will be triggered the first time after Vulnerability Detector is enabled. It performs a full scan for every single package installed as well as the operating system. As a result, the CVEs inventory will have the information of the vulnerabilities detected but no alerts will be generated.

*FULL_SCAN*: In this scan type, every single package installed as well as the operating system are scanned. It runs only when the configured min_full_scan_interval expires and the CVEs database is updated with new information. As a result, the newly detected vulnerabilities and the ones that no longer affect the agent will be alerted.

*PARTIAL_SCAN*: Only new packages are scanned and the vulnerabilities detected are alerted.

If Vulnerability Detector is enabled after having been disabled, the BASELINE scan should run again.
    The new min_full_scan_interval setting, will protect the manager performance from running many Vulnerability Detector scans in case of receiving many updates of vulnerabilities feeds.

**Alerts**

- No alerts are generated for the results of a BASELINE scan.
- Detection alerts are generated in a PARTIAL_SCAN when is detected that a vulnerability affects one of the packages scanned.
- Detection alerts are generated in a FULL_SCAN when is detected that a vulnerability affects one of the packages scanned.
- Removal alerts are generated in a FULL_SCAN when is detected that a vulnerability is OBSOLETE.

**Comment by DProvinciani** [comment]
Having the details of the changes that should be implemented, we close the issue.
