### ISSUE TITLE
Rules' if_sid documentation

### ISSUE THREAD

**Issue by nmkoremblum** [wazuh/wazuh-documentation#3653]
Hi team!

Given a Slack's Community question: 

> <if_sid> can have more than one id inside? like <if_sid>10231,10232</if_sid>

I realized that the [description of the rules' configuration label](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#if-sid) "**if_sid**" is not totally complete as _it is possible to include many rules' id_ inside of this label (separated by commas or spaces) but this is not explained in the docs and it may confuse the users regarding whether is possible to add múltiple rules' id inside or not.

Regards,

Mariano :)

**Comment by tinachoB** [comment]
Hi @davidfmiranda , @s-ocando - Another community user had the same confusion here (Reference: https://wazuh.slack.com/archives/C0A933R8E/p1623243901237000)

Could you please update the documentation with the Mariano' suggestion? I'd be really helpful to avoid future confusions.

Thanks!
