### ISSUE TITLE
Windows registration process

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-documentation#369]
Hi team, 

there's a problem with Windows versions older than Windows 2008 server, Windows 7, etc. when the agent tries to register with the manager using _authd_. 

By default, authd runs using TLS v1.2 but in old Windows version, the TLS is older than TLS v1.2, so the agent can't be registered using authd unless you run in the manager `ossec-authd` with the `-a` parameter or set `ssl_auto_negotiate` parameter to _yes_ in the `auth` section of the `ossec.conf`.

We should add a warning message in the _Install Wazuh agent on Windows_ page.

Regards,
Braulio.

**Comment by JuanjiJG** [comment]
Done here: #555

Regards,
Juanjo
