### ISSUE TITLE
5.0 Getting started components rework

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3691]
Hello team! 

The aim of this issue is to adapt the Components section in the Getting started section for Wazuh 5.0. 

We must adapt the content of this section to include the new components and nomenclature. 

Besides, we may study simplifying the components description and move this information to the user manual

Regards,

David

**Comment by s-ocando** [comment]
A new Getting Started components section, that includes descriptions of the new Wazuh componentes, was introduced in https://github.com/wazuh/wazuh-documentation/pull/3999.
