### ISSUE TITLE
5.0 Getting started Architecture rework

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3692]
Hello team!

The aim of this issue is to adapt the Architecture section in the Getting started for Wazuh 5.0.

We must also change the diagrams of the section.

Regards,

David

**Comment by s-ocando** [comment]
A new Getting Started, that includes an updated Architecture section, was introduced in https://github.com/wazuh/wazuh-documentation/pull/3999.
