### ISSUE TITLE
5.0 Getting started Use cases rework 

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3693]
Hello team!

The aim of this issue is to adapt the Use cases section of the Getting started for Wazuh 5.0.

We may link examples in the documentation to enrich this section.

Besides, we must improve/adapt the existing examples.

Regards,

David

**Comment by s-ocando** [comment]
A new Getting Started, that includes an updated 'Use cases' section, was introduced in https://github.com/wazuh/wazuh-documentation/pull/3999.
