### ISSUE TITLE
5.0 Installation guide - Adapt Wazuh agent section

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3700]
Hello team! 

The aim of this issue is to improve the existing Wazuh Agents installation section.

We must clarify and improve the instructions for its installation and if necessary, adapt it to the new changes.

Regards,

David

**Comment by s-ocando** [comment]
A new installation guide was introduced in https://github.com/wazuh/wazuh-documentation/pull/3999.
