### ISSUE TITLE
5.0 Installation guide - Create Wazuh manager section

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3701]
Hello team!

The aim of this issue is to create the Wazuh manager section. We will unify the instructions for single-node and multi-node clusters installation to simplify its process.

This section will explain how to install the Wazuh manager and how to modify its configuration so to make it work in distributed nodes, single and multi-node.

Regards,

David

**Comment by s-ocando** [comment]
A new installation guide, with unified instructions to install the Wazuh server as a single-node or as a multi-node cluster, was introduced in https://github.com/wazuh/wazuh-documentation/pull/3999.
