### ISSUE TITLE
5.0 Installation guide - Create Wazuh indexer section

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3702]
Hello team!

The aim of this issue is to create the Wazuh indexer section.

This section will explain how to install and configure it.

The section will explain how to install it as part of an all-in-one deployment and then, will explain how to modify the configuration to make it work in a distributed deployment for both single and multi-node clusters.

Regards,

David

**Comment by s-ocando** [comment]
A new installation guide, that includes instructions to install the Wazuh indexer, was introduced in https://github.com/wazuh/wazuh-documentation/pull/3999.
