### ISSUE TITLE
5.0 Installation guide - Create Quickstart section

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3704]
Hello team! 

The aim of this issue is to create the Quickstart section for Wazuh 5.0.

This section will explain how to use the unattended installation script to install Wazuh as an all-in-one deployment.

Besides, it must provide some useful information about what will be installed and how to continue after installing Wazuh.

Regards,

David

**Comment by MarVergara** [comment]
This issue is no longer structured according to our roadmap.
