### ISSUE TITLE
Amazon Linux support for Vulnerability Detector

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-documentation#3770]
### Description

Issue wazuh/wazuh#6734 adds Amazon Linux as a supported OS for Vulnerability Detector including a vendor feed as well.

These changes should be reflected in the documentation as follows:

- The Vulnerability Detector section must include the new feeds and the Amazon Linux and Amazon Linux 2 operating systems as supported platforms
- The Vulnerability Detector reference has to include the new provider as well

**Comment by alromeros** [comment]
**Devel branch:** https://github.com/wazuh/wazuh-documentation/tree/3770-vuln-detector-amazon-support

**Comment by alromeros** [comment]
**Pull Request:** https://github.com/wazuh/wazuh-documentation/pull/3796
