### ISSUE TITLE
Make the Vulnerability Detector module obtain the packages to be scaned in an atomic way - Documentation changes

### ISSUE THREAD

**Issue by palaciosjeremias** [wazuh/wazuh-documentation#3839]
Description
As part of the epic https://github.com/wazuh/wazuh/issues/8529, we improved Vulnerability Detector queries with WazuhDB to solve them in an atomic way excluding the possibility of race conditions and DB modifications between related queries.

With this new development, the following must be included/updated in the documentation:
- A new Vulnerability Detector config is added to ossec.conf and must be included in the corresponding section of Wazuh documentation.
  - This setting is named retry_interval, is 30 seconds by default, and out-of-the-box is hidden to the user. It's used to configure the amount of time that Vulnerability Detector will wait before retrying to scan an agent that wasn´t able to be scanned previously.

**Comment by DProvinciani** [comment]
Closing the issue as the pull https://github.com/wazuh/wazuh-documentation/pull/3838 was merged.
