### ISSUE TITLE
Review owner from Kibana files in major upgrades

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-documentation#385]
Since we are migrating to use `sudo -u kibana` when installing the Wazuh app, older environments probably have root:root for a few of files, we need to add the next commands before upgrading:

`chown -R kibana:kibana /usr/share/kibana/optimize`
`chown -R kibana:kibana /usr/share/kibana/plugins`

**Comment by JuanjiJG** [comment]
Done here: https://github.com/wazuh/wazuh-documentation/pull/396

Regards,
Juanjo
