### ISSUE TITLE
Review the Wazuh cluster development section and change `wazuh.cluster` paths

### ISSUE THREAD

**Issue by mcarmona99** [wazuh/wazuh-documentation#3854]
Hi team,

Our Wazuh cluster development documentation has wrong paths to cluster classes and functions.

As an example, the `Code structure` section says the following:

> The higher classes on the diagram (`wazuh.cluster.common.Handler`, `wazuh.cluster.server.AbstractServerHandler` and `wazuh.cluster.client.AbstractClient`) define abstract concepts ...

Every `wazuh.cluster` occurrence must be changed to `wazuh.core.cluster` as it is the real path.
We also need to change the pictures as these class paths are also wrong.

Review the entire **Development > Wazuh cluster** section to fix these errors. Change any other mistake in case there are more.

Regards,
Manuel.

**Comment by Selutario** [comment]
# Update

Hello team,

As explained in the original post, all paths like `wazuh.cluster.common.Handler`, `wazuh.cluster.server.AbstractServerHandler`, etc. should be renamed to `wazuh.core.cluster.common.Handler`, `wazuh.core.cluster.server.AbstractServerHandler`, etc. in the schemas.

It is, all paths starting with `wazuh.cluster.X` should now be renamed to `wazuh.core.cluster.X` in these 4 images:

------------------

- https://documentation.wazuh.com/current/_images/cluster_protocol_handler1.png
![imagen](https://user-images.githubusercontent.com/23361101/123981189-6ff2d480-d9c2-11eb-805a-a9f1c7239f21.png)

------------------

- https://documentation.wazuh.com/current/_images/cluster_clients1.png
![imagen](https://user-images.githubusercontent.com/23361101/123981255-7bde9680-d9c2-11eb-8d71-3aaaa2592246.png)

------------------

- https://documentation.wazuh.com/current/_images/cluster_servers1.png
![imagen](https://user-images.githubusercontent.com/23361101/123981293-839e3b00-d9c2-11eb-8fb6-c6574b755008.png)

------------------

- https://documentation.wazuh.com/current/_images/receive_file_task_cluster1.png
![imagen](https://user-images.githubusercontent.com/23361101/123981409-944eb100-d9c2-11eb-9c1c-133567d22ff8.png)

------------------

Regards,
Selu.

**Comment by FelipeKnudsen** [comment]
Next week we'll have those changes [here](https://drive.google.com/drive/u/4/folders/1y5tLjfv_TLgLaOvH4wfdZTX2va9H26sM).

**Comment by FelipeKnudsen** [comment]
I've made the paths renames. 
[**Files Here**](https://drive.google.com/drive/u/4/folders/11Nyhzj5SIRxxwz1m-XpsIjUiuUAEdOdS)

![cluster_protocol_handler](https://user-images.githubusercontent.com/80284649/124465135-6d4e0180-dd6b-11eb-92ee-b4756f87d8a0.png)
![cluster_servers](https://user-images.githubusercontent.com/80284649/124465137-6de69800-dd6b-11eb-967a-8fe97f04eed1.png)
![receive_file_task_cluster](https://user-images.githubusercontent.com/80284649/124465138-6e7f2e80-dd6b-11eb-99f3-f1b93aa186c7.png)
![cluster_clients](https://user-images.githubusercontent.com/80284649/124465131-6c1cd480-dd6b-11eb-9628-992b2e5eb068.png)

**Comment by Selutario** [comment]
Hi @FelipeKnudsen!

Thank you very much! Everything is correct, except in the first diagram where there is a path to update yet (`wazuh.cluster.common.Handler` -> `wazuh.core.cluster.common.Handler`). 
![imagen](https://user-images.githubusercontent.com/23361101/125244672-e27f8080-e2ef-11eb-9f73-92c4b2491506.png)

Let me know when it is ready.

Regards,
Selu.

**Comment by FelipeKnudsen** [comment]
@Selutario Thanks for your feedback, Selu! I've made the change in the path.
[**Files Here**](https://drive.google.com/drive/u/4/folders/11Nyhzj5SIRxxwz1m-XpsIjUiuUAEdOdS)

![cluster_protocol_handler](https://user-images.githubusercontent.com/80284649/125272080-d260a480-e2e1-11eb-8ac2-de97e6eedd17.png)
