### ISSUE TITLE
Current installation guide - Index

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3857]
Hello team!

The aim of this issue is to adapt the current installation guide index to the new structure proposed.

We must clarify the differences between the kinds of deployments type.

# Iteration 1

- [x] Technical review by @s-ocando 

# Iteration 2

- [x]  Editorial review by @MarVergara 

Regards,

David

**Comment by MarVergara** [comment]
Done - pending review
