### ISSUE TITLE
Current installation guide - Quickstart

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3858]
Hello team!

The aim of this issue is to create the `Quickstart `page on the installation guide.

This section will guide the user through the all-in-one unattended installation and will have some more extra information to show what can be done with Wazuh.

# Iteration 1

- [x] Technical review by @s-ocando #3999

# Iteration 2

- [x]  Editorial review by @MarVergara #4056 

Regards,

David

**Comment by MarVergara** [comment]
As a second iteration to this issue, an editorial review will be carried out in this section according to the Style Guide to ensure style consistency and avoid customer-facing errors.
