### ISSUE TITLE
Current installation guide - Step-by-step installation

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3859]
Hello team!

The aim of this issue is to reorganize the step-by-step installation guides to merge them into simpler guides that show the users how to install and configure both single-node and multi-node installation.

This task will require reorganizing the different installation steps and the documents to combine the different alternatives into simpler documents.

# Iteration 1. Technical review by @s-ocando. (In progress)

- [x] Wazuh server
- [x] Wazuh indexer
- [x] Wazuh interface

# Iteration 2. Editorial review by @MarVergara. 

- [x] Wazuh server
- [x] Wazuh indexer
- [x] Wazuh interface

Regards,
David

**Comment by MarVergara** [comment]
The editorial review will close the following issues related to each subsection included in the Step-by-step installation [macro]section.

- Wazuh single-node cluster #3733 
- Wazuh multi-node cluster #3734 
- Kibana #3735

**Comment by MarVergara** [comment]
7/16/2021
Starting editorial review for Wazuh server - step-by-step section.

**Comment by MarVergara** [comment]
7/20/2021
Editorial review of Wazuh server_step by step_ section done. 
Editorial review of Wazuh interface_step by step_ section WIP.

**Comment by MarVergara** [comment]
7/21/2021
Editorial review of Wazuh interface_step by step_ section - Done and ready for review.
