### ISSUE TITLE
Current installation guide - Unattended installation

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3860]
Hello team!

The aim of this issue is to create an `Unattended installation` section that explains to the users how to use the unified unattended installation script (#3634)  and how to install all the different Wazuh components.

This section will include a table with all the available options for the script and its usage. Besides, it must explain how to install every single Wazuh component one by one.

# Iteration 1. Technical review by @s-ocando.

- [x]  Wazuh indexer
- [x]  Wazuh server
- [x]  Wazuh interface

# Iteration 2.  Editorial review by @MarVergara. 

- [x]  Wazuh indexer
- [x]  Wazuh server
- [x]  Wazuh interface

Regards,

David

**Comment by MarVergara** [comment]
As a second iteration to this issue, an editorial review will be carried out in this section according to the Style Guide to ensure style consistency and avoid customer-facing errors.

**Comment by s-ocando** [comment]
We need to adapt instructions to the [new unified unattended installation](https://github.com/wazuh/wazuh-packages/blob/unify-unattended/unattended_scripts/unattended_installation.sh) script.
