### ISSUE TITLE
Current installation guide - Wazuh agent

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3861]
Hello team!

The aim of this issue is to improve the Wazuh agent section.

We must simplify the installation process, improve the explanations and update the screenshots. 

- [x] Wazuh agent index
- [x] AIX
- [x] HP-UX 
- [x] Linux
- [x] macOS
- [x] Solaris
- [x] Windows

Iterations

- [x] Technical work
- [x] Editorial review @MarVergara 
- [x] Technical review

Regards,

David

**Comment by MarVergara** [comment]
The editorial review will close the following issues related to each subsection included in the Wazuh agent [macro]section.

- Wazuh agent index #3736 
- AIX #3737 
- HP-UX #3738 
- Linux #3739 
- macOS #3740 
- Solaris #3741 
- Windows #3742 
- Deployment variables index #3743 
- Deployment variables for AIX #3744 
- Deployment variables for Linux index #3745 
- Deployment variables for Linux using apt repository #3746 
- Deployment variables for Linux using dnf repository #3747 
- Deployment variables for Linux using yum repository #3748 
- Deployment variables for Linux using zypper repository #3749 
- Deployment variables for macOS #3750 
- Deployment variables for Windows #3751
-
