### ISSUE TITLE
Current Getting started - Components

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3887]
The aim of this issue is to enhance the Components section of the Getting started, simplifying the language used and easing the explanations where possible. 
We should change this section to include the new Wazuh components and create new subsections accordingly.

Technical review / rework by @s-ocando
- [x] Update server architecture, agent architecture and data flow diagrams. 
- [x] Wazuh agent
- [x] Wazuh server
- [x] Kibana
- [x] Elasticsearch

 
Editorial review by @MarVergara 
- [x] Wazuh agent
- [x] Wazuh server
- [x] Kibana
- [x] Elasticsearch - by @Arcapas 

Regards,

David

**Comment by MarVergara** [comment]
Updates:
**GS - Wazuh dashboard**: Final editorial draft done - Technical review pending
**GS - Wazuh indexer:** Technical draft WIP - Editorial review pending

**Comment by Arcapas** [comment]
I left some review comments.

**Comment by s-ocando** [comment]
Currently working on branch https://github.com/wazuh/wazuh-documentation/tree/3887_Update_Getting_Started. Pending an image modification and a final editorial review.
