### ISSUE TITLE
Current Getting started - Use cases

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3889]
Hello team!

The aim of this issue is to improve the Use cases section of the Getting started. We must study if we should keep the current structure or we may rename the section to Capabilities as shown on the website. In that case, the current use cases must be relocated.

Regards,

David

### New works of this issue:
- [x] #4101 
- [x] #4110 

Content has been added to the current use cases sections. I'm adding a follow-up task:

- [x] #4132

**Comment by Arcapas** [comment]
I'm working to improve the Use cases section of the Getting started section. I believe that in order to maintain consistent documentation the name of the section should be changed to Capabilities, as it appears on the website.
