### ISSUE TITLE
Getting started rework

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3890]
Hello team!

The aim of this issue is to improve the current getting started section.

We must simplify the language used to be more user-friendly, leaving the more complicated aspects to the user manual.

We may also study the possibility of renaming this section.

This rework implies modifying the following sections:

- [x] Getting started index #3885
- [ ] Components #3887
- [x] Architecture #3888
- [x] Use cases #3889

Besides, the information removed from this section must be placed on the user manual.

Regards,

David

**Comment by s-ocando** [comment]
A new version of the Getting started section was introduced in https://github.com/wazuh/wazuh-documentation/pull/3999.
