### ISSUE TITLE
Wazuh -Style guide for writing documentation content

### ISSUE THREAD

**Issue by MarVergara** [wazuh/wazuh-documentation#3904]
Hi team,
The aim of this issue is to create a comprehensive Wazuh style guide to be used by the docu team and anyone deeply involved in writing documentation for Wazuh. This guide should be used when writing content for the documentation to create consistent texts with unified writing and style criteria. 

Tasks:

- [x] Define voice and tone - audience
- [x] Detail writing tips for voice and tone consistency
- [ ] Define consistent language use and grammar rules
- [ ] Define how to write section elements 
- [x] Detail writing tips for language use and grammar consistency
- [x] Include text-formatting summary
- [x] Create a word list of correct term usage and terminology 

 Next step: @vicmansilla
Vic is going to generate a Wazuh quick reference style guide based on this larger document. The idea is to send this smaller version to the teams for them to have as a go-to when creating documentation. Moreover, Vic is going to include guidelines to improve SEO. 

Regards,
Mariel

**Comment by PilarQuesada** [comment]
Hi! I have reviewed the terminology list and have suggested to Mar the addition of two changes. 

- In the line about File Integrity Monitoring, the abbreviation should be FIM instead of FMI. 
- In the other capabilities, it could be added how to abbreviate them (VD, LDA...). 

Regards!

**Comment by PilarQuesada** [comment]
Hi again, @MarVergara, could you add "Installation guide" to the list? I would like to know how is it correct to write it (all lower case?) and if it can be abbreviated. 

Thanks!

**Comment by MarVergara** [comment]
Issue moved to [wazuh/wazuh-marketing #886](https://github.com/wazuh/wazuh-marketing/issues/886) via [**ZenHub**](https://www.zenhub.com/)
