### ISSUE TITLE
Improve Ansible documentation

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-documentation#391]
Hello team,

The main idea is to improve the Ansible documentation by providing a simple and intuitive installation guide:

- Wazuh server
- Elastic Stack server
- Wazuh agent

Regards,

Alfonso

**Comment by SitoRBJ** [comment]
Hello team,

We have finished these sections:

1. Install Ansible
2. Install Wazuh manager
3. Install Elastic Stack (single server option)

Regards,

Alfonso

**Comment by JuanjiJG** [comment]
Done here: #400 

Thank you so much for your work @SitoRBJ!! :smile:

Regards,
Juanjo
