### ISSUE TITLE
New section - How to add a new user on Kibana

### ISSUE THREAD

**Issue by orsifacundo** [wazuh/wazuh-documentation#3919]
Hello team!

I'm creating this issue to request and addition of a new section on our documentation about how to add new users for Kibana. This request is based on the number of questions that we frequently receive on our community. 

This section should include at least:

- Creating internal users.
- Assign Elasticsearch roles to that user.
- Assign a roles mapping on the Wazuh Security section to that user.
- Explanation on the differences between Wazuh user and Elasticsearch user.

Regards.

**Comment by ar0dd** [comment]
Hello wazuh team!

I would add if it's possible or not to create an elasticsearch or wazuh user through their respective APIs :)

**Comment by daniejstriata** [comment]
I wasted a whole day figuring out how user access works. Even did a reinstall of the Wazuh server ad the users I created could not login.

**Comment by orsifacundo** [comment]
As a tentative guide:

There are 2 kind of access control security models: the Elasticsearch/Kibana and the Wazuh. Each of them has its own set of users/permissions/roles. To make a distinction between them:

- **Elasticsearch model**: this is used to perform the API requests against Elasticsearch API (by default port 9200) and also to login to Kibana.
- **Wazuh model**: this is used to perform the API requests against the Wazuh API (by default port 55000).

For the creation of a user that has access to the Wazuh application ([running on top of Kibana as a plugin](https://documentation.wazuh.com/current/user-manual/kibana-app/index.html)), search for security alerts and also to be able to configure the Wazuh nodes, then the following steps need to be followed:

<details>
  <summary>User with Administrator role</summary>

### Create Elasticsearch user
- Go to _Kibana_ -> _Security_ -> _Internal users_ and click _Create internal user_

![Screenshot_20210824_200407](https://user-images.githubusercontent.com/46934023/130701203-f15e6051-0947-4d0a-a1b3-6b88e7133853.png)

- Fill with the desired data and click _Create_:

![Screenshot_20210824_203004](https://user-images.githubusercontent.com/46934023/130703079-216729c1-626c-4ed7-99d6-f399a00cb337.png)

### Map the user to the Administrator role on Elasticsearch Security

- Go to  _Kibana_ -> _Security_ -> _Roles_ and select _all_access_:

![Screenshot_20210824_203342](https://user-images.githubusercontent.com/46934023/130703667-7e965841-df9f-49a2-8b2c-d4dda2209996.png)

- Select the _Mapped users_ tab and then click on _Manage mapping_:

![Screenshot_20210824_203936](https://user-images.githubusercontent.com/46934023/130703722-374fbf54-a25b-48c3-b893-4a71019bdb8a.png)

- On the _Users_ section select the newly created user and the click on _Map_:

![Screenshot_20210824_204043](https://user-images.githubusercontent.com/46934023/130703789-58a9888c-2f27-40d4-9d3d-1919910ab8ef.png)

### Map the user to the Administrator role on Wazuh Security

- Go to  _Wazuh_ -> _Security_ -> _Roles mapping_:

![Screenshot_20210824_204419](https://user-images.githubusercontent.com/46934023/130703998-33c809f7-ec23-4cef-8cc0-e8e9460dd782.png)

- Click on _Create Role mapping_ and fill with _Roles: administrator_ and _Internal users: newly created user_

![Screenshot_20210824_204531](https://user-images.githubusercontent.com/46934023/130704160-fe335fde-18c3-4498-9465-ca501263f7a5.png)

- Click _Save role mapping_

</details>
<details>
  <summary>User with Read-only role</summary>

### Create Elasticsearch user
- Go to _Kibana_ -> _Security_ -> _Internal users_ and click _Create internal user_

![Screenshot_20210824_200407](https://user-images.githubusercontent.com/46934023/130701203-f15e6051-0947-4d0a-a1b3-6b88e7133853.png)

- Fill with the desired data and click _Create_:

![Screenshot_20210824_204920](https://user-images.githubusercontent.com/46934023/130704348-34bdbc18-7895-43e3-8d35-406217ae8a67.png)

### Create Read-only role

- Go to  _Kibana_ -> _Security_ -> _Roles_ and click _Create role_:

![Screenshot_20210824_204943](https://user-images.githubusercontent.com/46934023/130704404-e803793d-b819-4ab8-a8db-a47cc78acf99.png)

- Add a role with _Cluster permissions: read_ , _Index permissions_ set to _get/search/read_ for _wazuh-alerts*_ and _.kibana*_ , _Tenant permissions_ set to _global_tenant_ and _Read only_

![Screenshot_20210824_205145](https://user-images.githubusercontent.com/46934023/130704775-98ee2f57-438d-4439-99c2-a2953053d3ad.png)

![Screenshot_20210824_205201](https://user-images.githubusercontent.com/46934023/130704797-53e89062-2926-4d83-86af-c33652434395.png)

![Screenshot_20210824_205214](https://user-images.githubusercontent.com/46934023/130704801-548302da-118c-43ac-bab6-efee4b284830.png)

- Click _Create_ , then select the _Mapped users_ tab and click on _Manage mapping_:

![Screenshot_20210824_205246](https://user-images.githubusercontent.com/46934023/130705022-3efebabf-e5b6-433d-aece-1d08254274f3.png)

- On the _Users_ section select the newly created user and the click on _Map_:

![Screenshot_20210824_205259](https://user-images.githubusercontent.com/46934023/130705049-4121b3fb-e104-4558-827b-8369170dfa8d.png)

### Map the user to the read-only role on Wazuh Security

- Go to  _Wazuh_ -> _Security_ -> _Roles mapping_:

![Screenshot_20210824_204419](https://user-images.githubusercontent.com/46934023/130703998-33c809f7-ec23-4cef-8cc0-e8e9460dd782.png)

- Click on _Create Role mapping_ and fill with _Roles: readonly and _Internal users: newly created user_

![Screenshot_20210824_210153](https://user-images.githubusercontent.com/46934023/130705185-16f001c2-abbd-4ccf-92ad-ab2ab9f913e0.png)

- Click _Save role mapping_

</details>
