### ISSUE TITLE
Add requirements.txt file 

### ISSUE THREAD

**Issue by BraulioV** [wazuh/wazuh-documentation#392]
Hi team,

it would be great to add a `requirements.txt` listing all the Python modules needed to build the wazuh-docs. Using this files it will be much easier to install all of them by running: 

`pip install -r requirements.txt`.

Regards,
Braulio

**Comment by cmccandless** [comment]
I think I have a working requirements.txt file, but I am still verifying it on Python3.6 and Python2.7.

It would be helpful if I knew what version of Sphinx and its extensions I was targeting. By trial and error, here's what I have so far:

```
sphinx==1.6.1
sphinx-rtd-theme==0.4.1
sphinxcontrib-images==0.7.0
```

**Comment by cmccandless** [comment]
[Here is my script](https://gist.github.com/cmccandless/a1d3a440b44ebadcc21cf77e67439aaa) I've been using to check the requirements file for correctness.

**Comment by JuanjiJG** [comment]
Hello @cmccandless, and sorry for the late response.

Currently, I use the following version of Sphinx:
```
Sphinx==1.6.5
sphinx-rtd-theme==0.2.4
sphinxcontrib-images==0.7.0
```

It's hard to determine what is the version to target. I think that we can't update to Sphinx 1.8.x because of some deprecations, but for now, a `requirements.txt` file that just works for ease of deployment would be enough.

Thanks a lot for your work on this, it's really appreciated.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Hi again @cmccandless,

This is the `pip freeze` that I'm currently using (Python 3.5.2):

```
alabaster==0.7.12
Babel==2.6.0
certifi==2018.10.15
chardet==3.0.4
docutils==0.14
idna==2.7
imagesize==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
pkg-resources==0.0.0
Pygments==2.2.0
pytz==2018.7
requests==2.20.1
six==1.11.0
snowballstemmer==1.2.1
Sphinx==1.6.5
sphinx-rtd-theme==0.2.4
sphinxcontrib-images==0.7.0
sphinxcontrib-websupport==1.1.0
urllib3==1.24.1
```

You can obtain the same result with just the following dependencies:

```
Sphinx==1.6.5
sphinx-rtd-theme==0.2.4
sphinxcontrib-images==0.7.0
```

If you want, give it a try on Python 2.7 and we can see if it's also compatible for that version along with Python 3.5+.

Thanks a lot! Let me know your findings and your suggestions for this, it's really appreciated. :smile:

Regards,
Juanjo

**Comment by cmccandless** [comment]
# Requirements.txt Status

## Contents

```
babel>=1.3,<2.0
Sphinx==1.6.5
sphinx-rtd-theme==0.2.4
sphinxcontrib-images==0.7.0
```

## Make Target Build Status

| Target | Python2.7 | Python3.5 | Python3.6 |
|:--- |:---:|:---:|:---:|
| applehelp | :x: | :x: | :x: |
| changes | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| coverage | :x: | :x: | :x: |
| devhelp | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| dirhtml | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| doctest | :x: | :x: | :x: |
| epub | :x: | :x: | :x: |
| gettext | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| html | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| htmlhelp | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| info | :x: | :x: | :x: |
| json | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| latex | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| latexpdf | :x: | :x: | :x: |
| latexpdfja | :x: | :x: | :x: |
| linkcheck | **T*** | **T*** | **T*** |
| man | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| pickle | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| pseudoxml | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| qthelp | :x: | :x: | :x: |
| singlehtml | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| texinfo | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |
| text | :x: | :x: | :x: |
| xml | :heavy_check_mark: | :heavy_check_mark: | :heavy_check_mark: |

**Timed out after 3 minutes*

**Comment by JuanjiJG** [comment]
Hello again @cmccandless,

Wow, thank you so much for your testing! It's really amazing and very appreciated. :smile:

For now, we only use the `make html` target in order to compile the documentation. As I can see on the table, all the different Python versions behave the same way using those dependencies.

Do you think we can get the same results without explicitly adding the `babel` dependency? It would be nice if we can use a minimal requirements file.

Let me know your thoughts about this.

Regards,
Juanjo

**Comment by cmccandless** [comment]
I just updated my comment; I ran the same tests without the Babel dependency, and there does not appear to be a change.

**Comment by JuanjiJG** [comment]
Done here: #607 

Thank you so much @cmccandless!

Regards,
Juanjo
