### ISSUE TITLE
Typo in who-data section

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-documentation#393]
https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-linux.html#configuration this is wrong for CentOS, audit must be installed using this:

`yum install audit` and not `auditd`

**Comment by JuanjiJG** [comment]
I've noticed that on that documentation section, the commands are missing the `#` character to indicate that the command must be executed with root permissions.

We'll fix that too.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
Done: https://github.com/wazuh/wazuh-documentation/pull/409
