### ISSUE TITLE
Table with alerts severity 

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-documentation#394]
Regarding several requests from users (for example [9RN--uit7rs](https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/wazuh/9RN--uit7rs)) it would be useful to add to the documentation a section with the meaning of each rule level.

The same way as OSSEC here: https://ossec-docs.readthedocs.io/en/latest/manual/rules-decoders/rule-levels.html

**Comment by JuanjiJG** [comment]
Done here: #534

Regards,
Juanjo
