### ISSUE TITLE
Found something missing in the step by step install

### ISSUE THREAD

**Issue by guillaumezisa** [wazuh/wazuh-documentation#3954]
Hello,

https://documentation.wazuh.com/current/installation-guide/open-distro/all-in-one-deployment/all_in_one.html

Following the new step to step install guide i had this error in my logs:
EACCES: permission denied, open '/etc/kibana/certs/kibana-key.pem'

Execute this line fixed the problem.
after the : # mv ~/certs/kibana* /etc/kibana/certs/ line
chown kibana:kibana /etc/kibana/certs/*

It can be more confortable if this line is added on the official documentation for others peoples.
I can't find this version of the documentation on github finishing by these lines.

![image](https://user-images.githubusercontent.com/32988752/122786531-b22a6080-d2b4-11eb-9359-1e4d5d80ea79.png)

Thanks

**Comment by davidfmiranda** [comment]
Hello @guillaumezisa thanks for opening this issue! We will fix this as soon as possible.
