### ISSUE TITLE
Wrong group separator value for group

### ISSUE THREAD

**Issue by davidfmiranda** [wazuh/wazuh-documentation#3979]
Version | Documents affected
-- | --
4.1 | [Integration](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/integration.html#group) section

Hello team!

The aim of this issue is to fix the separator value for `group` in the [Integration](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/integration.html#group) section.

It is now specified that for multiple groups, `|` must be used, but these values must be comma-separated.
![image](https://user-images.githubusercontent.com/60152567/123065382-63450e00-d40f-11eb-835e-9571f29fd23d.png)

Regards,

David

**Comment by jnasselle** [comment]
Hi @davidfmiranda,

This was already reported in #3580 and fixed by #3581.

Regards,
Nico

**Comment by davidfmiranda** [comment]
Thanks @jnasselle. We will close this issue now
