### ISSUE TITLE
Change users' password tool only works when the OpenDistro cluster is using localhost

### ISSUE THREAD

**Issue by alejandroorg** [wazuh/wazuh-documentation#3997]
Hi Team,

I observed that when trying to change the default password as explained here: https://documentation.wazuh.com/current/user-manual/elasticsearch/elastic_tuning.html?highlight=kibana%20password#change-users-password , with **wazuh-passwords-tool.sh** but it is only working if the node is configured for localhost. When trying to use another IP, it will fail.

It would be solved if there is an option to change the IP

Regards,
Alejandro Ruiz.

**Comment by MiguelCasaresRobles** [comment]
Solved.
