### ISSUE TITLE
Wazuh agent registration page states to proceed over insecure connection even proper certificate is configured

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#4000]
Hello team,

I'm opening this issue because I observed in our documentation we recommend proceeding with insecure connection even if the user might be using proper certificates: https://documentation.wazuh.com/current/user-manual/registering/restful-api-registration.html

We should state that option is only for insecure connections without certificates.

This may be happening in other sections of the documentation.

Regards,

Miguel Casares

**Comment by Nicogp** [comment]
Impact:

- Medium: user will continue to use insecure connection

Probability:

- Medium: it does not represent any changes to users who do not use certificates. This does represent a security change to users who have the appropriate certificates.

Cost to fix it:

- Low/Medium:

     - Review of the documentation involved
     - Indicate that the option is for insecure connections
