### ISSUE TITLE
Consider explaining command line registration method without using arguments

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#4001]
Hello team,

I'm opening this issue because I observed that we stated in the following registration page that we can paste the key generated to registering the agents: https://documentation.wazuh.com/current/user-manual/registering/restful-api-registration.html

However, we are not warning users that the agent key will be saved in the bash history. In addition to this, this is visible for all the users in the process list.

We should explain a method to use this method without arguments or any other secure method.

Regards,

MIguel Casares

**Comment by cborla** [comment]
Impact:
 - Medium: Will keep generated key for agent, to anyone that run history command with same user or group.  

Probability:
 - High: Anyone that run history command with same user or group. 

Cost to fix it:
 - Low: 
      - Recommend to clean history after completed Registering the Wazuh agents using the Wazuh API. Clean all history -c, or history -d <line to delete>.
      - Add a Warning message into documentation.
      - Recommend other registration methods.

**Comment by vicferpoy** [comment]
## Issue update
Hello team,

The suggested changes have been added to that section of the documentation in addition to the [CLI registration one](https://documentation.wazuh.com/current/user-manual/registering/command-line-registration.html) as it has the same issue.

Regards,
Víctor
