### ISSUE TITLE
Update "building from sources" steps for CentOS 8 with missing dependencies 

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-documentation#4030]
# Description

It was found that the Agent/Manager's steps for building from sources in the `develop` branch for CentOS 8 need the following improvements:
- The `http://mirror.centos.org/centos/8/PowerTools/x86_64/os/Packages/libstdc++-static-8.3.1-5.el8.0.2.x86_64.rpm` link should be replaced with `http://mirror.centos.org/centos/8-stream/PowerTools/x86_64/os/Packages/libstdc++-static-8.4.1-1.el8.x86_64.rpm`
- The `openssl-devel` package is necessary to build CMake

Also, the required packages could be uploaded to the Wazuh repository .

## DoD
- [x] libstdc++ to wazuh file repository.
- [x] Modify documentation to use/install/download libstdc++ from wazuh file repository
- [x] Modify documentation to install openssl-devel in centos8
- [x] Test steps for source installs with clean docker file.

**Comment by jnasselle** [comment]
### Uploading `libstdc++-static` package to Wazuh file repository
https://packages.wazuh.com/utils/libstdc%2B%2B/libstdc%2B%2B-static-8.4.1-1.el8.aarch64.rpm
https://packages.wazuh.com/utils/libstdc%2B%2B/libstdc%2B%2B-static-8.4.1-1.el8.i686.rpm
https://packages.wazuh.com/utils/libstdc%2B%2B/libstdc%2B%2B-static-8.4.1-1.el8.x86_64.rpm

**Comment by jnasselle** [comment]
### Testing install from sources via Docker using clean image
- Create `Dockerfile` next content in a desired folder i.e `test_install_from_sources`
  - Agent
```
FROM centos:8

RUN yum install -y make gcc gcc-c++ python3 python3-policycoreutils automake autoconf libtool openssl-devel
RUN yum install -y unzip
RUN rpm -i $(rpm --eval https://packages.wazuh.com/utils/libstdc%2B%2B/libstdc%2B%2B-static-8.4.1-1.el8.'%{_arch}'.rpm)
RUN curl -OL https://packages.wazuh.com/utils/cmake/cmake-3.18.3.tar.gz && tar -zxf cmake-3.18.3.tar.gz
RUN cd cmake-3.18.3 && ./bootstrap --no-system-curl
RUN cd cmake-3.18.3 && make -j$(nproc) && make install

RUN curl -OL https://github.com/wazuh/wazuh/archive/refs/tags/v4.2.0-rc11.zip && unzip v4.2.0-rc11.zip
RUN cd wazuh-4.2.0-rc11 && yes | USER_LANGUAGE="en" USER_NO_STOP="y" USER_INSTALL_TYPE="agent" USER_DIR="/var/ossec" USER_AGENT_SERVER_IP="" ./install.sh
```
  - Manager
```
FROM centos:8

RUN yum install -y make gcc gcc-c++ python3 python3-policycoreutils automake autoconf libtool openssl-devel
RUN yum install -y unzip
RUN rpm -i $(rpm --eval https://packages.wazuh.com/utils/libstdc%2B%2B/libstdc%2B%2B-static-8.4.1-1.el8.'%{_arch}'.rpm)
RUN curl -OL https://packages.wazuh.com/utils/cmake/cmake-3.18.3.tar.gz && tar -zxf cmake-3.18.3.tar.gz
RUN cd cmake-3.18.3 && ./bootstrap --no-system-curl
RUN cd cmake-3.18.3 && make -j$(nproc) && make install

RUN curl -OL https://github.com/wazuh/wazuh/archive/refs/tags/v4.2.0-rc11.zip && unzip v4.2.0-rc11.zip
RUN cd wazuh-4.2.0-rc11 && yes | USER_LANGUAGE="en" USER_NO_STOP="y" USER_INSTALL_TYPE="server" USER_DIR="/var/ossec"  USER_ENABLE_EMAIL="n" USER_WHITE_LIST="n" ./install.sh
```
- Build docker image
```
docker build test_install_from_sources
```
