### ISSUE TITLE
Fix typos in RESTful API - Getting Started section

### ISSUE THREAD

**Issue by MarVergara** [wazuh/wazuh-documentation#4074]
Hi team,

The aim of this issue is to fix typos in this section: https://documentation.wazuh.com/current/user-manual/api/getting-started.html?highlight=logging

The typo "logging" should be fixed to "log in" in several instances of the section, following the style guidelines of usage for this verb (please, check).

Regards,
Mariel

**Comment by javimed** [comment]
Although the section can benefit from improvements, this is not a typo or grammar error. This issue is being closed.
