### ISSUE TITLE
Wazuh Blog scripts/resources unaccurate encoding

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-documentation#4092]
Hi team,

There are some Wazuh Blog entries that have resources i.e scripts that have Windows encoding while they are meant to be run in Linux. Trying to execute them lead to the next error:
```
/usr/bin/env: ‘python\r’: No such file or directory
```
This is consequence of misunderstanding the python shebang. This could be easily fixed using `dos2unix` tool against the file.
```
dos2unix /var/ossec/etc/lists/iplist-to-cdblist.py
dos2unix: converting file /var/ossec/etc/lists/iplist-to-cdblist.py to Unix format...
```
Currently we have been reported about this error in two scripts, but all of them should be checked as well :

- https://wazuh.com/resources/blog/sending-wazuh-alerts-via-sms/custom-sns-integration.py
- https://wazuh.com/resources/iplist-to-cdblist.py

Regards,
Nico

**Comment by javimed** [comment]
Encoding of:
