### ISSUE TITLE
Reverse proxy configuration for Splunk

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-documentation#411]
Hello team, it would be nice if the documentation shows how to configure reverse proxy, ssl and authentication by htpasswd for Splunk.

- NGINX SSL proxy for Splunk (RPM-based distributions)
  - [x] Install NGINX
  - [x] Install your SSL certificate and private key
  - [x] Configure NGINX as an HTTPS reverse proxy to Splunk
  - [x] Allow NGINX to connect to the Splunk port if SELinux is being used
  - [x] Enable authentication by htpasswd
- NGINX SSL proxy for Splunk (DEB-based distributions)
  - [x] Install NGINX
  - [x] Install your SSL certificate and private key
  - [x] Configure NGINX as an HTTPS reverse proxy to Splunk
  - [x] Allow NGINX to connect to the Splunk port if SELinux is being used
  - [x] Enable authentication by htpasswd

Use https://documentation.wazuh.com/current/installation-guide/optional-configurations/kibana_ssl.html as reference.

Regards

**Comment by manuasir** [comment]
Done [here](https://github.com/wazuh/wazuh-documentation/pull/441).
