### ISSUE TITLE
Remote upgrading for MacOS agents

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-documentation#4130]
### Description

Support for remote upgrading of MacOS agents needs to be documented.

Some things to consider:

- MacOS agents can be upgraded using both API and CLI options.
- WPK for macOS contains:
  - `upgrade.sh` script to launch the upgrade process in the agent.
  - `pkg_installer_mac.sh` script, used by `upgrade.sh`.
  - `.pkg` file to execute an upgrade with packages (no sources).
- Version of support > `v4.2.1`

- Update:
  - [x] agent-upgrade-module.rst
  - [x] generate-wpk-package-manually.rst
  - [x] wpk-list.rst
  - [x] generate-wpk-package.html

**Comment by cborla** [comment]
generate-wpk-package.html page should be updated when _generate_wpk_package.sh_ script will be updated.
[](https://documentation.wazuh.com/current/development/packaging/generate-wpk-package.html)
