### ISSUE TITLE
Request to upload files related to unattended installation to aws

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-documentation#4142]
Hi! I would like to make a request to upload the files necessary for the installation of the [unattended script](https://github.com/wazuh/wazuh-documentation/blob/4.2-rc/resources/open-distro/unattended-installation/unattended-installation.sh) to aws.

Specifically, it seeks to have all those files that were previously obtained from GitHub and that are now obtained from `https://packages.wazuh.com/resources/4.2/`

The problem is that these files are not yet uploaded in `packages.wazuh.com` and they are necessary for the development of the ova. That is why this request is oriented so that while a development is being carried out, these files are placed in `https://packages-dev.wazuh.com/resources/4.2/` if possible.

Regards.

**Comment by s-ocando** [comment]
Done. Files have been placed in https://packages-dev.wazuh.com/resources/4.2/.
