### ISSUE TITLE
Fix several errors in wazuh docs.

### ISSUE THREAD

**Issue by pillarsdotnet** [wazuh/wazuh-documentation#416]
While making improvements to the [wazuh-ansible](https://github.com/wazuh/wazuh-ansible) playbooks, I've discovered several small errors in Wazuh documentation:

Merged *(thanks)*:
* [Fix typo in ossec-conf/rootcheck documentation.](https://github.com/wazuh/wazuh-documentation/pull/413)
* [Fix typo in ossec-conf/syslog-output docs.](https://github.com/wazuh/wazuh-documentation/pull/414)
* [Update osquery wodle docs to match example.](https://github.com/wazuh/wazuh-documentation/pull/415)
* [Label attribute "hidden" can be "no".](https://github.com/wazuh/wazuh-documentation/pull/417)
* [Fix the ciscat wodle default java_path.](https://github.com/wazuh/wazuh-documentation/pull/419)
* [Fix vulnerability_detector "disabled" default.](https://github.com/wazuh/wazuh-documentation/pull/420)
* [Fix osquery "disabled" default.](https://github.com/wazuh/wazuh-documentation/pull/421)
* [Edit "check_winaudit" docs for consistency.](https://github.com/wazuh/wazuh-documentation/pull/423)
* [Deprecate the unused alerts/use_geoip option.](https://github.com/wazuh/wazuh-documentation/pull/442)
* [Correct command/timeout_allowed default.](https://github.com/wazuh/wazuh-documentation/pull/444)
* [Note email_alerts/format can be "default".](https://github.com/wazuh/wazuh-documentation/pull/445)
* [Note "email_to" option is required.](https://github.com/wazuh/wazuh-documentation/pull/447)
* [Document the "max_log" integration option.](https://github.com/wazuh/wazuh-documentation/pull/448)
* [Document the global/helo_server option.](https://github.com/wazuh/wazuh-documentation/pull/450)
* [Fix global/memory_size default and limits.](https://github.com/wazuh/wazuh-documentation/pull/451)
* [Fix global/prelude_output default.](https://github.com/wazuh/wazuh-documentation/pull/452)
 * [Document prelude_log_level and prelude_profile.](https://github.com/wazuh/wazuh-documentation/pull/453) 

Still open:
* [Fix global geoip config docs.](https://github.com/wazuh/wazuh-documentation/pull/449) 

Closed:
* ~~[Note effect of cluster/disabled option.](https://github.com/wazuh/wazuh-documentation/pull/443)~~
   * *(See [related issue](https://github.com/wazuh/wazuh/issues/1178).)*

**Comment by JuanjiJG** [comment]
Thanks for your contributions @pillarsdotnet,

We'll review the pull requests and accept them if they look good to us.

Regards,
Juanjo

**Comment by pillarsdotnet** [comment]
Nine fixes so far; most of them one-liners.  Can I get even one review?

**Comment by JuanjiJG** [comment]
Hi @pillarsdotnet,

I'm sorry for the delay. We'll review your pull requests as soon as we can. Thank you for putting them together on the first comment if this issue.

The team is working on some other documentation improvements and additions, but be sure that we'll take a look at your proposals.

Thanks for your patience.

Regards,
Juanjo

**Comment by pillarsdotnet** [comment]
Ten fixes.  I find that I must read the code; I cannot rely upon the docs for accuracy.

**Comment by pillarsdotnet** [comment]
Eleven.

**Comment by jesusgn90** [comment]
Hello @pillarsdotnet ,

Awesome work. All your feedback is really appreciated, and right now we've reviewed all your PRs, most of them are now merged and a few of them are still in pending review status, but we are going to review as soon as possible. Many thanks for this feedback. 

Brief summary of already merged PRs:

- Fix typo in ossec-conf/rootcheck documentation. https://github.com/wazuh/wazuh-documentation/pull/413
- Fix typo in ossec-conf/syslog-output docs. https://github.com/wazuh/wazuh-documentation/pull/414
- Label attribute "hidden" can be "no". https://github.com/wazuh/wazuh-documentation/pull/417
- Fix the ciscat wodle default java_path. https://github.com/wazuh/wazuh-documentation/pull/419
- Fix vulnerability_detector "disabled" default. https://github.com/wazuh/wazuh-documentation/pull/420
- Fix osquery "disabled" default https://github.com/wazuh/wazuh-documentation/pull/421
- Edit "check_winaudit" docs for consistency. https://github.com/wazuh/wazuh-documentation/pull/423
- Correct command/timeout_allowed default https://github.com/wazuh/wazuh-documentation/pull/444
- Document the "max_log" integration option. https://github.com/wazuh/wazuh-documentation/pull/448
- Document the global/helo_server option https://github.com/wazuh/wazuh-documentation/pull/450
- Fix global/memory_size default and limits. https://github.com/wazuh/wazuh-documentation/pull/451
- Fix global/prelude_output default. https://github.com/wazuh/wazuh-documentation/pull/452
- Document prelude_log_level and prelude_profile https://github.com/wazuh/wazuh-documentation/pull/453

Best regards,
Jesús

**Comment by JuanjiJG** [comment]
The last pull request, #449, is now merged.

Thanks a lot for all your contributions @pillarsdotnet.

I'll proceed to close this issue.

Let us know if you have more questions or problems. If you want to make more contributions, feel free to open a new issue for a better tracking.

Regards,
Juanjo
