### ISSUE TITLE
Include Getting started with Wazuh RBAC in the documentation

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4189]
This issue aims to include the blog post "Getting started with Wazuh RBAC" in the documentation.

**Activities of the Issue:**
- [x] Take the content from the blog post draft
- [x] Talk with the author of the blog post, Adrián Peña
- [x] Review with the author the information of the blog post to create the documentation section
- [x] Create a 1st draft based on the blog post: [Getting started with Wazuh RBAC V1.0](https://docs.google.com/document/d/169aiIUAF7hVfJIPjn8hjE-Ro8MNWXk8ziOw9wORQKbY/edit?usp=sharing)
- [x] Create the branch 4189_4.2_getting_started_with_wazuh-_rbac to add this content to the docu.
- [x] Edit the draft with the information shared by the author: [Getting started with Wazuh RBAC V1.1 ](https://docs.google.com/document/d/1WPRIKhAJWYD5NYuUA9C32v8z8JruUNdMU4iTG6EbQnw/edit?usp=sharing)
- [x] Add images and make the final edition and format adjustment.
- [x] Make a last review of the text.
- [x] Make PR and ask the content team for review.

**Comment by FelipeKnudsen** [comment]
Here I attach the designed diagrams. If there's something else to adjust, please let me know.

![Wazuh_Diagrams_02-09-1](https://user-images.githubusercontent.com/80284649/131874296-f988b876-2b99-4f2a-8361-8810a066095b.png)
![Wazuh_Diagrams_02-09-2](https://user-images.githubusercontent.com/80284649/131874301-12dd5314-5b59-492b-a525-201750c88a7b.png)
