### ISSUE TITLE
Getting Started - Component definition order and left menu list

### ISSUE THREAD

**Issue by luiscontrerasdo** [wazuh/wazuh-documentation#4221]
Hi, team!

In the installation guide, the order shown in the left menu is:

> Wazuh indexer
> Wazuh server
> Wazuh dashboard
> Wazuh agent

In the Getting started, in the left menu side and at the component section detail, the order of the definition is set to:

> Wazuh agent
> Wazuh server
> Wazuh indexer
> Wazuh dashboard

The order proposed for list in the menu and for components definition is:

> Wazuh indexer
> Wazuh server
> Wazuh dashboard
> Wazuh agent

Visually, we keep an order in the list of components, and considering that the Wazuh agent is the last component that we deploy.

**Comment by s-ocando** [comment]
The team discussed these changes and decided not to implement them.
