### ISSUE TITLE
Error while using Monitor Office 365 with Wazuh (Blog) script 

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-documentation#4235]
Hi team!

Since v4.2.0, analysis engine (wazuh-analysisd) input socket was moved from `/var/ossec/queue/ossec/queue` to `/var/ossec/queue/sockets/queue`, breaking [Monitor Office 365 with Wazuh (Blog).](https://wazuh.com/blog/monitor-office-365-with-wazuh/) script.

![image](https://user-images.githubusercontent.com/1791430/132141818-fe8bd0fe-1580-4c9a-8591-e82efd4c939d.png)

Multiple users ([here](https://groups.google.com/g/wazuh/c/fKRa0MVrRRk), [here](https://github.com/wazuh/wazuh/issues/9945), [here](https://wazuh.slack.com/archives/C0A933R8E/p1630345509342800)) are reporting this, so it will be really useful to fix the script and add a note in the blog.

Regards,
Nico

**Comment by saramoran** [comment]
Hi @jnasselle, thanks for reporting this.
The blog post has been edited:
- A note before the script has been added:
![Screenshot 2021-09-06 at 09 27 49](https://user-images.githubusercontent.com/16825724/132177207-049c1884-47cc-4cfc-b8f0-54d046b69900.png)

- The script has been updated:

![Screenshot 2021-09-06 at 09 27 57](https://user-images.githubusercontent.com/16825724/132177221-a2652dc6-ad7f-4fc4-880c-b7f5a024be63.png)

**Comment by jnasselle** [comment]
Thanks @saramoran ! Excellent job. Closing this issue
