### ISSUE TITLE
Warning at CDB documentation adverting of relative path

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-documentation#426]
Hi team!
When looking at the documentation, i didn't realize that the path to the list file is forced to be relative starting from "/var/ossec/"
So using the complete path /var/ossec/etc/lists/list_name, or mistyping /etc/lists/list_name, with the initial "/" makes the list not to work and is hard to realize the detail.
It would be handy if the documentation included a warning about this issue to make it more visible and easier to notice.
Regards,
Miguel R

**Comment by JuanjiJG** [comment]
Done here: #555

Thanks @migruiz4 for reporting this!

Regards,
Juanjo
