### ISSUE TITLE
Improve cluster documentation: Every node needs Filebeat/Logstash

### ISSUE THREAD

**Issue by jesuslinares** [wazuh/wazuh-documentation#432]
https://groups.google.com/forum/#!topic/wazuh/xhaZ3XukxY8

> The document gave me the impression that the workers would communicate with the master entirely over the service on port 1516

**Comment by JuanjiJG** [comment]
I think that it would be more useful to link to both Elastic and Splunk forwarding methods.

**Comment by jesusgn90** [comment]
Done https://github.com/wazuh/wazuh-documentation/pull/457
