### ISSUE TITLE
Analysisd multithread

### ISSUE THREAD

**Issue by jesusgn90** [wazuh/wazuh-documentation#435]
Add tech reference for analysisd multithread feature.

**Comment by vikman90** [comment]
@TJOSERAFAEL has been working on this. 
Branch: [analysisd-parallel](https://github.com/wazuh/wazuh-documentation/tree/analysisd-parallel)

**Comment by bah07** [comment]
Done in [#456](https://github.com/wazuh/wazuh-documentation/pull/456)
