### ISSUE TITLE
Using Syscollector information to trigger alerts is OUT OF DATE

### ISSUE THREAD

**Issue by tinachoB** [wazuh/wazuh-documentation#4404]
## Description
This issue aims to update the documentation section: [Using Syscollector information to trigger alerts](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#using-syscollector-information-to-trigger-alerts) based on the latest **4.2** Wazuh version. Currently, this way to trigger alerts is not available. 

The following Core team epic: https://github.com/wazuh/wazuh/issues/7279 will take care of this functionality. 

## DoD
- [X] Update section appropriately
- [X] Check grammatic and English redaction
- [X] Generate local documentation to double-check that everything is working as excepted

**Comment by jnasselle** [comment]
Closed by #4471
