### ISSUE TITLE
Missing redirections

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh-documentation#4408]
The following documents are not properly redirected and can not be found when switching versions:

Not found from 4.2 to...
- [x] /2.1/cloud-service/account-billing/billing-history.html
- [x] /3.0/cloud-service/account-billing/billing-history.html
- [x] /3.1/cloud-service/account-billing/billing-history.html
- [x] /3.2/cloud-service/account-billing/billing-history.html
- [x] /3.3/cloud-service/account-billing/billing-history.html
- [x] /3.4/cloud-service/account-billing/billing-history.html
- [x] /3.5/cloud-service/account-billing/billing-history.html
- [x] /3.6/cloud-service/account-billing/billing-history.html
- [x] /3.7/cloud-service/account-billing/billing-history.html
- [x] /3.8/cloud-service/account-billing/billing-history.html
- [x] /3.9/cloud-service/account-billing/billing-history.html
- [x] /3.10/cloud-service/account-billing/billing-history.html
- [x] /3.11/cloud-service/account-billing/billing-history.html
- [x] /3.12/cloud-service/account-billing/billing-history.html
- [x] /3.13/cloud-service/account-billing/billing-history.html
- [x] /4.0/cloud-service/account-billing/billing-history.html
- [x] /4.1/cloud-service/account-billing/billing-history.html
- [x] /2.1/cloud-service/account-billing/stop-charges.html
- [x] /3.0/cloud-service/account-billing/stop-charges.html
- [x] /3.1/cloud-service/account-billing/stop-charges.html
- [x] /3.2/cloud-service/account-billing/stop-charges.html
- [x] /3.3/cloud-service/account-billing/stop-charges.html
- [x] /3.4/cloud-service/account-billing/stop-charges.html
- [x] /3.5/cloud-service/account-billing/stop-charges.html
- [x] /3.6/cloud-service/account-billing/stop-charges.html
- [x] /3.7/cloud-service/account-billing/stop-charges.html
- [x] /3.8/cloud-service/account-billing/stop-charges.html
- [x] /3.9/cloud-service/account-billing/stop-charges.html
- [x] /3.10/cloud-service/account-billing/stop-charges.html
- [x] /3.11/cloud-service/account-billing/stop-charges.html
- [x] /3.12/cloud-service/account-billing/stop-charges.html
- [x] /3.13/cloud-service/account-billing/stop-charges.html
- [x] /4.0/cloud-service/account-billing/stop-charges.html
- [x] /4.1/cloud-service/account-billing/stop-charges.html
- [x] /2.1/cloud-service/account-billing/user-settings.html
- [x] /3.0/cloud-service/account-billing/user-settings.html
- [x] /3.1/cloud-service/account-billing/user-settings.html
- [x] /3.2/cloud-service/account-billing/user-settings.html
- [x] /3.3/cloud-service/account-billing/user-settings.html
- [x] /3.4/cloud-service/account-billing/user-settings.html
- [x] /3.5/cloud-service/account-billing/user-settings.html
- [x] /3.6/cloud-service/account-billing/user-settings.html
- [x] /3.7/cloud-service/account-billing/user-settings.html
- [x] /3.8/cloud-service/account-billing/user-settings.html
- [x] /3.9/cloud-service/account-billing/user-settings.html
- [x] /3.10/cloud-service/account-billing/user-settings.html
- [x] /3.11/cloud-service/account-billing/user-settings.html
- [x] /3.12/cloud-service/account-billing/user-settings.html
- [x] /3.13/cloud-service/account-billing/user-settings.html
- [x] /4.0/cloud-service/account-billing/user-settings.html
- [x] /4.1/cloud-service/account-billing/user-settings.html
- [x] /2.1/cloud-service/apis/authentication.html
- [x] /3.0/cloud-service/apis/authentication.html
- [x] /3.1/cloud-service/apis/authentication.html
- [x] /3.2/cloud-service/apis/authentication.html
- [x] /3.3/cloud-service/apis/authentication.html
- [x] /3.4/cloud-service/apis/authentication.html
- [x] /3.5/cloud-service/apis/authentication.html
- [x] /3.6/cloud-service/apis/authentication.html
- [x] /3.7/cloud-service/apis/authentication.html
- [x] /3.8/cloud-service/apis/authentication.html
- [x] /3.9/cloud-service/apis/authentication.html
- [x] /3.10/cloud-service/apis/authentication.html
- [x] /3.11/cloud-service/apis/authentication.html
- [x] /3.12/cloud-service/apis/authentication.html
- [x] /3.13/cloud-service/apis/authentication.html
- [x] /4.0/cloud-service/apis/authentication.html
- [x] /4.1/cloud-service/apis/authentication.html
- [x] /2.1/cloud-service/cli/index.html
- [x] /3.0/cloud-service/cli/index.html
- [x] /3.1/cloud-service/cli/index.html
- [x] /3.2/cloud-service/cli/index.html
- [x] /3.3/cloud-service/cli/index.html
- [x] /3.4/cloud-service/cli/index.html
- [x] /3.5/cloud-service/cli/index.html
- [x] /3.6/cloud-service/cli/index.html
- [x] /3.7/cloud-service/cli/index.html
- [x] /3.8/cloud-service/cli/index.html
- [x] /3.9/cloud-service/cli/index.html
- [x] /3.10/cloud-service/cli/index.html
- [x] /3.11/cloud-service/cli/index.html
- [x] /3.12/cloud-service/cli/index.html
- [x] /3.13/cloud-service/cli/index.html
- [x] /4.0/cloud-service/cli/index.html
- [x] /4.1/cloud-service/cli/index.html
- [x] /2.1/cloud-service/your-environment/manage-auth.html
- [x] /3.0/cloud-service/your-environment/manage-auth.html
- [x] /3.1/cloud-service/your-environment/manage-auth.html
- [x] /3.2/cloud-service/your-environment/manage-auth.html
- [x] /3.3/cloud-service/your-environment/manage-auth.html
- [x] /3.4/cloud-service/your-environment/manage-auth.html
- [x] /3.5/cloud-service/your-environment/manage-auth.html
- [x] /3.6/cloud-service/your-environment/manage-auth.html
- [x] /3.7/cloud-service/your-environment/manage-auth.html
- [x] /3.8/cloud-service/your-environment/manage-auth.html
- [x] /3.9/cloud-service/your-environment/manage-auth.html
- [x] /3.10/cloud-service/your-environment/manage-auth.html
- [x] /3.11/cloud-service/your-environment/manage-auth.html
- [x] /3.12/cloud-service/your-environment/manage-auth.html
- [x] /3.13/cloud-service/your-environment/manage-auth.html
- [x] /4.0/cloud-service/your-environment/manage-auth.html
- [x] /4.1/cloud-service/your-environment/manage-auth.html
- [x] /2.1/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.0/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.1/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.2/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.3/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.4/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.5/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.6/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.7/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.8/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.9/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.10/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.11/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.12/cloud-service/your-environment/monitor-environment-usage.html
- [x] /3.13/cloud-service/your-environment/monitor-environment-usage.html
- [x] /4.0/cloud-service/your-environment/monitor-environment-usage.html
- [x] /4.1/cloud-service/your-environment/monitor-environment-usage.html

Not found from 4.1 to...
- [x] /2.1/amazon/services/supported-services/alb.html
- [x] /3.0/amazon/services/supported-services/alb.html
- [x] /3.1/amazon/services/supported-services/alb.html
- [x] /3.2/amazon/services/supported-services/alb.html
- [x] /3.3/amazon/services/supported-services/alb.html
- [x] /3.4/amazon/services/supported-services/alb.html
- [x] /3.5/amazon/services/supported-services/alb.html
- [x] /3.6/amazon/services/supported-services/alb.html
- [x] /3.7/amazon/services/supported-services/alb.html
- [x] /3.8/amazon/services/supported-services/alb.html
- [x] /3.9/amazon/services/supported-services/alb.html
- [x] /3.10/amazon/services/supported-services/alb.html
- [x] /3.11/amazon/services/supported-services/alb.html
- [x] /3.12/amazon/services/supported-services/alb.html
- [x] /3.13/amazon/services/supported-services/alb.html
- [x] /4.0/amazon/services/supported-services/alb.html
- [x] /2.1/amazon/services/supported-services/clb.html
- [x] /3.0/amazon/services/supported-services/clb.html
- [x] /3.1/amazon/services/supported-services/clb.html
- [x] /3.2/amazon/services/supported-services/clb.html
- [x] /3.3/amazon/services/supported-services/clb.html
- [x] /3.4/amazon/services/supported-services/clb.html
- [x] /3.5/amazon/services/supported-services/clb.html
- [x] /3.6/amazon/services/supported-services/clb.html
- [x] /3.7/amazon/services/supported-services/clb.html
- [x] /3.8/amazon/services/supported-services/clb.html
- [x] /3.9/amazon/services/supported-services/clb.html
- [x] /3.10/amazon/services/supported-services/clb.html
- [x] /3.11/amazon/services/supported-services/clb.html
- [x] /3.12/amazon/services/supported-services/clb.html
- [x] /3.13/amazon/services/supported-services/clb.html
- [x] /4.0/amazon/services/supported-services/clb.html
- [x] /2.1/amazon/services/supported-services/nlb.html
- [x] /3.0/amazon/services/supported-services/nlb.html
- [x] /3.1/amazon/services/supported-services/nlb.html
- [x] /3.2/amazon/services/supported-services/nlb.html
- [x] /3.3/amazon/services/supported-services/nlb.html
- [x] /3.4/amazon/services/supported-services/nlb.html
- [x] /3.5/amazon/services/supported-services/nlb.html
- [x] /3.6/amazon/services/supported-services/nlb.html
- [x] /3.7/amazon/services/supported-services/nlb.html
- [x] /3.8/amazon/services/supported-services/nlb.html
- [x] /3.9/amazon/services/supported-services/nlb.html
- [x] /3.10/amazon/services/supported-services/nlb.html
- [x] /3.11/amazon/services/supported-services/nlb.html
- [x] /3.12/amazon/services/supported-services/nlb.html
- [x] /3.13/amazon/services/supported-services/nlb.html
- [x] /4.0/amazon/services/supported-services/nlb.html
- [x] /2.1/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.0/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.1/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.2/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.3/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.4/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.5/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.6/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.7/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.8/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.9/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.10/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.11/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.12/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /3.13/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /4.0/deploying-with-kubernetes/kubernetes-local-env.html
- [x] /4.0/installation-guide/more-installation-alternatives/splunk/index.html
- [x] /4.0/installation-guide/more-installation-alternatives/splunk/splunk-app.html
- [x] /4.0/installation-guide/more-installation-alternatives/splunk/splunk-basic.html
- [x] /4.0/installation-guide/more-installation-alternatives/splunk/splunk-distributed.html
- [x] /4.0/installation-guide/more-installation-alternatives/splunk/splunk-polling.html
- [x] /4.0/installation-guide/more-installation-alternatives/splunk/splunk-reverse-proxy.html
- [x] /2.1/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.0/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.1/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.2/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.3/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.4/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.5/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.6/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.7/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.8/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.9/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.10/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.11/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.12/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /3.13/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html
- [x] /4.0/installation-guide/more-installation-alternatives/splunk/splunk-wazuh.html

Not found from 4.0 to...
- [x] /2.1/docker/upgrade-guide.html
- [x] /3.0/docker/upgrade-guide.html
- [x] /3.1/docker/upgrade-guide.html
- [x] /3.2/docker/upgrade-guide.html
- [x] /3.3/docker/upgrade-guide.html
- [x] /3.4/docker/upgrade-guide.html
- [x] /3.5/docker/upgrade-guide.html
- [x] /3.6/docker/upgrade-guide.html
- [x] /3.7/docker/upgrade-guide.html
- [x] /3.8/docker/upgrade-guide.html
- [x] /3.9/docker/upgrade-guide.html
- [x] /3.10/docker/upgrade-guide.html
- [x] /3.11/docker/upgrade-guide.html
- [x] /3.12/docker/upgrade-guide.html
- [x] /3.13/docker/upgrade-guide.html

Not found from 3.1 to...
- [x] /3.5/user-manual/capabilities/vuls.html
- [x] /3.6/user-manual/capabilities/vuls.html
- [x] /3.7/user-manual/capabilities/vuls.html
- [x] /3.8/user-manual/capabilities/vuls.html
- [x] /3.9/user-manual/capabilities/vuls.html
- [x] /3.10/user-manual/capabilities/vuls.html

**Comment by Arcapas** [comment]
**2021-** 11-08:
- [ ] Properly redirected the 4.2 sections to be found when switching versions.
