### ISSUE TITLE
Migrate Agent Key Polling to Authd module

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-documentation#4422]
## Description

Since Agent Key Polling will be integrated into the Authd module, it is necessary to update and modify the documentation with the new changes.

- [x] Modify the description, the general diagram and the section `How it works`: https://documentation.wazuh.com/current/user-manual/capabilities/agent-key-polling.html
- [x] Remove the `agent-key-polling` references in `wazuh-modulesd` and add them in `authd`: https://documentation.wazuh.com/current/user-manual/reference/daemons/wazuh-modulesd.html
- [x] Modify the configuration with the one added in `authd`: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-agent-key-polling.html
- [x] Remove `wodle="agent-key-polling"` configuration reference: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/index.html
- [x] Check if it is necessary to modify something else.

**Comment by juanmanuelug** [comment]
Devel branch: https://github.com/wazuh/wazuh-documentation/tree/4422-Migrate-Agent-Key-Polling-to-Authd
