### ISSUE TITLE
Create a guide for Wazuh Splunk App

### ISSUE THREAD

**Issue by fhielpos** [wazuh/wazuh-documentation#4428]
Hello team,

We need to add a guide for the Wazuh Splunk App to explain the basic usage of it:

* How to use the querying filters
* How to switch between API configs, indexes, and source types
* How to use the management console (agents section, DevTools, etc)

Regards,
Franco Hielpos

**Comment by gdiazlo** [comment]
Closing it, because we're working on:
- https://github.com/wazuh/wazuh-kibana-app/issues/5222
