### ISSUE TITLE
Considering adding how to enable Wazuh archives indices in Elasticsearch

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh-documentation#4433]
Hello Team,
I am reaching you with the request of adding to the documentation, the information on how to enable in Elasticsearch the Wazuh archives indices.
This step by step can be a guide for the configuration:
1. Configure logging of all events in Wazuh managers:
The following configuration needs to be done on the Wazuh manager. In case of having a cluster of Wazuh managers, this configuration needs to be done on all nodes.
Configure logall_json output in `/var/ossec/etc/ossec.conf`
```
<logall_json>yes</logall_json>
```
Then restart `wazuh-manager` service:
```
service wazuh-manager restart
```

2. Configure Filebeat output to send all events to Elasticsearch: 
The following configuration needs to be done on the Wazuh manager. In the case of having a cluster of Wazuh managers, this configuration needs to be done on all nodes.
Configure Wazuh Filebeat module to read both alerts and archives. This can be done at `/etc/filebeat/filebeat.yml` file:
```
filebeat.modules:
 - module: wazuh
  alerts:
   enabled: true
  archives:
   enabled: true
```
Then restart `filebeat` service:
```
service filebeat restart
```
Output can be tested running:
```
filebeat test output
```

3. Create a new index-pattern in Kibana:
**On Kibana WUI:**
a. Go to Management -> Stack Management -> Index Patterns
b. Click on Create index pattern
c. For the index pattern name choose wazuh-archives-* and click on Next step
d. For the timestamp field choose timestamp (be careful not to choose @timestamp instead)
e. Click on Create index pattern

4. Browse through indexed data:
On Kibana WUI, under the Discover section choose index pattern wazuh-archives-* instead of wazuh-alerts-*
---
As an alternative to the point 3, we can add something from the command line, like this:
**On the terminal:**
Download remote wazuh-alerts index pattern.
```
curl -sS -k -u admin:admin -XGET "https://<KIBANA_IP>/api/saved_objects/index-pattern/wazuh-alerts-*?pretty" -o wazuh-alerts-pattern.json
```
Remove json unnecesary entries
```
jq 'del(.references, .id, .type, .version, .updated_at, .migrationVersion, .namespaces)' wazuh-alerts-pattern.json > entries-removed.json
```
Set remote index-pattern name.
```
jq '.attributes.title = "wazuh-archives-*"' entries-removed.json > new-pattern.json
```
Load new index-pattern.
```
curl -sS -k -u admin:admin -XPOST "https://<KIBANA_IP>/api/saved_objects/index-pattern/wazuh-archives-*" -H 'Content-Type: application/json' -H 'kbn-xsrf: true' -d @new-pattern.json
```

I hope this could be added to the official documentations since it could be helpful to users and customers.
Thank you in advance!

**Comment by flygoody** [comment]
you are best!

**Comment by sirdaddits** [comment]
Hello
I made all of this
I saw, that index create and it store data
![image](https://github.com/user-attachments/assets/e66452f8-1592-4877-877c-8ce0c11a5736)
but it can view in dashboard
![image](https://github.com/user-attachments/assets/e9431e71-4496-4cc7-b353-d7b2b24bea26)
