### ISSUE TITLE
Improve format for azure-logs

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh-documentation#446]
Hi team!

It would be nice to improve the format of the documentation page for the `azure-logs` module. 

![captura de pantalla de 2018-10-01 15-26-13](https://user-images.githubusercontent.com/11405177/46291398-a2abdc00-c58e-11e8-8f14-abc02e20577b.png)

It's done this way because the following error:

```
ERROR: Duplicate target name, cannot be used as a unique reference: "timeout".
```

Regards!
Cerv1

**Comment by chemamartinez** [comment]
Fixed at https://github.com/wazuh/wazuh-documentation/pull/389/commits/985d7cd2d024be45e5a920c871596e1cb64add87
