### ISSUE TITLE
OVA  password modification does not take effect

### ISSUE THREAD

**Issue by Carochen13** [wazuh/wazuh-documentation#4463]
I just installed WAZUH from its OVA.

The web interface is wazuh/wazuh

When I click reset password from the web interface i get this error

Failed to reset password. {"status":"FORBIDDEN","message":"Resource 'admin' is read-only."}

update the new password in /etc/filebeat/filebeat.yml   modification does not take effect

**Comment by orsifacundo** [comment]
Hi @Carochen13, 

You can't change the password of the administrator user via GUI, For this you'll need to follow our documentation: https://documentation.wazuh.com/current/user-manual/elasticsearch/elastic_tuning.html#change-users-password

Let us know if this information helped.

**Comment by Carochen13** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
