### ISSUE TITLE
Fixing errors in the vulnerability detection page

### ISSUE THREAD

**Issue by Arcapas** [wazuh/wazuh-documentation#4472]
Hi team,
This issue aims to fix technical mistakes in the text of the **User manual > Capabilities > Vulnerability detection** section:
![138492860-9acadac8-3bba-4969-a1db-e5b50b7bbc80](https://user-images.githubusercontent.com/85168963/138493186-10dc2ed6-e0c3-4f70-9af7-5e922dc850aa.png)

Tasks:
- [x] Create a branch: 4472_4.2_fixing-error-vulnerability-detection-page
- [x] Edit the text fixing the text errors.
- [x] Make a last review of the text
- [x] Make PR and ask the content team for Review

Regards,
Damian

**Comment by saramoran** [comment]
testing comment
