### ISSUE TITLE
Add upgrade documentation for Kubernetes on major versions upgrade

### ISSUE THREAD

**Issue by fhielpos** [wazuh/wazuh-documentation#4535]
Hello team,

Since Kubernetes has grown in popularity as a deployment method, we should consider having upgrade guides for major versions upgrade.

### For example:
From Wazuh 3.x to 4.x, the Kubernetes manifest as well as the `docker` images had breaking changes that involves multiple steps before doing an upgrade.

In situations like this, we should have an upgrade guide with the steps to perform those upgrades.

Regards,
Franco Hielpos

**Comment by javimed** [comment]
Related issue: https://github.com/wazuh/wazuh-kubernetes/issues/314

**Comment by MiguelCasaresRobles** [comment]
Duplicated. Closed it.
