### ISSUE TITLE
Improve upgrading guide

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-documentation#454]
The upgrading guide, at least the one from a different minor, lacks steps related to upgrading logstash configuration and elasticsearch template.

**Comment by havidarou** [comment]
Moreover, in the minor upgrading guide there's a step to change ownership of Kibana's bundles.

In the next we remove the bundles.

Maybe it's related to the fact that we remove the plugin using the Kibana server in another step, but, could you try to reduce the number of steps?

**Comment by JuanjiJG** [comment]
Hello @havidarou,

I've submitted a pull request: #686 

I hope this makes clearer the different guides that we provide on the documentation.

Regarding your question about the steps to remove the Wazuh app bundles, I've checked this with the Kibana app team, and we've concluded that the steps are necessary and don't need to be changed.

Regards,
Juanjo
