### ISSUE TITLE
Update SCA policies documentation page with the OS we support

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#4595]
Hello team,

I observed the following page is outdated as we support more OS that stated here: https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/how-to-configure.html

For instance, Amazon Linux.

We should update this page.

Regards,

Miguel Casares

**Comment by s-ocando** [comment]
The list of available SCA policies was recently updated in https://github.com/wazuh/wazuh-documentation/pull/5193. 

New policies for Ubuntu 22 and macOS 12.0 will be included in Wazuh v4.3.6. These policies are included in https://github.com/wazuh/wazuh-documentation/pull/5467.
