### ISSUE TITLE
Update cluster development page to include new multiprocess behavior

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-documentation#4603]
## Description

We need to update the [Development - Wazuh cluster](https://documentation.wazuh.com/current/development/wazuh-cluster.html) section of the documentation after the changes carried out at:
- https://github.com/wazuh/wazuh/issues/10765
- https://github.com/wazuh/wazuh/issues/10770

Those developments add multiprocessing to the tasks of Agent-info sync and Local Integrity in the master node, so it should be mentioned at these sections at least:
- [Agent info thread](https://documentation.wazuh.com/current/development/wazuh-cluster.html#agent-info)
- [File integrity thread](https://documentation.wazuh.com/current/development/wazuh-cluster.html#file-integrity-thread)

It could also be implemented, if necessary, a section regarding the configuration of the process pool for the cluster and a new scheme that helps to understand it.

**Comment by Selutario** [comment]
## Issue update

To help understand the explanation of multiprocessing that has been added to the doc in this issue, it would be useful to create a schematic image in the Wazuh style.

I have made this small draft about what it is intended to represent:

![process_pool](https://user-images.githubusercontent.com/23361101/143413166-c31edf2a-b8cf-47e7-be73-8b2bf0528bfc.png)

The style should be similar to others like the ones already in the cluster section in the doc:
![image](https://user-images.githubusercontent.com/23361101/143413320-e93a5a44-99de-4dff-b57f-799620ec3fb5.png)
(link: https://documentation.wazuh.com/current/_images/cluster_flow.png, at https://documentation.wazuh.com/current/development/wazuh-cluster.html)

Thanks in advance!

**Comment by saramoran** [comment]
Hi, here is the diagram you asked for :
<img width="533" alt="image-b" src="https://user-images.githubusercontent.com/16825724/143419141-fdcf8e04-2d95-4c6e-998a-8ea3e7f90dc3.png">
)
