### ISSUE TITLE
Update documentation related to agent-groups files

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-documentation#4606]
Based on the development of the issue https://github.com/wazuh/wazuh/issues/10771, we need to adapt all the documentation related to the `agent-groups` files. These files disappear after this development and become part of the `global.db` database, being able to consult this information through `wazuh-db`.

We should update the information that appears in the cluster section within the Development and check for any other mention of these files:

- https://documentation.wazuh.com/current/development/wazuh-cluster.html#integrity-thread

**Comment by Selutario** [comment]
This [image](https://user-images.githubusercontent.com/23361101/157456893-6b69f705-259a-4e0d-8871-04889d8936df.png) needs to be replaced by a new one, which should look like this:

![agent-groups](https://user-images.githubusercontent.com/23361101/157457026-422d93b8-26a5-4a52-b3ca-2c1d575eab2c.jpg)

**Comment by pereyra-m** [comment]
Closing this issue after merging #4923.
