### ISSUE TITLE
Update documentation related to log rotation functionalities

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-documentation#4628]
## Description

With the new functionalities created in issue wazuh/wazuh#3072, it is necessary to update and modify the documentation that those changes affect.

- [ ] Deprecate `internal_options.conf` configuration referring to the log rotation.
- [ ] Update `ossec.conf` configuration (`<logging>` block) to add new functionalities.
- [ ] Check the _descriptions_ where they refer to the _log rotation_ to update them if necessary.
- [ ] Check the _variables_ of the _log rotation_ to update them if necessary

**Comment by vikman90** [comment]
Closing this issue as it will be superseded by version 5.0.
