### ISSUE TITLE
Add information regarding the use of the `only_logs_after` parameter in the external integration modules' documentation

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh-documentation#4648]
Due to [wazuh#9993](https://github.com/wazuh/wazuh/issues/9993) the documentation must be updated to clarify how the use of the `only_logs_after` parameter interacts with the AWS and GCP modules.  

Information regarding the use of the `--reparse` parameter should be added too to the AWS documentation, since there is no mention about that parameter in the documentation.

This issue is being worked in #4650 and #3994.

**Comment by CarlosRS9** [comment]
To be fixed in https://github.com/wazuh/wazuh-documentation/pull/4650 and https://github.com/wazuh/wazuh-documentation/pull/3994.

**Comment by noise-kngdm** [comment]
## Issue update
#4650 and #3994 have both been merged, so this issue will be closed.
