### ISSUE TITLE
Typo in the FTS example documentation

### ISSUE THREAD

**Issue by juliancnn** [wazuh/wazuh-documentation#4722]
Hi team,

There is a typo on [this documentation entry](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/decoders.html#fts). 
The decoder label is not correctly opened:

![image](https://user-images.githubusercontent.com/1891958/148229476-91333f85-51e2-401e-bd2b-60d7d971a9d5.png)

it should be:

```xml
<decoder name="fts-dec">
  <fts>srcuser, location</fts>
  ...
</decoder>
```

**Comment by jnasselle** [comment]
Closed by #4723
