### ISSUE TITLE
Indexer and dashboards migration guide

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#4729]
[New installers](https://github.com/wazuh/wazuh-packages/issues/1144) called `wazuh-indexer` and `wazuh-dashboards` will be released on 4.3.0. It's needed to provide a migration guide to those users with Opendistro installations who wants to use `wazuh-indexer` or `wazuh-dashboards` instead. 

The guide must explain:
- How to convert the `elasticsearch.yml` configuration to the `opensearch.yml` configuration. Changes to be done: settings and their parameters. `opendistro_<name_of_plugin>.<setting>` change by `plugins.<name_of_plugging>.<setting>`. The setting `opendistro_security.audit.type: internal_elasticsearch` change to `plugins.security.audit.type: internal_opensearch`. `wazuh-indexer` configuration file example below:
[opensearch.yml.txt](https://github.com/wazuh/wazuh-documentation/files/7856801/opensearch.yml.txt)

- Once `wazuh-indexer` is started, how to `filebeat`'s must be pointed to the `wazuh-indexer` instances, taking into account the new ports, user, password, and certificates configuration. 
- How to copy data from `elasticsearch`(Opendistro) to `wazuh-indexer` using the API. (See Refs). 
- How to migrate custom dashboards from Opendistro to `wazuh-dashboards` by exporting objects and importing them with `wazuh-dashboard`. 

Refs:
- https://opensearch.org/blog/technical-posts/2021/07/how-to-upgrade-from-opendistro-to-opensearch/

**Comment by s-ocando** [comment]
The Wazuh indexer and Wazuh dashboard migration guides were introduced in https://github.com/wazuh/wazuh-documentation/pull/5047.
