### ISSUE TITLE
Installation instructions for Wazuh with opendistro has wrong instructions for filebeat

### ISSUE THREAD

**Issue by sandeeprenjith** [wazuh/wazuh-documentation#4759]
Installation instructions for Wazuh with opendistro has wrong instructions for filebeat. 
Filebeat which is installed following the instructions is not compatible with Opendistro. The OSS version of Filebeat is required.

For Opendistro 7.10.1 the below works. 

```
wget https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-oss-7.10.1-amd64.deb
dpkg -i filebeat-oss-7.10.1-amd64.deb
```

**Comment by s-ocando** [comment]
Hi @sandeeprenjith, 

The Wazuh repository, added at the beginning of the installation, contains a compatible Filebeat OSS version. The installation instructions were designed with this in mind.  Nevertheless, if the Elastic repository is enabled, an incompatible version of Filebeat can be installed by mistake.
