### ISSUE TITLE
Explain the configuration of a load balancer in a cluster environment

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-documentation#477]
Hi team,

I just realized that the [cluster section](https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html) of the documentation doesn't currently have any explanation of the configuration of a load balancer in a Wazuh cluster environment. In my honest opinion, it would be necessary to offer a guide for this in order to clarify how the cluster works.

Regards

### Pending tasks

- [x] Research about load balancing. Decide about what's the best option to explain this concept on the documentation.
- [x] Try to configure a load balancer for a Wazuh cluster.
- [x] Elaborate a list of required steps to configure this. The list must be minimal but sufficient to properly configure the feature.
- [x] Structure and document the steps in a proper, user-readable format.
- [x] Revision: grammar, readability, format, document structure.

**Comment by aslap5** [comment]
I would also like to see this expanded and would be willing to do so if you can point me in the right direction.

**Comment by JuanjiJG** [comment]
Updating the first comment to add an initial list of pending tasks in order to accomplish this task.
