### ISSUE TITLE
Powershell deployment question?

### ISSUE THREAD

**Issue by killmasta93** [wazuh/wazuh-documentation#4807]
Hi 
Currently i have this script to install on my servers
`
Invoke-WebRequest -Uri https://packages.wazuh.com/4.x/windows/wazuh-agent-4.0.0-1.msi -OutFile wazuh-agent.msi; ./wazuh-agent.msi /q WAZUH_MANAGER='ids.domain.com' WAZUH_REGISTRATION_SERVER='ids.domain.com' WAZUH_AGENT_NAME='myserver'`

and it works fine but i need to also go to 
`
C:\Program Files (x86)\ossec-agent\ossec.conf`

and need to add this part 
```

<enrollment>
   <agent_name>myserver</agent_name>
 </enrollment>

```

Possible to add that part in the powershell section? 

Thank you

**Comment by JcabreraC** [comment]
Hello killmasta93,

I don't understand why do you need to add the `enrollment` block to the configuration. With the `agent_name` tag you specify with which name the agent will be registered in the manager, but, in your PowerShell script, you have already defined the name that it will have, with the variable "WAZUH_AGENT_NAME".

As I say, the agent must be registered automatically with the name "myserver", as you have indicated. You can see more information about `Deployment variables` here: https://documentation.wazuh.com/current/installation-guide/wazuh-agent/deployment-variables/deployment-variables-aix.html

On the other hand, you could edit the `ossec.conf` file using `Get-Content $file.FullName` and doing the pertinent operations on the file.

Regards!

**Comment by killmasta93** [comment]
sorry for the late reply, the email notification got in my spam 
as for the enrollment, what i have noticed is that sometimes the agent name is changed, because it uses the name of the computer name 
ex: computer name srv002 
but on wazuh agent i have it named as serverlab02

when i enroll it it seems to work but after a while the agent converts back to the same computer name
i read this which helped me adding always the enrollment 

the issue is that the i use AWS Fargate which the VMs auto regenerate themself using docker file and start up powershell scripts 

https://github.com/wazuh/wazuh/issues/7899

Thank you

**Comment by JcabreraC** [comment]
Hello killmasta93,

This is because the agent key has not been deleted, so Wazuh detects that this agent existed and recovers the agent's data.

To apply the changes, first, remove the agent. To do this run the following command on the server-side:
```
# /var/ossec/bin/manage_agents 


****************************************
* Wazuh v4.3.0 Agent manager.          *
* The following options are available: *
****************************************
   (A)dd an agent (A).
   (E)xtract key for an agent (E).
   (L)ist already added agents (L).
   (R)emove an agent (R).
   (Q)uit.
Choose your action: A,E,L,R or Q:
```

Select the `R` option to remove the agent and specify the agent ID.

Once removed, install the agent again. This should solve your problem.

Regards !

**Comment by killmasta93** [comment]
Thank you so far it working good
