### ISSUE TITLE
Wrong command in the OVA Generation Guide

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-documentation#4848]
Checking the OVA package generation 4.2 documentation: https://documentation.wazuh.com/current/development/packaging/generate-ova.html

I found the following error:

![Screenshot_20220217_091542](https://user-images.githubusercontent.com/64099752/154479895-c7475303-dd1b-4fdb-a954-81c356bd6e38.png)

the command should be `./generate_ova.sh -h`

**Comment by s-ocando** [comment]
Fixed https://github.com/wazuh/wazuh-documentation/commit/9dd70c352b20870eace4a0ff4a3e62216024e0c7.
