### ISSUE TITLE
Review "Centralized confguration"

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#485]
Hello team,

In the explanation of centralized configuration, when configuring `agent.conf `with `profile`, it is not clear enough how to classify this profile with the agent. It should be explained that is related to the `<config-profile>` of the `ossec.conf` of the agent.

Regards.

**Comment by elwali10** [comment]
The path for the local_internal_options.conf file should be completed to /var/osssec/etc/local_internal_options.conf in the **introduction** section and "**how to ignore shared configuration**" section

**Comment by JuanjiJG** [comment]
Done here: #555

Thanks @MiguelCasaresRobles and @elwali10 for reporting this.

Regards,
Juanjo
