### ISSUE TITLE
Improve the "Monitoring AWS based services" troubleshooting section

### ISSUE THREAD

**Issue by noise-kngdm** [wazuh/wazuh-documentation#4853]
## Description
The [troubleshooting section](https://documentation.wazuh.com/4.2/amazon/services/troubleshooting.html) of the AWS documentation should be improved adding common doubts and issues that an user might face when trying to run the module. We could use some answers made to the community channels as a first draft to make these changes:

<details><summary>Example of the new additions based on community answers</summary>

    **The module is failing**
	It is possible that the module is failing due to an incorrect configuration in the ossec.conf or that your credentials do not provide access. Please take a look at the ossec.log. You can find it in {wazuh-path}/logs/ossec.log or through the UI in Wazuh > Management > Logs. Once ossec.log is open, look for any messages containing AWS to check for errors and warnings.
	**The module is running but there is no logs for that date.**
	It is possible that the module is not failing but there are no logs for the dates you are trying to process. The module allows you to specify the date of the logs you want to process by using the only_logs_after parameter. If this parameter is not specified, the module will try to obtain the logs generated on the same day of the execution. Verify that you have logs for the date in question. Check this section to learn more about how to use the only_logs_parameter
	**The module works and there is data, but no alerts are generated.**
	Finally, you must understand that it is possible that  module is working and there are logs available, but they do not generate alerts. For this, it is necessary to understand the difference between events and alerts:
	When the module pulls logs from your AWS, it sends them to analysisd as events.
	The events are analyzed and if one of these events triggers an available rule, then and only then an alert will be triggered, which is what you will see in the UI.
	It is possible to check if the module is running and sending events, but no alerts are being generated.

</details>

Also, the `4. Wrong AWS service path:` section should use the paths defined in [supported services](https://documentation.wazuh.com/4.2/amazon/services/supported-services/index.html) instead of a *duplicated set* to have the most up-to-date information as possible and to ease the task of maintaining the documentation.

**Comment by CarlosRS9** [comment]
We have deprecated everything that was there before and rethought this whole section. It is almost finished.

This is the new structure of the contents reflected in this page:

```
Troubleshooting
	Checking if the module is running
	Enabling debug mode
	Checking if logs are being pulled
	Common problems and solutions
		Unable to locate credentials
		Invalid credentials to access S3 Bucket
		The config profile could not be found
		The security token included in the request is invalid
		The bucket configuration looks fine but no alerts are present in the Wazuh UI
		CloudWatch Logs integration is running but no alert is shown in the Wazuh UI
		Interval overtaken message is present in the ossec.log
		No data is being parsed
	Error codes reference
```

We are finishing adding details to the different common problems and considering whether to add any additional ones.
