### ISSUE TITLE
Wrong Default example for <auth> XML section in the docs

### ISSUE THREAD

**Issue by vaskosmihaylov** [wazuh/wazuh-documentation#4891]
Checking the documentation at https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/auth.html/ at the end for the docs where the Default configuration is presented there is a missing closing tag **<remote_enrollment>**:

In the docs:

`<remote_enrollment>yes<remote_enrollment>`

The correct syntax:

`<remote_enrollment>yes</remote_enrollment> `

[Screenshot](https://www.awesomescreenshot.com/image/23300240?key=eccc7e84081047ee3dd6b1ea70c48cbf)

**Comment by juliancnn** [comment]
Hi @vaskosmihaylov 

Thanks for the report, we have already created a PR to fix this typo.

You can follow the change request [here](https://github.com/wazuh/wazuh-documentation/pull/4896)

Regards,
Julian

**Comment by juliancnn** [comment]
The fix has already been implemented. Thank you for helping us correct these issues. 

Regards, Julian
