### ISSUE TITLE
Improve AWS supported services documentation

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-documentation#4918]
Once the improvements introduced in #4917 have been applied the next step to improve the quality of our AWS documentation is to review the pages corresponding to each one of the supported services and apply the following changes:

- Ensure they all follow the same unified structure.
- Simplify the steps to follow when configuring the service on the AWS side.
- Replace the old screenshots with new screenshots using the new style.
- Add a template that explains to the user how to configure the module from the UI.
- Add use cases. Some services already have while others do not. They should include screenshot from the UI.

**Comment by davidjiglesias** [comment]
With the recent changes and improvements for our AWS integration documentation, we have decided not to follow through with more changes.
