### ISSUE TITLE
Update remove_from_bucket option from wodle name=”aws-s3”

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-documentation#4921]
As part of https://github.com/wazuh/wazuh/issues/12670 the `remove_from_bucket` will be updated to allow the user to configure it per bucket instead of being a global parameter for the aws-s3 wodle. This change requires to update the aws-s3 wodle reference accordingly.

Required changes:
- Move the `remove_from_bucket` parameter from global to bucket section
- Update the configuration examples to show at least one bucket using this.

**Comment by mateojames** [comment]
A change has been specified on the issue. The user will be able to set the configuration both on the Wodle globally, or per Bucket specifically. This change requires to update the aws-s3 wodle reference accordingly.

Required changes:

- Add the remove_from_bucket parameter to bucket section
- Update the configuration examples to show at least:
    -     One bucket using this
    -     One wodle using this
    -     A scenario where both a wodle and a bucket are using this, to explain the priority of the bucket parameter over the wodle parameter
