### ISSUE TITLE
Remove logging.dest option in Migrating to Wazuh dashboard Documentation

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-documentation#4964]
It is necessary to remove the highlighted line from the Migration to Wazuh Dashboard documentation, particularly in step 5, since that configuration is not necessary
https://documentation-dev.wazuh.com/add_migration_guide/migration-guide/wazuh-dashboard.html

 server.host: 0.0.0.0
 server.port: 443
 opensearch.hosts: https://localhost:9200
 opensearch.ssl.verificationMode: certificate
 #opensearch.username:
 #opensearch.password:
 opensearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
 opensearch_security.multitenancy.enabled: true
 opensearch_security.readonly_mode.roles: ["kibana_read_only"]
 server.ssl.enabled: true
 server.ssl.key: "/etc/wazuh-dashboard/certs/wazuh-dashboard-key.pem"
 server.ssl.certificate: "/etc/wazuh-dashboard/certs/wazuh-dashboard.pem"
 opensearch.ssl.certificateAuthorities: ["/etc/wazuh-dashboard/certs/root-ca.pem"]
 `logging.dest: "/var/log/wazuh-dashboard/wazuh-dashboard.log"`
 uiSettings.overrides.defaultRoute: /app/wazuh?security_tenant=global

**Comment by s-ocando** [comment]
Removed the `logging.dest` setting as requested in the Migration guide https://github.com/wazuh/wazuh-documentation/commit/2b4859ff49eaa7414e63cb2aab447e421ddf703b, and in the new Installation guide https://github.com/wazuh/wazuh-documentation/commit/ca813cc8a688b0a58fce8aa9ed13253523b8b485.
