### ISSUE TITLE
4.3.0 Documentation. Check OpenDistro references in the different installation methods

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#4980]
Hi team,

I'm opening this issue because I observed that we are removing ODFE references in the documentation for the installation. For instance, it is not possible to install ODFE using our step-by-step documentation or using the unattended installer.

However, it is possible to do it using Ansible, K8s, it appears in the Learning Wazuh, etc...

We should consider removing those references for consistency.

Regards,

Miguel Casares

**Comment by s-ocando** [comment]
All installation alternatives have been updated for the Wazuh indexer and the Wazuh dashboard and references to Open Distro for Elasticsearch have been removed. 
- https://github.com/wazuh/wazuh-documentation/pull/5089
- https://github.com/wazuh/wazuh-documentation/pull/5141
- https://github.com/wazuh/wazuh-documentation/pull/5116
- https://github.com/wazuh/wazuh-documentation/pull/5106
- https://github.com/wazuh/wazuh-documentation/pull/5100
- https://github.com/wazuh/wazuh-documentation/pull/4945
- https://github.com/wazuh/wazuh-documentation/pull/5095
