### ISSUE TITLE
Add information to enable the AWS module

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-documentation#4988]
### Documentation
Right now, within [Monitoring AWS based services](https://documentation-dev.wazuh.com/4.3-rc/amazon/services/index.html) section of the documentation, there is no explanation on how to enable the Wazuh AWS module in the UI. In fact, its existence is not even clearly mentioned.

This could mean that many users do not activate it or do not know how to do it. I think it would be useful to add a new point in [Considerations for configuration](https://documentation-dev.wazuh.com/4.3-rc/amazon/services/prerequisites/considerations.html) to explain the steps for its activation and some image of the dashboard:

![image](https://user-images.githubusercontent.com/23361101/160775759-971d9aa9-229a-49ec-9313-16deeeb9fba6.png)

### Blogpost
In step 4 of this blogpost it is explained how to activate the AWS dashboard but the way to do it is now outdated. It should be changed too:
- [Integrating AWS CloudTrail in Wazuh.](https://wazuh.com/blog/integrating-aws-cloudtrail-in-wazuh/)

**Comment by EduLeon12** [comment]
@Selutario This Issue Title and description should be changed to include all modules found in [Cloud Security](https://documentation.wazuh.com/current/monitoring.html) section because the solution was replicable to all sections.
