### ISSUE TITLE
Move CloudWatchLogs bucket documentation pull to 4.3 branch

### ISSUE THREAD

**Issue by yanazaeva** [wazuh/wazuh-documentation#4991]
In our current `CloudWatch` documentation, it is mentioned that CloudWatch can be configured using an S3 bucket but that is not possible. This was already modified in the following [pull](https://github.com/wazuh/wazuh-documentation/pull/4917), alongside some other information. There is no reference to anything from 4.4.0 here, so I think we should migrate this data to 4.3. This way we will avoid having users wasting time trying this configuration.

**Comment by CarlosRS9** [comment]
# Status

This was already fixed in https://github.com/wazuh/wazuh-documentation/issues/4690 and it's pending to be applied for the 4.4 release. We will apply this change also for the 4.3 release to avoid confusion.

**Comment by CarlosRS9** [comment]
Fixed by https://github.com/wazuh/wazuh-documentation/pull/5017
