### ISSUE TITLE
Request for changes on the Wazuh 4.3 installation guide

### ISSUE THREAD

**Issue by JcabreraC** [wazuh/wazuh-documentation#4999]
# Description

As part of the manual tests of Wazuh 4.3 that are being performed, where the installation guide must be followed and verified, some errors were detected. Part of the errors found are related to the description of the steps that are needed to be followed to perform the installation and others appeared when trying to execute the installation commands.

The necessary changes in the guide for a correct installation are as follows:

**Wazuh-indexer:**
- It is necessary to uncomment the following lines
    ```
    #discovery.seed_hosts:
    # - "172.18.1.10"
    # - "172.18.1.11"
    # - "172.18.1.12"
    ```
- `network.host` must have the IP of the node

**Filebeat:**
- For a cluster, it is not explained how to setup the file `/etc/filebeat/filebeat.yml`:
    ```
    # Wazuh - Filebeat configuration file
    output.elasticsearch:
    hosts: ["10.0.0.80:9200", "10.0.0.81:9200", "10.0.0.84:9200"]
    ```
    where each IP in the cluster must be separated with commas

**Comment by nmkoremblum** [comment]
When editing `etc/wazuh-indexer/opensearch.yml` on the Wazuh indexer nodes, on the "plugins.security.nodes_dn:" configuration, there should be as many entries as indexer nodes the system has and every entry should have the indexer node's names.

On the template we have the following:
```
plugins.security.nodes_dn:
- "CN=node-1,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-2,OU=Wazuh,O=Wazuh,L=California,C=US"
#- "CN=node-3,OU=Wazuh,O=Wazuh,L=California,C=US"
```

And, if having three indexer nodes with custom names the final configuration should be something like this:

```
plugins.security.nodes_dn:
- "CN=indexer-1,OU=Wazuh,O=Wazuh,L=California,C=US"
- "CN=indexer-2,OU=Wazuh,O=Wazuh,L=California,C=US"
- "CN=indexer-3,OU=Wazuh,O=Wazuh,L=California,C=US"
```

This situation should correctly explained on the installation guide.
