### ISSUE TITLE
Add the permissions required to configure CloudWatch

### ISSUE THREAD

**Issue by yanazaeva** [wazuh/wazuh-documentation#5005]
Currently, in order to complete the following [guide](https://documentation-dev.wazuh.com/4.3-rc/amazon/services/supported-services/ecr-image-scanning.html), we will require `admin` privileges. Also, we should investigate and include the required permission to push images to an ECR repository. For this last task, I was granted `Full Access` permission as it was difficult to determine the required ones. When trying to push the image, we received the following message, which did not mention specific permission:
![image](https://user-images.githubusercontent.com/67015786/161026230-cd293967-4dc0-4861-903d-380b708e0088.png)

**Comment by fdalmaup** [comment]
# Issue Update

According to the [AWS documentation](https://docs.aws.amazon.com/AmazonECR/latest/userguide/image-push.html#image-push-iam), Amazon ECR requires that users have specific permissions to push images. The following is an example of those permissions:
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecr:CompleteLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:InitiateLayerUpload",
                "ecr:BatchCheckLayerAvailability",
                "ecr:PutImage"
            ],
            "Resource": "arn:aws:ecr:region:111122223333:repository/repository-name"
        },
        {
            "Effect": "Allow",
            "Action": "ecr:GetAuthorizationToken",
            "Resource": "*"
        }
    ]
}
``` 
In addition, to create the CloudFormation Stack, policies must be declared for theuser as described in the [CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/using-iam-template.html). That is what it should be added to the current Wazuh Documentation

**Comment by fdalmaup** [comment]
# Issue Update

`Policy configuration` section has been added to `AWS Configuration` in the `Amazon ECR Image scanning` page. It has the base policies needed to create the CloudFormation stack and to push images to private repositories. Due to the use of the [ECR template](https://github.com/aws-samples/ecr-image-scan-findings-logger/blob/main/Template-ECR-SFL.yml), the `iam:CreateRole` is also needed. 
All the mentioned policies have to be tested to assure the correct functioning of the module when following the documentation.

**Comment by fdalmaup** [comment]
# Issue Update

After testing the first added rules, it was found that more related `iam` rules are needed. This is due to the template mentioned in the previous comment. 
Below is the description of what permissions have been found to be needed for the different `Resources` defined in the template:
- For `LambdaExecutionRole` several `iam` rules are needed because it needs to create and/or delete roles and policies for the `CloudWatch` logs usage.
- For the `ECRSFLFunction` section the `iam:GetRolePolicy` and the `iam:GetRole` permissions are needed  due to `Role: !GetAtt LambdaExecutionRole.Arn` in `Properties`

The last described permissions weren't set at the time of testing and the creation of the `CloudFormation` stack was not finished. Therefore, to check this more tests are needed for the following `Resources` (`EventTrigger` and `lambdaPermission`)
Current permissions:
<details><summary>Permissions</summary>
    {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "RoleCreator",
            "Effect": "Allow",
             "Action": [
                "iam:CreateRole",
                "iam:PutRolePolicy",
                "iam:AttachRolePolicy",
                "iam:DeleteRolePolicy",
                "iam:DeleteRole"
              ],
            "Resource": "*"
          },
          {
            "Sid": "CloudFormationActions",
            "Effect": "Allow",
            "Action": [
                "cloudformation:CreateStack",
                "cloudformation:ValidateTemplate",
                "cloudformation:CreateUploadBucket",
                "cloudformation:GetTemplateSummary",
                "cloudformation:DescribeStackEvents",
                "cloudformation:DescribeStackResources",
                "cloudformation:ListStacks",
                "cloudformation:DeleteStack",
                "s3:PutObject",
                "s3:ListBucket",
                "s3:GetObject",
                "s3:CreateBucket"
            ],
            "Resource": "*"   
          },
          {
            "Sid": "ImagePush",
            "Effect": "Allow",
            "Action": [
                "ecr:CompleteLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:InitiateLayerUpload",
                "ecr:BatchCheckLayerAvailability",
                "ecr:PutImage"
            ],
            "Resource": "arn:aws:ecr:region:user-id:repository/test-repository"
          },
          {
            "Sid": "ECRAuthToken",
            "Effect": "Allow",
            "Action": "ecr:GetAuthorizationToken",
            "Resource": "*"
          }
        ]
      }

</details>

In parallel to the `CloudFormation` stack creation testing, it was tested whether the permissions assigned for the push of images worked as expected. The result was not successful:
```
docker push aws_account_id.dkr.ecr.region.amazonaws.com/my-repository:tag
The push refers to repository [aws_account_id.dkr.ecr.region.amazonaws.com/my-repository:tag]
509b3c228f71: Retrying in 1 second 
e096adc3b29e: Retrying in 1 second 
7080b0a8c3d6: Retrying in 1 second 
1a996540f50f: Retrying in 1 second 
EOF
```

**Comment by fdalmaup** [comment]
# Issue Update

To test the ECR image scanning following the documentation guide, the permissions `ecr:DescribeImages` and `ecr:DescribeRepositories`  are needed. Therefore they should be added to the previous listed permissions.

**Comment by fdalmaup** [comment]
# Issue Update

The permissions being tested are:
<details><summary>Permissions List</summary>
   
       {
              "Version": "2012-10-17",
              "Statement": [
                {
                  "Sid": "RoleCreator",
                  "Effect": "Allow",
                  "Action": [
                    "iam:CreateRole",
                    "iam:PutRolePolicy",
                    "iam:AttachRolePolicy",
                    "iam:DeleteRolePolicy",
                    "iam:DeleteRole",
                    "iam:GetRole",
                    "iam:GetRolePolicy",
                    "iam:PassRole"
                  ],
                  "Resource": "*"
                },
                {
                  "Sid": "CloudFormationActions",
                  "Effect": "Allow",
                  "Action": [
                      "cloudformation:CreateStack",
                      "cloudformation:ValidateTemplate",
                      "cloudformation:CreateUploadBucket",
                      "cloudformation:GetTemplateSummary",
                      "cloudformation:DescribeStackEvents",
                      "cloudformation:DescribeStackResources",
                      "cloudformation:ListStacks",
                      "cloudformation:DeleteStack",
                      "s3:PutObject",
                      "s3:ListBucket",
                      "s3:GetObject",
                      "s3:CreateBucket",
                      "lambda:RemovePermission",
                      "lambda:DeleteFunction",
                      "lambda:GetFunction",
                      "lambda:CreateFunction",
                      "events:RemoveTargets",
                      "events:DeleteRule",
                      "events:PutRule",
                      "events:DescribeRule",
                      "events:PutTargets"
                  ],
                  "Resource": "*"   
                },
                {
                  "Sid": "ImagePush",
                  "Effect": "Allow",
                  "Action": [
                      "ecr:CompleteLayerUpload",
                      "ecr:UploadLayerPart",
                      "ecr:InitiateLayerUpload",
                      "ecr:BatchCheckLayerAvailability",
                      "ecr:PutImage"
                  ],
                  "Resource": "arn:aws:ecr:region:user-id:repository/test-repository"
                },
                {
                  "Sid": "ECRAuthToken",
                  "Effect": "Allow",
                  "Action": [
                    "ecr:GetAuthorizationToken",  
                    "ecr:DescribeRepositories"    
                  ],
                  "Resource": "*"
                }
              ]
            }

</details>

Some of them, like `iam:PassRole`, when being declared with wildcards (`*`) in the resource can be overly permissive but it is needed by the template to create the lambda. Once the permission testing ends,  this should be reviewed and verify if it could be used with an specific `Resource` set.
Moreover, the permissions list will be divided in the documentation, having the proper section depending on the usage of each group and the disclaimer notes/warnings that need to be added.

**Comment by fdalmaup** [comment]
# Issue Update

The last set of permissions that were tested are
<details><summary>Permissions list</summary>

    {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Sid": "RoleCreator",
            "Effect": "Allow",
            "Action": [
              "iam:CreateRole",
              "iam:PutRolePolicy",
              "iam:AttachRolePolicy",
              "iam:DeleteRolePolicy",
              "iam:DeleteRole",
              "iam:GetRole",
              "iam:GetRolePolicy",
              "iam:PassRole"
            ],
            "Resource": "*"
          },
          {
            "Sid": "CloudFormationActions",
            "Effect": "Allow",
            "Action": [
                "cloudformation:CreateStack",
                "cloudformation:ValidateTemplate",
                "cloudformation:CreateUploadBucket",
                "cloudformation:GetTemplateSummary",
                "cloudformation:DescribeStackEvents",
                "cloudformation:DescribeStackResources",
                "cloudformation:ListStacks",
                "cloudformation:DeleteStack",
                "s3:PutObject",
                "s3:ListBucket",
                "s3:GetObject",
                "s3:CreateBucket",
                "lambda:RemovePermission",
                "lambda:DeleteFunction",
                "lambda:GetFunction",
                "lambda:CreateFunction",
                "lambda:AddPermission",
                "events:RemoveTargets",
                "events:DeleteRule",
                "events:PutRule",
                "events:DescribeRule",
                "events:PutTargets"
            ],
            "Resource": "*"   
          },
          {
            "Sid": "ImagePush",
            "Effect": "Allow",
            "Action": [
                "ecr:CompleteLayerUpload",
                "ecr:UploadLayerPart",
                "ecr:InitiateLayerUpload",
                "ecr:BatchCheckLayerAvailability",
                "ecr:PutImage",
                "ecr:ListImages",
                "ecr:DescribeImages",
                "ecr:DescribeImageScanFindings",
                "ecr:StartImageScan"
            ],
            "Resource": "arn:aws:ecr:region:user-id:repository/test-repository"
          },
          {
            "Sid": "ECRAuthToken",
            "Effect": "Allow",
            "Action": [
              "ecr:GetAuthorizationToken",  
              "ecr:DescribeRepositories"    
            ],
            "Resource": "*"
          },
          {
            "Sid": "ReadOnlyCloudWatch",
            "Effect": "Allow",
            "Action": [
              "logs:DescribeLogStreams",  
              "logs:GetLogEvents"    
            ],
            "Resource": "arn:aws:logs:region:user-id:log-group:/aws/ecr/image-scan-findings/test-repository:*"
          }
        ]
      }

</details>

The added permissions are for the image scanning and getting the log streams and events from the `/aws/ecr/image-scan-findings/test-repository` log group. These allowed the complete execution of the documentation guide, therefore achieving one of the goals of this issue.
The next step is updating the documentation with the required permissions for the execution.

**Comment by fdalmaup** [comment]
The last set of permissions are:

<details><summary>Permissions list</summary>

    {
      "Version": "2012-10-17",
      "Statement": [
          {
              "Sid": "RoleCreator",
              "Effect": "Allow",
              "Action": [
                  "iam:CreateRole",
                  "iam:PutRolePolicy",
                  "iam:AttachRolePolicy",
                  "iam:DeleteRolePolicy",
                  "iam:DeleteRole",
                  "iam:GetRole",
                  "iam:GetRolePolicy",
                  "iam:PassRole"
              ],
              "Resource": "arn:aws:iam::user-id:role/*"
          },
          {
              "Sid": "CloudFormationStackCreation",
              "Effect": "Allow",
              "Action": [
                  "cloudformation:CreateStack",
                  "cloudformation:ValidateTemplate",
                  "cloudformation:CreateUploadBucket",
                  "cloudformation:GetTemplateSummary",
                  "cloudformation:DescribeStackEvents",
                  "cloudformation:DescribeStackResources",
                  "cloudformation:ListStacks",
                  "cloudformation:DeleteStack",
                  "s3:PutObject",
                  "s3:ListBucket",
                  "s3:GetObject",
                  "s3:CreateBucket"
              ],
              "Resource": "*"
          },
          {
              "Sid": "TemplateRequired0",
              "Effect": "Allow",
              "Action": [
                  "lambda:RemovePermission",
                  "lambda:DeleteFunction",
                  "lambda:GetFunction",
                  "lambda:CreateFunction",
                  "lambda:AddPermission"
              ],
              "Resource": "arn:aws:lambda:region:user-id:*"
          },
          {
              "Sid": "TemplateRequired1",
              "Effect": "Allow",
              "Action": [
                  "events:RemoveTargets",
                  "events:DeleteRule",
                  "events:PutRule",
                  "events:DescribeRule",
                  "events:PutTargets"
              ],
              "Resource": "arn:aws:events:region:user-id:*"
          },
          {
              "Sid": "ScanPushImage",
              "Effect": "Allow",
              "Action": [
                  "ecr:CompleteLayerUpload",
                  "ecr:UploadLayerPart",
                  "ecr:InitiateLayerUpload",
                  "ecr:BatchCheckLayerAvailability",
                  "ecr:PutImage",
                  "ecr:ListImages",
                  "ecr:DescribeImages",
                  "ecr:DescribeImageScanFindings",
                  "ecr:StartImageScan"
              ],
              "Resource": "arn:aws:ecr:region:user-id:repository/test-repository"
          },
          {
              "Sid": "ECRUtilities",
              "Effect": "Allow",
              "Action": [
                  "ecr:GetAuthorizationToken",
                  "ecr:DescribeRepositories"
              ],
              "Resource": "*"
          },
          {
              "Sid": "ReadOnlyCloudWatch",
              "Effect": "Allow",
              "Action": [
                  "logs:DescribeLogStreams",
                  "logs:GetLogEvents"
              ],
              "Resource": "arn:aws:logs:region:user-id:log-group:/aws/ecr/image-scan-findings/test-repository:*"
          }
      ]
    }

</details>

Note that the last section of the policy `"ReadOnlyCloudWatch"` was not added to the AWS ECR documentation because it is already described in the `Amazon CloudWatch Logs` page
