### ISSUE TITLE
Deployment on Docker -  Docker compose guide

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-documentation#5021]
Docker installation fails, Missing deployment steps, Review outdated and duplicated content

# Deployment on Docker - Docker compose guide

## Docker installation 🔴

<details>

<summary>docker installation</summary>

2. Run the Docker installation script. 🔴 

![image](https://user-images.githubusercontent.com/8913336/161285571-add65914-f5b6-4c86-b4af-391b0040f08f.png)

![image](https://user-images.githubusercontent.com/8913336/161285770-4305e8d3-aa84-4f98-9699-d335002c39be.png)

![image](https://user-images.githubusercontent.com/8913336/161288065-ebe970dc-2fe8-437a-a337-503eecde1aac.png)

**NOTE: It fails in CentOS 8, we had to install docker trough dnf**

</details>

## Wazuh Docker deployment 🔴

<details>

<summary>wazuh docker deployment</summary>

### Requirements 🟡 

<details>

<summary>requirements</summary>

2. SELinux 🟡

We believe this is not necessary:

![image](https://user-images.githubusercontent.com/8913336/161291414-aa2c7714-b1a2-4cb5-9bb6-6ababe943844.png)

</details>

### Usage. Single Node 🔴

<details>

<summary>single-node</summary>
 
2. Start Wazuh using docker-compose 🔴 

![image](https://user-images.githubusercontent.com/8913336/161293286-04e85740-a474-4ba3-b171-1dea9595af39.png)

**NOTE: If we are deploying single-node the appropriate thing to do would be to add the step where we place ourselves in that directory within the repository or similar.** 🟡 

![image](https://user-images.githubusercontent.com/8913336/161293213-28461e72-5004-402a-83ee-22bd8f50ffda.png)

**NOTE: The step to generate the certificates is missing** 🔴 

![image](https://user-images.githubusercontent.com/8913336/161296108-5b10c180-9f41-4fd1-8752-4a073d9e9307.png)

</details>

### Usage. Multi Node 🔴

<details>

<summary>multi-node</summary>

1. Clone the Wazuh repository to your system  🔴

Reference to a non-existent file 🔴 

![image](https://user-images.githubusercontent.com/8913336/161299862-48b2dec8-3bfb-44b4-a4c7-8a530dc8ead6.png)

2. Secure traffic by replacing single-node certificates 🔴 

**NOTE: Explain what traffic we are referring to** 🟡 

Reference wrong path 🔴

![image](https://user-images.githubusercontent.com/8913336/161300183-41b407f5-ec23-4e02-be0b-45ed5aeb8c1d.png)

Reference wrong path 🔴

![image](https://user-images.githubusercontent.com/8913336/161301547-7f023060-6950-449e-9502-2e9d470997de.png)

2.3. Secure password

**NOTE: We believe that this sub-section should be a new section. 🟡 

Reference wrong path 🔴

![image](https://user-images.githubusercontent.com/8913336/161301830-ec650385-f98d-453c-85f5-3dbf34cb3244.png)

3. Start Wazuh using docker-compose: 🔴 

Reference wrong file 🔴

![image](https://user-images.githubusercontent.com/8913336/161303538-feaf3d49-423d-4417-b326-127cb031ca1c.png)

- Exposed ports 🔴 

![image](https://user-images.githubusercontent.com/8913336/161305246-15472e31-0237-4d16-9f9a-2d341c330daa.png)

it should be HTTPS

### Conclusion

All SSL and certificate sections should be reviewed. It is inconsistent that the certificate creation steps 2.2 2.4 and 2.5 are there when we choose multi-node but are not mentioned when we choose single-node. The best thing would be to leave it simplified as it appears in the repository and adds a new section that indicates how to use the own certificates (of the user that follows the documentation) both in single-node and multi-node.

</details>

</details>

Docker installation fails, Missing deployment steps, Review outdated and duplicated content
## Wazuh Docker utilities 🟡 

<details>

<summary>wazuh docker utilities</summary>

- Review references to elasticsearch and kibana 🟡

![image](https://user-images.githubusercontent.com/8913336/161306353-380ab372-6346-494e-8cb4-0a6a1eed00b4.png)
 
- Duplicated section for wazuh data volumes 🟡

![image](https://user-images.githubusercontent.com/8913336/161306253-b8a2b44c-2b9b-4fd9-88fe-3e702b187cdd.png)

![image](https://user-images.githubusercontent.com/8913336/161306291-9d507e33-0de3-4a2a-884d-eaa0a5577c20.png)

- As mentioned previously, we suggest adding a separate section for customizing certificates and securing containers that would be suitable for both single-node and multi-node.

</details>

**Comment by Spades0** [comment]
This issue has been reviewed. The test was done on the old version of the documentation. Issues have been resolved in [Installation alternatives - Deployment on Docker](https://docs.google.com/document/d/1oeYWlRQX8Dxco66ykO8dnBApxpS24Fgds0v5pwmomb8/edit#)
