### ISSUE TITLE
Improve documentation for stats files and Analysis engine

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-documentation#503]
Write more user-friendly documentation about how the statistical files work, and combine this explanation with the new multithreaded Analysis engine diagrams. Also, add a description for each stat field.

- [x] Correct typos.
- [x] Test different files in different virtual machines.
- [x] Write a more extensive doc about the statistical files.
- [x] Investigate about Analysis engine.
- [x] Improve the examples.
- [x] Write better doc about Analysis engine.

**Comment by JaoChaos** [comment]
Working on testing different statistical files in different machines to obtain better examples for the documentation.

Also, investigating the Analysis engine to improve its explanation.
