### ISSUE TITLE
" Grouping agents "  

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh-documentation#509]
Hello Team,

The paths for the default folder and for the agent.conf file must be completed (**/var/ossec/etc/shared/defaut** & **/var/ossec/shared/default/agent.conf**), also there's a typo the **agents.conf** should be **agent.conf**

**Comment by elwali10** [comment]
- Same modification for **"Integration with external APIs"** page

**Comment by JuanjiJG** [comment]
Done here: #514

Thanks @elwali10!

Regards,
Juanjo
