### ISSUE TITLE
GCP integration - Fix and improve guide documentation

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-documentation#5109]
# Google Cloud - Prerequisites 🔴

<details>

<summary>details</summary>

### Configuring GCP credentials 🔴

<details>

<summary>Configuring GCP credentials</summary>

- Create a service account 🟡 

**NOTE: I think it would be helpful for all users to add screenshots of how to create the Service Account.**

![image](https://user-images.githubusercontent.com/8913336/165070919-27f95aec-040c-4c12-ad28-ba0438038990.png)

**NOTE: Storage legacy bucket writer not found**

![image](https://user-images.githubusercontent.com/8913336/165078039-591e7cd1-869e-4ba2-ba7c-f3ac043896d7.png)

Duplicated screenshot  🔴 

![image](https://user-images.githubusercontent.com/8913336/165078531-23717be7-68fd-469e-a7dc-3f14a55838d1.png)

**NOTE: Outdated screenshots - create private key**

</details>

### Configuring Google Cloud Pub/Sub 🟡 
<details>

<summary>Configuring Google Cloud Pub/Sub</summary>

**NOTE: Outdated screenshots - create topic**

![image](https://user-images.githubusercontent.com/8913336/165081573-667bed13-c7fe-49f7-b3d8-bdeaccb1ee64.png)

**NOTE: The create subscription section is not needed, the subscription is automatically created when the topic is created.**

![image](https://user-images.githubusercontent.com/8913336/165081700-063c870e-d4dc-4505-853f-501afef456b0.png)

**NOTE: Outdated screenshots - create log sink**

![image](https://user-images.githubusercontent.com/8913336/165084240-853716c0-595b-4731-83d4-f475b375a8fc.png)

</details>

</details>

# Google Pub/Sub 🔴

<details>

<summary>details</summary> 

I would prioritize this section, following the guide the Wodle has not yet been configured and it could be good to do it earlier.

![image](https://user-images.githubusercontent.com/8913336/165085816-83b5bcd6-6044-419e-a718-c3b0ef280bed.png)

I don't see an intuitive way to fill in the configuration. It would be nice to show in screenshots where to get the information to fill in the Wodle.

![image](https://user-images.githubusercontent.com/8913336/165090883-3e2f61cb-8c26-4cbe-8457-7500d095babe.png)

I think it would be interesting for users to have screenshots of the entire configuration, Wodle fields included and additionally have examples of how to generate alerts to verify that the integration has been set up correctly.

</details>

# Google Cloud Storage 🔴 

<details>

<summary>details</summary>

- Wrong configuration example 🔴 

![image](https://user-images.githubusercontent.com/8913336/165134656-f14b15e1-067e-4b29-b0ac-c4954f1d8025.png)

![image](https://user-images.githubusercontent.com/8913336/165134730-fdc295d7-7b64-4dbc-951c-041fa9c92cb8.png)

</details>

## Related issue

https://github.com/wazuh/wazuh/issues/13221

**Comment by CarlosRS9** [comment]
The issue with the Storage Legacy Bucket write role will be reviewed and fixed in #4996.

The reference pages for gcp-bucket and gcp-pubsub will be reviewed and updated in #5699.

The review of the existing screenshot and the addition of new ones will be carried out in https://github.com/wazuh/wazuh-documentation/issues/5700.
