### ISSUE TITLE
Update download link in wazuh-labs windows agent install

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-documentation#511]
Being new I'm not sure if this is a page to be updated or how it's supposed to be different from the main installation guide [page on installing the windows agent](https://github.com/wazuh/wazuh-documentation/blob/master/source/installation-guide/installing-wazuh-agent/wazuh_agent_windows.rst) (maybe they're due merging).

[The build-lab version](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/build-lab/install-windows-agent.rst) points to version 3.1.0.1. This should be either updated or made to point to the [packages page](https://github.com/wazuh/wazuh-documentation/blob/master/installation-guide/packages-list/index.rst).

**Comment by JuanjiJG** [comment]
Hello @jctello,

The `Learning Wazuh` documents are still not ready, but we keep in mind they need an update to the latest available Wazuh version. You can check out [this issue](https://github.com/wazuh/wazuh-documentation/issues/341) to keep track of the progress.

I'll proceed to close this issue to avoid duplication. Nevertheless, thanks a lot for reporting this! It's really appreciated! :smile:

Regards,
Juanjo
