### ISSUE TITLE
Missing Docker for Desktop (Windows + macOS) install procedure

### ISSUE THREAD

**Issue by RamiroRD** [wazuh/wazuh-documentation#5110]
| Related issue|
|---|
| wazuh/wazuh#13224|

## Description
In the Docker installation section of the documentation, the guide only explains how to install Docker on Linux distros
https://documentation-dev.wazuh.com/current/deployment-options/docker/docker-installation.html.

This wouldn't be a problem if we simply didn't want users to do deploy Wazuh on Docker for desktop but then in the [Wazuh Deployment Section ](https://documentation-dev.wazuh.com/current/deployment-options/docker/wazuh-container.html#wazuh-docker-deployment) it goes on to explain how to fine-tune some Docker settings on Linux, Windows, and macOS (which is incorrectly listed as "OSX")

**Comment by Spades0** [comment]
Deployment on macOS and Windows was removed from the document to make users deploy primarily on Linux environments. So this issue can be closed.
