### ISSUE TITLE
Incorrect Docker for Desktop (macOS) fine tuning procedure

### ISSUE THREAD

**Issue by RamiroRD** [wazuh/wazuh-documentation#5113]
| Related issue|
|---|
| wazuh/wazuh#13224|
## Description
[This part](https://github.com/wazuh/wazuh-docker/issues/619) of the Wazuh Docker Deployment guide has two problems:
1. It refers to macOS as OSX instead of macOS
2. The procedure for incrementing the Docker machine RAM size is slightly incorrect. According to the guide, the RAM slider can be found on "Preferences -> Advanced", while it should be "Preferences -> Resources -> Advanced":
![Screen Shot 2022-04-26 at 10 18 40](https://user-images.githubusercontent.com/6182640/165308825-a8f6a4d1-bd1d-428f-8c4f-9b245440dde1.png)

**Comment by Spades0** [comment]
Installation on macOS was removed from the document to make users deploy primarily on Linux environments. So this issue should be closed.
