### ISSUE TITLE
Fix architecture support for Docker installation section

### ISSUE THREAD

**Issue by HanesSciarrone** [wazuh/wazuh-documentation#5114]
| Related issue|
|---|
| wazuh/wazuh#13224|

## Description

While following the steps in the Docker installation section [Link](https://documentation-dev.wazuh.com/current/deployment-options/docker/docker-installation.html) we saw that the documentation talks about 64 bits OS instead of architecture types. This description is very generic because includes `amd64` and `aarch64` architecture. Actually, the docker images delivered by Wazuh only support `amd64`. The documentation should talk of amd64 instead of 64 bits OS.

![image](https://user-images.githubusercontent.com/58960358/165308936-04c94677-4772-4225-b698-e9fc25bcd2ec.png)

**Comment by s-ocando** [comment]
Fixed in https://github.com/wazuh/wazuh-documentation/pull/5154.
