### ISSUE TITLE
Splunk installation - Update guide

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-documentation#5118]
# Splunk installation guide 🔴 

<details>

<summary>details</summary>

## Install Splunk indexer 🔴 

<details>

<summary> Install Splunk indexe</summary>

- outdated versions 🔴 

Latest Splunk version = 8.2.6

![image](https://user-images.githubusercontent.com/8913336/165286950-fffe5bf3-6899-4903-a41d-aca49aae9622.png)

![image](https://user-images.githubusercontent.com/8913336/165287039-ebb1465a-02e4-43e9-9cf1-caf4bb0ec785.png)

</details>

## Install Splunk forwarder 🔴 

<details>

<summary>Install Splunk forwarder</summary>

- outdated versions 🔴 

Latest Splunk version = 8.2.6

![image](https://user-images.githubusercontent.com/8913336/165290281-4342ce7b-ee53-4648-9a2a-ff57a7bb27fc.png)

![image](https://user-images.githubusercontent.com/8913336/165291106-48eb6a32-aec5-40f9-951b-1e7796dc3817.png)

</details>

</details>

## Related issue

https://github.com/wazuh/wazuh/issues/13240

**Comment by xrisbarney** [comment]
[Here](https://documentation-dev.wazuh.com/current/upgrade-guide/compatibility-matrix/index.html), The Splunk app for Wazuh is compatible with only those versions.
