### ISSUE TITLE
Outdated `RBAC-create and map users` section for the Wazuh Dashboard

### ISSUE THREAD

**Issue by vicferpoy** [wazuh/wazuh-documentation#5120]
|Branch|
|---|
|4.3-rc|

During the [manual tests for the Wazuh Dashboard (`v4.3.0-RC6`)](https://github.com/wazuh/wazuh/issues/13226), I tried to follow the [documentation](https://documentation-dev.wazuh.com/4.3-rc/) to add a new internal user with RBAC restrictions.

Currently, we only have a section for this and it is located under the `User manual > Wazuh Kibana plugin > RBAC - create and map users`. In this page, the last step asks the user to change the configuration to add `run_as: true` but it does not take into account that if you are using the Wazuh Dashboard, that path is not correct:

![image](https://user-images.githubusercontent.com/37274979/165484727-d3f30b67-43be-42d3-920b-758543fb33a4.png)

Quoting from the [original post](https://github.com/wazuh/wazuh/issues/13226#issuecomment-1109869994) with the report:

> This section belongs to Wazuh Kibana plugin but I am using the Wazuh Dashboard. The wazuh.yml configuration file is located in different paths. In my case, it is in /usr/share/wazuh-dashboard/data/wazuh/config/wazuh.yml. There is no other documentation section (as far as I know) where this whole process is documented using the Wazuh Dashboard with the correct paths.
 We should either add a new section for the Wazuh Dashboard or update the Wazuh Kibana plugin one with additional information.

**Comment by gdiazlo** [comment]
Being worked on https://github.com/wazuh/wazuh-kibana-app/issues/3907

**Comment by snaow** [comment]
Taking out from Release 4.3.0 project since it is being tracked (is included) already on issue: https://github.com/wazuh/wazuh-kibana-app/issues/3907

**Comment by davidjiglesias** [comment]
Already fixed in v4.3.0
