### ISSUE TITLE
Suggestions for Deployment with ansible documentation

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-documentation#5132]
During the [ansible deployment](https://github.com/wazuh/wazuh-qa/issues/2821) I have followed the documentation page and I proposed the following change:

 <details>

<summary> SSH service should be replaced as a root</summary>

![sudo](https://user-images.githubusercontent.com/11089305/165558581-18e13ee2-f278-4760-922c-cd78920ca8ca.png)

<details>

**Comment by xrisbarney** [comment]
Noted. This has been updated in the documentation [here ](https://docs.google.com/document/d/1sA4rsGDVxgCmeBJ9od4Zopl4ZVilSbAcwPoLikEj7to/edit?disco=AAAAYlJEHF8) and will be migrated.
