### ISSUE TITLE
Review "Integration with external APIs" 

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh-documentation#518]
Hello Team,

- [x] I think there must be more content about the **PagerDuty** integration, at least what the user should expect to see to know that the integration went correctly (an example of the alerts in PagerDuty dashboard like the ones for VirusTotal).

- [x] In the configuration paragraph the following sentence should be modified from : 

  > Integrations are configured in the **etc/ossec.conf** file which is located inside your Wazuh installation directory

  Into Something like this:

  >  Integrations are configured in the **ossec.conf** file which is located inside your Wazuh installation directory ( **/var/ossec/etc/** )

https://documentation.wazuh.com/3.x/user-manual/manager/manual-integration.html?highlight=integrator

### Related PRs

#732

**Comment by JuanjiJG** [comment]
We'll continue improving this documentation in #735
