### ISSUE TITLE
Add Solaris to syscollector´s compatibility matrix

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh-documentation#5195]
Hello, 

Solaris OS name is reported by syscollector and should be included in the matrix https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html#compatibility-matrix : 
![image](https://user-images.githubusercontent.com/16334770/166921008-f1982adb-3837-47cb-bcfb-4b093f71e8af.png)

Regards,
Elwali

**Comment by javimed** [comment]
![Image](https://github.com/wazuh/wazuh-documentation/assets/47069802/4df018ad-9844-4a7c-b6ec-02e74790b7c9)
