### ISSUE TITLE
Rework Puppet documentation

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-documentation#522]
The current Puppet documentation needs a complete rework to make it more useful, usable and easy to understand.

The development branch for this task is [`puppet-documentation`](https://github.com/wazuh/wazuh-documentation/tree/puppet-documentation).

Regards,
Juanjo

**Comment by JaoChaos** [comment]
I'm reading this part documentation to find how to improve it.
As I can see, there are many code blocks without explanation in the installing section.
The `Setting up your Puppet Certificates` is short and has typos for a fix.
