### ISSUE TITLE
The migration guide does not specify to change the jvm settings

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh-documentation#5224]
Hello Team,
When I migrate from ODFE to Wazuh Indexer, the Wazuh Indexer installation packages installs a new jvm.options file, with default configurations (`-Xms1g`, `-Xmx1g`) and the services do not start in certain environments.

The solution would be specify the change before the starting of the Wazuh Indexer services.
Thank you in advance.

**Comment by s-ocando** [comment]
Added a step to port any custom configurations, for example, the  ``-Xms`` and ``-Xmx`` settings, from ``/etc/elasticsearch/jvm.options`` to ``/etc/wazuh-indexer/jvm.options``. https://github.com/wazuh/wazuh-documentation/commit/268ec80ba8ad5e9babd8a4842162babab8b82aa8
