### ISSUE TITLE
When deploying Wazuh on Kubernetes, the default credentials don't work as specified in the documentation.

### ISSUE THREAD

**Issue by eacherkan-aternity** [wazuh/wazuh-documentation#5226]
Under Installation alternatives / Deployment on Kubernetes / Deployment / Verifying the deployment, the documentation says:
> The Wazuh dashboard will be accessible on `https://localhost:8443`.
> The default credentials are `admin:admin`.

When following that guide (on a local Minikube environment), I wasn't able to log in with `admin:admin`. After looking around in the `wazuh-kubernetes` repository, I found a reference to the password `SecretPassword` in [`elastic-cred-secret.yaml`](https://github.com/wazuh/wazuh-kubernetes/blob/master/wazuh/secrets/elastic-cred-secret.yaml#L16), and I was able to log in with the credentials `admin:SecretPassword`.

**Comment by Dwordcito** [comment]
Hi, I hope you are well!

Thanks for the report, I'm going to create a PR to solve it! thank you!
