### ISSUE TITLE
Add Wazuh API to Splunk installation guide

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh-documentation#523]
Hi team! 

I'm trying to install **Splunk** app following the documentation but at [this point](https://documentation.wazuh.com/3.x/installing-splunk/splunk_wazuh.html#installation) it assumes that the user has installed the **Wazuh API** previously.

I think we must specify that it sould be installed in order to use the Splunk application.

Best regards!
Cerv1

**Comment by JuanjiJG** [comment]
Done here: #527

Thanks for your suggestion @Cerv1! :smile:

Regards,
Juanjo
