### ISSUE TITLE
Wazuh sources installation missing `apt-get update`

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#5233]
Using fresh AWS Ubuntu virtual machines, following the guide https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-server/index.html, we noticed that it's necessary for an `apt-get update` before installing all necessaries packages.

**Comment by jnasselle** [comment]
Similar issue but using Vagrant https://github.com/wazuh/wazuh-documentation/issues/3152

**Comment by ace-109** [comment]
This issue has been reviewed and the installation from sources guide has been updated to include the `apt-get-update` command.
