### ISSUE TITLE
inexisting py extension in update_ruleset.py

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-documentation#524]
Minor change but that could save some users slight confusion:

In [the ruleset update page](https://github.com/wazuh/wazuh-documentation/blob/3.7-upgrade-revision/source/user-manual/ruleset/update.rst) `update_ruleset.py` is mentioned. 

However the actual file has no extension (`/var/ossec/bin/update_ruleset`)

**Comment by JuanjiJG** [comment]
Done here: #526 

Thanks @jctello! :smile:

Regards,
Juanjo
