### ISSUE TITLE
Fix wazuh-kibana-app repository link in wazuh kibana plugin packages list

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-documentation#5249]
The link displayed at the bottom of the kibana plugin package list table opens the wazuh-kibana-app repository under the tag v4.2.5-7.10.2. This should be updated to an updated tag as this repository tag only shows up to version 4.2.5.

![image](https://user-images.githubusercontent.com/14913942/169149995-0c5f74af-3ff7-4a0c-8d4b-55293a339bb3.png)

- Opened github url: https://github.com/wazuh/wazuh-kibana-app/tree/v4.2.5-7.10.2#wazuh---kibana---open-distro-version-compatibility-matrix

This error is because the link is hardcoded:

![image](https://user-images.githubusercontent.com/14913942/169150479-425b1775-5d64-4645-bd1e-48342ac5468b.png)

`I have not been able to find in the v4.3.1_x tags a compatibility table similar to the one used in 4.2.5`

Regards, Raúl.

**Comment by s-ocando** [comment]
Fixed: https://github.com/wazuh/wazuh-documentation/commit/5fa3d884b2d88ff825c3a8417872a78d2fce5107
