### ISSUE TITLE
Consider adding OpenSearch in compatibility matrix

### ISSUE THREAD

**Issue by dariommr** [wazuh/wazuh-documentation#5308]
Hello Team,
Since many users make use of OpenSearch from other sources than the Wazuh repositories, and having in mind the Wazuh Indexer has different versioning than Opensearch, I believe it is useful to publish the information about the compatibility of the Wazuh App with the Opensearch Dashboard.

Thank you in advance!

**Comment by AlexRuiz7** [comment]
https://github.com/wazuh/wazuh-dashboard/wiki/Compatibility
