### ISSUE TITLE
Wazuh Dasboard step-by-step installation - Outdated references to Kibana

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-documentation#5317]
| Reference branch |
|---|
| 4.3 branch on v4.3.4 |

# Description

Currently there's one Kibana reference, when Wazuh Dashboard should be used

https://documentation-dev.wazuh.com/4.3/installation-guide/wazuh-dashboard/step-by-step.html#configuring-the-wazuh-dashboard

![image](https://user-images.githubusercontent.com/1791430/172257850-6a132d5f-fbba-489b-a0df-b45cd3f33e86.png)

**Comment by s-ocando** [comment]
Fixed https://github.com/wazuh/wazuh-documentation/commit/f29c8dabe25a21e08eb85c5ea08eb5e53c9c8551. Thank @jnasselle for reporting!
