### ISSUE TITLE
Wazuh Dashboard step-by-step installation guide does not provide default `admin` password

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-documentation#5319]
| Reference branch |
|---|
| 4.3 branch on v4.3.4 |

# Description

Currently, there's no reference for `admin_password` on Wazuh Dashboard Step-by-step installation guide

https://documentation-dev.wazuh.com/4.3/installation-guide/wazuh-dashboard/step-by-step.html#starting-the-wazuh-dashboard-service

![image](https://user-images.githubusercontent.com/1791430/172389736-51c10ab6-dfe1-4932-b7e1-b14cd11bd023.png)

**Comment by s-ocando** [comment]
Fixed https://github.com/wazuh/wazuh-documentation/commit/5b20a7266ef4f1ee204090282b73bf7678be807b. 

![image](https://user-images.githubusercontent.com/61882981/172555790-24382f78-77ee-4a31-ae9b-10b780d9b824.png)
