### ISSUE TITLE
Improve the notes of "Install Wazuh App for Splunk" section.

### ISSUE THREAD

**Issue by Nicogp** [wazuh/wazuh-documentation#5320]
Hello team, 

testing the installation of Wazuh and Splunk found the following inconsistencies in the notes of the [**Install the Wazuh app for Splunk**](https://documentation.wazuh.com/current/deployment-options/splunk/splunk-app.html) section.

First, in the section **[Install the Wazuh app for Splunk in an all-in-one](https://documentation.wazuh.com/current/deployment-options/splunk/splunk-app.html#install-the-wazuh-app-for-splunk-in-an-all-in-one-architecture)** architecture we see how it is with double "#" and highlighted:
![image](https://user-images.githubusercontent.com/13004400/172390694-524011e9-50f2-4d8c-a91c-70fce398f794.png)
when in other parts with similar notes the double "#" is not added or highlighted:
https://documentation.wazuh.com/current/deployment-options/splunk/splunk-basic.html#install-and-configure-splunk-indexer
![image](https://user-images.githubusercontent.com/13004400/172391145-ec920233-c4fe-422e-b667-70ba787b541a.png)

Second, in a note one of the fields is empty:
https://documentation.wazuh.com/current/deployment-options/splunk/splunk-app.html#install-the-wazuh-app-for-splunk-in-a-minimal-distributed-architecture
![image](https://user-images.githubusercontent.com/13004400/172391986-a8d6bafb-2f07-4317-9604-74750b58c91f.png)

**Comment by Arcapas** [comment]
Work with this issue on the PR https://github.com/wazuh/wazuh-documentation/pull/5321

**Comment by Arcapas** [comment]
Issue closed with PR https://github.com/wazuh/wazuh-documentation/pull/5321
