### ISSUE TITLE
Invalid multi_path '/var/ossec/etc/vulnerability/nvd': 'feed not found'

### ISSUE THREAD

**Issue by ym2011** [wazuh/wazuh-documentation#5347]
hi, i have configured it following [this document ](https://documentation.wazuh.com/4.3/user-manual/capabilities/vulnerability-detection/offline-update.html#national-vulnerability-database). the  configuration  is below : 
 
    <provider name="nvd">
      <enabled>yes</enabled>
      <path>/var/ossec/etc/vulnerability/nvd/nvd-feed.*json$</path>
      <update_interval>7d</update_interval>
    </provider>
 however,this are  some errors  in the log, just like below:
Jun 14, 2022 @ 15:44:04.000 wazuh-modulesd:vulnerability-detector INFO  (5472): Vulnerability scan finished.
Jun 14, 2022 @ 15:44:03.000 wazuh-modulesd:vulnerability-detector INFO  (5430): The update of the 'JSON Red Hat Enterprise Linux' feed finished successfully.
Jun 14, 2022 @ 15:44:03.000 wazuh-modulesd:vulnerability-detector INFO  (5400): Starting 'National Vulnerability Database' database update.
Jun 14, 2022 @ 15:44:03.000 wazuh-modulesd:vulnerability-detector ERROR  (5551): Invalid multi_path '/var/ossec/etc/vulnerability/nvd': 'feed not found'
Jun 14, 2022 @ 15:44:03.000 wazuh-modulesd:vulnerability-detector INFO  (5400): Starting 'Microsoft Security Update' database update.
Jun 14, 2022 @ 15:44:03.000 wazuh-modulesd:vulnerability-detector INFO  (5430): The update of the 'Microsoft Security Update' feed finished successfully.
Jun 14, 2022 @ 15:44:03.000 wazuh-modulesd:vulnerability-detector ERROR  (5513): CVE database could not be updated.
Jun 14, 2022 @ 15:44:03.000 wazuh-modulesd:vulnerability-detector INFO  (5431): Starting vulnerability scan.
Jun 

after I do some tries , I solve this problem by modifying the  configuration below : 
 
    <provider name="nvd">
      <enabled>yes</enabled>
      <path>/var/ossec/etc/vulnerability/nvd/nvd-feed.*.json.gz</path>
      <update_interval>7d</update_interval>
    </provider>
after token effect of the change,  the log is : 
Jun 14, 2022 @ 16:25:55.000 wazuh-modulesd:vulnerability-detector INFO  (5472): Vulnerability scan finished.
Jun 14, 2022 @ 16:25:54.000 wazuh-modulesd:vulnerability-detector INFO  (5430): The update of the 'National Vulnerability Database' feed finished successfully.
Jun 14, 2022 @ 16:25:54.000 wazuh-modulesd:vulnerability-detector INFO  (5400): Starting 'Microsoft Security Update' database update.
Jun 14, 2022 @ 16:14:59.000 wazuh-modulesd:vulnerability-detector INFO  (5430): The update of the 'JSON Red Hat Enterprise Linux' feed finished successfully.
Jun 14, 2022 @ 16:14:59.000 wazuh-modulesd:vulnerability-detector INFO  (5400): Starting 'National Vulnerability Database' database update.
Jun 14, 2022 @ 16:14:16.000 wazuh-modulesd:vulnerability-detector INFO  (5430): The update of the 'Red Hat Enterprise Linux 8' feed finished successfully.

therefore , there maybe  is a mistake  in  [this document ](https://documentation.wazuh.com/4.3/user-manual/capabilities/vulnerability-detection/offline-update.html#national-vulnerability-database)
To update locally, the path to those files must be indicated by a regular expression as such:
<provider name="nvd">
    <enabled>yes</enabled>
    <path>/local_path/nvd-feed.*json$</path>
    <update_interval>1h</update_interval>
</provider>

_nvd-feed.*json$_   should be  _nvd-feed.*.json.gz_ or _nvd-feed.*.json$_

**Comment by ym2011** [comment]
thanks for your reply .

**Comment by jnasselle** [comment]
You're welcome! I will reopen this issue in order to link it to the PR
