### ISSUE TITLE
Create a copy of a user profile via API?

### ISSUE THREAD

**Issue by robinlennox** [wazuh/wazuh-documentation#5365]
Can you add this to the Wazuh Documentation for how to create a wazuh user via the API?
```sh
curl -k -u "INDEXER_USER:INDEXER_PASSWORD" -XPUT -H 'Content-type: application/json' "https://localhost:9200/_opendistro/_security/api/internalusers/USERNAME_TO_CREATE" -d '{"password": "NEW_USER_PASSWORD", "opendistro_security_roles": ["kibana_user", "Include required ones"]}'
```
Others might find it useful.

Also is it possible to create a copy of the read only group wazuh_ui_user via the API rather then editing: `/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/roles_mapping.yml`

I'd like to create a user via the API and add that user to the wazuh_ui_user group but I'm getting the error `{"status":"FORBIDDEN","message":"Resource 'wazuh_ui_user' is read-only."}`. I've been told by copying the `wazuh_ui_user` this should allow me to add the user to a group with access to the Wazuh GUI.

**Comment by AlexRuiz7** [comment]
There is extensive [documentation on OpenSearch](https://opensearch.org/docs/latest/security/access-control/users-roles/) about how to create users and roles.

You can also [clone existing reserved resources](https://github.com/wazuh/wazuh-packages/issues/1059#issuecomment-2115810801) for your own use.
