### ISSUE TITLE
Update syscheck check_sum attribute 

### ISSUE THREAD

**Issue by Cerv1** [wazuh/wazuh-documentation#539]
It does not take into account the new option `check_sha256sum` but it's listed bellow [here](https://github.com/wazuh/wazuh-documentation/blob/3.7/source/user-manual/reference/ossec-conf/syscheck.rst)

**Comment by JuanjiJG** [comment]
Done here: #540.

Thank you @Cerv1 for reporting this! :smile:

Regards,
Juanjo
