### ISSUE TITLE
[not_same_agent] is deprecated but still shown in Rules syntax documentation

### ISSUE THREAD

**Issue by ArielIvanOjeda** [wazuh/wazuh-documentation#5426]
Hi Team,

The Wazuh Rules syntax documentation for 4.2 and 4.3 is listing the option "not_same_agent" as available but the same has been deprecated in 3.13 as stated in version 4.1 of the same documentation.

https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#not-same-agent (4.3)
https://documentation.wazuh.com/4.2/user-manual/ruleset/ruleset-xml-syntax/rules.html#not-same-agent (4.2)
https://documentation.wazuh.com/4.1/user-manual/ruleset/ruleset-xml-syntax/rules.html#not-same-agent (4.1)

When using this option, a user noticed these messages in the Wazuh manager's log. I ran a test in my lab and I got the same:

```
2022/07/05 13:24:44 wazuh-analysisd: WARNING: Detected a deprecated field option for rule, not_same_agent is not longer available.
2022/07/05 13:24:44 wazuh-analysisd: INFO: Total rules enabled: '6332
```

This causes confusion as the option is listed as available, but cannot be used.

Best regards,

Ariel Ojeda.

**Comment by javimed** [comment]
Related issue #4203
