### ISSUE TITLE
Add as a note the necessary parameter for indexer-security-init.sh when configuring the cluster with DNS name

### ISSUE THREAD

**Issue by c-bordon** [wazuh/wazuh-documentation#5428]
This request arises from this community:
https://groups.google.com/g/wazuh/c/OOrtG9XSX-M

You need to add a note at this step:
https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html#cluster-initialization

For, in the case of configuring the cluster using DNS name, the command must be executed with the parameter: -ho

example:
`/usr/share/wazuh-indexer/bin/indexer-security-init.sh -ho wazuhindexer1.domain.name`

**Comment by javimed** [comment]
Related issue: https://github.com/wazuh/wazuh-packages/issues/1789

**Comment by okynos** [comment]
As @javimed mentioned in this PR https://github.com/wazuh/wazuh-packages/pull/1823 we have solved the problem of including the `-ho` flag to manage DNS names. Thanks all for your contribution. Closing. Feel free to open it if any matter approach.
