### ISSUE TITLE
Include OPENSEARCH_PATH_CONF in OpenSearch binary calls

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-documentation#5484]
Hello team,

From https://github.com/wazuh/wazuh-indexer/issues/227 we have detected that some users get an error related to their variable configuration.
We want to include the `OPENSEARCH_PATH_CONF` variable definition. It could be made in different forms:
- Include the variable into the environment file
- Export the variable inside the working terminal
- Including the variable definition in each binary call (As mentioned in the given issue)

Regards.

**Comment by AlexRuiz7** [comment]
Not needed as the bug is not present in the `wazuh-indexer` fork.
