### ISSUE TITLE
Add "Create a custom dashboard" section to current documentation

### ISSUE THREAD

**Issue by maumrsms** [wazuh/wazuh-documentation#5511]
Hello team!

I noticed that we have no section for custom dashboard creation in our current documentation for Wazuh Dashboard when we already had it in the past for Opendistro: https://documentation.wazuh.com/4.2/user-manual/kibana-app/reference/custom-dashboard.html

The process remains the same still in Wazuh Dashboard+Wazuh Indexer. We should only update the screenshots.

## Creating Visualization
Go to the **Visualize** tab.
![image](https://user-images.githubusercontent.com/29696136/184009469-c46bed21-54ed-4a52-897d-f4436d4acce9.png)

Click on **Create new visualization**.
![image](https://user-images.githubusercontent.com/29696136/184009700-9deb0fae-dcf7-4ebe-b341-41844f100b06.png)

And select a visualization type among the ones available. As an example, we will be taking the **Horizontal Bar** chart, but it is essentially the same for other types of visualization.
![image](https://user-images.githubusercontent.com/29696136/184009840-ce4ddf2c-ddb5-4b27-8977-98786bc755fc.png)

Next step will be selecting the index that will be used as a data source. We can work with any index that we created previously, but generally, we will be working with **wazuh-alerts-***.
![image](https://user-images.githubusercontent.com/29696136/184009984-9a117402-bdde-4145-9f3a-1d0767663da6.png)

At this point, a graph will be generated. You can select a lapse of time to display the information related to that period. Click on the following dropdown menu, define it and then update your changes.
![image](https://user-images.githubusercontent.com/29696136/184010189-3101a7b1-1a1c-4254-8dd8-6a0d643685ea.png)

This chart can be configured to match your preferences. You can organize your data using **Metrics** and **Buckets**.
![image](https://user-images.githubusercontent.com/29696136/184010629-c52ae45d-af2f-4b45-84bb-e4e9dc01a83c.png)

**Metrics** section has options in order to quantify the data: Count, average, sum, max/min, etc.

**Buckets** are aggregations of data that are sorted according to your search criteria.

For this example, we will leave the Y-Axis as default (count) and we will modify the Buckets (X-Axis) to sort them according to the level of the rules that have been triggered.

To do so we will have to click on **X-Axis**:
![image](https://user-images.githubusercontent.com/29696136/184010862-c138b9e1-25cb-4e34-8024-2a44ba3b5844.png)

Select the **Terms** option in the **Select an aggregation** menu:
![image](https://user-images.githubusercontent.com/29696136/184011062-ee188006-3697-482a-bbcf-ae1afb16cbb5.png)

Now you will be able to select a **Field** to sort by (e.g. rule.level):
![image](https://user-images.githubusercontent.com/29696136/184011522-aca51ce9-34d6-4afa-887c-5ec8f0461ce5.png)

And, eventually, you will need to apply the changes to visualize them:
![image](https://user-images.githubusercontent.com/29696136/184011644-3fae3c19-406f-475e-baae-b395c7c67065.png)

Now you will be able to see a chart like this:
![image](https://user-images.githubusercontent.com/29696136/184011764-40ea5e4e-48b8-4756-9749-eacbc65a1273.png)

## Saving a Visualization
Once we have created a customized visualization, as we did in the previous section, we can save it by clicking on Save.
![image](https://user-images.githubusercontent.com/29696136/184011984-56a67963-6e9e-4957-9e9b-5a0ebefd56f7.png)

After that, set a name for it and confirm.
![image](https://user-images.githubusercontent.com/29696136/184012070-8fec4392-64d7-4f58-aa7b-e2184a1d8f83.png)

## Creating a Custom Dashboard
In order to create a customized dashboard we can reuse a saved visualization in the Dashboard section:
![image](https://user-images.githubusercontent.com/29696136/184012268-3ac658dd-4337-4efb-9e19-d6d174e721a9.png)

Just have to click on **Create a new dashboard**:
![image](https://user-images.githubusercontent.com/29696136/184012409-0dfc6669-43bf-4581-a88f-8716884fc955.png)

And then click on **Add**.
![image](https://user-images.githubusercontent.com/29696136/184012502-96b7974b-bee7-40aa-a0c2-f435ae30c213.png)

Now you can select a visualization to add among the ones you have saved. We will choose the bar chart that we created previously and then click on **Create new visualization**:
![image](https://user-images.githubusercontent.com/29696136/184012724-12ebc5ee-4d90-4e27-9a2a-4cc1e7619891.png)

You will be able to see the visualization added to the dashboard:
![image](https://user-images.githubusercontent.com/29696136/184012843-d843c702-c7ce-4ade-b90e-21c59896ee17.png)

You can keep adding visualizations to the dashboard following the same process so that it fits your preferences.
![image](https://user-images.githubusercontent.com/29696136/184014272-e14417ba-9da6-430e-b0e3-8044076044ae.png)

Once you have finished editing your dashboard you will need to save it by clicking **Save**.
![image](https://user-images.githubusercontent.com/29696136/184014380-bcdaf91e-55bf-4cf5-a393-3712a084ef11.png)

Set its name, description and save it:
![image](https://user-images.githubusercontent.com/29696136/184014499-24f4dd16-1f9c-4631-8083-c6f2d37094a1.png)

**Additional comments**
Performed all steps in Wazuh 4.3.6 - App revision 4307
![image](https://user-images.githubusercontent.com/29696136/184014763-7e2d610f-6629-4cdf-a473-84e8692ca7b3.png)

**Comment by gdiazlo** [comment]
This will be work as part of a future work being done by the content team.
