### ISSUE TITLE
wazuh indexer image is not correct

### ISSUE THREAD

**Issue by Kuldeep6392** [wazuh/wazuh-documentation#5528]
Hi Team,

Please check wazuh indexer image is not correct, please check.

https://documentation.wazuh.com/current/getting-started/components/wazuh-indexer.html

**Comment by s-ocando** [comment]
Hi @Kuldeep6392, 

Thanks for reporting it! At node 2, we've changed `R1` to `R2` as it should be. 

You can see the updated image here: 

![image](https://user-images.githubusercontent.com/61882981/186088433-3f8db87c-2d91-4e88-ac33-555a8fde8104.png)

Here's the commit with the update: https://github.com/wazuh/wazuh-documentation/commit/848e76b158b04e543595b6cbf315640a5d9e5ace. 

Thanks again for bringing this to our attention. I will close this issue, feel free to reopen if necessary.
