### ISSUE TITLE
Syscollector reference to "System Inventory"

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-documentation#553]
Hi team,
It would be useful to change the description of the syscollector wodle. https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/wodle-syscollector.html
In its description it says:
```
Configuration options of the Syscollector wodle for system monitoring.
```
But the section for syscollector in the Capabilities index is not "system monitoring", it's called "System Inventory".
So would be easier to connect both things by adding a link and changing the description to reference the correct capability.

Kind regards,
Miguel

**Comment by JuanjiJG** [comment]
Done here: #555

Thanks @migruiz4 for reporting this!

Regards,
Juanjo
