### ISSUE TITLE
Add breaking changes section in release notes

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#5532]
Hello team,

I'm opening this issue because users had difficulties finding the breaking changes of the recent 4.3 version which led to some problems during the upgrade.

It would be useful if we can add a section containing those changes so it would be easier to explain new concepts and changes in the upgrade before proceeding. Also, this can be added to the 4.3 release although is out because it will be useful for new users coming to this version.

Regards,

Miguel Casares

**Comment by s-ocando** [comment]
Due to the time elapsed, we consider that it is not necessary to modify the 4.3 release notes. 

However, we have come to an understanding with the development team that going forward, breaking changes will be included in the changelog and therefore in the release notes.
