### ISSUE TITLE
smtp_authentication

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-documentation#557]
In `user-manual/manager/manual-email-report/smtp_authentication.rst` where it says:

> 6. Test the configuration with:
    # echo "Test mail from postfix" | mail -s "Test Postfix" you@example.com

This will fail with normal mail providers (such as gmail) because it will attempt to send it from `$hostname@$hostdomain`. 

A more appropriate test would likely be:

    # echo "Test mail from postfix" | mail -s "Test Postfix" -r "you@example.com" you@example.com
Which will override the "From:" field.

**Comment by JuanjiJG** [comment]
Done here: #555 

Thanks @jctello for reporting this!

Regards,
Juanjo
