### ISSUE TITLE
Add Wazuh dashboard report dependencies needed to generate PDF reports

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-documentation#5573]
Related: https://github.com/wazuh/wazuh-packages/issues/1520

It is necessary to indicate that for the generation of Wazuh dashboard reports in the recommended systems in PDF format, the installation of the following dependencies must be carried out. 

- RPM (Red Hat/CentOS/Amazon Linux 2)

```
sudo yum install -y libnss3.so xorg-x11-fonts-100dpi xorg-x11-fonts-75dpi xorg-x11-utils xorg-x11-fonts-cyrillic xorg-x11-fonts-Type1 xorg-x11-fonts-misc fontconfig freetype ipa-gothic-fonts
```

In Red Hat systems, it is necessary to register the system through subscription, if it is not done the packages will not be found when installed, in this [comment](https://github.com/wazuh/wazuh-packages/issues/1520#issuecomment-1240928321) it is verified that through subscription the installation is carried out correctly, so it would be interesting to add a note about these systems.

- Debian

```
sudo apt install -y libnss3-dev fonts-liberation libfontconfig1
```

Failure to install these dependencies causes an error message in the WUI when trying to generate or download the report.

These are the dependencies indicated by the OpenSearch documentation itself:

- https://opensearch.org/docs/latest/dashboards/reporting/#troubleshooting
- https://github.com/opensearch-project/dashboards-reports/blob/main/dashboards-reports/rendering-engine/headless-chrome/README.md#additional-libaries

**Comment by Tostti** [comment]
Researched about extra dependencies in deb and rpm packages. 
Will be added to `wazuh-dashboard` repo in https://github.com/wazuh/wazuh-dashboard/pull/184

**Comment by Tostti** [comment]
Tested installing packages in clean environments. The dependencies apparently are no longer necessary to generate reports
