### ISSUE TITLE
`indexer-security-init.sh` script sets unsecure defaullt credentials

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-documentation#5578]
|Wazuh version|Install type|Action performed|Platform|
|---|---|---|---|
| 4.3.4 |  - | Install  | - |

Following the documentation for an [offline installation](https://documentation.wazuh.com/current/deployment-options/offline-installation.html) we ask the user to use `indexer-security-init.sh` to initialize the `wazuh-indexer`.
This script set the default credentials to admin:admin. At least the password should be randomly generated.

**Comment by s-ocando** [comment]
The step-by-step installation guide includes instructions for changing the default API and Wazuh indexer credentials: [Securing your Wazuh installation](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/step-by-step.html#securing-your-wazuh-installation).

On the other hand, the [Offline installation guide](https://documentation.wazuh.com/current/deployment-options/offline-installation.html) includes the following note: "It is highly recommended to change the default Wazuh indexer passwords. To perform this action, see the [Change the Wazuh indexer passwords](https://documentation.wazuh.com/current/user-manual/securing-wazuh/wazuh-indexer.html) section".

We will rework these [instructions](https://documentation.wazuh.com/current/installation-guide/wazuh-dashboard/step-by-step.html#securing-your-wazuh-installation) to include the [recent changes](https://github.com/wazuh/wazuh-packages/pull/1548) in the `wazuh-passwords-tool.sh` and include them in the Offline installation guide as well.

**Comment by s-ocando** [comment]
A rework of the "Securing your Wazuh installation"  was introduced in https://github.com/wazuh/wazuh-documentation/pull/5635. This rework takes into account the [recent changes](https://github.com/wazuh/wazuh-packages/pull/1548) introduced in the Wazuh passwords tool and simplifies the instructions to secure the Wazuh installation.

Next, we will include these instructions in the offline installation guide adapting them to the particular conditions of this type of installation.

**Comment by s-ocando** [comment]
We updated and simplified the "Securing your Wazuh installation" instructions in the step-by-step installation guide https://github.com/wazuh/wazuh-documentation/pull/5635 and included an adapted version in the Offline installation guide https://github.com/wazuh/wazuh-documentation/pull/5642.
