### ISSUE TITLE
Remote syslog section suggestions to be clearer

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#5583]
Regarding the section: https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-it-works.html#remote-syslog where the users configure Wazuh to receive logs via Syslog, I suggest the following improvements:

## The two options should be identifiable
![image](https://user-images.githubusercontent.com/3830293/190098910-b0857194-22c4-47e1-a337-ae70592be14b.png)

The section explains that exist two options to achieve the Syslog logs receiving. I think that separating the two options by bullets, subtitles, or similar could help to understand better the explained options. 

## `allowed-ips` label is mandatory
I noticed that, if I copy and paste the explained configuration removing the `allowed-ips` line, the configuration doesn't take effect. But no message is shown by Wazuh in `ossec.log`. A message could be great, meanwhile, the documentation could help by indicating the obligatoriness of the label.

**Comment by Arcapas** [comment]
Closed with PR https://github.com/wazuh/wazuh-documentation/pull/5630
