### ISSUE TITLE
Improvements for AWS wodle documentation

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-documentation#559]
Add several improvements to current AWS wodle documentation:

- [ ] "Storing AWS logs on S3", step 14 (Click on Add target button), seems to be not needed
- [ ] Split the documentation, the scroll is way too long.
- [ ] Reduce the amount of screenshot where possible, or maybe re-structure the documentation to use fewer screenshots or their size.
- [ ] Verify that the installation process works without problems.

**Comment by mgmacias95** [comment]
Hello @JuanjiJG,

I'd like to add a few more tasks:
- [ ] Add a note about encrypted buckets.
- [ ] Improve documentation in the use of roles and credentials.

Best regards,
Marta
