### ISSUE TITLE
Correction in mentioned MULTITENANCY configurations 

### ISSUE THREAD

**Issue by DhirajVarma** [wazuh/wazuh-documentation#5596]
## Description
This issue aims to make a correction in the `Multitenancy` module configuration at https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/multi-tenancy.html#configuration

## Changes
The config block is given at https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/multi-tenancy.html#configuration
```
opensearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: false
opensearch_security.multitenancy.tenants.preferred: ["Global", "Private"]
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
```

I think it should be:

```
opensearch.requestHeadersWhitelist: ["securitytenant","Authorization"]
opensearch_security.multitenancy.enabled: true
opensearch_security.multitenancy.tenants.preferred: ["Global", "Private"]
opensearch_security.readonly_mode.roles: ["kibana_read_only"]
``` 

## Justification
The set value should be changed to `true`, since multitenancy will only be enabled when it is set to `true`, not `false`.

**Comment by Arcapas** [comment]
I made this changes in the PR #5629.
