### ISSUE TITLE
Wrong name of group configuration file

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-documentation#561]
Hi, I saw that the current documentation is naming the `agent.conf` file as `agents.conf` [here](https://documentation.wazuh.com/current/user-manual/agents/grouping-agents.html).

Regards

**Comment by JuanjiJG** [comment]
Hello @manuasir,

This was fixed on https://github.com/wazuh/wazuh-documentation/pull/514 and it will be available with the next Wazuh release.

In any case, thanks a lot for reporting this!

Regards,
Juanjo
