### ISSUE TITLE
Fix minor errors in the GCP service documentation

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-documentation#5662]
## Description

Hi team, working on issue [#15100](https://github.com/wazuh/wazuh/issues/15100), related to GCP service e2e tests, I have found some things that could be clarified.

- [Creating a service account](https://documentation.wazuh.com/current/gcp/prerequisites/credentials.html#creating-a-service-account):
  - To add the `Storage Legacy Bucket Writer` role you need to have first created a custom role with its same permissions. There is an [issue](https://github.com/wazuh/wazuh-documentation/issues/4996) associated with this problem.

- Some examples shown on the Wazuh configuration related to `gcp-bucket` show some tags that should not, such as `project_id` and `subscription_name`:
  - https://documentation.wazuh.com/current/gcp/prerequisites/credentials.html#using-an-authentication-file
  - https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/gcp-bucket.html#configuration-example

**Comment by CarlosRS9** [comment]
The issue with the `Storage Legacy Bucket write` role will be reviewed and fixed in https://github.com/wazuh/wazuh-documentation/issues/4996.

The reference pages for `gcp-bucket` and `gcp-pubsub` will be reviewed and updated in https://github.com/wazuh/wazuh-documentation/issues/5699.
