### ISSUE TITLE
Update and improve guide to create a custom WPK package

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh-documentation#570]
Hello team,

Our actual guide to create custom WPK packages has some details that need to be fixed:

1. The 1st step description specifies Wazuh 3.2 will be downloaded but the command downloads Wazuh 3.4:
![image](https://user-images.githubusercontent.com/8604906/47909362-fe200100-de8f-11e8-8132-2b58b4704b40.png)
2. `unzip` is required to run the previous command but it's not specified anywhere (and, for example, it's not installed by default on Ubuntu 18).
3. The following command will fail if the actual directory is not `wazuh-3.2/src`:
![image](https://user-images.githubusercontent.com/8604906/47909481-522ae580-de90-11e8-9b2b-a452ac8317ac.png)
4. Missing dependencies: `automake`, `autoconf` and `libtool`, necessary to compile the agent.

Best regards,
Marta

**Comment by SitoRBJ** [comment]
Hello team,

Additionally, we could put a note referring to the character `*` of this section:

```
6. Compile the WPK package using your SSL certificate and key:

# contrib/agent-upgrade/wpkpack.py output/myagent.wpk path/to/wpkcert.pem path/to/wpkcert.key *
```

The char `*` indicates that we add all the contents of the directory to the WPK. It is possible to add unwanted files to the WPK.


Regards,

Alfonso

**Comment by alberpilot** [comment]
Hello team

  We need to specify that the path of the custom WPK must be under /var/ossec folder. Otherwise, the upgrade process doesn't work properly. 

Best regards,

**Comment by JuanjiJG** [comment]
All the suggestions are done here: #593

Thank you so much @mgmacias95 @SitoRBJ and @alberpilot for your reports! :smile:

Regards,
Juanjo
