### ISSUE TITLE
Wazuh Agent Never Connected

### ISSUE THREAD

**Issue by r-aju** [wazuh/wazuh-documentation#5716]
Hello Team, 

We have Wazuh Server deployed on AWS Kubernetes Cluster and running as pods, we are in process of trying to add an agent to the server and the status of an agent is that it says `never connected`.

One of the agent connects successfully, but the other agent connect fails and says `never connected`.
Since, this is hosted on AWS can we also add agents from different VPC's as well??

![image](https://user-images.githubusercontent.com/43216503/199019062-81d618be-5805-4829-a534-060e7b8c2ee4.png)

Also, attaching the logs of failed agent below with ossec.conf file

![image](https://user-images.githubusercontent.com/43216503/199020071-699b79a6-0319-47f3-9a71-7262e0680cba.png)
![image](https://user-images.githubusercontent.com/43216503/199020325-2144a269-c0a7-48ed-b62b-9b492d1819dc.png)

**Comment by mari0rh** [comment]
Hi @r-aju,

Can you verify first if the agent you want to monitor is reachable from the cluster where Wazuh Server is deployed? If not, please make the respective configuration at VPCs level to allow traffic between each other.

**Comment by r-aju** [comment]
@mari0rh , Thank you for the support, I was able to quantify and solve the above issue. 
There was firewall rule which was blocking the flow to traffic, we've edited with appropriate Security Groups and is now working.
