### ISSUE TITLE
301 link Suricata configuration file in learning Wazuh

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#5730]
The following link contains a wrong link to a Suricata config file: 
https://documentation.wazuh.com/current/learning-wazuh/suricata.html#set-up-suricata-on-your-linux-agent
command: `wget -O /etc/suricata/suricata.yaml http://www.branchnetconsulting.com/wazuh/suricata.yaml`. 
The link can be changed to https://packages.wazuh.com/4.3/suricata.yml.

**Comment by javimed** [comment]
It's been published. Thanks
