### ISSUE TITLE
Command should be run as `sudo` in Docker Deployment documentation

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-documentation#5749]
On Installation Alternatives -> Docker Deployment -> Docker Installation, at [documentation.wazuh.com](documentation.wazuh.com), the first command to be run is written:
```
$ sysctl -w vm.max_map_count=262144
```
With the `$` symbolising it could be run as any user, when in fact it should be run as `sudo`, at least for this kernel variable, as we can see running `$ sysctl -a`, where some characteristics are reserved for the super user.

The correct alternative is:
```
# sysctl -w vm.max_map_count=262144
```

**Comment by s-ocando** [comment]
This issue was fixed in https://github.com/wazuh/wazuh-documentation/pull/5759.
