### ISSUE TITLE
Add documentation section explaining how to process AWS custom logs

### ISSUE THREAD

**Issue by CarlosRS9** [wazuh/wazuh-documentation#5753]
This issue is related to https://github.com/wazuh/wazuh/issues/13577. The idea is to update the documentation to explain to the user that it is possible to process custom logs, both via S3 as detailed in https://github.com/wazuh/wazuh/issues/13577 and via CloudWatch Logs. We should consider creating a new page dedicated to this purpose, with examples of how to use it and making it clear that it is necessary to create custom rules, as well as adding a link to the documentation of the custom rules. It would also be interesting to update the table of supported services to refer to this functionality.

**Comment by Selutario** [comment]
Already done in:
- https://github.com/wazuh/wazuh-documentation/pull/6254
