### ISSUE TITLE
Wrong template url in Elastic Stack basic license installation

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-documentation#5781]
In [this](https://documentation-dev.wazuh.com/v4.4.0-alpha1/deployment-options/elastic-stack/distributed-deployment/elasticsearch-cluster/elasticsearch-single-node-cluster.html#elasticsearch-installation-and-configuration) section of the Elastic Stack basic license installation, on tag https://github.com/wazuh/wazuh-documentation/tree/v4.4.0-alpha1, the second step has a wrong url in the command. Current command is:
```
curl -so /etc/elasticsearch/elasticsearch.yml https://packages.wazuh.com/4.3/tpl/elastic-basic/elasticsearch.yml
```
and should be 
```
curl -so /etc/elasticsearch/elasticsearch.yml https://packages.wazuh.com/4.4/tpl/elastic-basic/elasticsearch.yml
```

**Comment by s-ocando** [comment]
@verdx thanks for reporting! This issue has been fixed https://github.com/wazuh/wazuh-documentation/commit/0950dacfb4690ac0b8a4455d03715f2e9e2ae97f.
