### ISSUE TITLE
Wrong url in Indexer installation asistant

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-documentation#5782]
# Description
In the section [wazuh-indexer/installation-assistant](https://documentation-dev.wazuh.com/v4.4.0-alpha1/installation-guide/wazuh-indexer/installation-assistant.html) on step [initial-configuration](https://documentation-dev.wazuh.com/v4.4.0-alpha1/installation-guide/wazuh-indexer/installation-assistant.html#initial-configuration) the URL is not correctly parsed, also check that the `yml` is `config.yml` instead of `wazuh-config.yml`

### Current
```bash
curl -sO https://packages.wazuh.com/|WAZUH_LATEST_MINOR|/wazuh-install.sh
curl -sO https://packages.wazuh.com/|WAZUH_LATEST_MINOR|/wazuh-config.yml
```

### Expected 
```bash
curl -sO https://packages.wazuh.com/4.4/wazuh-install.sh
curl -sO https://packages.wazuh.com/4.4/wazuh-config.yml
```

**Comment by s-ocando** [comment]
Hi @QU3B1M, thanks for reporting. 

This issue has been fixed. The version variable was updated https://github.com/wazuh/wazuh-documentation/commit/3cc1c389ea28fb69f678a45828ad0f1a42ab1aa0 and now it's correctly parsed, and the `wazuh-config.yml` file name was renamed: https://github.com/wazuh/wazuh-documentation/pull/5787. 

![image](https://user-images.githubusercontent.com/61882981/206220093-0bca8a00-a447-4037-ae8d-6658ea0c30c5.png)
