### ISSUE TITLE
Single Sign-On guide modifies a file that no longer exists

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-documentation#5784]
The integration of Single Sign On in Wazuh through all the Identity Providers listed in the [documentation](https://documentation-dev.wazuh.com/v4.4.0-alpha1/user-manual/wazuh-dashboard/single-sign-on/index.html) requires modifying multiple files that until v4.3.X existed inside this folder:
```
/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig/
```

However, it seems it disappeared in Wazuh v4.4.0, as reported in this issue:
- https://github.com/wazuh/wazuh/issues/15531

```
[root@localhost plugins]# ls /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig
ls: cannot access /usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig: No such file or directory
```

This makes it impossible to integrate those services, also causing an error that prevents access to the dashboard:
```
{"statusCode":500,"error":"Internal Server Error","message":"Internal Error"}
```

**PD:** I'm not sure if this is a documentation error or a Wazuh-indexer error.

**Comment by gdiazlo** [comment]
We have updated wazuh-indexer to be based on OpenSearch 2.3 instead of 1.2. On this release, the security plugin changed its configuration folder. Please see https://opensearch.org/docs/2.3/security-plugin/configuration/configuration/ 

We need to update the documentation accordingly.

**Comment by ace-109** [comment]
A new documentation is currently in the work for 4.4 with the new file path to `securityadmin` and `securityconfig`
