### ISSUE TITLE
Inconsistent format in Single Sign On documentation

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-documentation#5785]
## 1. Inconsistent format
The format in the documentation of Azure SSO seems inconsistent:
- [Azure Active Directory - Single sign-on](https://documentation-dev.wazuh.com/v4.4.0-alpha1/user-manual/wazuh-dashboard/single-sign-on/azure-active-directory.html)

For most steps, the substeps are divided using letters (a, b, c, etc). However, for point 7 bullet points are used instead.
![image](https://user-images.githubusercontent.com/23361101/204811461-cd90e2c3-9877-4dd7-a178-c6526072c692.png)
![image](https://user-images.githubusercontent.com/23361101/204811539-5d3bc125-2896-41e2-8c48-e4825fc79a01.png)

## 2. Other suggestions
The documentation for step 7 in [Okta configuration](https://documentation-dev.wazuh.com/v4.4.0-alpha1/user-manual/wazuh-dashboard/single-sign-on/okta.html#okta-configuration) says this:
> The parameters already obtained during the integration are:
> - `sp.entity_id`
> - `roles_key`
> - `kibana_url`

I think accompanying those keys with the example values that are used throughout that documentation page can make it easier to understand:
> These are the parameters already obtained during the integration. Remember that these values were used as an example, yours may be different:
> - **sp.entity_id:** `wazuh-saml`
> - **roles_key:** `Roles`
> - **kibana_url:** `https://<Your_Wazuh-Dashboard_URL>`

**Comment by s-ocando** [comment]
Hi @Selutario, 

Thank you for your suggestions! I wanted to clarify that there's a reason for this apparent inconsistency. Bulleted lists, like the one in step number seven, are used for unordered items. The listed items have no particular order and can be rearrange without issues. 

In contrast, the numbered lists include steps that must follow a given order.  

Regarding your suggestion to include example of the key values, I will mention it to @ace-109 who is working on updating this documentation.

**Comment by ace-109** [comment]
A rework of the okta section has been done which includes the examples for the parameters, it now includes a snippet of the parameters in the `config.yml` file too.
