### ISSUE TITLE
Update How to collect Windows logs including new sysmon and powershell rules

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-documentation#5802]
### Description

Some of the available eventchannel sources are not included in the [How to collect windows log documentation page](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html).
There are different channels defined in other documentation pages, for example in [location](https://documentation-dev.wazuh.com/v4.4.0-alpha1/user-manual/reference/ossec-conf/localfile.html#location), in which is used not included location values like `Microsoft-Windows-Windows Firewall With Advanced Security/Firewall`.

In addition, rules files do not include all existing rules. The documentation page [How to collect windows log documentation page](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html#windows-ruleset-redesign) present a map with all eventchannel Windows alerts ids and the rule files. However, it is not included in 0915-win-powershell_rules.xml. Also, it is required to add the [new Sysmon events](https://github.com/wazuh/wazuh/pull/13594) to the rule IDs interval

**Comment by fabamatic** [comment]
Requested changes to [How to collect windows log documentation page](https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-to-collect-wlogs.html):

In table under **Available channels and providers** please add:

Source | Channel location | Provider name | Description
-- | -- | -- | --
Powershell|Microsoft-Windows-PowerShell/Operational|Microsoft-Windows-PowerShell|This channel collects and audits Powershell activity

To the list of rules add powershell file:
Source | Rule IDs | Rule file
-- | -- | --
Powershell|91801 - 92000|0915-win-powershell_rules.xml

There are some new rules related to **detection**, not **collection**, not sure if they belong to this page as it describes how to collect windows event channel events. If needed they may be added in a new table, they should have a description text like "for Wazuh >= 4.4.0 the following detection rules are available:"

Source | Rule IDs | Rule file
Sysmon event 1|92000 - 92100|0800-sysmon_id_1.xml
Sysmon event 3|92101 - 92150|0810-sysmon_id_3.xml
Sysmon event 7|92151 - 92199|0820-sysmon_id_7.xml 
Sysmon Event 11|2200 - 92299|0830-sysmon_id_11.xml
Event channel detections|92650 - 92700|0840-win_event_channel.xml
Sysmon Event 13|92300 - 92399|0860-sysmon_id_13.xml
Sysmon Event 8|92400-92450|0870-sysmon_id_8.xml
Sysmon Event 10|92900 - 92950|0945-sysmon_id_10.xml
Sysmon Event 20|89501 - 89550|0950-sysmon_id_20.xml

**Comment by javimed** [comment]
We're not including here then that Sysmon events rules files table related to detection and not collection
