### ISSUE TITLE
Azure configuration missing steps and sections

### ISSUE THREAD

**Issue by cborla** [wazuh/wazuh-documentation#5803]
## Sequence missing
Point number 4 missing, the sequence repeats number 1 instead 4. [documentation link](https://documentation-dev.wazuh.com/v4.4.0-alpha1/azure/activity-services/active-directory/graph.html#giving-permissions-to-the-application)

## Giving the application access to the Log Analytics API
In [Giving the application access to the Log Analytics API](https://documentation-dev.wazuh.com/v4.4.0-alpha1/azure/activity-services/services/log-analytics.html#giving-the-application-access-to-the-log-analytics-api) section, It would be advisable to add more details to complete the configuration easily. for example it not includes following screen.
 
![workspace_role](https://user-images.githubusercontent.com/41765669/205755593-ca96adfa-92c9-4731-b1cc-aee5374fdc95.JPG)

**Comment by GGP1** [comment]
## Update

The point number 4 is already in [place](https://github.com/wazuh/wazuh-documentation/blob/master/source/cloud-security/azure/activity-services/entra/graph.rst#giving-permissions-to-the-application) and the image displaying the role assignment is already [present](https://github.com/wazuh/wazuh-documentation/blob/master/source/images/cloud-security/azure/log-analytics-workspace-5.png).

I therefore conclude that the requested changes were already made in previous releases and that this issue should be closed.
