### ISSUE TITLE
Lack of rbac documentation in wazuh 

### ISSUE THREAD

**Issue by Abhilash-sandupatla** [wazuh/wazuh-documentation#5805]
Hi, we do not have any documentation of managing RBAC in wazuh. Even though the community suggests checking OpenSearch rbac docs, it's better to have good docs enabling  RBAC + OIDC or LDAP.

**Comment by AlexRuiz7** [comment]
Documentation was added in recent versions.

![image](https://github.com/wazuh/wazuh-documentation/assets/15186973/74439eda-42c2-4969-8ef3-2454a4c9801f)
