### ISSUE TITLE
Add a symbolic link to the `puppetserver` binary

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-documentation#5828]
## Description

The deployment of Wazuh through Puppet indicates that it is necessary to install this tool both on CentOS/RHEL/Fedora and Debian/Ubuntu systems according to the user's need, however, there is a step that is carried out in this second case that is not indicated in the first one.

On installation on Debian/Ubuntu, the creation of two symbolic links is indicated:

```
ln -s /opt/puppetlabs/bin/puppet /bin
ln -s /opt/puppetlabs/server/bin/puppetserver /bin
```

On the other hand, in the first case, only the creation of the first symbolic link is indicated:

```
ln -s /opt/puppetlabs/bin/puppet /bin
```

This causes that during the creation of certificates, the `puppetserver ca list` command indicates an error as the link is not created.

### Documentation affected

- https://documentation.wazuh.com/current/deployment-options/deploying-with-puppet/setup-puppet/install-puppet-master.html

**Comment by Arcapas** [comment]
Closed with PR #5866.
