### ISSUE TITLE
Add TCP ports warning with Ansible Deployment

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh-documentation#5852]
While performing [[Release 4.4.0 - Alpha 2 - E2E UX Tests - Deployment with Ansible](https://github.com/wazuh/wazuh/issues/15768#top)](https://github.com/wazuh/wazuh/issues/15768#issuecomment-1366681683) testing, one of the issues that appear were that no TCP ports were open at the server side.
although this is not strictly a deployment issue, an end user might expect Ansible playbooks to take care of these sort of things.

A warning or note could be added to the documentation warning about environment conditions that could prevent the deployment to fully work, including TCP ports opening.

**Comment by alberpilot** [comment]
I would include an info note at the Ansible documentation beginning, explaining all ports needed and asking the user to configure their `iptables`, `firewalld`, `ufw`, `Security Groups`, or any other firewall.
