### ISSUE TITLE
Filebeat configuration should be corrected in Deployment with Ansible

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh-documentation#5855]
While executing tests for [
Release 4.4.0 - Alpha 2 - E2E UX Tests - Deployment with Ansible](https://github.com/wazuh/wazuh/issues/15768), an issue was discovered relating filebeat port configuration. 

[Symptom 1 - Alerts index error](https://github.com/wazuh/wazuh/issues/15768#issuecomment-1366760607)

[Symptom 2 - No events are visible](https://github.com/wazuh/wazuh/issues/15768#issuecomment-1366766958)

[Resolution](https://github.com/wazuh/wazuh/issues/15768#issuecomment-1367413826)

The documentation shows the following configuration for `wazuh-manage
r-oss.yml`:

```console
---
- hosts: managers
  roles:
    - role: ../roles/wazuh/ansible-wazuh-manager
    - role: ../roles/wazuh/ansible-filebeat-oss
      filebeat_output_indexer_hosts:
      - "<indexer-node-1>:9200"
      - "<indexer-node-2>:9200"
      - "<indexer-node-2>:9200"
```

The port should not be specified because it is added in the `filebeat.yml.j2` file:

```console
# Send events directly to Wazuh indexer
output.elasticsearch:
  hosts:
{% for item in filebeat_output_indexer_hosts %}
  - {{ item }}:9200
{% endfor %}
```

So, the documentation should propose the following content for `wazuh-manager-oss.yml`:

```console
---
- hosts: managers
  roles:
    - role: ../roles/wazuh/ansible-wazuh-manager
    - role: ../roles/wazuh/ansible-filebeat-oss
      filebeat_output_indexer_hosts:
      - "<indexer-node-1>"
      - "<indexer-node-2>"
      - "<indexer-node-2>"
```

**Comment by alberpilot** [comment]
The change will be done in the ansible issue: https://github.com/wazuh/wazuh-ansible/issues/869. Documentation changes are not necessary.
