### ISSUE TITLE
Fix Missing Dependencies to Agent instalation From Source Linux

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh-documentation#5864]
# Description

## CentOS 8.
When following [agent installation from source](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html)  on a fresh CentOS 8 distribution using Yum as a package manager, this error will appear:

> 
/usr/bin/ld: cannot find -lstdc++

This is due to the **yum-utils** package not being installed, this causes **yum-config-manager** to not be foundable therefore not allowing **libstdc++-static** to be installed.

#### Fix:
```
 # yum install yum-utils
```
 It needs to be added to the dependencies installation command.

### Notes
When trying to install dependencies on a fresh CentOS 8 docker container, this error will show up.

```
Error: Failed to download metadata for repo 'appstream': Cannot prepare internal mirrorlist: No URLs in mirrorlist
```

This is due to CentOS removing all packages for CentOS 8 official mirrors,
They were moved to https://vault.centos.org/

To fix this, before installing dependencies run the following:

```
# sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*

# sed -i -e "s|#baseurl=http://mirror.centos.org/|baseurl=http://vault.centos.org/|g" /etc/yum.repos.d/CentOS-*
```

## APT package manager
When following [agent installation from source](https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html) for a fresh ubuntu distribution using APT as Packet manager, this error will appear:
```
E: Unable to locate package
```
This is due to **apt** not being updated first.
```
# apt-get update
```
It needs to be added to the dependencies installation command.

**Comment by EduLeon12** [comment]
## Issue Update 

During the [Release 4.8.0 - Alpha 2 - E2E UX tests - SAML SSO](https://github.com/wazuh/wazuh/issues/21768), it was found that the Wazuh installation assistant also failed due to the package mirror list being moved.
This also needs to be fixed in the documentation to avoid further issues during the centOS-8 installations.

**Comment by rauldpm** [comment]
Moved to @wazuh/core project as they have the ownership
