### ISSUE TITLE
Required dependency for PDF reports

### ISSUE THREAD

**Issue by elwali10** [wazuh/wazuh-documentation#5877]
Hello Team, 

Downloading the PDF reports from the reporting module requires having `chromium` https://github.com/opensearch-project/reporting/releases/tag/chromium-1.12.0.0 installed in the machine where a Wazuh Dashboard resides to avoid having the below error: 

![image](https://user-images.githubusercontent.com/16334770/212295233-29b72e9b-36d9-4bc8-b2cd-2818a66807ad.png)

It would be useful to include that in the installation process:  `yum install chromium` or `apt install chromium`.

Hope it helps.

Regards,
Wali

**Comment by havidarou** [comment]
Closing as this should be fixed at a package level, and no documentation should be needed https://github.com/wazuh/wazuh-packages/issues/2041.
