### ISSUE TITLE
Running in LXD container ubuntu 22.04 fails

### ISSUE THREAD

**Issue by greenpdx** [wazuh/wazuh-documentation#5884]
I have no idea what is happening.

Jan 22 19:02:01 wazuh systemd[1]: Starting Wazuh-indexer...
Jan 22 19:02:11 wazuh systemd-entrypoint[4918]: WARNING: An illegal reflective access operation has occurred
Jan 22 19:02:11 wazuh systemd-entrypoint[4918]: WARNING: Illegal reflective access by io.protostuff.runtime.PolymorphicThrowableSchema (file:/usr/share/wazuh-indexer/plugins/opensearch-anomaly-detection/protostuff-runtime-1.7.4.jar) to field java.lang.Throwable.cause
Jan 22 19:02:11 wazuh systemd-entrypoint[4918]: WARNING: Please consider reporting this to the maintainers of io.protostuff.runtime.PolymorphicThrowableSchema
Jan 22 19:02:11 wazuh systemd-entrypoint[4918]: WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
Jan 22 19:02:11 wazuh systemd-entrypoint[4918]: WARNING: All illegal access operations will be denied in a future release
Jan 22 19:02:12 wazuh systemd-entrypoint[4918]: ERROR: [1] bootstrap checks failed
Jan 22 19:02:12 wazuh systemd-entrypoint[4918]: [1]: max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
Jan 22 19:02:12 wazuh systemd-entrypoint[4918]: ERROR: OpenSearch did not exit normally - check the logs at /var/log/wazuh-indexer/wazuh-indexer-cluster.log
Jan 22 19:02:14 wazuh systemd[1]: wazuh-indexer.service: Main process exited, code=exited, status=78/CONFIG
Jan 22 19:02:14 wazuh systemd[1]: wazuh-indexer.service: Failed with result 'exit-code'.
Jan 22 19:02:14 wazuh systemd[1]: Failed to start Wazuh-indexer.
Jan 22 19:02:14 wazuh systemd[1]: wazuh-indexer.service: Consumed 1min 45.026s CPU time.

**Comment by rauldpm** [comment]
Hello @greenpdx 

As can be seen in the log, the following entry is indicated:

```
max virtual memory areas vm.max_map_count [65530] is too low, increase to at least [262144]
```

You need to increase this number to `262144` as specified in our documentation: https://documentation.wazuh.com/current/deployment-options/docker/docker-installation.html#increase-max-map-count-on-your-host-linux, to do this, please run the following command:

```
sysctl -w vm.max_map_count=262144
```

**Comment by rauldpm** [comment]
Closed due to inactivity. Please don't hesitate to open it again if necessary.
