### ISSUE TITLE
Review and improve Ruleset documentation

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-documentation#590]
https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html

Related issues: #151 #587 #395

- [x] Add more examples.
- [x] Add a better description of each setting.
- [x] Add a paragraph describing the contents of the current section (what is going to be explained to the user).
- [x] Add information about the `<group>` tag and its relevance when creating rules or modifying the existing ones.
- [x] Add information about the allowed custom rule ID range.
- [x] Add description and example for `regex` on Decoders documentation and its options.

**Comment by pereyra-m** [comment]
## Update

The issue #151 was closed and only this one remained open.
It is important to properly document the requirement of the `<group>` tag in the `local_rules.xml` file because it can cause confusion in the users.

See for example https://github.com/wazuh/wazuh/issues/16761.

Thank you.
