### ISSUE TITLE
Documentation typos

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-documentation#594]
I went typo hunting in the documentation by cloning the repo and running aspell on all rst files, with a bit of grep and some patience later this what I found:

Highlighted | Typo | In github
------------ | -------------  | -------------
[In the Docs](https://documentation.wazuh.com/current/deploying-with-ansible/install-ansible-control.html?highlight=distrutions )| distrutions | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/deploying-with-ansible/install-ansible-control.rst)
[In the Docs](https://documentation.wazuh.com/current/deploying-with-ansible/reference.html?highlight=Elasticseach )| Elasticseach | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/deploying-with-ansible/reference.rst)
[In the Docs](https://documentation.wazuh.com/current/deploying-with-ansible/reference.html?highlight=propectors )| propectors | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/deploying-with-ansible/reference.rst)
[In the Docs](https://documentation.wazuh.com/current/deploying-with-ansible/roles/wazuh-elasticsearch.html?highlight=enviroment )| enviroment | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/deploying-with-ansible/roles/wazuh-elasticsearch.rst)
[In the Docs](https://documentation.wazuh.com/current/deploying-with-ansible/roles/wazuh-kibana.html?highlight=enviroment )| enviroment | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/deploying-with-ansible/roles/wazuh-kibana.rst)
[In the Docs](https://documentation.wazuh.com/current/deploying-with-ansible/roles/wazuh-logstash.html?highlight=enviroment )| enviroment | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/deploying-with-ansible/roles/wazuh-logstash.rst)
[In the Docs](https://documentation.wazuh.com/current/deploying-with-ansible/roles/wazuh-logstash.html?highlight=defauls )| defauls | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/deploying-with-ansible/roles/wazuh-logstash.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/audit-commands.html?highlight=evalutated )| evalutated | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/audit-commands.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/rdp-brute-force.html?highlight=heirarchy )| heirarchy | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/rdp-brute-force.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/rdp-brute-force.html?highlight=mulitiple )| mulitiple | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/rdp-brute-force.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/suricata.html?highlight=elasic )| elasic | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/suricata.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/suricata.html?highlight=configation )| configation | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/suricata.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/suricata.html?highlight=elasic )| elasic | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/suricata.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/build-lab/install-windows-agent.html?highlight=tis )| tis | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/build-lab/install-windows-agent.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/build-lab/launch-ec2-instances.html?highlight=acknowledgement )| acknowledgement | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/build-lab/launch-ec2-instances.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/survive-flood.html?highlight=droped )| droped | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/survive-flood.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/survive-flood.html?highlight=acrosss )| acrosss | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/survive-flood.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/registering/registration-process.html?highlight=aproach )| aproach | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/registering/registration-process.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/kibana-app/features/dev-tools.html?highlight=beggining )| beggining | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/kibana-app/features/dev-tools.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/capabilities/policy-monitoring/ciscat/ciscat.html?highlight=benchamark )| benchamark | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/capabilities/policy-monitoring/ciscat/ciscat.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/agentless.html?highlight=checkis )| checkis | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/reference/ossec-conf/agentless.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/registering/registration-process.html?highlight=comunicating )| comunicating | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/registering/registration-process.rst)
[In the Docs](https://documentation.wazuh.com/current/amazon/use-cases/vpc.html?highlight=comunicating )| comunicating | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/amazon/use-cases/vpc.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/registering/registration-process.html?highlight=comunicate )| comunicate | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/registering/registration-process.rst)
[In the Docs](https://documentation.wazuh.com/current/amazon/use-cases/vpc.html?highlight=comunicate )| comunicate | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/amazon/use-cases/vpc.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/agents/agent-life-cycle.html?highlight=conected )| conected | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/agents/agent-life-cycle.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/ssh-brute-force.html?highlight=congatulations )| congatulations | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/ssh-brute-force.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html?highlight=formated )| formated | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/reference/ossec-conf/global.rst)
[In the Docs](https://documentation.wazuh.com/current/release-notes/release_3_4_0.html?highlight=frecuency )| frecuency | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/release-notes/release_3_4_0.rst)
[In the Docs](https://documentation.wazuh.com/current/migrating-from-ossec/index.html?highlight=increaing )| increaing | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/migrating-from-ossec/index.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html?highlight=percentaje )| percentaje | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/capabilities/syscollector.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/reference/daemons/wazuh-modulesd.html?highlight=performant )| performant | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/reference/daemons/wazuh-modulesd.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-windows-policies.html?highlight=polies )| polies | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/capabilities/auditing-whodata/who-windows-policies.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/capabilities/syscollector.html?highlight=proccesor )| proccesor | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/capabilities/syscollector.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/kibana-app/features/app-overview.html?highlight=quickily )| quickily | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/kibana-app/features/app-overview.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/kibana-app/features/app-overview.html?highlight=quickily )| quickily | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/kibana-app/features/app-overview.rst)
[In the Docs](https://documentation.wazuh.com/current/amazon/use-cases/s3.html?highlight=realible )| realible | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/amazon/use-cases/s3.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html?highlight=recomended )| recomended | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/reference/ossec-conf/global.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/shellshock.html?highlight=resposes )| resposes | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/shellshock.rst)
[In the Docs](https://documentation.wazuh.com/current/docker/wazuh-container.html?highlight=runneable )| runneable | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/docker/wazuh-container.rst)
[In the Docs](https://documentation.wazuh.com/current/learning-wazuh/ssh-brute-force.html?highlight=sigle )| sigle | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/learning-wazuh/ssh-brute-force.rst)
[In the Docs](https://documentation.wazuh.com/current/development/message-format.html?highlight=significative )| significative | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/development/message-format.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/reference/daemons/ossec-authd.html?highlight=specifig )| specifig | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/reference/daemons/ossec-authd.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/kibana-app/features/dev-tools.html?highlight=splitted )| splitted | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/kibana-app/features/dev-tools.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html?highlight=triger )| triger | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/reference/ossec-conf/global.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/overview.html?highlight=visualizaiton )| visualizaiton | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/overview.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/registering/use-registration-service.html?highlight=whith )| whith | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/registering/use-registration-service.rst)

The following three are a typo in the variable name that really stems from wazuh-kibana-app:
( https://github.com/wazuh/wazuh-kibana-app/blob/master/server/integration-files/known-fields.js )

Highlighted | Typo | In github
------------ | -------------  | -------------
[In the Docs](https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-linux.html?highlight=proccess )| proccess | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/capabilities/auditing-whodata/who-linux.rst)
[In the Docs](https://documentation.wazuh.com/current/user-manual/capabilities/auditing-whodata/who-windows.html?highlight=proccess )| proccess | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/user-manual/capabilities/auditing-whodata/who-windows.rst)
[In the Docs](https://documentation.wazuh.com/current/getting-started/use-cases.html?highlight=proccess )| proccess | [In github](https://github.com/wazuh/wazuh-documentation/blob/master/source/getting-started/use-cases.rst)

Now I don't guarantee I got all of them, but at least those are there. Setting up a script to ignore the known false positives and keep a constant eye out for this might not be a bad idea.

**Comment by JuanjiJG** [comment]
Done here: #597 

Thank you so much @jctello for reporting this! It's amazing and really appreciated! :smile:

Regards,
Juanjo
