### ISSUE TITLE
Configuring SSL certificates on the Wazuh dashboard using NGINX Document is wrong

### ISSUE THREAD

**Issue by TheKourosh** [wazuh/wazuh-documentation#5950]
Hi 
i started installing wazuh and after that, it should have an valid ssl.
but the document in this article is not working:
https://documentation.wazuh.com/current/user-manual/wazuh-dashboard/configuring-third-party-certs/ssl.html
when wazuh itself use port 443, then you can't use nginx or any other webserver to handle your ssl cerificate because they are need to port 443 to not be in used.
i tried this document and it's just not make any sense.

**Comment by damoche** [comment]
Hello @TheKourosh 
Thank you for the notification.

Let me investigate this issue. I will come back to you with feedback.

**Comment by damoche** [comment]
Hello @TheKourosh
This issue has been resolved.

Please check the documentation again.
