### ISSUE TITLE
Add new setting to client buffer, eps_timeframe

### ISSUE THREAD

**Issue by jotacarma90** [wazuh/wazuh-documentation#5967]
# Description

Hello team,
working on the issue: https://github.com/wazuh/wazuh/issues/3766
With PR: https://github.com/wazuh/wazuh/pull/16346

We have added a new configuration variable related to the client buffer and its events per second.
Its called `eps_timeframe` and is in charge of setting the time interval to update the available events for the client buffer.

Default value: `1`
Minimum value: `1`
Max value: `3600`

_A positive number expressed in seconds that indicates the time period where the events per second processed are increased and restored._

It is similar to the setting we have in analysisd for this same functionality:
https://documentation-dev.wazuh.com/v4.4.0-rc1/user-manual/reference/ossec-conf/global.html#limits-eps-timeframe

Regards, Jose

**Comment by jotacarma90** [comment]
Reopening this issue because we're going to move it forward to a next release.
https://github.com/wazuh/wazuh/issues/20168

**Comment by vikman90** [comment]
We're closing this issue as we will be working on a new communication mechanism: 
- https://github.com/wazuh/wazuh/issues/22677

Best regards.
