### ISSUE TITLE
Update Wazuh Alpine (APK) repository RSA key

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-documentation#6018]
Related issue: wazuh/wazuh-jenkins#4958

## Description

Since v4.4.0, Wazuh officially released Alpine packages that were signed using https://packages.wazuh.com/key/alpine-devel%40wazuh.com-633d7457.rsa.pub key.

Naming alpine-devel%40wazuh.com-633d7457.rsa.pub to the key could lead to the false interpretation of it as a development key.

![image](https://user-images.githubusercontent.com/1791430/230165800-8f13fdf7-ac7b-402a-a889-0514cccb1fe0.png)

## DoD
- [ ] Update such key URL based on wazuh-jenkins#4966 implementation

**Comment by davidjiglesias** [comment]
To be done as part of the new Wazuh packages redesign.
