### ISSUE TITLE
Add docker volume mounts in upgrade steps

### ISSUE THREAD

**Issue by fcaffieri** [wazuh/wazuh-documentation#6078]
Due to changes made in version 4.4.1 on the opensearch.yml and certificate paths, which were moved from the `/usr/share/wazuh-indexer/config` path to `/usr/share/wazuh-indexer `, it is required to add the following steps in the Wazuh docker upgrade documentation https://documentation.wazuh.com/current/deployment-options/docker/upgrading-wazuh-docker.html#upgrading-wazuh-docker.

Steps (These steps would be required only if an upgrade from 4.3 to 4.4 is performed without performing a checkout and the images are updated):
In order to correctly raise Wazuh indexer, it is necessary to modify the assembly of the paths in the following way:

```
volumes:
      - wazuh-indexer-data:/var/lib/wazuh-indexer
      - ./config/wazuh_indexer_ssl_certs/root-ca.pem:/usr/share/wazuh-indexer/certs/root-ca.pem
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer-key.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.key
      - ./config/wazuh_indexer_ssl_certs/wazuh.indexer.pem:/usr/share/wazuh-indexer/certs/wazuh.indexer.pem
      - ./config/wazuh_indexer_ssl_certs/admin.pem:/usr/share/wazuh-indexer/certs/admin.pem
      - ./config/wazuh_indexer_ssl_certs/admin-key.pem:/usr/share/wazuh-indexer/certs/admin-key.pem
      - ./config/wazuh_indexer/wazuh.indexer.yml:/usr/share/wazuh-indexer/opensearch.yml
      - ./config/wazuh_indexer/internal_users.yml:/usr/share/wazuh-indexer/opensearch-security/internal_users.yml
```

This was reported by a community user in this issue: https://github.com/wazuh/wazuh-docker/issues/822

**Comment by AlexRuiz7** [comment]
Fixed in recent versions.
![image](https://github.com/wazuh/wazuh-documentation/assets/15186973/1a6cc679-3d86-4c7b-8f2c-c3df38dc5ee8)
