### ISSUE TITLE
New section: restore from backup

### ISSUE THREAD

**Issue by gdiazlo** [wazuh/wazuh-documentation#6112]
Currently, we have documentation on how to back up Wazuh servers and agents in https://documentation.wazuh.com/current/user-manual/files-backup/index.html, but we do not have a step-by-step guide in how to recover a Wazuh server or agent from a backup.

We comment briefly that all it's needed is to copy the files back to their original location.

We should to create a step-by-step guide on how to recover a server or agent from its backup.

**Comment by re-toor** [comment]
Hi everyone,
Have any update?

**Comment by s-ocando** [comment]
Hi @gdiazlo @re-toor, 

A guide on how to restore a Wazuh backup is now included in our documentation: https://documentation.wazuh.com/current/user-manual/files-backup/restoring/index.html. Check it out!
