### ISSUE TITLE
Admin password change fails  for Wazuh on Docker deployment

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh-documentation#6158]
In Wazuh 4.4, following the steps in [Change the password of an existing user](https://documentation.wazuh.com/current/deployment-options/docker/wazuh-container.html#change-the-password-of-an-existing-user) does not accomplish the password change. It works for Wazuh 4.3, though.

**Comment by javimed** [comment]
Related issue:
- https://github.com/wazuh/internal-devel-requests/issues/34

**Comment by pereyra-m** [comment]
Hi!
Just wanted to add that in `4.4`, I also receive this message during the password update

```bash
$ docker run --rm -ti wazuh/wazuh-indexer:4.4.3 bash /usr/share/wazuh-indexer/plugins/opensearch-security/tools/hash.sh                                                           
**************************************************************************
** This tool will be deprecated in the next major release of OpenSearch **
** https://github.com/opensearch-project/security/issues/1755           **
**************************************************************************
[Password:]

```

**Comment by javimed** [comment]
Additional related issue: https://github.com/wazuh/wazuh-docker/issues/838

**Comment by javimed** [comment]
@pereyra-m the upcoming deprecation of Security Plugin Tools, such as `tools/hash.sh`, is being tracked by https://github.com/wazuh/wazuh-packages/issues/1968
