### ISSUE TITLE
Add documentation for new Maltiverse integration

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-documentation#6216]
| Related issue |
|--|
|https://github.com/wazuh/wazuh/issues/17752|

## Description

A new integration with Maltiverse is being developed here:
- https://github.com/wazuh/wazuh/issues/17752

We will need to add a section explaining how to configure and use it, similarly to other existing integrations as Pagerduty, Slack, Virustotal, etc.

**Comment by fdalmaup** [comment]
# Issue Update

Documentation generated with use case showing an alert example in the dashboard. It only remains to add the steps related to the Maltiverse platform and how to get the API key.
