### ISSUE TITLE
Wazuh central components backup documentation is outdated

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-documentation#6236]
### Description

In Wazuh 4.4, there are some differences in file paths compared to earlier versions, but these changes have not been updated in the [Wazuh Central components documentation](https://documentation.wazuh.com/current/user-manual/files-backup/wazuh-central-components.html). 

For instance, in the [Backing up the wazuh indexer and dashboard](https://documentation.wazuh.com/current/user-manual/files-backup/wazuh-central-components.html#backing-up-the-wazuh-indexer-and-dashboard) step it refers to `/usr/share/wazuh-indexer/plugins/opensearch-security/securityconfig \`, but the correct path in version 4.4 is `/usr/share/wazuh-indexer/opensearch-security/`

Additionally, there are some steps in the documentation that require further clarification:

- The note provided does not specify how to perform the mentioned task. Furthermore, it does not inform about that the backup alerts will not been indexed automatically. For more information on this, you can refer to the blog post titled "Recover Your Data Using Wazuh Alert Backups" at https://wazuh.com/blog/recover-your-data-using-wazuh-alert-backups/.

![image](https://github.com/wazuh/wazuh-documentation/assets/11089305/e7f595f4-31b0-44fc-bbd8-2a36ae2203a2)
 
- Documentation is not clear enough about how to apply the backup configuration in the new environment

**Comment by javimed** [comment]
Related issue https://github.com/wazuh/wazuh-documentation/issues/5907
