### ISSUE TITLE
Task Manager cleanup option documentation does not inform about minimum values

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-documentation#6253]
### Description:

The [task manager configuration](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/task-manager.html) lacks the specification of the minimum values for the [cleanup option](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/task-manager.html#cleanup-time). If a value less than 1 hour is used, the task manager fails to function properly, generating the following error:

```
2023/07/19 16:07:05 wazuh-modulesd: ERROR: The cleanup_time value is too short in the 'task-manager' module.
2023/07/19 16:07:05 wazuh-modulesd: ERROR: (1202): Configuration error at 'etc/ossec.conf'.
```

It should be desirable to change the `Allowed values` of this option specifying this condition.

**Comment by s-ocando** [comment]
There's no minimum value for the `cleanup_time` parameter but there's the [condition that cleanup_time must be greater or equal than the task_timeout parameter](https://github.com/wazuh/wazuh/blob/v4.4.5/src/config/wmodules-task-manager.c#L101). We'll add a note in the documentation clarifying this.
