### ISSUE TITLE
Confusing group tags and a not explained tag

### ISSUE THREAD

**Issue by mauromalara** [wazuh/wazuh-documentation#6268]
# Description

While searching in the documentation I could not find an explanation of the group tag that, for instance, is being used in the [creation of custom rules](https://documentation.wazuh.com/current/user-manual/ruleset/custom.html#adding-new-decoders-and-rules) or in the [rules syntax](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#var) documentation.

But, I'm able to see the following tag which has the same name but it is used **inside** a rule: [group](https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#group). I think this is very confusing for our community users, so we have to write a note clarifying this.

**Comment by JorgeMarinoDev** [comment]
Status Update:

[Related PR 6421](https://github.com/wazuh/wazuh-documentation/pull/6421)  was updated after sync with @javimed .

The main lack of documentation here was related to an ambiguity of the <group> token in the rules definitions.

<group> can be used enclosing a whole rule or inside the rule itself.

Both cases have totally different purposes and `source/user-manual/ruleset/ruleset-xml-syntax/rules.rst` was updated accordingly.
