### ISSUE TITLE
Add instructions on how to upgrade a Wazuh Alpine agent

### ISSUE THREAD

**Issue by s-ocando** [wazuh/wazuh-documentation#6285]
The Wazuh agent upgrade guide is currently missing instructions on how to upgrade the Alpine agent. We should include these instructions under the [Upgrading Wazuh agents on Linux systems](https://documentation.wazuh.com/current/upgrade-guide/wazuh-agent/linux.html) section.

**Comment by ed108206** [comment]
Correction of compilation errors

**Comment by ed108206** [comment]
Conflict branch version

**Comment by ed108206** [comment]
I had more problems than I expect to solving the issue

**Comment by ncvicchi** [comment]
Moved ETA waiting for final review from documentation team
