### ISSUE TITLE
Error in the remoted.request_pool maximum value (website documentation)

### ISSUE THREAD

**Issue by Leoquicenoz** [wazuh/wazuh-documentation#6369]
### Description

Hello team,

Responding to a community user, they asked why in the Wazuh documentation: 

- [https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#remoted](https://documentation.wazuh.com/current/user-manual/reference/internal-options.html#remoted) 

Specifically in the section `remoted.request_pool`, the allowed value is specified between `1` and `64`, with a default value of `8`. However, in the `internal_options.conf` file, there is a range of `1` to `4096` and a default value of `1024`.

Upon further investigation, I found this information in the file `src/client-agent/request.c` in the GitHub repository (`wazuh/wazuh`). Specifically, in this line of code: 

```c
request_pool = getDefine_Int("remoted", "request_pool", 1, 4096);
``` 

Documentation should be changed to match the values that this parameter can actually take?

**Comment by javimed** [comment]
Related PR https://github.com/wazuh/wazuh/pull/1473
