### ISSUE TITLE
Redesign diagrams for documentation

### ISSUE THREAD

**Issue by saramoran** [wazuh/wazuh-documentation#637]
- [x] apply feedback

---

- [x] proposal with several options

---

### Getting Started
- https://documentation.wazuh.com/current/getting-started/index.html
- [x] https://documentation.wazuh.com/current/_images/ossec_openscap_elastic_1024x4451.png

### Components
- https://documentation.wazuh.com/current/getting-started/components.html
- [x] https://documentation.wazuh.com/current/_images/agent_1024x10161.png
- [x] https://documentation.wazuh.com/current/_images/server_1024x8721.png
### Architecture
- https://documentation.wazuh.com/current/getting-started/architecture.html
- [x] https://documentation.wazuh.com/current/_images/installing_wazuh1.png
- [x] https://documentation.wazuh.com/current/_images/installing_wazuh_singlehost1.png
- [x] https://documentation.wazuh.com/current/_images/data_flow_2048x7941.png
### User Manual: Configuring a cluster
- https://documentation.wazuh.com/current/user-manual/manager/wazuh-cluster.html
- [x] https://documentation.wazuh.com/current/_images/introduction_cluster.png
- [x] https://documentation.wazuh.com/current/_images/cluster_flow.png
### User Manual: Agent life cycle
- https://documentation.wazuh.com/current/user-manual/agents/agent-life-cycle.html
- [x] https://documentation.wazuh.com/current/_images/agent-status1.png
### User Manual: Capabilities: Log data collection
- https://documentation.wazuh.com/current/user-manual/capabilities/log-data-collection/how-it-works.html
- [x] https://documentation.wazuh.com/current/_images/log-analysis-flow1.png
### User Manual: Capabilities: File integrity monitoring
- https://documentation.wazuh.com/current/user-manual/capabilities/file-integrity/how-it-works.html
- [x] https://documentation.wazuh.com/current/_images/fim-flow1.png
### User Manual: Capabilities: Anomaly and malware detection
- https://documentation.wazuh.com/current/user-manual/capabilities/anomalies-detection/how-it-works.html
- [x] https://documentation.wazuh.com/current/_images/rootcheck-flow1.png
### User Manual: Capabilities: Monitoring security policies
- https://documentation.wazuh.com/current/user-manual/capabilities/policy-monitoring/rootcheck/how-it-works.html
- https://documentation.wazuh.com/current/user-manual/capabilities/policy-monitoring/openscap/how-it-works.html
- [x] https://documentation.wazuh.com/current/_images/rootcheck-compliance1.png
- [x] https://documentation.wazuh.com/current/_images/openscap-flow1.png
### User Manual: Capabilities: Command monitoring
- https://documentation.wazuh.com/current/user-manual/capabilities/command-monitoring/how-it-works.html
- [x] https://documentation.wazuh.com/current/_images/command-monitoring1.png
### User Manual: Capabilities: Active response
- https://documentation.wazuh.com/current/user-manual/capabilities/active-response/how-it-works.html
- [x] https://documentation.wazuh.com/current/_images/automatic-remediation1.png
### User Manual: Capabilities: Antiflooding
- https://documentation.wazuh.com/current/user-manual/capabilities/antiflooding.html
- [x] https://documentation.wazuh.com/current/_images/bucket3.png
- [x] https://documentation.wazuh.com/current/_images/graphic_with_flood1.png
- [x] https://documentation.wazuh.com/current/_images/graphic_without_flooding1.png
### Development: Standard OSSEC message format
- https://documentation.wazuh.com/current/development/message-format.html
- [x] https://documentation.wazuh.com/current/_images/encryption_flow.png 
### Installing Splunk
- https://documentation.wazuh.com/current/installing-splunk/index.html
- [x] https://documentation.wazuh.com/current/_images/simple-distributed-arch.png
- [x] https://documentation.wazuh.com/current/_images/distributed-arch.png

___

- [x] design azure graphic

___
- [x] correct diagrams

___
- [x] analysisd-alerts-queue-full
- [x] analysisd-flow-example
- [x] analysisd-structure
- [x] analysisd-syscheck-full

**Comment by JuanjiJG** [comment]
Done here: #638

Thank you so much @saramoran!! :smile:

Regards,
Juanjo
