### ISSUE TITLE
Documentation to build wazuh-indexer and wazuh-dashboard packages is missing

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-documentation#6403]
## Description

Currently there is not documentation on the steps needed to build the `wazuh-indexer`  and the `wazuh-dashboard` packages in the [Wazuh Documentation page.](https://documentation.wazuh.com/current/development/packaging/index.html) 

![imagen](https://github.com/wazuh/wazuh-documentation/assets/14501079/8e564075-f43f-471c-8d24-9e897e6717b1)

## Tasks
- [x] Add documentation on building the `wazuh-indexer` package
- [x] Add documentation on building the `wazuh-dashboard` package

**Comment by QU3B1M** [comment]
LGTM 🚀

**Comment by davidjiglesias** [comment]
LGTM!
