### ISSUE TITLE
Update `securityadmin.sh` output examples in SSO documents for 4.7

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh-documentation#6416]
Supporting `Opensearch 2.9.0` for `wazuh-indexer` and `wazuh-dashboard` `4.7` involves updating the terminal output examples for the steps when running the `securityadmin.sh` script. For example:

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/75f487b2-df92-4568-9a0c-9d733707d65b)

It's required to update each document for both `administrator` and `read-only` roles for the following platforms:

- [ ] Okta
- [ ] Azure Active Directory
- [ ] PingOne
- [ ] Google
- [ ] Jumpcloud
- [ ] OneLogin
- [ ] Keycloak

**Comment by gdiazlo** [comment]
This won't be required anymore for Wazuh 4.7 as it will use the same OpenSearch version as 4.6.
