### ISSUE TITLE
Update `GET https://<IP_ADDRESS>:9200` output examples for 4.7

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh-documentation#6417]
Supporting `Opensearch 2.9.0` for `wazuh-indexer` and `wazuh-dashboard` `4.7` involves updating the terminal output examples for the steps when querying indexer with `GET https://<IP_ADDRESS>:9200`. For example:

![imagen](https://github.com/wazuh/wazuh-documentation/assets/47069802/c6a3f3eb-b009-4f08-80e4-b800e5e313bb)

It's required to update in the following documents:

- [ ] [wazuh-indexer / installation-assistant / testing-the-cluster-installation](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/installation-assistant.html#testing-the-cluster-installation)
- [ ] [wazuh-indexer / step-by-step / testing-the-cluster-installation](https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html#testing-the-cluster-installation)
- [ ] [offline-installation / installing-the-wazuh-indexer](https://documentation.wazuh.com/current/deployment-options/offline-installation.html#installing-the-wazuh-indexer)

**Comment by gdiazlo** [comment]
This won't be required anymore for Wazuh 4.7 as it will use the same OpenSearch version as 4.6.
