### ISSUE TITLE
Fix rbac reference for decoders and rules

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-documentation#6422]
[RBAC reference documentation](https://documentation.wazuh.com/user-manual/api/rbac/reference.html#decoders) needs to be fixed. 

The PUT /decoders/files/{filename} endpoint requires decoders:update and decoders:delete RBAC actions, but only decoders:update is listed. 
The PUT /rules/files/{filename} endpoint requires rules:update and rules:delete RBAC actions, but only rules:update is listed.

**Comment by RamosFe** [comment]
## Update

Added missing RBAC policies for `PUT /rules/files/{filename}`.

https://github.com/wazuh/wazuh-documentation/blob/b987695763d2b0f427da5aa1d6c7da794da8b3ad/source/user-manual/api/rbac/reference.rst?plain=1#L556-L559

Added missing RBAC policies for `PUT /decoders/files/{filename}`.

https://github.com/wazuh/wazuh-documentation/blob/b987695763d2b0f427da5aa1d6c7da794da8b3ad/source/user-manual/api/rbac/reference.rst?plain=1#L410-L413
