### ISSUE TITLE
Update docker compose installation link

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-documentation#643]
Hello team,
the docker compose installation link in our documentation is outdated: https://documentation.wazuh.com/current/docker/docker-installation.html#docker-compose

We should update it to the latest version.

Regards.

**Comment by JuanjiJG** [comment]
Hello @havidarou,

I've updated the Docker Compose version on the following PR: #641. You can see the changes in [this commit](https://github.com/wazuh/wazuh-documentation/pull/641/commits/165b512f6229b03f544789187bd9e7811c621f34).

The modifications will be available when the PR is merged, so I'll proceed to close the issue.

Thank you so much for reporting this!

Regards,
Juanjo
