### ISSUE TITLE
Improvements to How to set up custom branding section

### ISSUE THREAD

**Issue by mhamra** [wazuh/wazuh-documentation#6459]
During https://github.com/wazuh/wazuh/issues/18850 for the 4.6.0-alpha1 version, I used this documentation section to run the E2E test.

I've found confusing the way the bullets are initialized in the [Custom logos in the Wazuh dashboard](https://documentation-dev.wazuh.com/v4.6.0-alpha1/user-manual/wazuh-dashboard/custom-branding.html#custom-logos-in-the-wazuh-dashboard) and the [Custom branding of the PDF reports](https://documentation-dev.wazuh.com/v4.6.0-alpha1/user-manual/wazuh-dashboard/custom-branding.html#custom-branding-of-the-pdf-reports) sections.

Each bullet is initialized with the name of a property instead of the field's name. For example, in this bullet:

- `customization.logo.app.` This property sets the App main logo image. It has a size limit of 1 MB. It replaces the logo image in the Wazuh main menu located top left. Recommended size: 300 pixels width, 70 pixels height. See # 1 in the image below.

This could be changed by something like this:
- "App main logo": This field replaces the logo image in the Wazuh main menu located top left when it is set. The recommended size is 300 pixels in width, 70 pixels in height. See # 1 in the image below. The field sets the property `customization.logo.app.`  in xxx.yaml.

**Comment by gdiazlo** [comment]
This does not make sense, as the setting is called as it is described in the documentation. The setting name is what the user must use to configure it. We are not going to change it.
