### ISSUE TITLE
Missing Documentation on the Installation of Wazuh Agent on Arch Linux

### ISSUE THREAD

**Issue by thony4uu** [wazuh/wazuh-documentation#6467]
During E2E testing on [#18441](https://github.com/wazuh/wazuh/issues/18841), the documentation does not cover the installation of the Wazuh agent on 4.6.0

In the [documentation](https://documentation-dev.wazuh.com/v4.6.0-alpha1/installation-guide/wazuh-agent/index.html), here are instructions to install Wazuh agent on Arch Linux

Based on what is available on the Wazuh dashboard, Arch Linux does not natively support deb and rpm packages as it uses Pacman as its package manager.

![image](https://github.com/wazuh/wazuh-documentation/assets/108103499/fa46d6bc-cc3b-4442-a89f-872672a96472)

It will be nice to link the installation of the Wazuh agent on Arch Linux to installation from [sources](https://documentation-dev.wazuh.com/v4.6.0-alpha1/deployment-options/wazuh-from-sources/wazuh-agent/index.html) as it provides an option for Linux distributions using Packman package manager.

**Comment by thony4uu** [comment]
A Note from @rauldpm : The development we have in Wazuh-packages for Arch Linux was contributed by a community user and it is not being maintained officially, therefore we do not have a package and it is not included in the documentation.

**Comment by davidjiglesias** [comment]
Noted, I will be removing Arch Linux from E2E test deployment as it is not part of our tier 1 right now.
