### ISSUE TITLE
MITRE - The customization section triggers a different rule than expected

### ISSUE THREAD

**Issue by JorgeMarinoDev** [wazuh/wazuh-documentation#6469]
During execution of tests regarding  [E2E MITRE](https://github.com/wazuh/wazuh/issues/18849) a mismatch was found in the **customization** section
https://documentation-dev.wazuh.com/v4.6.0-alpha1/user-manual/ruleset/mitre.html#customization

The added rule 100003 is not triggered, since rule 5712 is catching the event before.

**Comment by thecotilking** [comment]
After retest, both the custom rule was triggered.
![image](https://github.com/wazuh/wazuh-documentation/assets/113598572/ff8bcf7e-ca66-41f8-8722-43def9563f64)

However, since the default rule already triggers the intended alert. documentation has been modified and the custom rule taken.
