### ISSUE TITLE
Review cloud modules dependencies section after upward merges for numbered branches 

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh-documentation#6552]
# Description

In https://github.com/wazuh/wazuh-documentation/pull/6545, the latest changes from the versioned branches were introduced into the master branch. Given the urgency of said update of the versioned and master branches and the necessary changes added in [Add differentiation between commands from different Python versions](https://github.com/wazuh/wazuh-documentation/pull/6514) in the dependencies sections due to Python 3.11 dependencies installation, the changes added in [Refactored and standarized the Python dependencies section for cloud and docker modules](https://github.com/wazuh/wazuh-documentation/pull/6232) were discarded in favor of the detailed explanation on how to install the necessary dependencies for the different Python versions. 

This issue aims to adapt the changes from #6232 to the modified master branch.

**Comment by GGP1** [comment]
## Update

Adapts the discarded changes from https://github.com/wazuh/wazuh-documentation/pull/6232 to the `4.8.0` branch. The `pip` installation instructions were kept because of https://github.com/wazuh/wazuh-documentation/pull/6232#discussion_r1262462422.
