### ISSUE TITLE
Rename Azure Active Directory as Microsoft Entra ID

### ISSUE THREAD

**Issue by thony4uu** [wazuh/wazuh-documentation#6559]
During E2E testing on  https://github.com/wazuh/wazuh/issues/19156, there is mention of Azure Active Directory in several sections. However, Microsoft has renamed Azure Active Directory as Microsoft Entra ID

![image](https://github.com/wazuh/wazuh-documentation/assets/108103499/eea8b109-e1dd-4e28-bc99-ed1e0f0dd8ac)

**Comment by GGP1** [comment]
## Update

Updated Azure Active Directory name to Microsoft Entra ID.

**Comment by GGP1** [comment]
## Update

Rebased branch to 4.5.0.

**Comment by GGP1** [comment]
## Update

Rebased branch to 4.5.

**Comment by GGP1** [comment]
## Update

Rebased branch to 4.6.
