### ISSUE TITLE
Some Dashboard plugins have changed category

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-documentation#6692]
# Description

In newer versions of OpenSearch Dashboards (2.10.0 and above), some plugins have moved from category. From example, the `Index Management` plugin has been moved from the `OpenSearch plugins` category to the `Management` category. In the documentation, there are step-by-step guides that will require an update.

We are adopting OpenSearch 2.10.0 in our 4.8.0 version.

After a brief exploration, at least these files will require an update:

- `/user-manual/wazuh-indexer/index-life-management`
- `/user-manual/wazuh-indexer/wazuh-indexer-indices`

![image](https://github.com/wazuh/internal-devel-requests/assets/15186973/c9b3a34c-f90c-4840-978d-ef59a96f99b2)
_`Index Management` plugin under the `OpenSearch plugins` category. v2.6.0`

![image](https://github.com/wazuh/internal-devel-requests/assets/15186973/e091da2b-2cce-4864-a142-c945aeb58716)
_`Index Management` plugin under the `Management` category. v2.10.0`

# Approved by

DRI name: @AlexRuiz7

**Comment by SamsonIdowu** [comment]
Noting this for reference purposes.

**Comment by AlexRuiz7** [comment]
Superseded by latest Dashboard changes.
