### ISSUE TITLE
Improve the quickstart guide when installing from package using a not recommended OS. 

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh-documentation#6730]
During the [Release 4.7.0 - Alpha 2 - E2E UX tests - Windows events #20014](https://github.com/wazuh/wazuh/issues/20014). It was found that when installing all components from packages using the [quickstart guide](https://documentation.wazuh.com/current/quickstart.html) on a not-recommended operating system an error is shown.

```command
root@localhost /]# ./wazuh-install.sh -a
03/11/2023 13:53:46 INFO: Starting Wazuh installation assistant. Wazuh version: 4.7.0
03/11/2023 13:53:46 INFO: Verbose logging redirected to /var/log/wazuh-install.log
03/11/2023 13:53:48 INFO: --- Dependencies ---
03/11/2023 13:53:48 INFO: Installing lsof.
03/11/2023 13:54:15 ERROR: The recommended systems are: Red Hat Enterprise Linux 7, 8, 9; CentOS 7, 8; Amazon Linux 2; Ubuntu 16.04, 18.04, 20.04, 22.04. The current system does not match this list. Use -i|--ignore-check to skip this check.
```

This issue should tend to improve the documentation to include a section for not other OS to include the fix shown in the logs which is to execute the command using the `-i` or `--ignore-check` flag.

```command
[root@localhost /]# ./wazuh-install.sh -a -i
```

**Comment by davidjiglesias** [comment]
Already covered in other issues
