### ISSUE TITLE
Single bold word in text block

### ISSUE THREAD

**Issue by manuasir** [wazuh/wazuh-documentation#681]
Hi team,

I saw this lonely word was bold in the text block:

![image](https://user-images.githubusercontent.com/10210567/49226722-af5e7c00-f3e7-11e8-9ada-4496c75ff61f.png)

Maybe the whole text in the box should have the same applied style.

Thanks!

**Comment by JuanjiJG** [comment]
Moved into #688

Regards,
Juanjo
