### ISSUE TITLE
Add information to Alpine Linux users about Audit and whodata

### ISSUE THREAD

**Issue by ed108206** [wazuh/wazuh-documentation#6833]
**FIM whodata not working on Alpine Linux

This issue is closed by [6871](https://github.com/wazuh/wazuh-documentation/pull/6871)

From the analysis conducted on this [issue](https://github.com/wazuh/wazuh/issues/19412), it has been determined that Alpine Linux, and potentially other operating systems, may encounter an incorrect installation of the Auditd tool, leading to potential malfunctions. In order to mitigate such issues, it is recommended to follow the steps related in the issue.

On alpine linux, after auditd is installed:

```
:# cp /usr/sbin/audisp-af_unix  /sbin/audisp-af_unix
:# rc-service auditd restart
:# /var/ossec/bin/wazuh-control restart
```

I's offer to your consideration the following steps to advice users as a clarification or if it falls outside the scope of the documentation.

**Comment by ed108206** [comment]
This issue is closed since not correspond to the Wazuh-documentation service

**Comment by ncvicchi** [comment]
This issue is closed by [6871](https://github.com/wazuh/wazuh-documentation/pull/6871)

**Comment by ncvicchi** [comment]
Merged!
