### ISSUE TITLE
Centralize wazuh agent cloud modules dependencies installation

### ISSUE THREAD

**Issue by GGP1** [wazuh/wazuh-documentation#6849]
## Description

We have 3 ([1](https://documentation.wazuh.com/current/cloud-security/amazon/services/prerequisites/dependencies.html), [2](https://documentation.wazuh.com/current/cloud-security/azure/activity-services/prerequisites/dependencies.html), [3](https://documentation.wazuh.com/current/cloud-security/gcp/prerequisites/dependencies.html)) almost identical pages that describe the steps to install the dependencies necessary to run the cloud modules in a Wazuh agent. We often have to modify all of them to avoid setup differences. 

They could be unified in a single page called something in the lines of "Wazuh agent dependencies installation" that contains:

- Python/pip installation ([example](https://documentation.wazuh.com/current/cloud-security/amazon/services/prerequisites/dependencies.html#python))
- AWS dependencies installation ([current section](https://documentation.wazuh.com/current/cloud-security/amazon/services/prerequisites/dependencies.html#aws-pip-dependencies))
- Azure dependencies installation ([current section](https://documentation.wazuh.com/current/cloud-security/azure/activity-services/prerequisites/dependencies.html#azure-storage-blobs-client-library-for-python))
- GCP dependencies installation ([current section](https://documentation.wazuh.com/current/cloud-security/gcp/prerequisites/dependencies.html#google-cloud-pip-dependencies))

We should review if this change makes sense or if we should keep the guides separate.

**Comment by javimed** [comment]
We could use a template and keep all those pages divided.

We can use the  [docutils directive include](https://docutils.sourceforge.io/docs/ref/rst/directives.html#include) to re-use dependency installation templates containing the repeating blocks of texts with a syntax like:

`.. include:: _templates/.../dependency1_template.rst`

For example, we do currently use templates with steps to add the Wazuh repository for the different installation alternatives like here:

- https://github.com/wazuh/wazuh-documentation/blob/v4.7.1/source/installation-guide/wazuh-indexer/step-by-step.rst?plain=1#L103-L119
  - https://github.com/wazuh/wazuh-documentation/blob/v4.7.1/source/_templates/installations/common/yum/add-repository.rst?plain=1
  - https://github.com/wazuh/wazuh-documentation/blob/v4.7.1/source/_templates/installations/common/deb/add-repository.rst?plain=1

What do you think of this alternative approach? It allows keeping dedicated pages while avoiding maintaining multiple copies of the same blocks. In our case we could use a pyhton3 installation template and a pip installation template.

**Comment by GGP1** [comment]
## Update

Added templates for the python and pip installations as suggested by the documentation team. The PR also includes some changes to eliminate style and spelling differences between the documents.

**Comment by GGP1** [comment]
## Update

Applied the changes suggested and explained why the template does not contain part of the text repeated.
