### ISSUE TITLE
Registering process need to be explained for Windows. 

### ISSUE THREAD

**Issue by alberpilot** [wazuh/wazuh-documentation#685]
Hello team 

If we follow the guide: 

https://documentation.wazuh.com/current/user-manual/registering/use-registration-service.html#register-the-agent

The point: 

![image](https://user-images.githubusercontent.com/3830293/49284127-ee4a0b80-f493-11e8-9a8b-ad8959976959.png)

could be confusing if the somebody uses Windows. I think that we could provide the instruction to execute agent-auth in a Windows agent. 

Best regards,

**Comment by JuanjiJG** [comment]
Hello @alberpilot,

Thank you so much for reporting this. In fact, we already have this PR which includes a rework of the authd registration guide: https://github.com/wazuh/wazuh-documentation/pull/642

We'll improve the pull request adding information about the registration process for Windows systems. This is indeed a necessary step.

Regards,
Juanjo

**Comment by JuanjiJG** [comment]
Working on this issue on the branch [`3.7-review-auth-docs`](https://github.com/wazuh/wazuh-documentation/tree/3.7-review-auth-docs), it will be included in #642.

**Comment by JuanjiJG** [comment]
Closing this issue as #642 was merged.

Regards,
Juanjo
