### ISSUE TITLE
Add macOS Sonoma 14 to available SCA policies table

### ISSUE THREAD

**Issue by ncvicchi** [wazuh/wazuh-documentation#6887]
Since 4.7.1 version, macOS Sonoma 14 has official SCA policies available. Although [the changelog](https://documentation.wazuh.com/current/release-notes/release-4-7-1.html#packages) reflects this situation, it is not properly reflected at the [available SCA policies table](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/available-sca-policies.html).

**Comment by mateocervilla** [comment]
## Update

The missing SCA policy was added in the linked [PR](https://github.com/wazuh/wazuh-documentation/pull/6890)

Commit: https://github.com/wazuh/wazuh-documentation/issues/6887

**Comment by ncvicchi** [comment]
Awesome! I'm not sure if master is the right branch to push the PR, since the policies are already deployed with 4.7.1.
