### ISSUE TITLE
Upgrade guide will broke API dependencies

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-documentation#691]
Hi team,

Searching on the documentation I see this post https://documentation.wazuh.com/current/installation-guide/upgrading/latest_wazuh3_minor.html#upgrading-latest-minor 
It says that manager must upgrade with this commands: 
`# apt-get update && apt-get install --only-upgrade wazuh-manager` for Ubuntu.
`# yum upgrade wazuh-manager` for rhel.

In 3.7.0 the API depends of manager so to upgrade correctly you need to upgrade both manager and API at same time, anyway maybe we can also include specific version upgrade e.g. 3.6.1 to 3.7.0

Possible workaround: remove `--only-upgrade` from commands.

**Comment by JuanjiJG** [comment]
Related PR: #766

**Comment by JuanjiJG** [comment]
Closing the issue since #766 has been merged.

Regards,
Juanjo
