### ISSUE TITLE
Typo in "Install Elastic Stack Server" documentation

### ISSUE THREAD

**Issue by LuisGi93** [wazuh/wazuh-documentation#694]
We need to change https://documentation.wazuh.com/current/deploying-with-ansible/guide/install-elk-server.html#access-to-wazuh-ansible :
In the Logstash section:
`    - { role: /etc/ansible/roles/wazuh-ansible/roles/elastic-stack/ansible-logstash, elasticsearch_network_host: 'localhost' }`
to
`    - { role: /etc/ansible/roles/wazuh-ansible/roles/elastic-stack/ansible-logstash, elasticsearch_network_host: 'your elasticsearch IP' }`

**Comment by SitoRBJ** [comment]
Hello team,

The PR #710 solves this issue.

Regards,

Alfonso Ruiz-Bravo

**Comment by JuanjiJG** [comment]
Closing this issue as #710 has been merged.

Regards,
Juanjo
