### ISSUE TITLE
Link to alerts config section lead you to the global one

### ISSUE THREAD

**Issue by havidarou** [wazuh/wazuh-documentation#696]
Hello, 
the link for the alerts configuration section in this documentation page: https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html points to the global configuration section.

It should point to the alerts config one.

Regards.

**Comment by JuanjiJG** [comment]
Hello @havidarou,

Thank you so much for reporting this. However, this is duplicated. It's already on #688, and previously on #687.

I'll proceed to close this.

Regards,
Juanjo
