### ISSUE TITLE
Missing step in article `Monitoring Docker container logs with Wazuh`

### ISSUE THREAD

**Issue by kujo-jotaro** [wazuh/wazuh-documentation#6961]
## Description

The article [Monitoring Docker container logs with Wazuh](https://wazuh.com/blog/monitoring-docker-container-logs-with-wazuh/) makes mention of a section of the article that never comes to be:

![image](https://github.com/wazuh/wazuh-documentation/assets/32543175/20495c32-da6e-4a3b-98d6-dd8d9cfcbf7a)

The mentioned change (from "yes" to "no") is never explicitly performed per the article's instructions after this.

Can you please take a look at this? Thanks in advance.

**Comment by javimed** [comment]
This a recommendation. It can be added if it's decided to be strictly necessary. Is this really necessary to be added?
