### ISSUE TITLE
Wrong default value of queue_size for Analysisd and Remoted 

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-documentation#697]
The current documentation sets those values to 16384:

https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/global.html#queue-size
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/remote.html#queue-size

Nevertheless, the correct default value is 131072.

Regards.

**Comment by snaow** [comment]
Corrected here: https://github.com/wazuh/wazuh-documentation/commit/123eeef62f36afca44d36366504fbc52c0cbf855
Going out in 3.7 docs.

Closing.
