### ISSUE TITLE
Port 9200 inaccessible in the Elastic integration

### ISSUE THREAD

**Issue by Leoquicenoz** [wazuh/wazuh-documentation#6978]
## Description
|Wazuh version|Component|
|---|---|
| 4.8.0-alpha2 | Indexer |

## Description
 - Working on the integration of Wazuh with [Elastic in Release 4.8.0 - Alpha 2 - E2E UX tests - Elastic integration](https://github.com/wazuh/wazuh/issues/21382), using the Quickstart installation method for the Wazuh manager, there was an issue because by default it is configured so that this port is accessible by the `ip 127.0.0.1.1:9200` and as the machine that has `Elasticsearch`, `Kibana` and `Logstash` installed has a different `ip`, the communication can be complicated.   

```console

[root@localhost vagrant]# netstat -tuln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:1515            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:1514            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:55000           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp6       0      0 127.0.0.1:9200          :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 127.0.0.1:9300          :::*                    LISTEN     
udp        0      0 10.0.2.15:68            0.0.0.0:*                          
udp        0      0 127.0.0.1:323           0.0.0.0:*                          
udp6       0      0 ::1:323                 :::*

```

I tried to modify the Wazuh configuration files (`./config.yml`, `opensearch.yml`, `filebeat.yml`, among others) to give access to the other machine and I did not succeed, this may be because it was presenting some communication problems with the virtual machine I was using, but perhaps a user who is trying to perform this integration may face the same issue.

**Comment by gdiazlo** [comment]
Wazuh documentation will not cover how to set up and manage Elastic product, they have a great documentation already. Because this issue is related to the execution of a test, we might revisit our test documentation.

**Comment by davidcr01** [comment]
Regarding this, as such it is a consequence of the configuration of the Wazuh indexer. When using the WIA (Wazuh installation assistant) with the -a (AIO) option, the `unattended_installer/config/indexer/indexer_all_in_one.yml` configuration is loaded, which among other things has `localhost` specified in the `network.host`

```yml
network.host: "localhost"
node.name: "node-1"
cluster.initial_master_nodes:
- "node-1"
cluster.name: "wazuh-cluster"
```

This causes port 9200 to be exposed on `127.0.0.1` as you mentioned in the issue, not accessible.
```console
> telnet 192.168.57.203 9200
Trying 192.168.57.203...
telnet: Unable to connect to remote host: Connection refused
```

To solve this scenario, it is a matter of editing the `/etc/wazuh-indexer/opensearch.yml` file where the configuration that has been loaded in the installation is located and changing that localhost to `0.0.0.0`, restarting the Wazuh indexer service with `systemctl restart wazuh-indexer` and the port is as follows:

```console
root@ubuntu22:/home/vagrant# netstat -tuln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State      
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:9200            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:9300            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:1515            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:1514            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:55000           0.0.0.0:*               LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
udp        0      0 127.0.0.53:53           0.0.0.0:*                          
udp        0      0 10.0.2.15:68            0.0.0.0:*   
```

Then, the port is accessible from the outside.
```console
> telnet 192.168.57.203 9200
Trying 192.168.57.203...
Connected to 192.168.57.203.
Escape character is '^]'.
exit
```

Take into account that this may not be the best configuration because of security reasons. It's just an explanation and workaround for this behavior.
