### ISSUE TITLE
Add a warning label for multiple pubsubs in gcp configuration section

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh-documentation#6986]
## Description

The GCP module does not support multiple pubsub configurations in the same _ossec.conf_.

This issue tends to improve the documentation by adding a warning block to state this improve the user experience and avoid future errors.

**Comment by GGP1** [comment]
## Update

Added the warning note in the related files.

**Comment by GGP1** [comment]
## Update

Applied the changes suggested.

**Comment by GGP1** [comment]
## Update

Applied the changes suggested in the code review.
