### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by netflash** [wazuh/wazuh-documentation#7]
Hello, is it possible to rename repo to something like ossec-documentation ?
B/c fork looks a bit strange - netflash/documentation - not really related to anything.

**Comment by santiago-bassett** [comment]
makes sense to me. Let me ask the team about it, to be sure we don't break any kind of automated process.

**Comment by jlruizmlg** [comment]
Hi @netflash now you have the new repo name.

**Comment by netflash** [comment]
Thanks!
