### ISSUE TITLE
Improve the explanation of licenses usage

### ISSUE THREAD

**Issue by TomasTurina** [wazuh/wazuh-documentation#7015]
### Description

As stated in our [documentation](https://documentation.wazuh.com/current/installation-guide/index.html):

> Wazuh is free and open source. Its components abide by the [GNU General Public License, version 2](https://www.gnu.org/licenses/old-licenses/gpl-2.0.en.html), and the [Apache License, Version 2.0](https://www.apache.org/licenses/LICENSE-2.0) (ALv2).

It doesn't really explain which components follow each license (GLP and Apache).

it is necessary to detail this better. Wazuh mostly adopts [GLPv2 license](https://github.com/wazuh/wazuh?tab=readme-ov-file#authors) but there are some components that adopt Apache v2.0, for example:

- Some dependencies listed [here](https://github.com/wazuh/wazuh?tab=readme-ov-file#software-and-libraries-used).
- Filebeat.
- Indexer.
- Dashboard.

Please, review every component and update the documentation accordingly.

**Comment by rauldpm** [comment]
Previously blocked note: `This issue needs to be discussed (ownership, steps to take)`
