### ISSUE TITLE
Add labels to inform on how to fix CentOS 8 package removal from official mirrors

### ISSUE THREAD

**Issue by EduLeon12** [wazuh/wazuh-documentation#7019]
## Description 

During the https://github.com/wazuh/wazuh/issues/21768, it was found that the Wazuh installation assistant failed due to the package mirror list being moved since the packages needed for the installation were not being downloaded properly.
CentOS removed all packages for CentOS 8 official mirrors, They were moved to https://vault.centos.org/. 

This issue should be to confirm if this specific OS restriction should be included in the Wazuh documentation or if due to not being a specific Wazuh installation issue is to be avoided. 

If it is decided to include any label (Note, warning) in the documentation it should be referenced when a centOS-8 package is being installed. For example:
- https://documentation.wazuh.com/current/deployment-options/wazuh-from-sources/wazuh-agent/index.html

#### Documentation solution

Below is the fix for the mentioned problem.

Before installing dependencies run the following:

```command
sed -i -e "s|mirrorlist=|#mirrorlist=|g" /etc/yum.repos.d/CentOS-*

sed -i -e "s|#baseurl=http://mirror.centos.org/|baseurl=http://vault.centos.org/|g" 
/etc/yum.repos.d/CentOS-*
```

**Comment by rauldpm** [comment]
@EduLeon12 Please expand the issue description stating what needs to be changed and where, also, is this issue duplicated from https://github.com/wazuh/wazuh-documentation/issues/5864?

---

>During the https://github.com/wazuh/wazuh/issues/21768, it was found that the Wazuh installation assistant failed due to the package mirror list being moved.
>
>This also needs to be fixed in the other parts of the documentation to avoid further issues during the centOS-8 components installations.

If something needs to be fixed in the Wazuh installation assistant, the correct repository is wazuh-packages, but I do not see any issue related to this in that repository, did you open it?

**Comment by EduLeon12** [comment]
@rauldpm Updated issue description.

**Comment by rauldpm** [comment]
Changed to Blocked status

We need to discuss whether we are going to address system repository deprecation in the documentation

Also, we need to discuss if CentOS 8 should be a recommended system due to repository deprecation

**Comment by davidjiglesias** [comment]
Agreed with @rauldpm
