### ISSUE TITLE
Outdated Amazon Macie configuration guide

### ISSUE THREAD

**Issue by JuanGarriuz** [wazuh/wazuh-documentation#7032]
The document appears to be outdated from 2020 therefore it is difficult to follow as Kinesis, Cloudwatch has all changed drastically from documentation:

[Amazon Macie documentation](https://documentation.wazuh.com/current/cloud-security/amazon/services/supported-services/macie.html#amazon-macie)

[Community related](https://github.com/wazuh/community/issues/19469)

**Comment by DamianNud** [comment]
# Update

I read the outdated guide and investigated about Amazon Macie.

**Comment by DamianNud** [comment]
# Update

I started following the steps detailed in Wazuh's Amazon Macie documentation and recording the steps with the new AWS services involved, which replace the ones mentioned in the guide, also taking screenshots in the process.

**Comment by DamianNud** [comment]
# Update

The Amazon Macie guide has already been updated in [this PR](https://github.com/wazuh/wazuh-documentation/pull/7546).
The specific changes made on the documentation can be seen [here](https://github.com/wazuh/wazuh-documentation/pull/7546/files#diff-f295a73e5439d6951554c3ec98631fbcaafbd51b50ee7a9dc381c421c200a060).
