### ISSUE TITLE
Create migration guide from Elastic 6.x to 7.x

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-documentation#704]
Elastic 7.x will be released in any moment, and we'll need to create a proper migration guide, so the users can upgrade their installations from Elastic 6 to Elastic 7.

We'll need to research and make lots of tests in order to create a migration process that will be formatted into a documentation guide.

The migration guide will include steps for updating the Elastic Stack packages, and also the necessary steps to migrate the 6.x indices to the new 7.x format.

More details and specific tasks will be indicated in the future in this description.

**Comment by jesusgn90** [comment]
Included in https://github.com/wazuh/wazuh-kibana-app/issues/1433, branch already uploaded https://github.com/wazuh/wazuh-documentation/tree/elastic-7
