### ISSUE TITLE
Not able to start the wazuh indexer service 

### ISSUE THREAD

**Issue by Gajendrawepindia** [wazuh/wazuh-documentation#7041]
Give guide to  starting the Wazuh indexer in environments where systemd is not fully supported.

**Comment by rauldpm** [comment]
Hello @Gajendrawepindia, can you tell us more about your problem?

- What specific operating system and version are you using? 
- What version of Wazuh are you using?
- What type of deployment are you doing? Are you deploying it with the installation assistant or step-by-step guide?

Both methods allow components to be started using either `Systemd` or `SysV init`

In the specific case of step-by-step, you can see that both methods are offered when changing the tab.

https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html#starting-the-service

In the case of `Sysv init`, the steps will be:

- If it is an RPM system

> \# chkconfig --add wazuh indexer
> \# start of wazuh-indexer service

- If it is a Debian system

> \# update-rc.d defaults wazuh-indexer 95 10
> \# start of wazuh-indexer service
