### ISSUE TITLE
OS Vulnerability Detection for Ubuntu 23

### ISSUE THREAD

**Issue by gitezri** [wazuh/wazuh-documentation#7055]
I followed https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/allow-os.html to the "T" and still can get anything but: 0 Critical, 0 High, 0 Medium
`root@wazuh:~# sqlite3 /var/ossec/queue/db/global.db "SELECT OS_NAME, OS_MAJOR FROM AGENT WHERE ID = 2;"`
`Ubuntu|23`
```
<provider name="canonical">
    <enabled>yes</enabled>
    <os allow="Ubuntu-23">bionic</os>
    <update_interval>1h</update_interval>
</provider>
```

Help, what am I missing?? Thanks.

**Comment by gitezri** [comment]
Actually it finally just started working
10 critical, 152 high, 223 medium, 28 low.

**Comment by rauldpm** [comment]
Hi @gitezri is your issue solved? If so, please tell us so we can close the issue, thank you!

**Comment by rauldpm** [comment]
Closed due to inactivity
