### ISSUE TITLE
Support new stage RC 2 for 4.7.3 in wazuh-documentation repository

### ISSUE THREAD

**Issue by damarisg** [wazuh/wazuh-documentation#7073]
## Description

This issue attempts to support a new stage RC 2 for 4.7.3 in the wazuh-documentation repository.

#### Upward merging to carry latest production changes to the new stage
- [x] Merge branches upwards up to 4.7.3. Not needed https://github.com/wazuh/wazuh-documentation/compare/4.7.3...4.7

#### Staging preliminary tasks
- [x] Check 4.7.3 documentation `CHANGELOG.md`. Create a PR to update it if necessary. Not needed
- [x] Review changelogs for the following repositories.
  - [x] `wazuh/wazuh`. 
  - [x] `wazuh/wazuh-dasboard-plugins` 
  - [x] `wazuh/wazuh-packages`
- [x] Check 4.7.3 release notes in documentation. Create a PR to update them if necessary. https://github.com/wazuh/wazuh-documentation/pull/7075

#### Staging
- [x] Create tag v4.7.3-rc2 from branch 4.7.3 on wazuh-documentation repository. https://github.com/wazuh/wazuh-documentation/tree/v4.7.3-rc2
- [x] Create and publish a pre-release: https://github.com/wazuh/wazuh-documentation/releases/tag/v4.7.3-rc2.
- [x] Upload docs to https://documentation-dev.wazuh.com/v4.7.3-rc2/.

**Comment by Rebits** [comment]
Waiting feedback for missing entry in changelog https://github.com/wazuh/wazuh/pull/22155

**Comment by QU3B1M** [comment]
LGTM!
