### ISSUE TITLE
Wazuh server ossec.log warning message - "WARNING: vulnerability-detector configuration is deprecated"

### ISSUE THREAD

**Issue by dupuju** [wazuh/wazuh-documentation#7076]
## Deployment requirements

| Component | Installation | Type | OS |
|----------|--------------|------|----|
| Indexer | [Quickstart](https://documentation-dev.wazuh.com/v4.8.0-beta2/quickstart.html) | - | Amazon Linux 2023 x86_64 |
| Server | Same as indexer, all-in-one | - | - |
| Dashboard | Same as indexer, all-in-one | - | - |
| Agent | [Installing Wazuh agents](https://documentation-dev.wazuh.com/v4.8.0-beta2/installation-guide/wazuh-agent/index.html) | - | Windows 11 x86_64, Debian 11 x86_64 |

### Upgrading Wazuh components to 4.8   🔴

9 warnings were reported at the time of the testing Release 4.8.0 - Beta 2 - E2E UX tests - Central components upgrade https://github.com/wazuh/wazuh/issues/22110 . I believe 7 warnings are from enrolling the agent, while 2 warnings are about vulnerability-dectector

```
[root@ip-172-31-42-25 ec2-user]# grep -i -E "error|critical|fatal|warning" /var/ossec/logs/ossec.log  | wc -l
9
[root@ip-172-31-42-25 ec2-user]# cd /var/ossec/logs/wazuh/2024/Feb/
[root@ip-172-31-42-25 Feb]# gunzip -k ossec-27.log.gz
[root@ip-172-31-42-25 Feb]# ls
ossec-27.log  ossec-27.log.gz  ossec-28.log.gz
[root@ip-172-31-42-25 Feb]# cat ossec-27.log
....
2024/02/27 13:15:49 wazuh-modulesd: WARNING: vulnerability-detector configuration is deprecated. Use vulnerability-detection instead.
.....
2024/02/27 13:16:01 wazuh-modulesd: WARNING: vulnerability-detector configuration is deprecated. Use vulnerability-detection instead.


```
A note is advised to be included in the Wazuh manager upgrade guide, so that the users know that a new block (indexer) has been added and that the VD block has changed, so VD will not work as expected. This is inform the users to update the ossec.conf with the new module and add the indexer module if used with a Wazuh indexer component. If the user does not add the new block by hand, the following warning will appear.

**Comment by davidjiglesias** [comment]
We should change this message:

WARNING: vulnerability-detector configuration is deprecated. Use vulnerability-detection instead.

with

WARNING: The "vulnerability-detector" configuration is now obsolete and will not function. Please update your settings to use the new "vulnerability-detection" block for continued vulnerability management. See https://documentation.wazuh.com.
