### ISSUE TITLE
Error in the MS-Graph reference example

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh-documentation#7103]
# Description 

A [community user](https://discord.com/channels/1049711339578331186/1212850257600315463/1212850265384947832) recently found that the [example configuration](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/ms-graph-module.html#example-of-configuration) from the MS-Graph reference contains a mistype in the `<api_auth>` block section. Instead of containing the `api_type` option, the name of the block is repeated. The error is still present in the master branch:
https://github.com/wazuh/wazuh-documentation/blob/5d8e6d5eb17f614f5508604d7cba93f1fa869d16/source/user-manual/reference/ossec-conf/ms-graph-module.rst?plain=1#L278-L283

And the `4.8.0` branch:

https://github.com/wazuh/wazuh-documentation/blob/19f256ad932e6c3cc0e672f3d65ef8c7a18feab5/source/user-manual/reference/ossec-conf/ms-graph-module.rst?plain=1#L278-L283

**Comment by RemiOS0456** [comment]
I am community user in question. Linked for visibility.
