### ISSUE TITLE
macOS Wazuh agent uninstall step fails

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-documentation#7109]
## Description

- Source issue: https://github.com/wazuh/wazuh-jenkins/issues/6341
- OS: macOS 12
- Documentation: https://documentation.wazuh.com/current/installation-guide/uninstalling-wazuh/agent.html#uninstalling-a-macos-wazuh-agent
- https://documentation-dev.wazuh.com/v4.8.0-beta3/installation-guide/wazuh-agent/wazuh-agent-package-macos.html#uninstall-a-wazuh-agent
- Version: 4.8.0

---

When uninstalling the macOS agent, an error is obtained when the following command is executed:

```
sh-3.2# /bin/launchctl unload /Library/LaunchDaemons/com.wazuh.agent.plist
/Library/LaunchDaemons/com.wazuh.agent.plist: Could not find specified service
Unload failed: 113: Could not find specified service
```

We need to fix the documentation with the correct command

```
sh-3.2# installer -pkg agent.pkg -target /
installer: Package name is Wazuh Agent
installer: Upgrading at base path /
installer: The upgrade was successful.
sh-3.2# ls -l /Library/LaunchDaemons/com.wazuh.agent.plist 
-rw-r--r--  1 root  wheel  461 Mar  7 14:42 /Library/LaunchDaemons/com.wazuh.agent.plist
```

---

If this error is related to the package or the source code, please migrate the issue to the related repository

**Comment by vikman90** [comment]
@rauldpm I've tested the install/uninstall procedure, and I got no errors:

## System

macOS Sonoma 14.3.1 (23D60) @ arm64

## Procedure

### Install

```shell
installer -pkg wazuh-agent-4.8.0-1.arm64.pkg -target /
```

> installer: Package name is Wazuh Agent
installer: Installing at base path /
installer: The install was successful.

### Uninstall

```
/Library/Ossec/bin/wazuh-control stop
```

> wazuh-modulesd not running...
> wazuh-logcollector not running...
> wazuh-syscheckd not running...
> wazuh-agentd not running...
> wazuh-execd not running...
> Wazuh v4.8.0 Stopped 

```
/bin/rm -r /Library/Ossec
/bin/launchctl unload /Library/LaunchDaemons/com.wazuh.agent.plist
/bin/rm -f /Library/LaunchDaemons/com.wazuh.agent.plist
/bin/rm -rf /Library/StartupItems/WAZUH
/usr/bin/dscl . -delete "/Users/wazuh"
/usr/bin/dscl . -delete "/Groups/wazuh"
/usr/sbin/pkgutil --forget com.wazuh.pkg.wazuh-agent
```

> Forgot package 'com.wazuh.pkg.wazuh-agent' on '/'.

**Comment by rauldpm** [comment]
@vikman90 I used a macOS 12 Monterey ARM instance
