### ISSUE TITLE
Is it really nessacary to be such a overly complicated task to change from the default credentials anyone can google to find? 

### ISSUE THREAD

**Issue by SHoover80** [wazuh/wazuh-documentation#7144]
Overlooking the obvious security risk this presents by making it so difficult for one to change from the default password I guarantee most of the homelab users still run this with the default credentials. 

So I'm just curious if the methods to change the passwords have changes from what's on  your documentation, YT tutorials, etc? 

To be honest, I havn't even tried the software yet, as the first thing anyone should do when using software to manage network security or any self hosted software is change the $ucking default credentials. And the fact that even by following your documentation with the 20 step process, editing multiple configuration files, running multiple scripts and rebooting services multiple times, only to create more issues due to the over complicated process to do what should be a simple intuitive task. Or the "automated tool" that doesnt work even when copying/pasting the commands posted in your documentation. I still cant change the password. 

So I'm having my doubts of the ability of this software to provide any security bennifit to my network is possible based on the innability to script a functional process to change credentials from the default. I dont know, maybe after user signs in for first time to prompts user for a required password change through the GUI. scripting a option in the GUI to change PW that actually allows you to change the password. 

![image](https://github.com/wazuh/wazuh-documentation/assets/43644167/bc9fd81c-b5a4-4428-acad-71c6fa398c0f)

2FA, authentication, There's many secure options other than making it so difficult to update/change credentials that it's most likely those who use this software will just avoid doing so. 

I'm mostly providing feedback as I dont think I'm going to continue to invest any more of my time looking into this software. When taking a $ucking day of my time, reading page after $ucking page, following multiple steps, watching multiple youtube tutorials just to try and find out how to change the default password. Cant help but wonder where else did they "cut corners" or overlook more secure features.

**Comment by davidcr01** [comment]
Hello.

I recommend you to take a look at our official documentation. All the documentation is tested before its publication and it is the most reliable information source of our tool. 

To change the passwords automatically and easily, we have a dedicated tool that performs these types of operations. I leave you the related documentation: https://documentation.wazuh.com/current/user-manual/user-administration/password-management.html. If you want to change all the passwords, just run `bash wazuh-passwords-tool.sh -A`, just as simple as that.

As you can see, it has some examples of usage to better understand the script. If you want to change only the `admin`, take a look at the dedicated paragraph: https://documentation.wazuh.com/current/user-manual/user-administration/password-management.html#changing-the-password-for-single-user.

Also, I think that the automated tool you mention is the Installation assistant. This tool allows you to install Wazuh easily with one simple command: https://documentation.wazuh.com/current/quickstart.html#installing-wazuh.
Also, this tool changes automatically the passwords of the Wazuh installation, so there is no "default" password or weak password in this deployment. 

Also, I leave you the related documentation about all the user administration: https://documentation.wazuh.com/current/user-manual/user-administration/index.html
