### ISSUE TITLE
Add documentation for Splunk to install it with Indexer cluster architecture

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-documentation#715]
Along with the existing single-instance and multi-instance architectures explained on the Splunk documentation, we now have to add documentation for the [Indexer cluster](http://docs.splunk.com/Documentation/Splunk/7.2.1/Deploy/Indexercluster) architecture.

### Current tasks

- [ ] Write a list of steps to configure this architecture. The list must be clear, minimal but sufficient to get this properly configured.
- [ ] Format the list into documentation format.
- [ ] Follow the documentation after writing it and make sure everything is properly explained and easy to follow.

**Comment by JaoChaos** [comment]
A duplicated issue in #817 -> (https://github.com/wazuh/wazuh-documentation/issues/817)
