### ISSUE TITLE
Add necessary inbound ports for every component

### ISSUE THREAD

**Issue by migruiz4** [wazuh/wazuh-documentation#716]
Hi team,

It is a frequent question what inbound ports are required to be open for Wazuh to work in every instance.

It would be helpful to have this information in the documentation available for everyone. With a detailed explanation of the purpose of each port. For example:
```
- Wazuh Manager:
    1514/udp or 1514/tcp: Remoted - Agents reporting
    1515/tcp: Authd - Agents registering
    1516/tcp: Wazuh cluster
    514/udp or other - if syslog configured
-Wazuh Agent:
    None (inbound)
- Logstash:
    5000/tcp or other: Logstash input port (depends on configuration)
- Elasticseach:
    9200/tcp: Elasticsearch input 
    9300-9400/tcp: Elasticsearch cluster communication
- Kibana:
    5601/tcp: Kibana access
    80/tcp or 443/tcp or other: HTTP or HTTPS access, depends on configuration
```

### Pending tasks

- [x] Add a visual diagram. (@JuanjiJG and @saramoran)
- [x] Add note about inbound ports.
- [x] Split content from tables.
- [x] External references (URLs) for third party software.

### Related PRs

#729 #745

**Comment by JuanjiJG** [comment]
First approach here: #729
