### ISSUE TITLE
Modify AWS supported services index

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh-documentation#7165]
# Description

During the development of the Amazon Security Hub documentation (#6900), it was suggested to modify the `:ref:` command for the `:doc:` command ([PR comment](https://github.com/wazuh/wazuh-documentation/pull/7111#discussion_r1535618858)). The main reason for this change is that `:doc:` references the entire document without adding a custom anchor required by the `:ref:` use which generates a loading delay that needs to be manually modified.

This issue aims to replace every `:ref:` command used in `source/cloud-security/amazon/services/supported-services/index.rst` with `:doc:`, removing the custom anchor from each document to be consistent with the required change and avoid manually crafted modifications when a native one can be used.

**Comment by GGP1** [comment]
## Update

Updated all `:ref:` to `:doc:` and removed their anchors.
