### ISSUE TITLE
offline-url option is not included in the vulnerability detection module documentation

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-documentation#7185]
### Description

The `offline-url` used for [Offline Update](https://documentation-dev.wazuh.com/v4.8.0-beta5/user-manual/capabilities/vulnerability-detection/offline-update.html) is not mentioned in the [vulnerability detection module documentation](https://documentation-dev.wazuh.com/v4.8.0-beta5/user-manual/reference/ossec-conf/vuln-detector.html)

![image](https://github.com/wazuh/wazuh-documentation/assets/11089305/8b58ba3a-144a-4ead-92bb-7f48deebb852)

**Comment by Dwordcito** [comment]
delayed 1 day, waiting the review of @javimed

**Comment by sebasfalcone** [comment]
Issue ready to merge, moved ETA awaiting merge
