### ISSUE TITLE
Include multiple agent assignment to the same group documentation section

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-documentation#7205]
### Description

Include in [Grouping agents](https://documentation.wazuh.com/current/user-manual/agent/agent-management/grouping-agents.html#multiple-groups) documentation page a section about assigning multiple agents to the same group.

As @Selutario commented [here](https://github.com/wazuh/wazuh/issues/8293#issuecomment-823837215), this is possible using the following commands:

- Create a group
```
curl -k -X POST "https://localhost:55000/groups?pretty=true" -H  "Authorization: Bearer $TOKEN" -H  "Content-Type: application/json" -d "{\"group_id\":\"aws_agents\"}"

```
- Assign multiple agents to the same group
```
curl -k -X PUT "https://localhost:55000/agents/group?agents_list=005,004&group_id=aws_agents" -H  "Authorization: Bearer $TOKEN"
```

**Comment by GGP1** [comment]
## Update

Included a new section indicating how to add multiple agents to a single group and how to list the agents belonging to a group.
