### ISSUE TITLE
State the name change in the `<vulnerability-detection>` configuration

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh-documentation#7207]
In v4.8.0, the [\<vulnerability-detector\>](https://github.com/wazuh/wazuh/blob/v4.7.3/etc/templates/config/generic/wodle-vulnerability-detector.manager.template#L1) option has been changed to [\<vulnerability-detection\>](https://github.com/wazuh/wazuh/blob/v4.8.0-beta5/etc/templates/config/generic/wodle-vulnerability-detection.manager.template#L1). We should clearly state the change. For example by adding a note at the beginning of the current [vulnerability-detection](https://github.com/wazuh/wazuh-documentation/blob/4.8.0/source/user-manual/reference/ossec-conf/vuln-detector.rst) section. We should consider adding a "Deprecated" notice at top of the old `vulnerability-detector` as well.

**Comment by sebasfalcone** [comment]
> We should consider adding a "Deprecated" notice at top of the old vulnerability-detector as well.

This file was removed in 4.8.0

**Comment by javimed** [comment]
> > We should consider adding a "Deprecated" notice at top of the old vulnerability-detector as well.
> 
> This file was removed in 4.8.0

I meant to add a "deprecated" notice in previous branches such as 4.7, 4.6 etc. But it's a name change not a real deprecation. Maybe just a note in 4.8+ to warn users of the later versions.
