### ISSUE TITLE
Auditd won't work on newer OSs because of a default audit rule "-a never,task"

### ISSUE THREAD

**Issue by MarcelKemp** [wazuh/wazuh-documentation#7283]
## Description

Due to the problem found in the following issue, and the fact that the tests performed to fix it in the code have been unsuccessful, it has been considered that the best option for `4.9.0` is to leave the responsibility of removing the rule to the user, by adding a note to the documentation informing about the problem in question:
- https://github.com/wazuh/wazuh/issues/19399

Since the Audit daemon also warns about this problem in its documentation:
- [Auditctl man](https://man7.org/linux/man-pages/man8/auditctl.8.html#top_of_page)

```
DISABLED BY DEFAULT     
       On many systems auditd is configured to install an -a never,task
       rule by default. This rule causes every new process to skip all
       audit rule processing. This is usually done to avoid a small
       performance overhead imposed by syscall auditing. If you want to
       use auditd, you need to remove that rule by deleting 10-no-
       audit.rules and adding 10-base-config.rules to the audit rules
       directory.

       If you have defined audit rules that are not matching when they
       should, check auditctl -l to make sure there is no never,task
       rule there.
```

### Tasks
- [x] Add a note, reporting the problem and referring to the Auditctl manual.

**Comment by jotacarma90** [comment]
Issue reopened due to the need to modify the description and advice made on the never,task rule.
We should remove the rule completely as filtering only the syscheck daemon alone may not be allowing to monitor other processes correctly.
