### ISSUE TITLE
Ansible installation documentation update

### ISSUE THREAD

**Issue by adavinchi** [wazuh/wazuh-documentation#7295]
The Wazuh documentation for installation via Ansible is not very clear and there are steps that can be improved. 

1. The `Windows endpoints` subsection is not consistent with similar subsections making it seem like it is a different step rather than an optional step
2. The `Remote Connection` section includes the command `cat ~/.ssh/id_rsa.pub | ssh centos@192.168.33.31 "cat >> ~/.ssh/authorized_keys"` this command fails because the Ansible server does not yet have access to the remote server. this steps is supposed to created the access. It also does not clearly state that some values are placeholders that should be replaced eg `centos`
3. The guide does not clearly separate all-in-one installation from cluster installation.
4. The cluster installation section does not clearly guide the user on how to modify the` /etc/ansible/roles/wazuh-ansible/playbooks/wazuh-production-ready.yml` file

**Comment by teddytpc1** [comment]
Hi, @adavinchi.
Could you update the issue description with links to the documentation and screenshots related to each item, please?
We need it to have a better understanding of what you mean.

**Comment by adavinchi** [comment]
1.  **The Windows endpoints subsection:** This section is found at **Installation alternatives** > **Deployment with Ansible** > **Installation Guide** > **Install Ansible**. This section provides multiple methods for installing Ansible: Centos/rhel/fedora, Debian/ubuntu.

As seen in the image below, the [Windows endpoints](https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/guide/install-ansible.html#windows-endpoints) is under the Installation guide, this is confusing and makes it seem like it is a configuration that is required for installing Ansible. I think it is better suited under the [Remote Connection](https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/guide/install-ansible.html#remote-connection) section so the user understands that this is only related to deploying on Windows agents with Ansible.
<img width="704" alt="image" src="https://github.com/wazuh/wazuh-documentation/assets/120424104/68f029fd-c31a-47f2-a437-fd018f059ea1">

2. [Remote Connection](https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/guide/install-ansible.html#remote-connection): There is a step to run command `cat ~/.ssh/id_rsa.pub | ssh centos@192.168.33.31 "cat >> ~/.ssh/authorized_keys"` in step 3 [here](https://documentation.wazuh.com/current/deployment-options/deploying-with-ansible/guide/install-ansible.html#remote-connection:~:text=.ssh/authorized_keys-,Return,-to%20the%20Ansible)

This commands attempts to use ssh to write the ssh key to the remote server. The document contains an actual IP and user instead of a placeholder and we do not notify the user that the remote user needs to have required permissions on the remote machine. it should be clearer to the user that they need to replace those values.

3. **all-in-one installation and cluster installation not clearly separated**: As seen in the below image, the single node and cluster installation is not clearly separated like in other documentation, for example in [Deployment with puppet](https://documentation.wazuh.com/current/deployment-options/deploying-with-puppet/wazuh-puppet-module/index.html)
<img width="698" alt="image" src="https://github.com/wazuh/wazuh-documentation/assets/120424104/10cbe8e0-4c49-463c-98a4-ebf8b3eeb5d8">

4.  **Cluster installation section does not clearly guide the user on how to modify the `/etc/ansible/roles/wazuh-ansible/playbooks/wazuh-production-ready.yml` file**: The default configuration contains 2 Wazuh nodes, 3 Wazuh indexer nodes, and a Wazuh dashboard node. In a case where the user needs a different architecture, the document does not guide the user on how to modify this document like in other installation document, for example as seen in the puppet documentation:
<img width="707" alt="image" src="https://github.com/wazuh/wazuh-documentation/assets/120424104/17803d24-745d-401e-b6ec-bb5d71932a79">
