### ISSUE TITLE
Amazon Security Lake integration as source blog post

### ISSUE THREAD

**Issue by AlexRuiz7** [wazuh/wazuh-documentation#7303]
## Description

Relates issue: https://github.com/wazuh/wazuh-indexer/issues/204

We have been working on an integration as a [custom source for Amazon Security Lake](https://docs.aws.amazon.com/security-lake/latest/userguide/custom-sources.html). Wazuh has already and integration with ASL, but as a subscriber. As well as it had a [blog post](https://wazuh.com/blog/wazuh-integration-with-amazon-security-lake/) when that integration was released, we'd like to have a blog post for this integration.

From our side, we have generated a [user guide](https://github.com/wazuh/wazuh-indexer/blob/211-amazon-security-lake-integration/integrations/amazon-security-lake/README.md) which is hosted on the wazuh-indexer repository.

We request your help to test the implementation of the integration and generate a blog post about it. We'll be adding a documentation page for it soon in https://github.com/wazuh/wazuh-indexer/issues/211.

Best regards,
Alex.

@Spades0

**Comment by Spades0** [comment]
Blog post published: https://wazuh.com/blog/wazuh-integration-with-amazon-security-lake-as-a-custom-source/
