### ISSUE TITLE
I want to connect a server that other network

### ISSUE THREAD

**Issue by asep3003** [wazuh/wazuh-documentation#7318]
How to connect an agent from other network? pls give me the step by step

**Comment by davidcr01** [comment]
Hello.

You should connect an agent from another network without problems. I recommend you to follow our [documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/index.html) for adding a Wazuh agent to your Wazuh installation.
The step-by-step guide is located inside the type of agent you want to add (depending on its operative system). For example, the Linux documentation for adding the Wazuh agent step-by-step is located in this [documentation](https://documentation.wazuh.com/current/installation-guide/wazuh-agent/wazuh-agent-package-linux.html). 

When specifying the `WAZUH_MANAGER` variable, please specify the public IP address of the Wazuh manager. Please, make sure that the new agent you want to add and the system with the Wazuh manager installed can reach to each other. You can check this connectivity with the `telnet` tool for example.
With this, you should be able to add a Wazuh agent from another network.

Hope it helps.
