### ISSUE TITLE
Missing variables in the internal configuration documentation for the Vulnerability Detection module.

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh-documentation#7336]
## Description

Due to the recent changes related to the Vulnerability Detection module, I think it is necessary to add in the documentation the following variables in the internal configuration page:

- `vulnerability-detection.remediation_lru_size`
- `vulnerability-detection.disable_scan_manager`

These two variables are not currently included in the [documentation](https://documentation-dev.wazuh.com/v4.8.0-rc3/user-manual/reference/internal-options.html#vulnerability-detection:~:text=1%20and%20300.-,Vulnerability%20Detection,-Permalink%20to%20this).

**Comment by sebasfalcone** [comment]
Despite being in 4.9.0 release, the changes should impact 4.8.0

**Comment by sebasfalcone** [comment]
Attempt to fix this in the same PR as
- https://github.com/wazuh/wazuh-documentation/issues/7337
