### ISSUE TITLE
Add documentation on how to disable/enable vulnerability detection in the Manager

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh-documentation#7337]
## Description

After talking to @Rebits, we think it would be useful to include in the [Vulnerability Detection](https://documentation-dev.wazuh.com/v4.8.0-rc3/user-manual/capabilities/vulnerability-detection/index.html) module documentation specific information on how to disable/enable vulnerability detection in the manager with the `vulnerability-detection.disable_scan_manager` option in the `internal_options.conf` file, as there is currently no mention of this.

In addition, it should take into account what has been reported in this [issue](https://github.com/wazuh/wazuh/issues/23668).

**Comment by sebasfalcone** [comment]
Despite being in 4.9.0 release, the changes should impact 4.8.0

**Comment by sebasfalcone** [comment]
Attempt to fix this in the same PR as
- https://github.com/wazuh/wazuh-documentation/issues/7336

**Comment by sebasfalcone** [comment]
This feature won't be documented since it was decided when it was implemented
- https://github.com/wazuh/wazuh/issues/22059

See "special considerations"
