### ISSUE TITLE
Rework documentation for Elastic Stack SSL and security

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-documentation#734]
We need to review and rewrite the documentation available [here](https://documentation.wazuh.com/current/installation-guide/optional-configurations/index.html) for securing the Elastic Stack.

**Comment by JaoChaos** [comment]
- Removed different notes and options that were unnecessary.
- Added a section explaining user authentication methods Elastic supports:
  - SAML
  - Kerberos
  - LDAP user
  - PKI user
  - Native user

**Comment by JaoChaos** [comment]
Added new section with "Kibana keystore"

**Comment by JaoChaos** [comment]
Testing the Securing Wazuh:
  - [ ] Kibana with Nginx
  - [ ] searchguard
  - [ ] Logstash and Elasticsearch SSL
  - [ ] X-Pack
  - [ ] Kibana keystore
