### ISSUE TITLE
Outdated architecture diagram

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh-documentation#7513]
## Description
The current architecture doesn't reflect the new capabilities of the **Wazuh Server** to interact directly with the **indexer**, via the **Vulnerability Detector** module

![image](https://github.com/wazuh/wazuh-documentation/assets/34063881/dc93dd40-8b39-40dc-8c5d-4710aadb58fc)

Also, we should update the [Wazuh Server - Wazuh indexer communication](https://documentation.wazuh.com/current/getting-started/architecture.html#wazuh-server-wazuh-indexer-communication) section to reflect this changes

Original:
> The Wazuh server uses Filebeat to send alert and event data to the Wazuh indexer, using TLS encryption. Filebeat reads the Wazuh server output data and sends it to the Wazuh indexer (by default listening on port 9200/TCP).

Added behaviour:
> Similarly, the Vulnerability Detector module generates alerts and updates the vulnerability inventory.

> [!IMPORTANT]
> Given that this feature was added in 4.8.0, we are going to add this to the 4.8 project

## DoD
- [x] Update the architecture diagram
- [x] Update the Wazuh Server - Wazuh indexer communication section

**Comment by sebasfalcone** [comment]
## Update
New diagram
![image](https://github.com/user-attachments/assets/9f4c62bb-189a-4e79-ae72-ca292b2097a5)

**Comment by GabrielEValenzuela** [comment]
# Update

- Task complete. Awaiting review.
