### ISSUE TITLE
Add new GET /agents/uninstall endpoint documentation

### ISSUE THREAD

**Issue by RamosFe** [wazuh/wazuh-documentation#7533]
# Description

As part of [Wazuh agent package uninstallation protection for Linux #23466](https://github.com/wazuh/wazuh/issues/23466), the documentation needs to be updated with the related information about the `GET /agents/uninstall` endpoint to be added, initially carried out in [SPIKE - Define the API schema for the validation request for the uninstallation process](https://github.com/wazuh/wazuh/issues/24369).

Tasks:
- [x] Add the new RBAC action to the [RBAC Reference](https://documentation.wazuh.com/current/user-manual/api/rbac/reference.html#id1).

**Comment by GGP1** [comment]
## Update

Added the new RBAC action to the reference. Changes related to the agent `anti_tampering` configuration will be added by the Agent team.

**Comment by RamosFe** [comment]
## Review

As mentioned in https://github.com/wazuh/wazuh-documentation/issues/7533#issuecomment-2307258693, the documentation related to the agent `anti_tampering` will be added in https://github.com/wazuh/wazuh-documentation/issues/7562.
