### ISSUE TITLE
Improve agent status polling for distributed/clustered architectures

### ISSUE THREAD

**Issue by JuanjiJG** [wazuh/wazuh-documentation#755]
Hello team,

Regarding [this issue](https://github.com/wazuh/wazuh-documentation/issues/254), we've found that the current implementation of the agents status polling script doesn't work on distributed architectures (those using search peers).

The script expects a specific index to be on the same instance where the Wazuh app is installed, but the distributed architecture doesn't configure any indexes on the search head instance.

For a future enhancement, the script could be improved to make it work properly using the multi-instance architecture.

Regards,
Juanjo

**Comment by jesusgn90** [comment]
@JuanjiJG I'm going to close this ticket, in any case, take a look at the above comment from @manuasir and put it well formatted in our documentation
