### ISSUE TITLE
Agent Registered Twice

### ISSUE THREAD

**Issue by agentsofshield** [wazuh/wazuh-documentation#756]
Hey
I added a new wazuh agent on a RHEL5.1
The manager wrote "Never connected" on that agent when i run the "agent-control -l" command.
I tried to register the same agent again via certification. Now i see the same agent twice on the list- one is still "Never connected" and the second one is "Active".

On the agent i can see the new conf file i spreaded, but it has not applyed yet.
The agent does not commiunicate with the manager.

What can i do?

Thank you,
Agentsofshield

**Comment by JuanjiJG** [comment]
Hello @agentsofshield,

To remove the previous agent, you can use the `manage_agents` tool on the manager.

As you can see in [our documentation](https://documentation.wazuh.com/current/user-manual/agents/command-line/remove.html), you can remove an agent without confirmation if you use the `-r` flag:

```
/var/ossec/bin/manage_agents -r <AGENT_ID>
```

Being `<AGENT_ID>` the ID fo the agent that you want to remove. After that, be sure to restart the Wazuh manager:

```
systemctl restart wazuh-manager
```

I assume that when you're talking about "the new config file I spreaded" you mean a centralized configuration file or "[grouping agents](https://documentation.wazuh.com/current/user-manual/agents/grouping-agents.html)". In that case, be sure to restart the Wazuh agent so that it will apply the new configuration:

```
service wazuh-agent restart
```

Let me know if this helps you.

Regards.
Juanjo

**Comment by agentsofshield** [comment]
Thanks for the quick reply.
I was talking about the ossec.conf file in the "shared" directory.

Which agent should i remove? The one that is "Never connected"?
Will the second one starts communicationg after I restart the service?

**Comment by JuanjiJG** [comment]
If the second registration were right and it's showing "active", then you should remove the agent registration whose status is "Never connected".

After restarting both manager and agent, the `agent_control` tool should indicate an "Active" status, which means that they're properly communicating.

About the "ossec.conf" file, could you please indicate the absolute path? As far as I'm concerned, there's no "ossec.conf" file on the "/var/ossec/etc/shared" folder, but an "agent.conf" file, where the centralized configuration is stored.

**Comment by JuanjiJG** [comment]
@agentsofshield, try the following steps to check your connection between the agents and the manager:

1. Check that you added the proper manager's IP address on your agent's configuration file, located at:
   ```
   /var/ossec/etc/ossec.conf
   ```
   If you didn't add it previously, you'll have to edit the file and then restart the Wazuh agent.

2. Check that your agent is properly working on the port 1514:
   ```
   netstat -punta | grep 1514
   ```

Let me know about the results.

Regards,
Juanjo

**Comment by agentsofshield** [comment]
After i registered the agent again I used the command '/var/ossec/bin/ossec-control restart' and i got some error masssages:

![error](https://user-images.githubusercontent.com/40832804/50396130-845e1280-0770-11e9-963e-2c04a5343242.png)

**Comment by JuanjiJG** [comment]
@agentsofshield, as stated in the [documentation](https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html):

> When setting up remote commands in the shared agent configuration, **you must enable remote commands for Agent Modules**. This is enabled by adding the following line to the `/var/ossec/etc/local_internal_options.conf` file in the agent:
>```
>wazuh_command.remote_commands=1
>```

Edit the internal options to enable remote commands, and restart the Wazuh agent one more time.

Regards,
Juanjo

**Comment by agentsofshield** [comment]
It works!!

I just have one more question- after i deleted the agent and registered it again it got a new ID. Is there a way to permanently delete the previous agent so that the IDs will be consecutive?

**Comment by JuanjiJG** [comment]
Hi @agentsofshield,

For now, there is no automatic way to do that. Agent IDs are not supposed to be reused.

If you want to change an agent ID, you can kill the process "ossec-authd" and manually edit the file "/var/ossec/etc/client.keys". Then, you must copy the exact line to the corresponding agent.

In any case, we don't recommend that you perform these steps, and let the agent IDs be assigned automatically.

Regards,
Juanjo

**Comment by agentsofshield** [comment]
Thank you for all your help!

**Comment by JuanjiJG** [comment]
You're welcome @agentsofshield,

I'll proceed to close this issue. Feel free to open a new one if you have more questions.
