### ISSUE TITLE
Improve Ansible deployment documentation for multi-node installation

### ISSUE THREAD

**Issue by pereyra-m** [wazuh/wazuh-documentation#7575]
## Description

This issue was created during the E2E testing https://github.com/wazuh/wazuh/issues/24838.
The documentation section https://documentation-dev.wazuh.com/v4.9.0-alpha3/deployment-options/deploying-with-ansible/index.html should be improved.

A previous E2E test (https://github.com/wazuh/wazuh/issues/23239) already generated documentations improvements (#7295), but I as a tester consider that the guide still isn't detailed enough to allow users to completely deploy a Wazuh multi-node installation with Ansible.

### Warning message during Ansible installation (low impact)

During installation, these commands
```
echo "deb http://ppa.launchpad.net/ansible/ansible/ubuntu trusty main" | sudo tee -a /etc/apt/sources.list.d/ansible-debian.list
apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 93C4A3FD7BB9C367
apt-get update
```

Generates the following warnings

```
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).

W: http://ppa.launchpad.net/ansible/ansible/ubuntu/dists/trusty/InRelease: Key is stored in legacy trusted.gpg keyring (/etc/apt/trusted.gpg), see the DEPRECATION section in apt-key(8) for details.

```

It should be verified that it won't impact in the installation process in the near future.

### The SSH configuration could be clearer (medium impact)

The steps 3 and 4 under **Configuring SSH key-pairing** could be more clear about the fact that the following command will request a password

```
cat ~/.ssh/id_rsa.pub | ssh <USERNAME>@<REMOTE_SERVER_IP_ADDRESS> "cat >> ~/.ssh/authorized_keys"
```

And after this, the password will no longer be required.
If we don't update this section, it's confusing that the `ssh` command is used in the suggested command but then, in the last step, it is tested again.

### Include an example for many Ansible endpoints (high impact)

Under **Testing the Ansible connection to remote endpoints**, there is only an example for `all-in-one deployment`. 
It would be useful an example for many endpoints.

### The folder /etc/ansible doesn't exist (low impact)

We could add an extra step for creating the folders `/etc/ansible` and `/etc/ansible/roles` because they don't exist after the installation of Ansible.

### A full example for multi-node installation is missing (high impact)

The documentation doesn't guide the user for a complete multi-node installation.
It names many thing (roles, etc.) but it lacks of a step-by-step guide. The examples of `/etc/ansible/hosts` only show an all-in-one installation, and many roles require specific groups that aren't named (`[wi_cluster]` for example)

 Also:
- The `wazuh-indexer` role has some dependencies (like `gpg`) that aren't detailed, so the playbook fails if they aren't installed. We should indicate its installation or make the script to automatically install them
- The certificates aren't created if the folder `playbooks/indexer/certificates/` exists but it's empty.

## DoD

- [ ] All suggestions were considered, and implemented/rejected after consideration.
- [ ] The full guide was tested again with a clean environment to verify it works

**Comment by juliamagan** [comment]
This issue will be worked by @wazuh/devel-devops and the PR will be reviewed by @javimed.

**Comment by vcerenu** [comment]
I've been working on improving Ansible Installation and SSH connection, these are the screenshots of the changes:
![image](https://github.com/user-attachments/assets/3544832b-f41c-440b-bf37-2334970940d6)

![image](https://github.com/user-attachments/assets/2d64b050-89de-4f47-9f27-4544501cd39d)

**Comment by teddytpc1** [comment]
It's been decided to fix this kind of issues as part of the DevOps overhaul for 5.0.0.
