### ISSUE TITLE
Docker Volumes Certs Error

### ISSUE THREAD

**Issue by xafirox2** [wazuh/wazuh-documentation#7619]
When generating the certificates using step listed in documentation:

docker-compose -f generate-indexer-certs.yml run --rm generator

Errors occur that prevent Wazuh containers from starting:

cp: cannot overwrite directory '/certificates/admin-key.pem' with non-directory
cp: cannot overwrite directory '/certificates/admin.pem' with non-directory
cp: cannot overwrite directory '/certificates/root-ca.pem' with non-directory
cp: cannot overwrite directory '/certificates/wazuh.indexer-key.pem' with non-directory
cp: cannot overwrite directory '/certificates/wazuh.indexer.pem' with non-directory
cp: cannot overwrite directory '/certificates/wazuh.manager-key.pem' with non-directory
cp: cannot overwrite directory '/certificates/wazuh.manager.pem' with non-directory

**Comment by davidcr01** [comment]
Hello. 
- Could you please tell me the exact steps you are performing here? 
- Is the error generated when using the certificates generator? 
- Do you have a previous Wazuh docker deployment?
- What version of Wazuh are you using?

It seems that the Wazuh docker certificate generator is not able to copy the certificates into the destination folder. Can you please try to remove the `/config/wazuh_indexer_ssl_certs` directory (where the certificates are created), and try to create them again with the `docker-compose -f generate-indexer-certs.yml run --rm generator` command?
