### ISSUE TITLE
Remove SCA for Rocky Linux 8 from the available policies

### ISSUE THREAD

**Issue by lchico** [wazuh/wazuh-documentation#7624]
# Description

According to the [documentation](https://documentation.wazuh.com/current/user-manual/capabilities/sec-config-assessment/available-sca-policies.html#:~:text=Rocky%20Linux%208-,Rocky%20Linux%208,-cis_debian7) we are supporting SCA for Rocky Linux 8 on wazuh-agent 4.8.1 but this will be only available on 4.9.0. 

You can confirm this by visiting these links:

- https://github.com/wazuh/wazuh/issues/22044
  - **`4.8.1`**: https://github.com/wazuh/wazuh/tree/v4.8.1/ruleset/sca
  - **`4.9.0`**: https://github.com/wazuh/wazuh/tree/v4.9.0-alpha3/ruleset/sca

# Task

- [ ] Remove support SCA for Rocky Linux 8 on wazuh-agent 4.8.1

**Comment by vikman90** [comment]
## Update

I've created PR #7644 again, in order to change the branch's name.
