### ISSUE TITLE
Installation from sources fails in Debian 10

### ISSUE THREAD

**Issue by rauldpm** [wazuh/wazuh-documentation#7645]
## Description

The APT installation from sources is falling due to GCC steps, based on https://github.com/wazuh/wazuh/issues/25071#issuecomment-2271192576, the current steps should work for Debian 11-based systems as there is a base GCC version change.

We should add a note about the GCC version required or say something about system requirements/restrictions

- https://documentation-dev.wazuh.com/v4.9.0-beta1/deployment-options/wazuh-from-sources/wazuh-agent/index.html

**Comment by mjcr99** [comment]
## Update
**(08/08/2024)** Opened PR with the proposed solution.
