### ISSUE TITLE
The key location in the agentless connection document is in the /var/ossec/.ssh/ directory.

### ISSUE THREAD

**Issue by hcql** [wazuh/wazuh-documentation#7666]
The key location generated by sudo -u wazuh ssh-keygen is in the /var/ossec/.ssh/directory.

The ssh-copy-id command should specify the key location

ssh-copy-id -i /var/ossec/.ssh/id_rsa.pub user@test.com`

**Comment by hcql** [comment]
![image](https://github.com/user-attachments/assets/b87fae94-d8b8-4a84-8d0c-03debb0a0a94)

**Comment by davidcr01** [comment]
Hello.

Yes, as you reported, I could reproduce that the location where the new SSH key is generated is wrong in [this](https://documentation.wazuh.com/current/user-manual/capabilities/agentless-monitoring/connection.html#endpoints-with-public-key-authentication) documentation.

```
sh-4.2$ sudo -u wazuh ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/var/ossec/.ssh/id_rsa):
```

The key is generated in the `/var/ossec/.ssh/`, not in the `~/.ssh/` path. It would be desirable that the `ssh-keygen` command in our documentation specifies a standard directory, in order not to have these mistakes. However, take into account that, when you execute the `ssh-keygen` command, it will ask you for a location where you want to save the output file, just for your information.

I will notify the related team about this change and we will fix this mistake in future releases. Thank you!

**Comment by pereyra-m** [comment]
## Update

I update the documentation with the requested change.

**Comment by sebasfalcone** [comment]
## Issue concluded
The changes in documentation are merged
