### ISSUE TITLE
Add the need of wazuh-install.sh file in Offline Installation process

### ISSUE THREAD

**Issue by CarlosALgit** [wazuh/wazuh-documentation#7670]
During the [test of the Installation Assistant for 4.9.0-beta2](https://github.com/wazuh/wazuh/issues/25170), I deployed a Wazuh AIO using the Offline Installation method.

I used an instance with internet connection to download the packages and configuration files and then copied the files to the instance where Wazuh was going to be deployed.

Following strictly the documentation does not mention you have to also have a copy of the `wazuh-install.sh` file in the host you want to perform the installation. It only says you need a copy of wazuh-install-files.tar and wazuh-offline.tar files as seen on the following image:
![imagen](https://github.com/user-attachments/assets/eb98b20d-1944-4923-91d9-53639e2641cd)

So, it's required to add the need of having the `wazuh-install.sh` file in the host the Offline Installation is going to be done.

**Comment by davidcr01** [comment]
Also, it is necessary to add the `--offline-installation` parameter in [this](https://documentation-dev.wazuh.com/v4.9.0-beta2/deployment-options/offline-installation/installation-assistant.html#installing-the-wazuh-indexer) documentation, specifically in the `--start-cluster` step. Related: https://github.com/wazuh/wazuh-packages/issues/3072
