### ISSUE TITLE
Update redirect link for readthedocs.io

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-documentation#771]
https://wazuh-documentation.readthedocs.io/ redirects to https://documentation.wazuh.com/1.1/+path which currently causes a 404. 

It should point to https://documentation.wazuh.com/current/+path to avoid this. If there's no access to edit the readthedocs a redirect could be put in place for all /1.1/ requests.

Also this redirect only works when javascript is enabled for readthedocs so search engines might not benefit from it.

**Comment by snaow** [comment]
Hi,

We are no longer using `readthedocs` hosting, we should deprecate it and warn the community.
I have just stopped the redirection and the automatic builds in the RTD project.

Here: https://readthedocs.org/projects/wazuh-documentation/

Regards,
Pedro.
