### ISSUE TITLE
Restore AIX packages and purge Alpine references

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-documentation#7726]
# Description

It was found that, based on the following decisions towards 4.9.0, we need to fix:

- Restore AIX at package list: wrongly removed here https://github.com/wazuh/wazuh-documentation/pull/7684
- Purge documentation for Alpine agents: [not only packages](https://github.com/wazuh/wazuh-documentation/issues/7445) but [source compilation](https://github.com/wazuh/wazuh-packages/issues/3012#issuecomment-2186026225).

*NOTE*: Remember to add this as a breaking change or something similar.

**Comment by javimed** [comment]
@jnasselle only major versions come with a release note with breaking changes. What do you mean by adding ome kind of breaking change in 4.9? Do you mean to make a mention in the Wazuh documentation changelog entry for this PR?
