### ISSUE TITLE
E: Unable to locate package wazuh-indexer

### ISSUE THREAD

**Issue by emptymalicious** [wazuh/wazuh-documentation#7741]
Halo Wazuh Teams,

Im deploying wazuh indexer on my local mac Virtual Machine. and i found an error says "E: Unable to locate package wazuh-indexer". Im using Mac with ARM arch. and the VM spesification are:
OS: Ubuntu 22.04
Arch: aarch64
is there any limitation for installing wazuh indexer on these?

Thank you
![Screenshot 2024-09-06 at 15 08 27](https://github.com/user-attachments/assets/86299129-7f96-47ae-8c1e-60e2682848f3)

**Comment by hossam1522** [comment]
Hi @emptymalicious,

Based on the information you've provided, it seems that the issue arises from the fact that you're running an ARM-based architecture (aarch64) on your Mac's Virtual Machine (Ubuntu 22.04). Currently, Wazuh Indexer is supported on AMD64/x86_64 architectures, and that is the reason the package isn't available for your specific deployment.

If you want to use an Intel architecture, you can use a virtualization tool like Rosseta 2 to deploy a VM environment. You can follow the official documentation to install the Wazuh indexer for the supported architectures: https://documentation.wazuh.com/current/installation-guide/wazuh-indexer/step-by-step.html.

If you have any further questions or need additional guidance, feel free to ask.

Best regards,
Hossam
