### ISSUE TITLE
Support new stage xx 1 for x.x.x in wazuh-documentation repository

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-documentation#7772]
## Description

This issue attempts to support a new stage xx 1 for x.x.x in the wazuh-documentation repository.

#### Upward merging to carry latest production changes to the new stage
- [ ] Merge branches upwards up to x.x.x.

#### Staging preliminary tasks
- [ ] Check x.x.x documentation `CHANGELOG.md`. Create a PR to update it if necessary.
- [ ] Review changelogs for the following repositories.
  - [ ] `wazuh/wazuh`
  - [ ] `wazuh/wazuh-dasboard-plugins`
  - [ ] `wazuh/wazuh-packages`
- [ ] Check x.x.x release notes in documentation. Create a PR to update them if necessary.

#### Staging
- [ ] Create tag vx.x.x-xx1 from branch x.x.x on wazuh-documentation repository.
- [ ] Create and publish a pre-release: https://github.com/wazuh/wazuh-qa-automation/releases/tag/vx.x.x-xx1.
- [ ] Upload docs to https://documentation-dev.wazuh.com/vx.x.x-xx1/.

**Comment by juliamagan** [comment]
This issue was a test
