### ISSUE TITLE
Inaccurate OS compatibility on Packages List section

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-documentation#7795]
# Description

It seems that there are several inaccurate statements on https://documentation.wazuh.com/current/installation-guide/packages-list.html regarding OS compatibility

- https://github.com/wazuh/wazuh/issues/25921 (kudos to @dstr-wpd): armhf deb is supported since Debian Stretch based on https://github.com/wazuh/wazuh/blob/v4.9.0/packages/debs/armhf/agent/Dockerfile#L1
- https://github.com/wazuh/wazuh-documentation/issues/7785 (kudos to @vnasser): Raspbian is an arm-based OS, so the package

This list should be checked exhaustively.

**Comment by vikman90** [comment]
We will continue on #7785
