### ISSUE TITLE
MD5 correct for wazuh-api_2.1.0-1xenial_amd64.deb?

### ISSUE THREAD

**Issue by starlton-eb** [wazuh/wazuh-documentation#78]
Could be something I am doing wrong but when I run an md5 checksum for:

https://packages.wazuh.com/apt/pool/xenial/main/w/wazuh-api/wazuh-api_2.1.0-1xenial_amd64.deb

I get: 1ba518802ea5a0bbd85524e8b02df28b
which doesn't match checksum: ff44c351de4ba1866fe8f8d669a6b07a

The other two matched as expected so it is concerning.

**Comment by erseco** [comment]
We have checked the source and it was a mistake in the documentation. All the md5 checksum of wazuh-api .deb files are wrong. The wazuh-api was not compromised :)

https://github.com/wazuh/wazuh-documentation/commit/920bce240c0ddb0aaac5c24cc8446aac6d9e9fe7#diff-7f066932e626b3e7bd4a9c8dcece6422L190

Thank you for your help!

**Comment by starlton-eb** [comment]
Thanks appreciate confirming this.
