### ISSUE TITLE
Update the WPK package generation documentation for macOS to include support Apple Silicon

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-documentation#7813]
**Parent issue:**
- https://github.com/wazuh/wazuh/issues/25976

## Description

The current WPK package generation documentation for macOS only references Intel architecture. This documentation needs to be updated to include instructions for creating WPK packages for both Intel and arm64. The Intel example should be highlighted as a basic reference, with instructions for arm64 following.

## Tasks

- [ ] Update the documentation to include steps for generating WPK packages for macOS (Intel and arm64).
- [ ] Mention that the Intel steps serve as an example.

## Definition of Done

- The WPK package generation documentation mentions that both Intel and arm64 architectures are supported.
- The steps are clear, and the Intel example is properly referenced.

**Comment by mjcr99** [comment]
## Update
**(14/10/2024)** Reviewed present documentation. Added reference to the WPK list, currently reviewing references in the WPK generation documentation.
