### ISSUE TITLE
Vulnerability Detector - Improve alert generation documentation

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh-documentation#7832]
## Description
We noticed that users have recurrent questions regarding alert generation. It seems like the documentation is not clear enough on how and when the alerts are generated

We need to update the [alert generation documentation](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/how-it-works.html#alert-generation) to better reflect alert generation scenarios 

> [!NOTE]
> Users tend to restart the agent expecting for alerts to be generated when this is not the case.

## DoD
- [x] Diagram updated
- [x] Further explained via text

**Comment by pereyra-m** [comment]
## Update

I begin to write the explanation of the module behavior.

**Comment by pereyra-m** [comment]
## Update

Now that I have the draft of the written changes, I need to create the new image

**Comment by sebasfalcone** [comment]
## ETA update
Due to higger priority issues, the ETA was delayed

We have yet to request the @wazuh/marketing team for the diagrams generation and the documentation team for their review

**Comment by pereyra-m** [comment]
## Update

I apply the changes after the review

**Comment by pereyra-m** [comment]
## Update

I apply new changes after review.

**Comment by sebasfalcone** [comment]
## Update
New graphs provided
![Image](https://github.com/user-attachments/assets/86549419-a2f7-4883-838d-d1ee57bb5a22)

**Comment by pereyra-m** [comment]
## Update

I take the v4.8 changes to a v4.9 PR.

**Comment by sebasfalcone** [comment]
## Updated diagram
![Vulnerability-scanner-alert-generation-ver2](https://github.com/user-attachments/assets/ddb42b9e-27bd-432a-a5e7-92bef4ecb2d1)

**Comment by pereyra-m** [comment]
## Update

I've updated the PRs with the new image

**Comment by pereyra-m** [comment]
@sebasfalcone 
The PRs were merged but the issue is still open
