### ISSUE TITLE
Extend anti-flooding explanation for all Wazuh modules

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-documentation#784]
This [section](https://documentation.wazuh.com/3.x/user-manual/capabilities/antiflooding.html#anti-flooding-in-agent-modules) explains that the OpenSCAP module sends the events at a regulated speed to avoid flooding. 

However, this functionality has already been extended to the rest of the modules.

**Comment by JaoChaos** [comment]
Hi team, 
I'm researching the different modules where it has been extended, and I'm trying to document with the largest explanations every module.

This will take time so I will keep a log over here.

Regards,
Juan Anaya Ortiz.

**Comment by JaoChaos** [comment]
- [ ] OpenSCAP
- [ ] Log Collector
- [ ] Rootcheck
- [ ] Syscheck
- [ ] Agent Daemon

**Comment by JaoChaos** [comment]
Added new modules in PR: https://github.com/wazuh/wazuh-documentation/pull/925
