### ISSUE TITLE
Update CCS setup blog to work with Vulnerability Scanner

### ISSUE THREAD

**Issue by MiguelazoDS** [wazuh/wazuh-documentation#7842]
# Description 

A [user](https://wazuh.slack.com/archives/C07CCCCGHHP/p1726500297099159) reported that the scanner was not working properly

After troubleshooting, the user shared the configuration used for the UI stack. Cross-Cluster Search detailed [here](https://wazuh.com/blog/managing-multiple-wazuh-clusters-with-cross-cluster-search/?highlight=mssp). 

<details><summary> CCS architecture </summary>

![image](https://github.com/user-attachments/assets/04068f86-cc44-4060-8724-fd9310ad441f)

</details>

## Conclusion

The manager was properly configured and the indexer directly connected to the manager has the information indexed, but the dashboard could not display the information in the dashboard. 

## DoD 

This issue was created to investigate this setup and find a solution or the required changes through all the components to make this work.

**Comment by sebasfalcone** [comment]
Blog already updated
