### ISSUE TITLE
Outdated authd documentation

### ISSUE THREAD

**Issue by SitoRBJ** [wazuh/wazuh-documentation#787]
Hello team,

The section in which we use the **auhtd** registration service with passwords is outdated.
 
https://documentation.wazuh.com/current/user-manual/registering/use-registration-service.html#password-authorization

In the second point of section 1. 

_If no password is specified on /var/ossec/etc/authd.pass, the registration service will create a password itself and tell you what it is on the console output:_

```
# /var/ossec/bin/ossec-authd -P

Accepting connections on port 1515. Random password chosen for agent authentication: abdc1234
```

If we execute the command `/var/ossec/bin/ossec-authd -P` we do not get any response in the output of the console. Instead, we can see the output in `/var/ossec/logs/ossec.log`.

Another option could be to add the `-f` option to the command:

`/var/ossec/bin/ossec-authd -fP`

We also do not have any section that comments the entry `<use_password>` in `ossec.conf`.

Finally, mention that in version 3.8 of Wazuh this registration daemon will come running and we would have to adapt the documentation. 

Best regards,

Alfonso Ruiz-Bravo

**Comment by JaoChaos** [comment]
Hello @SitoRBJ:
Thanks for your report, I'm on it right now.

I've added all the changes you propose and actually I'm testing all that options to check if everything works well.

Best regards,

Juan Anaya Ortiz.
