### ISSUE TITLE
template_file.json not found

### ISSUE THREAD

**Issue by Jskobos** [wazuh/wazuh-documentation#79]
In the **ElasticSearch** section of the **Install ElasticSearch with RPM** Guide, step 3 includes a request for `template_file.json`:

`$ curl https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/master/server/startup/integration_files/template_file.json | curl -XPUT 'http://localhost:9200/_template/wazuh' -H 'Content-Type: application/json' -d @-
`
The initial curl command returns a 404, and I can't find a matching file anywhere in the Wazuh repo.

**Comment by jlruizmlg** [comment]
Hi @Jskobos if you are trying to install the latest stable (2.1.1) version with Elastic 5.6.2, please follow the next link:

https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_rpm.html#elasticsearch
