### ISSUE TITLE
Update API configuration sections for IPv6 connections

### ISSUE THREAD

**Issue by fdalmaup** [wazuh/wazuh-documentation#7921]
# Description

In https://github.com/wazuh/wazuh/issues/24981, the team has modified the API configuration to accept IPv6 connections. The changes carried out were not reflected in the documentation which might mislead the users if they do not review the `api/api/configuration/api.yaml` file:
![image](https://github.com/user-attachments/assets/b224d94d-9bd7-4421-9b4e-398686e244d1)

This issue aims to update the sections where the API host is mentioned as a string, not an array.

**Comment by GGP1** [comment]
## Update

I applied the changes to the documentation and opened a pull request pointing to the `4.9` branch (production).
