### ISSUE TITLE
The documentation of the registration service using SSL could have a better explanation

### ISSUE THREAD

**Issue by Skeptor** [wazuh/wazuh-documentation#794]
I think the explanation of how to verify the manager and the agents via SSL is poor and we have to clarify that part of the documentation.
I think a visual schema would be so useful and it can resolve the initial doubts presented reading the functionality for the first time.

- [x] Added SSL agent->manager flow diagram.
- [x] Added SSL manager->agent flow diagram.
- [x] Added notes to clarify the connection warning.

**Comment by JaoChaos** [comment]
- [ ] Add information about the 2 types of validations.
