### ISSUE TITLE
Incorrect log sample given in Sibling Decoders section

### ISSUE THREAD

**Issue by jftuduri** [wazuh/wazuh-documentation#7954]
# Description

The log example given in the Practical Example section for Sibling Decoders is incorrect and does not give the expected output when used in logtest as is stated in the documentation.
https://github.com/wazuh/wazuh-documentation/blob/7c6d963e91913f2a57e707dec2480d1fe5ae2423/source/user-manual/ruleset/decoders/sibling-decoders.rst?plain=1#L50

It should be replaced by 
```
Apr 12 14:31:38 hostname1 securityapp: INFO: srcuser="Bob" action="called" dstusr="Alice"
```
 
## Details
A [user pointed out](https://github.com/wazuh/wazuh/issues/26685) that the examples given out for decoders were not working and as a result the decoders were difficult to understand.

After reviewing the documentation, it was found that the log message given as an example in the [Practical Example](https://documentation.wazuh.com/current/user-manual/ruleset/decoders/sibling-decoders.html#practical-example) section was incorrect.

Example in documentation:
```
2019/01/02 13:16:35 securityapp: INFO: srcuser="Bob" action="called" dstusr="Alice"
```

However, when this log format is tested with the `wazuh-logtest` utility, using the decoder from the documentation, the output is as follows:
```
Starting wazuh-logtest v4.9.1
Type one log per line

2019/01/02 13:16:35 securityapp: INFO: srcuser="Bob" action="called" dstusr="Alice"

**Phase 1: Completed pre-decoding.
	full event: '2019/01/02 13:16:35 securityapp: INFO: srcuser="Bob" action="called" dstusr="Alice"'

**Phase 2: Completed decoding.
	No decoder matched.
```
Which is not the expected output according to the documentation.

The correct log example should be:
```
Apr 12 14:31:38 hostname1 securityapp: INFO: srcuser="Bob" action="called" dstusr="Alice"
```

With this log sample, the output is correct:
```
Starting wazuh-logtest v4.9.1
Type one log per line

Apr 12 14:31:38 hostname1 securityapp: INFO: srcuser="Bob" action="called" dstusr="Alice"


**Phase 1: Completed pre-decoding.
	full event: 'Apr 12 14:31:38 hostname1 securityapp: INFO: srcuser="Bob" action="called" dstusr="Alice"'
	timestamp: 'Apr 12 14:31:38'
	hostname: 'hostname1'
	program_name: 'securityapp'

**Phase 2: Completed decoding.
	name: 'securityapp'
	action: 'called'
	dstuser: 'Alice'
	srcuser: 'Bob'
	type: 'INFO'

```

**Comment by Damian-Mangold** [comment]
@jftuduri Point the change to branch 4.9.
