### ISSUE TITLE
Vulnerability Detector - Offline update 

### ISSUE THREAD

**Issue by sebasfalcone** [wazuh/wazuh-documentation#7996]
## Description
Documentation on how to use the [Vulnerability detector offline mode](https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/offline-update.html) is not clear enough. 

We show how to obtain the content's snapshot URL but it is a bit disconnected on how to configure it:
> ![image](https://github.com/user-attachments/assets/158d24c7-c34c-41d4-82cf-f3867ba8d4e0)

Also, to prevent people from using the example output values:
> ![image](https://github.com/user-attachments/assets/4cf69132-626e-4ab6-922a-ca96beaa9f15)

We should show an example of the format the data will be returned (without actual values)

## Definitions
- Target branch 4.8

## DoD
- [x] Documentation updated

**Comment by MiguelazoDS** [comment]
# Update 

- Compilation without warnings 
![image](https://github.com/user-attachments/assets/9d20d4b4-c6f4-4682-8327-68fa0df69799)

- Results
![image](https://github.com/user-attachments/assets/f178acc7-0f06-4c51-af38-17ca3ae828e3)

**Comment by sebasfalcone** [comment]
## Issue closure
Changes implemented in the documentation
