### ISSUE TITLE
Discrepancy in offline-url path in vulnerability detection section

### ISSUE THREAD

**Issue by joaquinsgi** [wazuh/wazuh-documentation#7997]
| Version |
|:--:|
|  4.9, 4.8  | 

## Description

It has been noticed a discrepancy with the documentation, in the following link: https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/vuln-detector.html, when we use an offline feed, it needs to use a file, but its wrong in the code:
![image](https://github.com/user-attachments/assets/b53dbe70-45e5-4cbf-a1af-5edef718e217)

the code for offline-url has to be: `<offline-url>file:///path/to/content/file.tar.xz</offline-url> <!-- Optional -->`, with 3 `///`, like it is declarated in: https://documentation.wazuh.com/current/user-manual/capabilities/vulnerability-detection/offline-update.html, because with 3 `///` it searches the file on the local system

### Current result

offline-url appear with only 2 `//` and searches on Internet.

### Expected result

offline-url needs to appear with 3 `///` to search on the local system.

**Comment by MiguelazoDS** [comment]
Just a comment, besides this change, I think it is more important to fix the expected format here. 

```console
2024/12/02 18:24:54 wazuh-modulesd:vulnerability-scanner[101825] databaseFeedManager.hpp:370 at operator()(): ERROR: Error updating feed: Invalid line. file: queue/vd_updater/tmp/contents/1117976_1733137820.tar.
```

**Comment by MiguelazoDS** [comment]
# Update 

![image](https://github.com/user-attachments/assets/dfeab955-f478-44a0-8e95-b0ad36a7678f)
![image](https://github.com/user-attachments/assets/1cb1ae32-184f-4ce8-8c09-5124e14b93e0)
