### ISSUE TITLE
Typo in distributed upscale documentation

### ISSUE THREAD

**Issue by paradoxl** [wazuh/wazuh-documentation#8006]
The documentation shows the following commands that cause sequential execution to fail

mkdir /etc/filebeat/certs
rm -rf /etc/filebeat/certs

This can be found under "Configuring existing components to connect with the new node" -> All-in-one deployment in the wazuh server cluster section of the user manual. 

![Screenshot at 2024-12-03 16-36-11](https://github.com/user-attachments/assets/eb28504d-1675-4731-91ff-7e5655f3633f)

**Comment by rauldpm** [comment]
For reference: https://documentation.wazuh.com/current/user-manual/wazuh-server-cluster.html#id6

**Comment by rauldpm** [comment]
Hi @paradoxl, I am closing this issue as the documentation has been fixed, if you have any problems, don't hesitate to tell us!
