### ISSUE TITLE
Broken `kaspersky.c` link

### ISSUE THREAD

**Issue by javimed** [wazuh/wazuh-documentation#8037]
In the [Default active response scripts](https://documentation.wazuh.com/current/user-manual/capabilities/active-response/default-active-response-scripts.html#linux-macos-and-unix-based-endpoints) page the following link is broken and needs to be replaced.

- Broken link: https://github.com/wazuh/wazuh/blob/master/src/active-response/kaspersky.c

**Comment by damarisg** [comment]
LGTM!
