### ISSUE TITLE
Java downloads fails due to Oracle update

### ISSUE THREAD

**Issue by okynos** [wazuh/wazuh-documentation#812]
Hi team,

I was trying to install the elastic stack but recently Oracle updated java version to 201/202 instead of 191/192 on the documentation, now the download link is broken, could you please update it?

Documentation section -> https://documentation.wazuh.com/current/installation-guide/installing-elastic-stack/elastic_server_rpm.html#preparation

new Oracle download link -> https://download.oracle.com/otn-pub/java/jdk/8u202-b08/1961070e4c9b4e26a04e7f5a083f551e/jre-8u202-linux-x64.rpm

Thanks for your time, regards.

**Comment by jesusgn90** [comment]
Fixed https://github.com/wazuh/wazuh-documentation/commit/6d2a9dee56a725680c8810d6089575383b65a571, thanks!
