### ISSUE TITLE
Deploy Wazuh app in a search heads cluster

### ISSUE THREAD

**Issue by adri9valle** [wazuh/wazuh-documentation#817]
Hi team,

Would be nice to create a new section explaining how to deploy a distributed Wazuh app installation for Splunk in a search heads cluster.

I think that this section should contain:

- [x] Explanation about Splunk search head cluster.
- [x] How to index in a remote index from the Wazuh app in a search head instance.
- [x] Explanation about Splunk deployer.
- [x] How to deploy a distributed Wazuh app in a search heads cluster from the deployer.

Regards,

**Comment by JaoChaos** [comment]
I'm on it :+1: 

Thanks :)
