### ISSUE TITLE
The configuration of "Monitoring containers activity" could explain better where configure the woodle of Docker

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#821]
Hi team,

In the documentation of [_monitoring containers activity_](https://documentation.wazuh.com/current/docker-monitor/monitoring_containers_activity.html), the configuration of the woodle could have a better explanation, such where is configured the woodle (docker host or docker container), which configuration file and if it is necessary to restart the agent.

Regards,

Miguel Casares

**Comment by JaoChaos** [comment]
- [ ] Configuration file.
- [ ] Docker host or container.
- [ ] Restart the agent.
