### ISSUE TITLE
Missing steps in AWS VPC documentation

### ISSUE THREAD

**Issue by mgmacias95** [wazuh/wazuh-documentation#823]
Hello team,

While testing the new AWS VPC implementation released in Wazuh v3.8, I noticed I needed additional permissions in my policy:
```javascript
       {
            "Sid": "VisualEditor0",
            "Effect": "Allow",
            "Action": "ec2:DescribeFlowLogs",
            "Resource": "*"
        },
```
This step isn't mentioned in the current documentation.

Best regards,
Marta

**Comment by JaoChaos** [comment]
Fixing it on branch issue-823
