### ISSUE TITLE
 How to activate NGINX rules / PHP rules ?

### ISSUE THREAD

**Issue by rakening** [wazuh/wazuh-documentation#853]
Everything is in the question, we did not find anything in the documentation.

**Comment by JaoChaos** [comment]
Hello @rakening:
Yes, we've checked it and there's no any information about that in the documentation.
We will try to fix it as soon as possible.

Thanks for your aport.

Regards,
Juan Anaya Ortiz.

**Comment by JaoChaos** [comment]
Hello @rakening :

We've been checking it:
If no NGINX or PHP rules are created, you should create them.
Although, we are going to create a pair of examples in the documentation for future cases like this one.

We recommend checking the https://github.com/wazuh/wazuh-ruleset repository, where many rules exist.

Thanks for using Wazuh, kind regards,

Juan Anaya Ortiz.

**Comment by JaoChaos** [comment]
@rakening 

https://github.com/wazuh/wazuh-ruleset/blob/master/rules/0260-nginx_rules.xml
https://github.com/wazuh/wazuh-ruleset/blob/master/rules/0265-php_rules.xml

There are the NGINX and PHP alerts that Wazuh has configured in the ruleset.

For example, 
`
    <rule id="31310" level="0">
       <if_sid>31301</if_sid>
       <match>failed (2: No such file or directory)|is not found (2: No such file or directory)</match>
       <description>Nginx: Server returned 404 (reported in the access.log).</description>
    </rule>
`
 checks if a file or directory exists. 
To use them, download the rulesets and follow our Official documentation to include them into your Wazuh configuration.

Please, feel free to try them and report or question any problem yo have.

Regards,

Juan Anaya Ortiz.
