### ISSUE TITLE
Missing options in Rules Syntax

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-documentation#874]
I noticed the following options are missing and are referenced used in the ruleset:

 - [x] ~action~ (caught on #834 by Vikman)
 - [x] status
 - [x] extra_data
 - [x] check_if_ignored
 - [x] compiled_rule
 - [x] ignore
 - [x] location

The following are allowed by the code and are also missing but not currently used in the ruleset:
 - [x] cve
 - [x] ignore
 - [x] if_fts
 - [x] check_diff 
 - [x] not_same_source_ip
 - [x] not_same_same_user
 - [x] not_same_same_agent
 - [x] not_same_id

**Comment by jctello** [comment]
additionally the option to add variables with `<var name=...` should be somehow mentioned

**Comment by JaoChaos** [comment]
The last four options were not documented as they are not used in Wazuh.

**Comment by JaoChaos** [comment]
Hello @jctello:
In the following PR is a full improvement of the ruleset.
Hope it fixes every point of this issue:
https://github.com/wazuh/wazuh-documentation/pull/868

Best regards,

Juan Anaya Ortiz.

**Comment by jctello** [comment]
Great, thanks :-)

**Comment by jctello** [comment]
As shown here: https://github.com/wazuh/wazuh/issues/3440 
Although the last options are not part of our ruleset they may be useful for custom or future rules, and as such should be documented.

**Comment by UranusBytes** [comment]
Please consider adding stubs to the documentation for these options, even if the explanation is minimal for now.  When trying to write some rules today, I was using the 0240-ids_rules.xml as a reference, was was confused by the check_if_ignored tag.  I was sent on a wild goose chase thru the source to figure out what this option does.

**Comment by Canon88** [comment]
Please consider updating the documentation.
need to use `not_same_source_ip` field when writing rules, but it does not exist in the document. 
I asked by 'slack' and found the answer. I think the Wazuh Team can consider updating these fields to the document for your convenience. Thanks again to WazuhTeam.
