### ISSUE TITLE
All https://raw.githubusercontent.com/wazuh pages throw invalid request.

### ISSUE THREAD

**Issue by travisph** [wazuh/wazuh-documentation#88]
https://raw.githubusercontent.com/wazuh

All pages respond with:
"400: Invalid Request"

I'm not sure if this is an issue with github or the wazuh repository.  It's kinda hard to get kibana installed at the moment tho.

Thank you

**Comment by snaow** [comment]
Hi @travisph,

Is this issue still affecting you? I went over the documentation testing different links and everything seems work properly.

Remember to use the full URL to download the files you need:

- https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/2.1/server/startup/integration_files/template_file.json
- https://raw.githubusercontent.com/wazuh/wazuh-kibana-app/2.1/server/startup/integration_files/alert_sample.json
- https://raw.githubusercontent.com/wazuh/wazuh/2.1/extensions/logstash/01-wazuh.conf
- https://raw.githubusercontent.com/wazuh/wazuh/2.1/extensions/elasticsearch/wazuh-elastic5-template.json

Best regards,
Pedro.
