### ISSUE TITLE
Field option for rules accepts sregex instead of regex syntax

### ISSUE THREAD

**Issue by chemamartinez** [wazuh/wazuh-documentation#887]
The current ruleset reference says that the `field` option to match dynamic fields of events accepts standard regex expressions. However, it only accepts the syntax of sregex (which supports simple string matching and the following special characters: `^`, `$`, `|`).

It should be specified in the field description: https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/rules.html#field

Here can be found the difference between the Regex syntax and SRegex syntax: https://documentation.wazuh.com/current/user-manual/ruleset/ruleset-xml-syntax/regex.html#regular-expression-syntax

**Comment by JaoChaos** [comment]
This issue closes with PR #868 
Removed the "regex" option and added "sregex".
