### ISSUE TITLE
Grammar typo in Agents groups section

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#898]
Hi, 
I just realized about this section of `centralized configuration` [page](https://documentation.wazuh.com/current/user-manual/reference/centralized-configuration.html#agent-groups)

>The manager pushes all files included in the group folder to the agents `belonging this group`. For example, all files in /var/ossec/etc/shared/default will be pushed to all agents` belonging to default group`.

It should be replaced by `belonging to this group` and `belonging to the default group`

Regards,

**Comment by JaoChaos** [comment]
Hello @MiguelCasaresRobles 

Thank you for your report, I've fixed it in the following PR:
https://github.com/wazuh/wazuh-documentation/pull/899

Regards,

Juan Anaya Ortiz.
