### ISSUE TITLE
Integration 'groups' setting is not Regex

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-documentation#920]
[This](https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/integration.html#group) claims the `<group>` follows OS_Regex syntax.

However [here](https://github.com/wazuh/wazuh/blob/852146faece1c041c8b90045d8a53bd6a4f037a1/src/os_integrator/integrator.c#L183-L212) it shows that it is doing a simple comma separated match.

**Comment by JaoChaos** [comment]
This issue is solved with the PR #943

**Comment by JaoChaos** [comment]
Thanks for the report @jctello :D
