### ISSUE TITLE
Update documentation OpenScap

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#926]
Hi Team,

In the documentation of OpenScap, I cannot find the policy to use for Amazon Linux AMI.

https://documentation.wazuh.com/current/user-manual/capabilities/policy-monitoring/openscap/how-it-works.html#default-policies

OpenSCAP support this OS? If so, which one is compatible with Amazon Linux AMI?

Regards,

**Comment by JaoChaos** [comment]
Hello @MiguelCasaresRobles :
Thanks for contacting us.

No, Amazon did not add the SCAP or the OpenSCAP packages to the list of supported packages of Amazon Linux AMI.

So I'm sorry to say that they are not compatible.

Hope this answer is useful to you.

Best regards,

Juan Anaya Ortiz.
