### ISSUE TITLE
Documentation GET /agents/:agent_id/config/:component/:configuration

### ISSUE THREAD

**Issue by JmZero** [wazuh/wazuh-documentation#966]
Hello team,

I've found an error in the parameters of GET /agents/:agent_id/config/:component/:configuration request into the 3.9 documentation. `Configuration` parameter has three time the **internal** value. 

https://github.com/wazuh/wazuh-documentation/blob/3.9/source/user-manual/api/reference.rst#get-active-configuration

Best regards,
Jesús

**Comment by JaoChaos** [comment]
This issue is related with the API team and has its duplicate here -> https://github.com/wazuh/wazuh-api/issues/336
