### ISSUE TITLE
issues with the AWS Config

### ISSUE THREAD

**Issue by jctello** [wazuh/wazuh-documentation#982]
The screenshots in [the AWS Config page](https://github.com/wazuh/wazuh-documentation/blob/master/source/amazon/services/config.rst) correspond to PagerDuty instead of the AWS Config.

Also there are some naming problems.
Kinesis firehose path - firehose
ossec.conf s3 wodle path - config

Another problem is that multiple guides suggest using kinesis firehose.
There should be some recommendations to only use one bucket for the firehose with different service prefixes instead of creating multiple firehose buckets.

The guide also doesn’t say that you have to add the bucket the the IAM user policy.

**Comment by JaoChaos** [comment]
The new AWS module fixes a big part of this issue:
https://github.com/wazuh/wazuh-documentation/pull/829/files

Regards @jctello :)

**Comment by JaoChaos** [comment]
This issue has been extended in issue #998 :+1:

Regards.
