### ISSUE TITLE
Group field in email_alerts not clear.

### ISSUE THREAD

**Issue by DanielMorLoz** [wazuh/wazuh-documentation#987]
Hello team,
In the following link: 
https://documentation.wazuh.com/current/user-manual/manager/manual-email-report/index.html?highlight=group
When it's explained how to use the <group> field it is said you only need to put the group name to use the field.
![imagen](https://user-images.githubusercontent.com/47329460/53742602-55170080-3e99-11e9-8c11-4df46de4c3bb.png)
However, if you follow the link:
https://documentation.wazuh.com/current/user-manual/reference/ossec-conf/email_alerts.html#group
The note says you must finish a group with a comma.
![imagen](https://user-images.githubusercontent.com/47329460/53742625-619b5900-3e99-11e9-8351-a64f42bc197d.png)
And then it is given an example using it
![imagen](https://user-images.githubusercontent.com/47329460/53742672-74ae2900-3e99-11e9-9a7d-b5eeb77a061e.png)
What is the correct form to use it?

**Comment by JaoChaos** [comment]
Hello @DanielMorLoz, 

the correct way to do it is the second one, always using the comma.

The first example is wrong and I'm going to fix it immediately.

Thanks for the report, 
Juan Anaya Ortiz.
