### ISSUE TITLE
Prerequisites are missing in the how it works section of virustotal

### ISSUE THREAD

**Issue by MiguelCasaresRobles** [wazuh/wazuh-documentation#991]
Hi team,

In the Virustotal [page](https://documentation.wazuh.com/current/user-manual/capabilities/virustotal-scan/integration.html) are missing the prerequisites to make Virustotal works as install the `requests` Python package and `enable` _integrator_

Regards,

Miguel Casares

**Comment by JaoChaos** [comment]
Hi, @MiguelCasaresRobles:

I have reviewed your issue and I've found this in our VirusTotal doc page:

![imagen](https://user-images.githubusercontent.com/16852482/53942383-e5805b80-40ba-11e9-9d93-2e7684439305.png)

Isn't that all the prerequisites needed?
Regards,

Juan Anaya Ortiz.
